### ISSUE TITLE
Can you update the non-CFW Version?

### ISSUE THREAD

**Issue by GrafBoko** [FlagBrew/PKSM#1000]
Hello!

I have a **Sky3ds Flashcard** with  **Freakyhax Homebrew Launcher** and I used the old version of **PKSM** a lot. It worked fine! But now I need **CFW (Luma and Rosalina)** and I don't want to install Custom Firmware! I want to edit my **Pokemon Ultra Moon and Ultra Sun** savefiles and the old version of PKSM doesn't work for Pokemon USUM!

So my Question is: Can you make the latest PKSM compatible with **HAX-Homebrew** Launcher (Freakyhax, Ninjahax etc...) again?

**Comment by BernardoGiordano** [comment]
Of course not

**Comment by piepie62** [comment]
Alright, first off, you don't need to make everything bold, and please, use actually correct capitalization. It's just annoying. Second, and the TLDR for the rest of this post, no, we can't.
The long version: No, it's not possible to add *hax support to the current version of PKSM. It uses multiple CFW-only features, the graphics library we use doesn't like *hax, and there's an *unsurpassable* technical restriction on how much compiled code can actually go into a *hax application. The technical difficulty of changing how we do everything we do, combined with the fact that there is literally no reason to not install CFW (it's free, for god's sake) makes this a huge undertaking for very little gain.

**Comment by SpiredMoth** [comment]
I'm not sure what version of PKSM you're using, but it's really, *really* old (even for builds that support \*hax) if it doesn't work on USUM. USUM support first came in [v5.0.0](https://github.com/FlagBrew/PKSM/releases/tag/5.0.0) (released New Years 2018) and the last build with \*hax support was [v5.1.4](https://github.com/FlagBrew/PKSM/releases/tag/5.1.4).

You're free to try one \*hax builds with USUM support, but we will **NOT** be providing support if you can't get it working or run into bugs.
