### ISSUE TITLE
Living Dex/Living Shiny Dex

### ISSUE THREAD

**Issue by Tee14** [FlagBrew/PKSM#1002]
**Is your feature request related to a problem? Please describe.**
I prefer my mons to have my ot name of T, so it gets frustrating. 

**Describe the solution you'd like**
Maybe make it so that if you run the living dex, it has your ot name or the name you entered in settings as well as a living shiny dex option

**Comment by piepie62** [comment]
You don't quite understand: that's not how that works. The living dex Pokémon are not dynamically generated, and doing so would be a huge hassle on its own. The same principle applies to the issue of the shiny dex.

**Comment by piepie62** [comment]
Also, this is the wrong repository for scripts issues; look at [the scripts repo](https://github.com/FlagBrew/PKSM-Scripts) for any other issues you may have with them
