### ISSUE TITLE
Where do I put my save files

### ISSUE THREAD

**Issue by Ya-boi-mees** [FlagBrew/PKSM#1003]
I have lost my hgss cartridge years ago and have run a backup from tilight menu ever since. I now want my starters and many other pokemon to be transfered over to my usum game. 

The problem is, I have no freaking idea where to put my heartgold.sav file to make it show up in "absent games". The manual also doesn't say anything, it just says "it works the same way". (which it doesn't. It is not humanly possible to give a .sav file phisical form and insert it into the cartridge slot.)

**Comment by piepie62** [comment]
You missed the relevant section [here](https://github.com/FlagBrew/PKSM/wiki/Configuration#extra-saves)

**Comment by SpiredMoth** [comment]
This wiki page should help https://github.com/FlagBrew/PKSM/wiki/Configuration#extra-saves

**Comment by Ya-boi-mees** [comment]
I am sorry for the time spent on this rtfm noob problem

**Comment by GriffinG1** [comment]
Just gonna put a requisite "buy the damn game again" here, as what you're currently doing _is_ piracy, as you no longer have access to the cartridge.
