### ISSUE TITLE
Bug Report - Pokemon Black 2 crash

### ISSUE THREAD

**Issue by zjthang** [FlagBrew/PKSM#1007]
**Describe the bug**
when i open PKSM and open Black 2, everything runs smoothly expect the events section. in the beginning, i only open it for a while browsing through, then suddenly the app will crash and i will be sent back to my home screen.. i tried clearing my events wondercards but it only made it worse.. now when i open up the event section the app immediately crashed.. please help :(
**To Reproduce**
just input black 2 and press the events section somehow mine crashes immediately..

**Information about your environment**(im not very sure about this part)
 - OS version: (i guess this is the 3ds firmware) 11.10.0
 - PKSM version: 6.2.1

**Comment by piepie62** [comment]
This is likely the B2 text issue, which has been fixed in commits

**Comment by zjthang** [comment]
So how should i fix this??

**Comment by piepie62** [comment]
Wait for the next release
