### ISSUE TITLE
No bugs but a brief question about transfer conversions

### ISSUE THREAD

**Issue by mrsclitoris** [FlagBrew/PKSM#1009]
So I'm just curious about the conversions of pokemons. HGSS/DPPt -> BW/B2W2 -> XY/ORAS -> SM/USUM. Does it follow the pal park and poketransfer/pokemonbank conversion algorithm?

**Comment by Admiral-Fish** [comment]
Conversion code was taken from PKHeX which I believe was originally coded from reverse engineering pal park/poketransfer/pokemon bank.
