### ISSUE TITLE
[feature request] save transfer between supported titles

### ISSUE THREAD

**Issue by mer2329** [FlagBrew/PKSM#1010]
personally i would love a way to transfer saves between supported games, on the fly. 

in games of the same gen/opposing versions where it dosent cause issues.
for example i have read that pkmn ultra sun/moon saves can be transferred between the 2 games, as long as the game identifier is correctly matched to the save. im not sure about the other series (like B/W, HG/SS, B2/W2)

this would be useful for those who want to play through the game with as little cheats as possible (ie this being the only one)

now im no programmer (i know a little, but its very rudimentary), but with the nature of scripts i imagine this could be implemented pretty easily in the scripts.
just have 2 scripts that saves to the other game's cart save, and one script that makes/uses/overwrites a save slot called "Transferred Save" for each game upon use.

**Comment by mer2329** [comment]
now that the request is written, i want to add. thanks for the work on this awesome tool.

**Comment by GriffinG1** [comment]
Considering the rather low amount of use I’d expect this to get, the fact it’s easy enough to handle yourself through gm9 or fbi, and the issue of there not really being a full list of games that work like that (if there is one, it’s likely short anyways), I can’t see a point to implementing it that would make it worth implementing to Bernardo.

**Comment by mer2329** [comment]
griffing1, i think it belongs in pksm more then checkpoint. for a couple of reasons.
1) this is pokemon game related, and wont work for many other games.
2) checkpoint is simply a save backup/restore tool, and it dosent allow manipulating the saves, and these are not just drop and go. for games other then the one that made the save, they must have the game flag changed. ie putting a unmodified sun save in moon will result in a corrupted save error.

**Comment by piepie62** [comment]
No
