### ISSUE TITLE
Bug Report - Brief Description/Name of issue

### ISSUE THREAD

**Issue by Halfshadow** [FlagBrew/PKSM#1011]
I re-hacked my 3DS with the latest firmware yesterday. And my old PKSM worked, but was old wythout support ti DS games and Ultra Sun/Moon. I tried to download the new 3dsx file but don't work. I have to delete some files from the SD card? Can you please tell me every location where I have to delete something?

**Comment by deadair3210** [comment]
Pksm doesn't support Homebrew loader anymore as far as I know

**Comment by Halfshadow** [comment]
I see... I can do something to hack my 3DS with the CFW and install also VC versions?

**Comment by deadair3210** [comment]
https://3ds.hacks.guide/

**Comment by Halfshadow** [comment]
Thank you. I currently download the 5.14 version with support to UltraMoon and UltraSun, but doesn't work with DS games like the previous... Isn't possible without CFW?

**Comment by deadair3210** [comment]
Not sure, easiest way to make sure is to just install cfw, it's so easy there really isn't a reason not to

**Comment by Halfshadow** [comment]
Thank you.
