### ISSUE TITLE
Event Injection doesnt work gen 4 in the newest version

### ISSUE THREAD

**Issue by Soccar** [FlagBrew/PKSM#1013]
When i try to inject an event pokemon to my pokemon pearl in the newest version of PKSM it doesnt appear in game . Although the cards get injected. So i tried an older version 6.0.1 and it worked perfectly.

**Comment by piepie62** [comment]
Known issue. Don't downgrade as it causes issues.

**Comment by piepie62** [comment]
Has been fixed in commits

**Comment by Soccar** [comment]
Nice! But how do i implement the fix to the newest version ?

**Comment by piepie62** [comment]
Wait

**Comment by Soccar** [comment]
So, how do I do it?

**Comment by GriffinG1** [comment]
Wait.
