### ISSUE TITLE
PKSM doesn't detect save files from RTS rs4 card

### ISSUE THREAD

**Issue by MatchaPotato** [FlagBrew/PKSM#1015]
PKSM does detect ultra moon save files, but doesn't seem to detect the other save files (platinum & black) within my RTS cardridge. Do I need to copy - paste my save files in a diff map??

**Comment by piepie62** [comment]
If an "RTS rs4" card is some sort of flashcard, flashcards are not supported and never will be

**Comment by MatchaPotato** [comment]
It is a flashcard and that's too bad. Thanks for the quick reply though!
