### ISSUE TITLE
Wireless Injecting Pokemon Help

### ISSUE THREAD

**Issue by HiHello67** [FlagBrew/PKSM#1016]
A little bit of background.....

I first used PKSM a year back to wireless inject pokemon from my laptop using servpkx software ( I had the pk6/pk7 files of my pokemon from BW2/ HG/Plat). It was a simple process of typing in IP address in the servpkx program, selecting the pk6 files and sending and it would show up in the 'wireless' box. 

Recently my SD card on my 3DS became damaged so I got a new one, installed latest homebrew and also the latest PKSM (different version from the one I had a year ago obviously). Fortunately I still have my pk6 files on my laptop which I'm using to wirelessly inject. Problem I am having is when I wirelessly send it over servepkx I get the notification that it was successful, but when I check PKSM I don't see my pokemon anywhere.

Previous version of PKSM my pokemon would be appear in the 'Wireless' box once I have wirelessly sent it, but for this 6.2.1 version I don't see a wireless box, or know how to get to it (previous version I would go into Storage or Edit I believe, and then press Y and it would show up). 

I am wondering if there is a step I am missing with this new version of PKSM or doing something wrong, or if there is supposed to be a better method.

**Comment by HiHello67** [comment]
Thanks for the reply.

I was browsing through the scripts before you replied and saw two scripts in particular:

1. servepkx_server....I started this script and figured I could wireless inject using servpkx which did nothing (this was before you wrote Servepkx is gone, so I guess that won't work)

2. pkx-injector....I went to 3ds/PKSM and then created a folder called Inject (the description for the script said to put files into the inject folder which I did not have). I then proceeded to place all my pk6 files there and then I ran the script but then my 3DS crashed with an exception occurred screen.

**Comment by GriffinG1** [comment]
The injector has an upper limit on how many can be injected at a time. I can’t remember the number off the top of it head, but I’d say stick to 5 at a time, and just switch out the pkx files through fbi, gm9, or ftp. Of course, if you have a large number of pkx files to do, this will not be quick. In that case, I advise using pkhex to inject them into your save instead.

Note: make sure your inject folder is all lowercase too, how you wrote it in your reply makes it seem like it’s capitalized.

**Comment by HiHello67** [comment]
Ahh, the upper limit was the reason. Thanks for that!

I do have a large number of Pk files so I'll try using pkhex to inject (idk how to switch files using fbi/gm9).

I'm surprised servpkx isn't supported, which is very unfortunate. Nonetheless thanks for the tips and help!

**Comment by GriffinG1** [comment]
Between 5.1.4 and 6.0.0, pksm was changed to c++, and servepkx would’ve been... painful... to bring over. That servepkx script you were talking about _can_ work, but it takes some in depth knowledge.

P.S: can you please close this issue now? Thanks.
