### ISSUE TITLE
[Feature Request] Allow loading NDS saves from SD card

### ISSUE THREAD

**Issue by Filo97** [FlagBrew/PKSM#1017]
**Is your feature request related to a problem? Please describe.**
You might know that TWiLightMenu++ has become quite popular. If i want to use PKSM with a save from it, i have to inject that save into a cart and then load up the cart, then dump the cart's save and put it back in TWiLightMenu++. Something not possible when i'm travelling and don't have my carts with me.

**Describe the solution you'd like**
Allow save loading from a specific path in the sd card, so i can just load up godmode9, move the save, load up pksm, do whatever, then put it back in place still using godmode9

**Describe alternatives you've considered**
Could also specifically scan TWiLightMenu++'s save directory

**Comment by BernardoGiordano** [comment]
already possible, please have a look at the documentation.
