### ISSUE TITLE
Glitched pokemon and crash with new bank file 

### ISSUE THREAD

**Issue by Matt8898** [FlagBrew/PKSM#1018]
After installing PKSM from scratch(deleting the previous 3ds/pksm directory) and going into storage and hovering the cursors over one of the pokemon shown in the screenshot crashes the game.

**To Reproduce**
1. Install pksm
2. Open a save
3. hover over one of the eggs

**Screenshots**
![glitch](https://user-images.githubusercontent.com/9578391/61221896-cf923f80-a719-11e9-837e-5a6e5ddf2c3a.jpg)

**Information about your environment**
 - OS version: 11.6.0-39RE
 - PKSM version: 6.2.1
 - Entrypoint: CFW

crash dump:
[crash_dump_00000001.txt](https://github.com/FlagBrew/PKSM/files/3392593/crash_dump_00000001.txt)

**Comment by piepie62** [comment]
Send a dump of your PKSM ExtData, please

**Comment by Matt8898** [comment]
Here is the extdata dump:
[extdata.zip](https://github.com/FlagBrew/PKSM/files/3392617/extdata.zip)

**Comment by piepie62** [comment]
I have no clue how the hell that happened, but could you try deleting your ExtData and reopening the program? Your bank file is majorly fucked up

**Comment by Matt8898** [comment]
That seems to have fixed it, thanks.
