### ISSUE TITLE
[Feature Request] Offline Asset Support for Citra

### ISSUE THREAD

**Issue by raptortech-js** [FlagBrew/PKSM#1020]
PKSM requires additional assets to work, and as of major version 6 it must download those from the internet. The Citra 3DS emulator does not currently support that sort of internet access, and as such PKSM version 6 cannot be used within Citra.

Previous versions of PKSM allowed you to download an additionalassets folder and put it on the SD card so PKSM does not need to directly connect to the internet, and this allowed those previous versions to be used with Citra.

It would be wonderful if the most recent version of PKSM were also compatible with Citra, and the most easiest way to make this work would appear to be re-adding support for manually downloading and installing additional assets.

The Citra team are looking at supporting internet access within the emulator, but it will take quite a while to get that working.

**Comment by BernardoGiordano** [comment]
But you already can

**Comment by raptortech-js** [comment]
How? I've tried it with version 6 and it didn't work for me. The installation instructions state quite clearly that you must have internet access to make PKSM work

**Comment by piepie62** [comment]
Read the rest of the README. It has the required path there

**Comment by ORLOX93** [comment]
> Read the rest of the README. It has the required path there

Where's the rest of the readme? It doesn't mention citra anywhere

**Comment by GriffinG1** [comment]
Please do not post on 3 year old closed issues. The README still has the asset path listed.
