### ISSUE TITLE
[LIST OF REQUESTS] Script PKX manipulation

### ISSUE THREAD

**Issue by piepie62** [FlagBrew/PKSM#1024]
I've been thinking of adding PKX editing functions to the scripting API. Feel free to add requests for any of the existing functions in any of [these files](https://github.com/FlagBrew/PKSM/tree/master/core/source/pkx). I will acknowledge requests I've seen by editing this message.
Current requests:
- [x] OT name
- [x] Shiny
- [x] Language
- [x] Generate function (uses PKSM's logic to generate a Pokémon from scratch)
- [x] Met location
- [x] Move
- [x] Ball
- [x] Level
- [x] Gender
- [x] Ability
- [x] IVs
- [x] Nickname
- [ ] Ribbons. I cannot think of a good interface for these, as even within PKSM, ribbons are magic numbers
- [x] Held item
- [x] Pokérus
- [x] Egg date
- [x] Met date

**Comment by FM1337** [comment]
how about IVs?

**Comment by FM1337** [comment]
Also maybe Held Item, Pokerius, Egg Date?

**Comment by FM1337** [comment]
Also maybe add a function to get some data instead of setting it if that's not already a thing (I scanned through the wiki so I apologize if this already exists and I just missed it), an example would be getting the species name for a pokemon by providing the ID of that pokemon, e.g 151 would return "mew"

**Comment by piepie62** [comment]
Nearly everything has now been added. If anybody sees this and wants the few things I left out, mostly because I don't know of a good interface/don't think they're at all important, just comment here and I'll likely add it and/or ask you to come into the Discord for discussion on the best interface for it

**Comment by FM1337** [comment]
~~Happiness~~ (yeah I know it's too late to ask :P
