### ISSUE TITLE
Feature Request: Add method for scripting to get the total PC boxes for save file.

### ISSUE THREAD

**Issue by FM1337** [FlagBrew/PKSM#1027]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
I would like a method for getting the number of PC boxes for the save file so that I don't accidentally overwrite important data.

**Describe alternatives you've considered**
N/A

**Additional context**
Context is in relation to the random generation script.

**Comment by GriffinG1** [comment]
Isn't number of boxes game based? It's just a matter of being able to access the higher boxes, which occurs when the box prior is filled, no?

**Comment by FM1337** [comment]
Actually yes it is, my bad.
