### ISSUE TITLE
My pokemons in the bank is deleted

### ISSUE THREAD

**Issue by FahriBilici** [FlagBrew/PKSM#1032]
İ add pokemons to bank bu i clucked wrongly and i didnt save so all of them deleted. How can i restore ? İ find backup folder under pksm but what should i do next?

**Comment by piepie62** [comment]
Copy the relevant backup into Checkpoint's folder for the game, then restore it through Checkpoint

**Comment by FahriBilici** [comment]
What is checkpoint? İs it in pksm ? My pksm version is older than last release i think

**Comment by piepie62** [comment]
[Checkpoint](https://github.com/FlagBrew/Checkpoint) is a save manager. If you're not using 6.2.1, then upgrade

**Comment by FahriBilici** [comment]
İs my backup may be damaged because of update?

**Comment by piepie62** [comment]
No, no version of PKSM deletes backups
