### ISSUE TITLE
Can't open PKSM on 3DS

### ISSUE THREAD

**Issue by Joxpert** [FlagBrew/PKSM#1033]
Firstly, when I installed the .cia file using FBI, it did not open properly and it shows an issue that says "failed to download assests" and right behind it tells me it could be due to an outdated Luma version, however I updated some days ago. I'm using the 6.2.1 PKSM version.
Later I tried to reinstall it, but now it just ssend me to the home menu with a message that says "the program was closed due to an issue" and then it gets restarted.

 - OS version: Sys11.10.0-43E
 - PKSM version: 6.2.1

Thank you!

**Comment by piepie62** [comment]
Download the assets manually if you can't connect your 3DS to the internet. Also try deleting your PKSM Extra Save Data through FBI
