### ISSUE TITLE
Bug Report - Crash on "Events" page as of latest master (Platinum)

### ISSUE THREAD

**Issue by andrew-d** [FlagBrew/PKSM#1035]
**Describe the bug**
I just (~10 minutes ago) compiled PKSM off `master` to play around with Wonder Card injection in Platinum - it's broken in the latest release, so I figured I'd compile off `master` and see if it was fixed. However, tapping on the "Events" button immediately crashes the app and returns to the Homebrew launcher.

**To Reproduce**
1. Load a Platinum game save
2. Click on "Events"

**Information about your environment**
 - OS version: Latest
 - PKSM version: v6.2.1-6280d50b
 - Entrypoint: boot9strap via seedminer, per https://3ds.hacks.guide/

**Additional context**
I'm happy to help debug if I can be useful here (EDIT: though you'll need to link me to how I can get logs or a crashdump, since I'm new to 3DS development).  I've made only the smallest changes to get this compiling; mainly a diff to PKSM-Scripts to fix a Unicode error:
https://gist.github.com/andrew-d/2f9990e24e3385c48d6bee04b956d460

Other than that, no changes have been made.

**Comment by BernardoGiordano** [comment]
You just didn't compile PKSM properly

**Comment by BernardoGiordano** [comment]
Make sure you have everything needed to build the event database

**Comment by andrew-d** [comment]
The build process appears to have generated all the same `sheet*.json.bz2` and `data*.bin.bz2`, but when I rebuild using the official Docker file that y'all use in Drone, it appears to work :man_shrugging: Sorry for the spurious bug report, even though I have no idea what changed :sweat_smile:
