### ISSUE TITLE
Bug Report - PKSM v7.0.1 error

### ISSUE THREAD

**Issue by IceBear199** [FlagBrew/PKSM#1039]
it appears this "erros during starup: 0xD900458B
 - OS version: New 3ds XL
 - PKSM version: 7.0.1

**Comment by piepie62** [comment]
I believe this problem was solved by backing up and immediately restoring PKSM's ExtData with Checkpoint. Try doing that, please

**Comment by Multimegamander** [comment]
still not closed?
