### ISSUE TITLE
Problem loading 4th gen save file

### ISSUE THREAD

**Issue by host1126** [FlagBrew/PKSM#1040]
- OS version: New 3ds XL 
 - PKSM version: 7.0.1

I am using TWiLightMenu.
In Korean version BW / BW2, PKSM loads the save file normally, but in Korean version DP / PT / HG / SS I get 'xxxx.sav not a valid save file' error.

**Comment by piepie62** [comment]
What is the exact size in bytes of your DPPtHGSS saves?

**Comment by host1126** [comment]
524,288 bytes

**Comment by piepie62** [comment]
Interesting. Does PKHeX work with them?

**Comment by host1126** [comment]
Yes, it works on PKHeX.

**Comment by piepie62** [comment]
And you're certain that the path PKSM is using does point at the file?

**Comment by host1126** [comment]
Yes. I checked the path, but I couldn't find anything wrong.

**Comment by piepie62** [comment]
Ah, I see the issue. This has apparently been an issue since 6.0.0 and nobody noticed

**Comment by piepie62** [comment]
Should be fixed with the latest commit

**Comment by piepie62** [comment]
I'd rather not release for a single bug, so I'll likely wait for a couple more (or merging #1005) before another release
