### ISSUE TITLE
Bug Report - GPSS Downloading

### ISSUE THREAD

**Issue by LonerPupper** [FlagBrew/PKSM#1041]
**Describe the bug**
When I go through the GPSS looking for gen6/7 pokemon and I download it and go to the editor it will say the pokemon is not a gen6/7 but a gen 3-5 (past gen then listed)

**To Reproduce**
1. Go to 'Storage'
2. Click on 'GPSS'
3. Grab a Pokemon that is a shiny from gen6/7 that could be from an old lets use this as an example **6794344652** Ditto
4. When shown in the GPSS on the app its says Gen6/7 then when its downloaded goto the editor it will display the non-listed gen

**Expected behavior**
Expected is that the generation symbol will change from its listed to the actual

**Screenshots**
**cant list screenshots due this happening last night and have school**

**Information about your environment**
 - OS version: 11.9
 - PKSM version: latest
 - Entrypoint: CIA

**Comment by piepie62** [comment]
The generation symbol has two meanings in the application. On the storage screen, it indicates the format of the Pokémon, and on the editor screen, it represents the origin game of the Pokémon
