### ISSUE TITLE
Feature Request - Button cue on main menu to save data

### ISSUE THREAD

**Issue by noirscape** [FlagBrew/PKSM#1043]
**Is your feature request related to a problem? Please describe.**
It's not intuitive to figure out how to save the data without referencing the wiki.

**Describe the solution you'd like**
On the bottom part for the main interface (the one with the 6 buttons), add an informative text to the extent of `Press B to save game data.`

**Describe alternatives you've considered**
Alternatives I tried to save data that didn't work:
- Close software (software closes without a warning of data loss, should probably be fixed using the correct SMDH flag, but that's a different issue). Data wasn't saved.
- Mess around with the storage box, no save data prompt popped up, aside from asking to save the box. Went on assumption it saved save data too, but it didn't.

Had to end up referencing the wiki to figure out what I had to do was press `B`.

**Additional context**
The software is for the most part fairly intuitive to figure out, however this one bit was a stumbling block.

**Comment by piepie62** [comment]
This has been handled in a different way, but has been changed to be more clear. It now matches the way the Pokémon editor works.
