### ISSUE TITLE
Feature Request - New Setting Item: Storage Save Style (Toggle)

### ISSUE THREAD

**Issue by TheeAnonymousOne** [FlagBrew/PKSM#1045]
**Is your feature request related to a problem? Please describe.**
When using PKSM, there are two save points. First one is when exiting the storage, second one is when exiting the main menu. This proposes a problem: if you have moved Pokemon from the storage to your game and for any reason your use of PKSM is disrupted either via crash, battery dying, accidental incorrect button tap, anything during the exiting of the main menu, those Pokemon are now all gone. This has personally happened multiple times.

**Describe the solution you'd like**
In the settings of PKSM, there would be a toggle switch between two save "styles" of PKSM. 
1) The default one, being two different save points, one for the storage and one for the game; 
2) and the second save style, which is a "save everything after exiting the storage". This way, this secures the Pokemon without worry of losing anything. It will be as usual, a pop-up saying, "Would you like to save EVERYTHING? A: Yes, B: No".

**Describe alternatives you've considered**
An alternative function would be more of a Pokemon Bank approach: save everything automatically upon exiting.
An alternative way to switch save styles would be to go into a config file for PKSM on the SD Card and change a boolean item from "false" to "true" (ie. a config item called "auto_save=" or something).

**Additional context**
(none)

**Comment by TheeAnonymousOne** [comment]
Unsure if "boolean" is correct terminology. Either way, what is meant is "toggleable" from 2 to maybe, even 3 saving styles.

**Comment by piepie62** [comment]
PKSM automatically creates backups to mitigate that specific problem. If you'd like help in restoring your backups, join the [FlagBrew server](https://discord.gg/bGKEyfY). For that reason, I consider this a nonissue, and instead a request to give a toggle to remove a feature
