### ISSUE TITLE
Bug Report - Archive::init failed. on boot 

### ISSUE THREAD

**Issue by chaosweeb** [FlagBrew/PKSM#1050]
**Describe the bug**
First time installer of PKSM (7.0.1); opened from home menu (.cia version), it shows the PKSM icon on the top screen for 5 seconds then gives me Error '0xD900458B' and a description of 'Archive::init failed.

**To Reproduce**
1. Install PKSM (7.0.1) via QR Code on FBI
2. Open from Home Menu

**Expected behavior**
Downloads assets and required files (and/or opens to menu)

**Information about your environment**
 - OS version: New 2DS XL (11.10), Luma3DS (v10.1)
 - PKSM version: 7.0.1
 - Entrypoint: CIA

**Comment by chaosweeb** [comment]
Fixed, please mark as closed

**Comment by GriffinG1** [comment]
What was your solution? No cause has been figured out for this yet, and so far we've been recommending backing up and importing PKSM's ExtData to fix it

**Comment by chaosweeb** [comment]
> What was your solution? No cause has been figured out for this yet, and so far we've been recommending backing up and importing PKSM's ExtData to fix it

Yes this is what I did to fix the problem
