### ISSUE TITLE
Problems with Event Pokemon (Pokemon White 2)

### ISSUE THREAD

**Issue by Rcxd999** [FlagBrew/PKSM#1052]
Hi, After using PKSM with Pokemon White 2, I seem to have encountered several problems regarding Event Pokemon. 

First issue is that after downloading the first 12 Pokemon, even after Clearing Mystery Gift data via the Scripts menu,  while it says all the wondercards are gone, I can still only get 1 Pokemon at a time, rather than 12. This is also despite specifically trying to inject certain Pokemon into slots 1 to 11 in an attempt to replace the current wondercard. Also each time I load up PKSM with Pokemon White 2, it still says I have 11 wondercards despite that being incorrect. 

The Second issue is when accessing the wondercard album. Most of the time when I try to access the card album the screen goes black and the music keeps playing. This only resolves itself when you reset the game by returning to the home screen. The few times I have managed to see into the card album, I've seen a random item wondercard in slot 1 with the date ?0/41/?829. This card says that I've already picked up whatever it was, despite never downloading a item mystery gift for White 2. I've tried deleting this card to see if that fixed the issue but when I've deleted the card, and then exit and try to reenter the card album, I stuck on a black screen and have to reset the game. I've also randomly received an Encounter Power Up, but this has only happened once. 

Those are the issues. While I can still download event Pokemon, it's been reduced to 1 at a time and is quite slow and the inability to access my card album is quite annoying, but otherwise this issue doesn't present any other problems other than those and due to my ability to still download and receive event Pokemon only being slowed but not stopped completely, a fix is not urgently needed.

Some other information:
3DS Model: 3DS XL (EU Region)
Game: Pokemon White 2 (EU Region)
System version: 11.11.0-43E
PKSM: v7.0.1-3b12f3e0

**Comment by piepie62** [comment]
The "11 wonder cards on the main menu" problem has been fixed. Currently looking into that slot 1 issue

**Comment by Rcxd999** [comment]
Thank you. I'll check when I next have free time.

**Comment by piepie62** [comment]
This should now be fixed
