### ISSUE TITLE
How do i check if my pokemon is legal (pkmn sun)

### ISSUE THREAD

**Issue by MrAntho** [FlagBrew/PKSM#1055]
I'm wanting to know how to check Pokémon legality custom Pokémon (generated)

**Comment by GriffinG1** [comment]
![image](https://user-images.githubusercontent.com/28538707/66146420-fa2dbf00-e5c9-11e9-9390-6691599b52e2.png)

**Comment by MrAntho** [comment]
What I can't use it on my 3ds?

**Comment by GriffinG1** [comment]
far too memory intensive.

**Comment by MrAntho** [comment]
Hoe am I supposed to check it then,...

**Comment by GriffinG1** [comment]
read. the. photo. contents.

**Comment by MrAntho** [comment]
Wym read the photo ik It says I can't use it on my 3ds how Am I going to check if they legit ?????!?!?!? If I can't use my 3ds

**Comment by piepie62** [comment]
Read the entire thing carefully. It's possible, and you use your 3DS to do it; it just has to go through an external server.
