### ISSUE TITLE
Sorry me again..im mew to this plz help

### ISSUE THREAD

**Issue by MrAntho** [FlagBrew/PKSM#1056]
Read the entire thing carefully. It's possible, and you use your 3DS to do it; it just has to go through an external server. Do I need to setup the external server or something and it wont break my 3ds right??

**Comment by GriffinG1** [comment]
Don't open new issues. Read it, it tells you ***exactly*** what to do.

**Comment by GriffinG1** [comment]
@piepie62 close and lock please.
