### ISSUE TITLE
SD-card directory browsing

### ISSUE THREAD

**Issue by DavveDP** [FlagBrew/PKSM#1057]
One feature that would be really beneficial would be the added option of browsing the SD directory for a .sav file. I am currently playing some of my gen 5 games through twighlight menu. However those saves aren’t detected by checkpoint or flag brew so a manual way of selecting the .sav file would be fantastic.

I’m not too experienced with the design of 3ds homebrew but I don’t think it would be too hard to implement. Would also help everyone who still uses an emulator.

Fantastic work guys! The most useful homebrew on the 3ds for sure

**Comment by Gudf** [comment]
It's already implemented, as you can see by reading the wiki: https://github.com/FlagBrew/PKSM/wiki/Configuration#extra-saves

**Comment by DavveDP** [comment]
Oh I’m terribly sorry I missed that. Thanks a lot for the quick reply! I’ll close this issue now then

**Comment by GriffinG1** [comment]
Just as a note, you'd been told the same thing on the discord. Please do not ignore people helping you there. 
![image](https://user-images.githubusercontent.com/28538707/66255258-e0fa4f00-e73e-11e9-9d7d-2a7a6d6b8ce9.png)
