### ISSUE TITLE
Attempting to access absent games' saves without a cartridge cases a crash

### ISSUE THREAD

**Issue by Epicpkmn11** [FlagBrew/PKSM#1063]
**Describe the bug**
When I try to access absent games' saves without a cartridge in I get an ARM11 Translation exception.

**To Reproduce**
1. (note the additional information)
2. Go to the save select screen
3. Don't have a cartridge in
4. Press `Y`
5. Crash

**Expected behavior**
Doesn't crash, and you can access saves from SD

**Information about your environment**
 - OS version: 11.10.0-43U
 - PKSM version: a8b2ca07
 - Entrypoint: The Homebrew Launcher home screen app

**Additional context**
This is on a 3dsx build I made of a8b2ca07 on macOS 10.14 with the latest devkitARM, libcrtu, and such, this does not happen on my cia install of the latest release, sorry if this is a problem with my build setup and not PKSM itself.

**Comment by GriffinG1** [comment]
I can't reproduce it on the same commit. Can you try building a cia version instead? Could be a 3dsx specific issue

**Comment by Epicpkmn11** [comment]
When building it always fails for me after building the 3dsx...
```
linking PKSM.elf
built ... PKSM.3dsx
Created banner "build/banner.bnr".
Created SMDH "build/icon.icn".
[EXHEADER ERROR] Invalid FileSystemAccess Name: "SeedDB"
[EXHEADER ERROR] Failed to create ExHeader
[NCCH ERROR] NCCH Build Process Failed
[RESULT] Failed to build outfile
make[1]: *** [no-deps] Error 245
make: *** [3ds] Error 2
```
Do you know how I can fix those errors?

**Comment by GriffinG1** [comment]
Compiling is not my strong suit. Perhaps @piepie62 will be able to ~~if they ever look at their computer again~~ :p

**Comment by BernardoGiordano** [comment]
Use a makerom version compiled from latest source

**Comment by Epicpkmn11** [comment]
Hmm... It's still crashing for me with a cia install, even after a clean rebuild... 
[PKSM.zip](https://github.com/FlagBrew/PKSM/files/3721518/PKSM.zip)
Here's my builds (sorry if I'm not supposed to share builds, I can delete it) if you want to see if it's a problem with my builds or something on my system.

**Comment by piepie62** [comment]
What happens if you have a cart that does not show the icon (any non-Pokémon cart) in?

**Comment by Epicpkmn11** [comment]
Same crash as with no cart (for both DS and 3DS carts)

**Comment by piepie62** [comment]
Very interesting. I cannot reproduce in either of those conditions with my own build

**Comment by piepie62** [comment]
Quick thought: could you `make clean` and rebuild and see if that makes any difference? Don't know what might have changed to break it, but worth a shot

**Comment by piepie62** [comment]
Crash fixed, was due to trying to update a button after TitleLoadScreen was destroyed
