### ISSUE TITLE
How the fuck do I fix this?

### ISSUE THREAD

**Issue by MissMedicMain** [FlagBrew/PKSM#1065]
Your software caused the top screen to glitch out and then this happened.
How the fuck do I fix it?

[https://drive.google.com/file/d/103oYGWvNC8a3ePBVK2ScBCZN6AgY8eXk/view?usp=drivesdk](url)

**Comment by FM1337** [comment]
Try turning the console off and on?

**Comment by BernardoGiordano** [comment]
Closing this because that's not the tone you refer to a team working to provide software to you for free, without any kind of warranty, as stated in the license file you should have had a look at.
