### ISSUE TITLE
Problems with Event Pokemon (Pokemon White 2) (Unresolved)

### ISSUE THREAD

**Issue by Rcxd999** [FlagBrew/PKSM#1066]
Hi, I'm making another bug report about the problems with event Pokemon in Pokemon White 2 due to my original bug report being "locked as resolved" despite this not being the case. 

The issues remain the same, with me being unable to download more than 1 event Pokemon at a time as well as being unable to access the Wonder Cards from the mystery gift section of the game most of the time. I'll place the information from the original bug report down below. 

The only new piece of information that I could possibly think to add is that when injecting an event Pokemon, it by default wants to inject to slot 12, and when choosing another slot, it shows slots 1 to 11 with the "item" symbol and "pressing A to change slot" and then pressing start to inject doesn't appear to do anything. This is regardless of whether or not Mystery Gift data has been cleared or not. Other than that, I don't know what other new information I could provide.

Original bug report:

"Hi, After using PKSM with Pokemon White 2, I seem to have encountered several problems regarding Event Pokemon.

First issue is that after downloading the first 12 Pokemon, even after Clearing Mystery Gift data via the Scripts menu, while it says all the wondercards are gone, I can still only get 1 Pokemon at a time, rather than 12. This is also despite specifically trying to inject certain Pokemon into slots 1 to 11 in an attempt to replace the current wondercard. Also each time I load up PKSM with Pokemon White 2, it still says I have 11 wondercards despite that being incorrect.

The Second issue is when accessing the wondercard album. Most of the time when I try to access the card album the screen goes black and the music keeps playing. This only resolves itself when you reset the game by returning to the home screen. The few times I have managed to see into the card album, I've seen a random item wondercard in slot 1 with the date ?0/41/?829. This card says that I've already picked up whatever it was, despite never downloading a item mystery gift for White 2. I've tried deleting this card to see if that fixed the issue but when I've deleted the card, and then exit and try to reenter the card album, I stuck on a black screen and have to reset the game. I've also randomly received an Encounter Power Up, but this has only happened once.

Those are the issues. While I can still download event Pokemon, it's been reduced to 1 at a time and is quite slow and the inability to access my card album is quite annoying, but otherwise this issue doesn't present any other problems other than those and due to my ability to still download and receive event Pokemon only being slowed but not stopped completely, a fix is not urgently needed.

Some other information:
3DS Model: 3DS XL (EU Region)
Game: Pokemon White 2 (EU Region)
System version: 11.11.0-43E
PKSM: v7.0.1-3b12f3e0"

**Comment by piepie62** [comment]
It is fixed in commits, there hasn't been a release containing the fix yet

**Comment by Rcxd999** [comment]
My apologies. I didn't realise that that was how it worked. Thank you for fixing the issue and sorry for the repost.
