### ISSUE TITLE
Bug Report - No background music

### ISSUE THREAD

**Issue by DeStilleGast** [FlagBrew/PKSM#1067]
**Describe the bug**

**To Reproduce**
1. Turn up volume to max
2. Select a pokemon game (in my case Ultra moon)
3. Go to 'Settings'
4. Click on 'Misc.'
5. Notice 'Randomize music' option
6. Hear totaly nothing (even after restarting app)

**Expected behavior**
hearing background music

**Information about your environment**
 - OS version: 11.11.0-43E
 - PKSM version: v7.0.1-3b12f3e0
 - Entrypoint: CIA

**Additional context**
Before I updated to v7.x it had music

**Comment by piepie62** [comment]
If you would read the [changelog](https://github.com/FlagBrew/PKSM/releases/tag/7.0.0), you'd notice that it said that the default music was removed. This was done to reduce the binary size

**Comment by DeStilleGast** [comment]
Woeps, didn't saw it. I skipped the v7.0.0 update.

**Comment by DeStilleGast** [comment]
Is there a way to get the old music file back so I can download and place it on my sd card ?

**Comment by GriffinG1** [comment]
Go look through the commit history for the file. It was a Mewmore song.

**Comment by DeStilleGast** [comment]
Found it, thx

**Comment by ubergeek77** [comment]
Actually, even on the latest release (7.0.1), I am unable to get any .mp3 to play.

Can anyone reproduce this issue?

**Comment by piepie62** [comment]
Please don't post on month-old, only-vaguely-related issues
