### ISSUE TITLE
PKSM no longer opening on New3DS

### ISSUE THREAD

**Issue by Rakidas** [FlagBrew/PKSM#1070]
PKSM abruptly stopped working along with NTR recently so I updated my N3DS to the latest firmware and Luma. I've read that the new Luma makes NTR incompatible, so that's fine, but PKSM just hangs on the initial black screen with the square blue icon in the centre of the screen until I turn the system off. Being online or offline makes no difference and have done multiple reinstalls using both the QR code (latest FBI version) and the cia. I apologise if this bug report is in the wrong place but I love this program and have used it for years and really want to get it back. Any help or ideas would be much appreciated. Thank you.

**To Reproduce**
1. Go to 'PKSM'
2. Click on 'PKSM'
3. Hangs on boot screen (black with blue icon)
4. No recourse except to turn off system

**Expected behavior**
I expected a clean install with internet connected to download the necessary assets then boot normally from then on.

**Screenshots**

**Information about your environment**
 - OS version: Latest (11.10 I think) and latest Luma (10.0.1 I think)
 - PKSM version: 7.0.1
 - Entrypoint: CIA direct install to Home Menu

**Additional context**

**Comment by GriffinG1** [comment]
Keep waiting, that shows that pksm is loading. If it takes more than a few minutes, try clearing `/3ds/pksm/backups`

**Comment by Rakidas** [comment]
> Keep waiting, that shows that pksm is loading. If it takes more than a few minutes, try clearing `/3ds/pksm/backups`

Thanks Griffin, I'll give that a try. The loading has never taken so long before, not even close. Not even the initial boots of new versions over the years that need to download assets have, and once that's done, booting has always been practically instant. I'll try clearing the folder you mentioned, maybe that's the trouble. Is this new version of PKSM much bigger or more intensive than previous ones? Because I can't press the Home button or anything else while it's hanging on that screen, only turn it off. That's why I was concerned that it was freezing/crashing rather than downloading assets or booting up, etc. Thanks for the tip :)

**Comment by GriffinG1** [comment]
I’m not sure, but I believe @piepie62 disabled the home button on the loading screen to prevent corruption.

**Comment by Rakidas** [comment]
> I’m not sure, but I believe @piepie62 disabled the home button on the loading screen to prevent corruption.

I see . . . My DS is still hanging on the black screen after leaving it for about 5 mins and clearing the folder you mentioned, so now I'm not sure :/ Thanks for trying though!

**Comment by piepie62** [comment]
I did no such thing. I disabled the home button when running scripts and the QR reader because of infinite loops in use there

**Comment by piepie62** [comment]
Could you try downloading and placing the assets into the correct location manually?

**Comment by piepie62** [comment]
Instructions:
1. Download the assets from https://github.com/dsoldier/PKResources/tree/master/additionalassets
2. Copy the assets to /3ds/PKSM/assets/. You may need to create the folder.
3. Launch PKSM, and you should be good to go.

**Comment by Rakidas** [comment]
Thanks piepie, I'll try it out right now!

**Comment by Rakidas** [comment]
> Instructions:
> 
> 1. Download the assets from https://github.com/dsoldier/PKResources/tree/master/additionalassets
> 2. Copy the assets to /3ds/PKSM/assets/. You may need to create the folder.
> 3. Launch PKSM, and you should be good to go.

Unfortunately, even this didn't work :( I wind up with files about 302 and 362kb respectively (give or take a little for my terrible memory). Then it just hangs infinitely. I thought I had progress for a second when PKSM told me it needed to be connected to the internet (hadn't ever gotten that far yet!) but when I connected and tried again, the same issue occurred. I don't know what I could be doing wrong.

**Comment by GriffinG1** [comment]
Try backing up your extdata with checkpoint, then clearing it with FBI

**Comment by Rakidas** [comment]
Thanks, I'll try it now. Hopefully that's what's causing all this trouble lol

**Comment by Rakidas** [comment]
I went to FBI, Ext Save Data, PKSM, and deleted it. Now it gives me an ARM9 data abort crash every time I open it :( Even restoring the extdata with checkpoint doesn't stop it.

**Comment by Rakidas** [comment]
[crash_dump_00000000.zip](https://github.com/FlagBrew/PKSM/files/3774381/crash_dump_00000000.zip)
If it helps, this is the crash dump that was generated.

**Comment by GriffinG1** [comment]
...the fuck?

**Comment by Rakidas** [comment]
> ...the fuck?

Dude, you're telling me. I'm confused as fuck

**Comment by GriffinG1** [comment]
Can you try installing 7.0.1 again, just to confirm it? Also backup your /3ds/pksm folder and remove it from the sd card. Repeat extdata steps too - this will mimic a completely fresh pksm install

**Comment by Rakidas** [comment]
Thanks Griffin, I'll give it a spin now!

**Comment by Rakidas** [comment]
I really appreciate the help :) Thanks man

**Comment by Rakidas** [comment]
> Can you try installing 7.0.1 again, just to confirm it? Also backup your /3ds/pksm folder and remove it from the sd card. Repeat extdata steps too - this will mimic a completely fresh pksm install

. . . Well, it isn't ARM9 crashing anymore, so that's something lol. Back to the original hanging-on-black-screen-with-icon-for-eternity. I'm starting to wonder if this is nothing to do with PKSM at all at this point. I've NEVER had problems with this program before, it's always been so simple to install and use, practically instant. Is there anything you can think of off the top of your head that might cause problems with apps like PKSM? I've got Twilight Menu ++ as well and it's been playing up where it wasn't before. 

P.S. Never mind lads got another ARM9 crash :( Went in the first time to download the assets but it dropped out, so PKSM closed. Went in again after reconnecting and it just hung and then crashed. ARM9 crash on boot every time now. I think I may have offended 3DS Jesus.

**Comment by GriffinG1** [comment]
I think pksm might be corrupting a bit when you close out like that. Wipe again, reinstall, then just let it sit on the boot screen for like an hour or something, see if it makes its way past. Pie and I and both confused af right now, but doing that showed improvement last time so...

**Comment by Rakidas** [comment]
Thanks Griffin and Pie, I’ll give that a go. I appreciate your time helping out with this, seriously. I’ve got no idea what’s playing up, but other than formatting my SD card to try and wipe whatever nasty bug this is, I’m out of ideas, so leaving it to try and get through over time might be best.

**Comment by piepie62** [comment]
Well, I'm not sure what the issue here is, but it obviously isn't a PKSM issue (as PKSM runs entirely in the ARM11 processor), so I'm closing it. Feel free to hop onto our Discord if you'd like to continue trying to figure out what's wrong
