### ISSUE TITLE
Bug Report - Brief Description/Name of issue

### ISSUE THREAD

**Issue by CrimsonGamer12** [FlagBrew/PKSM#1071]
this issue is very weird, i recently bought pokemon heartgold off of ebay and i can confirm that it is a legit cartridge and not some bootleg, right now i'm trying to use it with pksm but whenever i boot up the program it doesn't detect my heartgold cartridge at all, i read that i'm supposed to look at a readme file but i can't find one anywhere when i download the program files, i use LUMA3DS CFW and installed it through the cia method but it just won't work with my heartgold cartridge pls help

**Comment by piepie62** [comment]
How can you confirm that it's a legitimate cartridge? Also, is it a Korean copy?

**Comment by CrimsonGamer12** [comment]
1 no it is a US copy and 2 i don't have the time to explain every way to differ a bootleg cartridge or an official cartridge

**Comment by piepie62** [comment]
If you're not willing to give the information needed to possibly solve an issue, why open an issue at all, then? I have no guarantee that you're not wrong in your identification. If you wish to open a new issue, please use the issue template, as well

**Comment by CrimsonGamer12** [comment]
look it's an official cartridge okay it is not bootleg that's the information you need i can't give any other information, i open pksm and it doesn't detect the cartridge, my other 3ds pokemon games work just fine

**Comment by CrimsonGamer12** [comment]
and besides why would i need to describe how i know it's not a bootleg, how does that specific information help with my problem if i already know it's an official cartridge?

**Comment by piepie62** [comment]
Once again, open a new issue using proper issue templates.
