### ISSUE TITLE
Bug Report - Brief Description/Name of issue

### ISSUE THREAD

**Issue by CrimsonGamer12** [FlagBrew/PKSM#1072]
**Describe the bug**
pksm is not detecting my heartgold cartridge

**To Reproduce**
open the pksm program and the cartridge is not read by pksm

**Expected behavior**
it should allow me to access my heartgold save to edit it but it won't
**Screenshots**
i do not have any screenshots

**Information about your environment**
 - OS version: LUMA3DS
 - PKSM version: 7.0.1
 - Entrypoint: ¯\_(ツ)_/¯

**Additional context**
there is this the formatted report you wanted?

**Comment by Mike007899** [comment]
1, still not the info needed.
2, no need to be smart when the devs wanna help you get your cart to work.
3, see 1 and 2.

**Comment by CrimsonGamer12** [comment]
what other info do they need? i don't understand what else there is to add

**Comment by piepie62** [comment]
Once again, without further information on how you're saying with certainty that your cartridge isn't a fake, I cannot tell you what is wrong. My own HeartGold cartridge works perfectly fine, for example, as do many others, leading me to believe that yours is in some way different

**Comment by CrimsonGamer12** [comment]
well a few other things that i know is that my friend has the same issue and he bought his cartridge around the time it came out at our local gamestop, his cartridge isn't working either

**Comment by CrimsonGamer12** [comment]
i've checked with about 5 other people online describing everything about my cartridge that i can and my cartridge is legitimate according to all of them, one of which was a former gamestop employee

**Comment by Mike007899** [comment]
New? Used? If used, it could 99% chance be an undocumented bootleg. I have my new (when it dropped) one and it works while my used GameStop one shows up as bomberman when I extract its save. The used one idc about, so thats a moot point from me.

(PS: this is some info thats needed.)

**Comment by CrimsonGamer12** [comment]
i bought my cartridge about 2 years ago used from my local gamestop, i don't know anything else i can give other than that

**Comment by CrimsonGamer12** [comment]
also if i'm honest this seems like it would be a lot simpler if the devs could just tell me any solutions i could try and if it doesn't work i'll just leave

**Comment by piepie62** [comment]
Could you run Checkpoint with it inserted and upload the log generated from it?

**Comment by piepie62** [comment]
And we don't know what any solutions could be because we've never encountered this issue before

**Comment by CrimsonGamer12** [comment]
seriously?

**Comment by CrimsonGamer12** [comment]
i've seen messages on other sights from just last year, i've seen about a couple dosen by now while looking for a way to solve this issue

**Comment by CrimsonGamer12** [comment]
also i don't know what checkpoint is...sorry if that makes me look stupid

**Comment by piepie62** [comment]
Most of the issues related to this we have had have been carts that are actually flashcarts in disguise, which dump... weird saves, to say the least. If you are absolutely, 100% certain that this is a legitimate cart, then yes, this is a new issue. [Checkpoint](https://github.com/FlagBrew/Checkpoint) is a save manager, with a couple nice features build in, including dumping cartridge save chip ID information. Also try backing the save up with Checkpoint and sending it here

**Comment by CrimsonGamer12** [comment]
little note i just found a post of this exact issue from 2017 link here: https://github.com/FlagBrew/PKSM/issues/265 (scroll down to midnightabs)

**Comment by piepie62** [comment]
Still gives absolutely no helpful information

**Comment by CrimsonGamer12** [comment]
you know what this seems like too much trouble for me, sorry for wasting your time i'll just give up on this, i really only wanted to fix this issue so i could complete my pokedex without buying another game
