### ISSUE TITLE
Error: Banks::Init failed

### ISSUE THREAD

**Issue by thesunisjustfine** [FlagBrew/PKSM#1075]
**Describe the bug**
Upgraded from a version >1 year old, attempting to re-initialize.
Screen reads:
PKSM v7.0.1-3b12f3e0
Error during startup: 0xFFFFFFFF
Description: Banks::init failed.
Press start to exit

**To Reproduce**
1. Boot up 2DS, open home menu
2. Wait 30-60s as recommended in a different issue thread
3. Open PKSM, view Homebrew screen -> Black screen with blue/white pokeball logo -> Brief Checking for Updates screen
4. Error

**Expected behavior**
App to properly open and initialize, allowing save editing

**Information about your environment**
 - OS version: v11.9.0-42U
  (i also JUST updated my OS as well)
 - PKSM version: v7.0.1-3b12f3e0
 - Entrypoint: Nintendo 3DS Sound

**Additional context**
After seeing error the first time, figured that there was an issue initializing banks after the upgrade so /3ds/PKSM directory was deleted. Error still occurred

**Comment by piepie62** [comment]
Interesting problem. Could you dump your PKSM ExtData with Checkpoint and send a ZIP of it here?

**Comment by thesunisjustfine** [comment]
[Zip here](https://www.dropbox.com/s/vc20av8zk8zafdt/20191107-005113.zip?dl=0) 
I feel like I jumped through a good number of hoops for this (no pc) so if it doesn't work let me know and ill try a different way

**Comment by piepie62** [comment]
Yeah, not entirely certain what happened, but the file that keeps track of your banks (banks.json) is completely broken. Could you replace it with this? Just rename it to banks.json over the one in your Checkpoint backup
[banks.txt](https://github.com/FlagBrew/PKSM/files/3820425/banks.txt)

**Comment by thesunisjustfine** [comment]
it works, thank you!!
I have a feeling I accidentally corrupted it by closing PKSM as it was booting up for the first time, oops
Lesson learned, closing thread!

**Comment by Focas2003** [comment]
Hi i have the same problem:
erorr during startup: 0zD8E06406
Description: nsInit failed.
