### ISSUE TITLE
Bug Report - Homebrew Launch

### ISSUE THREAD

**Issue by Oshawott50** [FlagBrew/PKSM#1078]
When loading in to PKSM through Homebrew it would freeze in a yellow screen.

I expected to load in to PKSM as usual, but got stopped. Do I need to download anything else besides the 3dsx file? or do you suggest something is wrong on Homebrew? Pksm latest Whopsie ver. 3ds Version 11.12.

- 3dsx file was under 3ds folder.
- Homebrew Launches just fine and only crashes when opening/starting PKSM.

**Comment by Oreo639** [comment]
The PKSM 3dsx requires Luma.
