### ISSUE TITLE
Bug Report - Hardy nature from bank to gen4 games

### ISSUE THREAD

**Issue by mrsclitoris** [FlagBrew/PKSM#1079]
Whenever i transfer my mons from bank to dpp or hgss, their nature changes to hardy. Well it could easily be tweaked in the editor but it's really inconvenient if you're trying to transfer a bunch

**Comment by piepie62** [comment]
Are you talking about backwards transfers or in-generation transfers?

**Comment by piepie62** [comment]
And does PKSM show the change or is it just in-game?

**Comment by mrsclitoris** [comment]
Oh. It's backwards transfer.. Maybe that's why?

**Comment by mrsclitoris** [comment]
Both in-game and pksm

**Comment by piepie62** [comment]
Should be fixed with the latest commit
