### ISSUE TITLE
Bug Report - Brief Description/Name of issue

### ISSUE THREAD

**Issue by nicolehall93** [FlagBrew/PKSM#1080]
There's a bug with transferring a gen 6 to gen 7 pokemon, other gens not tested.
Checked in PKHex, the transferred Pokemon are "illegal". When you check why, the alert "Invalid: Untraded: Current handler should not be the Handling Trainer" pops up.

1. Catch a pokemon in gen 6 (mine is X)
2. Add that pokemon into the storage box.
3. Move it into a gen 7 game (mine is ultra moon).
4. Save, backup your save with checkpoint and check in PKHex.

There will be a red triangle on the affected sprite.

 N3DSXL on 11.12, Luma, PKSM 7.0.1.

Thank you for reading!

**Comment by piepie62** [comment]
What is the "Edit during transfers" setting set to? If it's not "Yes", then set it as such and redo the transfer; I believe it should use proper transfer logic then. I meant to have that be the default, but accidentally defaulted it to false

**Comment by nicolehall93** [comment]
It was set to "no", I will change that. Thanks for getting back to me so quickly about it!

**Comment by piepie62** [comment]
No problem. If that does fix it, as I believe it should, please close this issue. If it does not, we can figure out what's wrong together

**Comment by nicolehall93** [comment]
That fixed it! Thank you again.
