### ISSUE TITLE
Trying to restore backup files

### ISSUE THREAD

**Issue by MBatisti** [FlagBrew/PKSM#1083]
**Describe the bug**
I had to format my SD card because my pokémon games were crashing. I backed up the files inside the SD card, but I forgot to backup PKSM via checkpoint. I have all my bank files, and I'm trying to restore them but I keep getting:

Error during startup: 0xFFFFFFFF
Description: Banks::init failed.

I tried to manually forge a Checkpoint Backup folder with the .bak files i've copied from the old SD card, it looks like this atm:
https://drive.google.com/drive/folders/1jS34faOUYOZBnXXJXYO547ZUeWTpMzYy?usp=sharing

**To Reproduce**

1. Use checkpoint to restore the cursed folder i've created
2. Open PKSM
3. It crashes right after the logo

**Expected behavior**
I just want to be able to access my pokémon from my old Banks. Theres SO MANY of them :T

**Information about your environment**
 - OS version: v11.12.0-44U
 - PKSM version: 7.0.1
 - Entrypoint:

**Additional context**
I also have some .bak.old files, are they important?

**Comment by piepie62** [comment]
Do you have the latest version of Checkpoint? That seems like an "outdated Checkpoint" problem, looking at the only place that error happens

**Comment by MBatisti** [comment]
Yes, I have v3.7.3 !

I've formatted my SD card and installed everything brand new

**Comment by MBatisti** [comment]
Maybe I did something wrong when writing the .json files that go inside the "forged checkpoint backup"?

But I'm not finding the error. I've also tried many different things regarding the banks.json, like:
-only attempt to load a single .bnk
-remove spaces from the .bnk file names
-play around with the storage size of each .bnk to be loaded (tried with 1, 150, 999 and the correct number of storages in that file)

nothing has worked

**Comment by piepie62** [comment]
Alright, there are two things you need to do: First, remove the `.bak` extension from the bank files (both `.bnk` and `.json`). Second, remove the final comma in your `banks.json`; that is what's causing the error

**Comment by piepie62** [comment]
Leave the numbers at what they should be; if you don't, the sizes will change

**Comment by MBatisti** [comment]
It worked!!

Thanks a lot for the fast response, I guess I'll close this

All the best!
