### ISSUE TITLE
Cannot mass clone Pokémon into extra storage 

### ISSUE THREAD

**Issue by piotrmil** [FlagBrew/PKSM#1085]
Cloning more than one Pokémon is impossible. 

**To Reproduce**
1. Change the cursor to the mass mode,
2. Select more than one Pokemon,
3. Click "clone"
4. Only one Pokemon gets cloned - the one that cursor was on when the clone button was pressed. 

**Expected behavior**
It should clone the whole lot.

This is a copy of https://github.com/FlagBrew/PKSM/issues/974 which has been deemed as "fixed", despite not being fixed.

**Comment by piepie62** [comment]
Upgrade; that behavior is outdated. When you hit X after selecting but before picking up, it will clone them. I might bind the button to that same behavior; I did not realize that it didn't do it properly in the current version until now

**Comment by piotrmil** [comment]
Ah, okay, that does explain it.
