### ISSUE TITLE
Twilight Menu++ Support?

### ISSUE THREAD

**Issue by GreenAndEievui** [FlagBrew/PKSM#1087]
Would it be possible to open the .sav files that Twilight Menu creates for NDS games? I've tried looking through the source myself to find a solution but I'm not smart enough to figure it out. I figure it'd be easy to implement for someone who understands the source, but I might be wrong.

**Comment by piepie62** [comment]
Already possible. Read the [documentation](https://github.com/FlagBrew/PKSM/wiki/Configuration#extra-saves)

**Comment by GreenAndEievui** [comment]
> Already possible. Read the [documentation](https://github.com/FlagBrew/PKSM/wiki/Configuration#extra-saves)

Sorry about that. Thank for the quick reply.
