### ISSUE TITLE
Pokémon Black2/White2 does not show up

### ISSUE THREAD

**Issue by trucidate** [FlagBrew/PKSM#1089]
- OS version: Old 3ds XL
- PKSM version: 7.0.1

Hello. First of all: **this SM is AMAZING!**

My only issue is something I cannot find any information about.
When using my Black 2 or White 2 card game, the PKSM does not show the cartridge or saves...
It only happens with these two games, and work fine with my White 1, Diamond, Ultra Moon (cia), Omega Ruby (cia) and the saves from Twlightmenu++.

Is something I am missing? Thanks in advance.

**Comment by piepie62** [comment]
That's interesting; it should. Could you try sending a Checkpoint dump of your B2/W2 save(s) so I can see if PKHeX recognizes it/them?

**Comment by trucidate** [comment]
> That's interesting; it should. Could you try sending a Checkpoint dump of your B2/W2 save(s) so I can see if PKHeX recognizes it/them?

Wow. Just when I was almost giving up for today, I tryied something:
Used the command to delete my normal save of Black 2 (still early game) and  then created a new one. Now it does read the cartridge... And I could edit and apply one script to make a test.

Geez. Gonna try it in White 2 soon, but it probably will work...?
Sorry if this wasted your time.

**Comment by FM1337** [comment]
Since it's been 11 days and the author claims to have wiped the save file, there is no need to keep this issue open.
