### ISSUE TITLE
Stuck on launch

### ISSUE THREAD

**Issue by ichimoon** [FlagBrew/PKSM#1093]
**Describe the bug**
When opening PKSM, it becomes stuck on launch & gives no further response. I can't revert back to v5.1.4 of pksm anymore as there is no sprites of pokemon showing up when i installed it again through FBI & pskm v6 is having the same problem as it also becomes stuck at launch.

**To Reproduce**
1.Open PKSM 7.0.1 on the main interface of 3DS
2. 3DS display PKSM logo
3. Becomes stuck and gives no response,home button becomes unfunctional
4. Force shutdown of the 3ds

**Information about your environment**
 - OS version: 11.13.0-45U (luma v10.0.1)
 - PKSM version: 7.0.1
 - Entrypoint: CIA
 
Boot9strap , godmode9 , checkpoint:-latest version

**Comment by GriffinG1** [comment]
Well, downgrading might've fucked it up more. Do not downgrade. Ever.

"Becomes stuck" isn't accurate. PKSM can take some time loading up. You should be waiting.

Backup PKSM's extdata through Checkpoint, then delete its extdata through fbi>extdata.

**Comment by ichimoon** [comment]
ill try backing it up & booting it up again , in the case of waiting for it , i usually wait 5-10 minutes and tried many time hoping for it to work.

**Comment by GriffinG1** [comment]
Having a lot of backups at `/3ds/pksm/backups/` can slow it down. And if you force closed it even once, it could've corrupted your extdata and then it won't boot at all

**Comment by ichimoon** [comment]
If the extdata is corrupted, should i instead delete it & try booting pksm again?

**Comment by GriffinG1** [comment]
You're deleting it either way, as I said. The backup is to possibly save your bank

**Comment by ichimoon** [comment]
Does'nt seem to work , starting out pokemon with a completely new save & dont really care what i had in my bank.Deleted all backups and been waiting for 10 mins with no response.The only thing that comes to my mind now is deleting all the files related to pksm and deleting the newly created pksm extdata & trying again.

**Comment by ichimoon** [comment]
the wifi light is blinking while pksm is launching that may indicate pksm might still be functioning or loading up?

**Comment by ichimoon** [comment]
Even though i have no backups it has'nt loaded up in 17 min.

**Comment by GriffinG1** [comment]
Hmm, @piepie62 will have to take a look at this in the morning.

**Comment by ichimoon** [comment]
Tried booting it up again after deleting extdata and pksm folder still did'nt work. Here is what i had in 3ds/pksm 
![pksmfolder](https://user-images.githubusercontent.com/59360156/71580005-f00b5600-2b0f-11ea-88de-942a349d54ce.png)

made a backup of it before deleting it on my 3ds, I emptied the backup & backups folder in pksm .Hopefully this issue gets resolved, got me really annoyed.

**Comment by piepie62** [comment]
Did you delete your ExtData via FBI?

**Comment by ichimoon** [comment]
Yeah,Everytime before I tried booting up pksm but it didn't seem to work.

**Comment by GriffinG1** [comment]
Do me a favor and uninstall pksm through system settings, backup `/3ds/pksm/` and delete that as well, then reinstall pksm and try to boot it

**Comment by ichimoon** [comment]
I tried this before, but I'll try it again & yeah I checked other bug reports & no one seems to have this same problem .Really confused right now.

**Comment by ichimoon** [comment]
Made a video, point me out if i'm doing something wrong.New to github not sure how to upload vids so i just uploaded it to google drive .
https://drive.google.com/file/d/1MpJdQW0uZb3KJcvC3r-Fgto-O0BPpZJp/view?usp=sharing

Been waiting for literally an hour now still doesn't seem to work.

**Comment by ichimoon** [comment]
At this point i'm just giving up because don't really think there is way of fixing this for now , tried everything.I'll try again after a couple of updates for pksm .

**Comment by FM1337** [comment]
probably a bad SD card

**Comment by ichimoon** [comment]
Probably, but just a day before I updated pksm and booted it up,I switched my SD card and made extra sure I don't transfer any files that may be corrupted or harmful.
