### ISSUE TITLE
Bug Report - Japanese event names turned to jibberish in event database

### ISSUE THREAD

**Issue by orange-strawberry** [FlagBrew/PKSM#1094]
**Describe the bug**
When in the event database (tested with Platinum), Japanese event names are jibberish. For example, the event "うみのおうじ　マナフィ　プレゼント" (read "umi no ouji manafi purezento" is displayed in the database as "004 - ぅまねぉぅし" (004 - uMANEouSI).

**To Reproduce**
1. Go to 'Events'
2. Click on 'JPA'
3. Look at names in event database

**Expected behavior**
The cards titles should make sense

**Screenshots**
https://0x0.st/zkSS.png

**Information about your environment**
 - OS version: 11.13.0
 - PKSM version: 7.0.1
 - Entrypoint: Luma CFW

**Additional context**
Clicking on an event shows the proper name at the top.
It seems to be some sort of transliteration problem. There are a series of cards that begin with "さいきょうクラスプレゼント" (saikyou kurasu purezento) that are displayed as "ごぃがゆぅギヨブルセヲ" (GOiGAYUuGIYOBURUSEWO) consistently. Vowels seem to turn into small versions. If needed, I think that each kana is always replaced with another, I could take a closer look and make a list of what replaces what if needed.

**Comment by piepie62** [comment]
Hmm. Is this true only of G4 or does it apply to other generations as well?

**Comment by piepie62** [comment]
Also, if you could join our Discord for some extra troubleshooting, that woudl be wonderful

**Comment by piepie62** [comment]
Actually, never mind. As soon as I looked at the relevant code the problem was immediately apparent. Should be fixed in the next version

**Comment by piepie62** [comment]
Thank you for the level of detail you provided, it made testing the fix far easier as a person who does not read Japanese
