### ISSUE TITLE
Bug Report - Pokemon Bank only 50 boxes and Pokemon deleted / How can I fix it?

### ISSUE THREAD

**Issue by MercuryGamer** [FlagBrew/PKSM#1095]
When I opened PKSM and updated automatically (function enabled for me), there was a problem, in my Pokemon Bank there was no Pokemon in any box, and I have only 50 boxes (I had 2000 boxed before and 78 boxes were filled with Pokemon from many generations), I checked out the "backup" folder and the "banks" folder and there was nothing, so I want to recover either my boxes and all my Pokemon

**To Reproduce**
1. Opened PKSM
2. Click on 'Pokemon X game file'
3. Selected 'Deposit'
4. No Pokemon and only 50 boxes in bank (only the Pokemon from my save file)

**Expected behavior**
All Pokemon and boxes there

**Screenshots**

**Information about your environment**
 - OS version: 11.13.0-45U
 - PKSM version: v7.0.1-3b12f3e0
 - Entrypoint: (don't know)

Hope can be helped, I don't know so much about these things

**Comment by piepie62** [comment]
I probably can help you in a few hours on our Discord server. Please join and I'll get to you as soon as I can; I would work here, but this issue will require a fair amount of back-and-forth. Please ping me in the PKSM assistance channel when you're there; my ID is piepie62 there as well

**Comment by MercuryGamer** [comment]
Okay, I never was in Discord, son I'll try it, thanks

**Comment by MercuryGamer** [comment]
What's the four digits? because is asking me for them
And my ID is Mercury643

**Comment by MercuryGamer** [comment]
Well... I just don't know how to add people

**Comment by MercuryGamer** [comment]
My ID: Mercury643 #3035

**Comment by Gudf** [comment]
There should be an invite to the Flagbrew Discord server in the [README](https://github.com/FlagBrew/PKSM/blob/master/README.md).

**Comment by MercuryGamer** [comment]
I just don't know

**Comment by MercuryGamer** [comment]
Got it, and now?

**Comment by MercuryGamer** [comment]
Got response, thanks

**Comment by MercuryGamer** [comment]
I'm around, check your messages, I can't reply because "I don't have permission", but I already sent you a message

**Comment by piepie62** [comment]
Situation has been handled
