### ISSUE TITLE
How to import .pk7 files from Computer to PKSM

### ISSUE THREAD

**Issue by StagesOfMania** [FlagBrew/PKSM#1096]
I'm not too keen on how to use the app, but I'm trying to import my .pk7 files from my computer into my physical copy of Moon through PKSM. Because I don't understand how scripts work and would rather not want to brick my 3DS through trial and error, can someone please tell me how to transfer my pokemon. Any and all help is appreciated. 

Also, I know the QR scanner is part of the editor but my camera, along with the L&R buttons, do not work properly,

**Comment by piepie62** [comment]
The script you want is a universal one named `pkx-injector.c`. It will take any PK4, PK5, PK6, or PK7 files you have in `/3ds/PKSM/inject` and place them into your boxes, starting with box 1, slot 1, with validity-of-transfer checks, of course. It cannot brick your 3DS. No PKSM script that I know of can.
In the next update, you will be able to choose a single file to inject. That script will be named `injector.c`
