### ISSUE TITLE
Bug Report - Adding "None" to end of bag pocket removes last actual item

### ISSUE THREAD

**Issue by Lavorther** [FlagBrew/PKSM#1098]
**Describe the bug**
Inserting a new item at the bottom of a bag pocket and then selecting "None" removes the last actual item in the pocket, rather than canceling the item insertion.

**To Reproduce**
1. Open the Bag menu in PKSM, and go to any pocket that has items in it
2. Move the cursor down to the last entry, which is "None"
3. Press A to bring up the item selection menu
4. Press A again to select the first option, the "None" item
5. The last item in the bag (that was above the "None" entry) has now vanished, and the cursor is now below the actual item list.

You can go back to step 3 and repeat this as often as you like, removing one item at a time. As long as you don't move the cursor, it will stay in its original place, below the actual item list.

**Expected behavior**
I expected nothing would happen, that selecting "None" from the options would just cancel the item insertion since there was nothing there to begin with either.

**Information about your environment**
 - OS version: 3DS 11.6.0-39E
 - PKSM version: v7.0.1
 - Entrypoint: installed CIA

**Comment by GriffinG1** [comment]
Have verified this behavior persists on latest commit to master

**Comment by piepie62** [comment]
Has been fixed locally, waiting on feedback about another change to push at the same time
