### ISSUE TITLE
Feature Request - Reinject All Wondercards Slots

### ISSUE THREAD

**Issue by chan4est** [FlagBrew/PKSM#1103]
**Is your feature request related to a problem? Please describe.**
Right now you are able to renew wondercards in slots 1-3, but there should be a script to renew all of your wondercards. https://github.com/FlagBrew/PKSM/wiki/Script-Injector

**Describe the solution you'd like**
Give a script to renerw all wondercards.

**Describe alternatives you've considered**
Give us the ability to switch around wondercard slots we can run renew 1-3 over and over again.

**Additional context**
N/A

**Comment by piepie62** [comment]
I'm... confused by this request. What do you mean by re-inject, and what do you mean by "inject all wondercards"? The latter is definitely impossible taken literally; there are far more cards than there are slots.

**Comment by chan4est** [comment]
I updated my request and comment. I meant renew wondercard. There's a script that lets you replay the wondercards you already have in your game.

https://github.com/FlagBrew/PKSM/wiki/Script-Injector -> Other scripts -> Renew wondercard

**Comment by piepie62** [comment]
So, this is more of a script request than it is a PKSM request. As such, I'm going to close this issue here. Feel free to open one on the [script repository](https://github.com/FlagBrew/PKSM-Scripts) if you'd still like this.
