### ISSUE TITLE
Bug Report - PKSM Crashes when Converting Storage

### ISSUE THREAD

**Issue by ElectronicWizard** [FlagBrew/PKSM#1104]
**Describe the bug**
I've recently found my old New 3DS XL which had PKSM on it. When I went to load PKSM, it performed an update then closed. Now, whenever it launches, it gets to Converting Storage, then crashes.

**To Reproduce**
1. Launch PKSM
2. Wait for bouncing logo to stop
3. PKSM starts converting storage
4. it crashes

**Expected behavior**
PKSM to load to its menu

**Screenshots**
Just closes back to main menu, so no error message

**Information about your environment**
 - OS version: 11.13.0-45U
 - PKSM version: 8192 (8.0.0)
 - Entrypoint: SIGHAX

**Comment by piepie62** [comment]
Interesting... That behavior should be impossible now. Could you send a zipped Checkpoint backup of your PKSM ExtData?

**Comment by piepie62** [comment]
Also, please update to PKSM 8.0.1. I doubt it will help this problem, but it's might be necessary for troubleshooting later

**Comment by ElectronicWizard** [comment]
PKSM isn't visible in Checkpoint. Also, FYI, the QR Code on 8.0.1 still points to a 7.x release CIA file.
@piepie62

**Comment by ElectronicWizard** [comment]
@piepie62 FYI, the QR code on release 8.0.1 points to a 7.x CIA file.
Attached is the zip file.
[0xEC100 PKSM.zip](https://github.com/FlagBrew/PKSM/files/4100449/0xEC100.PKSM.zip)

**Comment by piepie62** [comment]
I don't know where you're getting that information, but it is not true; I just ran it through a QR decoder and it definitely points at 8.0.1. Your ExtData does seem to be correct; does it boot properly on 8.0.1?

**Comment by ElectronicWizard** [comment]
Ah, sorry. **8.0.0**'s QR code scans as 7.0.1. Image below. And no, still crashes. Video below.
![20200122_180620](https://user-images.githubusercontent.com/2800931/72942776-5451bc00-3d42-11ea-8af6-786acfaa6320.jpg)


[Video](https://streamable.com/3dywd)

**Comment by piepie62** [comment]
Ah. I'll fix that, thank you. Let me see what happens if I try using your ExtData backup on my system

**Comment by piepie62** [comment]
Hmm... I have no issues here. You appear not to have a bank file to even convert; what version did you upgrade from?

**Comment by ElectronicWizard** [comment]
I couldn't really tell you that, sorry. Unless there's some way for me to check in a log file or something.
I last updated PKSM in like... early 2018, so some version released around then.

**Comment by piepie62** [comment]
Would you happen to have a `/3ds/PKSM/bank/bank.bin` on your SD card? If so, could you upload it here?

**Comment by piepie62** [comment]
That would be the only other place a bank could be converted from, and would contain your bank if you had used PKSM before version 6.0

**Comment by ElectronicWizard** [comment]
Had to zip since otherwise Github wouldn't accept the upload.
[bank.zip](https://github.com/FlagBrew/PKSM/files/4100548/bank.zip)

**Comment by piepie62** [comment]
You appear to only have a single Drowzee in this bank. I'm able to reproduce the issue, though; would you like me to send you the PK7 file while I work to find it? If you don't care about the Drowzee, you can just delete that file and it'll start properly

**Comment by ElectronicWizard** [comment]
I don't particularly care about a single drowzee, no. If that's all that's in there, if you still wanna fix it feel free, but otherwise yeah I can just settle for deleting it.

**Comment by piepie62** [comment]
Likely; first I have to figure out what's wrong. If you don't care, feel free to delete it; being able to reproduce the issue personally makes this much easier

**Comment by ElectronicWizard** [comment]
Gotcha. I'll rename it to bank.bin.bak so I can test whenever the update is pushed. Yeah, I'll just delete and recreate it for now.

Also if you do figure it out let me know, curious what caused it to bug out.

**Comment by piepie62** [comment]
Ah, found it. I'm actually surprised that that compiled; I was initializing something improperly. I'll probably hold onto this until somebody else either has the issue and does need it fixed or the next release, whichever comes first; I've already done two releases today and I don't feel like my heart could really handle the hassle of a third. Thanks for your cooperation on this.

**Comment by ElectronicWizard** [comment]
Gotcha. Glad to have helped find that lol.
And understandable, can't imagine there are too many people that are upgrading really old PKSM banks at the moment ;p.

**Comment by Leighmond** [comment]
Funnily enough I just had the exact same problem in the same situation. Removing my bank.bin also solved the problem

**Comment by piepie62** [comment]
Yeah, it'll be fixed soon. For anyone that does read this thread, IF your bank was empty before upgrading, this is how you would fix it, if it was not, then PLEASE wait for the next version. I promise it's coming soon.
