### ISSUE TITLE
Error: Incorrect Size for version received

### ISSUE THREAD

**Issue by SkyBoltDom** [FlagBrew/PKSM#1105]
This error happens when entering a share code for the GPSS.

**To Reproduce**
1. Go to GPSS
2. Click on a slot
3. Enter a share code

**Expected behavior**
The pokemon would be downloaded.

**Screenshots
I don't have any.

**Information about your environment**
 - New 3ds XL (latest update version and model)
 - PKSM version: 8.01

**Comment by piepie62** [comment]
Oh, damn. Yes, I see exactly where that problem would occur; I had pretty close to the same code copy-pasted in multiple places and forgot to change one. I'll fix it right now; the release may be a little bit so I can accumulate a couple bugs to fix before I do one.

**Comment by SkyBoltDom** [comment]
ok thanks

**Comment by Dom13377** [comment]
Error persists when downloading generation 8 pokemon. All conditions are the same.

**Comment by piepie62** [comment]
First, don't comment on a closed issue from nearly a year ago. Second, try checking your PKSM version. You're out of date, if all conditions truly are the same
