### ISSUE TITLE
Error: Auto pokémon repair not working

### ISSUE THREAD

**Issue by zaulilloxone** [FlagBrew/PKSM#1106]
The issue is when I´m using the misc option in pksm 8.0.1 

When you try to check if a pokemon is legal you get several messages like these:

Not a pokemon!

And when you finally get the message about what´s wrong with the pokemon if you try to pres L to repair the pokemon you will get the message "Uknown HTTP Answer" Error: 10x0000190 press a to continue"

so the auto repair is not working while it was on pksm 8.0

could you fix it?

greetings my friends of pksm ;)

**Comment by piepie62** [comment]
This is a timeout on the website side. If you'd like to join [our Discord](https://discord.gg/bGKEyfY), we'll try to provide updates there, but I'm closing this issue because it's not a problem I can fix from PKSM's side.
