### ISSUE TITLE
Error : Segfault in storage

### ISSUE THREAD

**Issue by zaulilloxone** [FlagBrew/PKSM#1107]
This bug is very frecuent since this update, when I'm saving pokemon in my pksm storage and I change pokemon to another box the  app just crashes and I need to restart my console, the error that I can see for a few seconds is something like "Using a different language"

I'm using spanish instead of english, could you please fix this bug?

greetings to my friends of pksm! 

;)

**Comment by piepie62** [comment]
Could you back up your PKSM ExtData and send it to me? I want to check something about it, because that's an odd error.

**Comment by zaulilloxone** [comment]
how do I do that in the new version?

**Comment by piepie62** [comment]
Use [Checkpoint](https://github.com/FlagBrew/Checkpoint/releases)

**Comment by zaulilloxone** [comment]
[data.zip](https://github.com/FlagBrew/PKSM/files/4110034/data.zip)

Here you go!

**Comment by zaulilloxone** [comment]
and also the auto legalization is not working anymore since the update 8.0.1 

I think I did another report but I don´t see it anymore :(

**Comment by piepie62** [comment]
What box are you going to when it crashes?

Also, I closed that issue because it's not solvable through PKSM's side, it's a server-side issue. It should also be resolved by now

**Comment by zaulilloxone** [comment]
ok, you´re supposed to see my pokemon by now, when I select arceus, pikachu and jirachi and I put them into box 6 and then I tried to mov on of the pokemon back to my game the app crasshes and It tells me to reset my console, but pksm tells me a message about "Using a different languaje"

**Comment by piepie62** [comment]
Does it say exactly "Translation error"? If so, that's not actually related to language, it's a computer term that has a specific meaning

**Comment by piepie62** [comment]
And what game are you using?

**Comment by ChanceArthur** [comment]
I'm also frequently having this translation error. I can send a dump tonight if you'd like.

**Comment by piepie62** [comment]
What game are you using? And can you take a picture of a Pokémon's top-screen information that appears when you hover over it? This is sounding like a different issue than I initially thought: does it occur on trying to move a Pokémon into a game from storage, or just swapping storage boxes?

**Comment by ChanceArthur** [comment]
Soul Silver though TWiLightMenu. The translation error has occurred as I was switching between banks, and I believe at one point the app just froze and crashed with the error.

I've also had a bank get corrupted through resizing, requiring me to restore from Checkpoint backup. Not sure if that's related.

I'll mess around with the app tonight so I can provide further information.

**Comment by piepie62** [comment]
Corruption through resizing shouldn't be possible (at least in 8.0.1, can't speak for before then); I doubt it is. On switching between banks is interesting; what were the sizes of the two banks?

**Comment by zaulilloxone** [comment]
Yeah the other person is right, Let me see if I can find the dump in my 3ds. and my bank is 150 boxes long. the game I'm using is pokemon Omega ruby

**Comment by piepie62** [comment]
"the other person is right" does not tell me what they were right about. What exact operation are you attempting at the time of the crash? An answer from both of you would be very appreciated

**Comment by zaulilloxone** [comment]
In this case the action would be "Changing between boxes and putting pokemon into the game"
Thanks for reading, hope you can solve it.

**Comment by ChanceArthur** [comment]
For me it was likely going from my default bank of 37 boxes to a bank with a single box.

Of course now that I'm trying to make it crash, it's working fine. It did crash when I went back to game select and pressed Start for the Home menu. I've attached that dump as well as the crash dump from last night.

[dumps.zip](https://github.com/FlagBrew/PKSM/files/4111528/dumps.zip)

**Comment by piepie62** [comment]
Were either of you using the green cursor when your crashes happened?

**Comment by piepie62** [comment]
Also, for you, @ChanceArthur, I'm fairly certain I actually fixed the bug that led to crashes on bank load

**Comment by piepie62** [comment]
Okay, I think there were a couple bugs that got mixed together here because they happened in the same-ish area. I'm fairly certain I've fixed both of them, so when the next version releases, I'm going to close this issue. If the same bug(s) occur(s) then, please open another issue, but for now I'm going to consider this fixed.
