### ISSUE TITLE
Got an unknown HTTP response Error: 0x000001F7

### ISSUE THREAD

**Issue by SkyBoltDom** [FlagBrew/PKSM#1108]
**Describe the bug**
The bug happens when trying to auto-legalize a pokemon. I am not sure if this is a serverside error.
**To Reproduce**
1. Go to editor
2. Click on a pokemon
3. Check to see if legal, if illegal, auto-legalize

**Expected behavior**
The pokemon should be legal with no problems

**Screenshots**
I do not have any

**Information about your environment**
 - 3ds latest model XL, with latest software
 - PKSM version: 8.01

**Additional context**
Again, this might be a serverside error but auto-legalization worked in version 8.00

**Comment by FM1337** [comment]
Auto legality on the server-side is disabled while I rewrite the entire API to be more efficient and to fix bugs.

**Comment by SkyBoltDom** [comment]
Okay, that makes more sense, thanks.

**Comment by SkyBoltDom** [comment]
Where is the server located?
