### ISSUE TITLE
Bug Report - Black/White Wonder Card clear script breaks Wonder Card system

### ISSUE THREAD

**Issue by gaster7664** [FlagBrew/PKSM#1109]
Wonder Card injector is not working for Pokemon Black and White Cartridges

1. Load Pokemon Black or White
2. Go to Scripts and hit clear mystery gift script
3. go to events and inject one
4. save and open pokemon black or white and there is no wonder card

**Information about your environment**
 - OS version:11.13
 - PKSM version:8.0.1
 - Entrypoint:

**Comment by piepie62** [comment]
Will be good in the next version

**Comment by gaster7664** [comment]
Thank you for helping!
