### ISSUE TITLE
Bug Report - Innaccurate Pokedex "Seen" counts

### ISSUE THREAD

**Issue by SadisticMystic** [FlagBrew/PKSM#1110]
**Describe the bug**
After selecting a game, PKSM's main screen says I have "National Dex Seen: 803 / National Dex Caught: 807". This result is nonsensical, and appears to stem from four specific species: Wormadam, Scatterbug, Spewpa, and Vivillon due to the copies of those Pokemon that I have.

**To Reproduce**
1. Have a Pokemon species where the only copies of it you've ever seen on that save file are of a form other than #0, such as Alola forms or non-Spring Deerling
2. Load the save file into PKSM
3. Verify that such species aren't being counted in the Seen tally. (The Caught tally, which consolidates all of a species' forms into a single flag, is unaffected by this.)

**Expected behavior**
PKSM should correctly be able to track Seen counts among species, even if the none of the ones that have been seen are form #0.

**Information about your environment**
 - OS version: 11.13.0-45
 - PKSM version: 8.0.1
 - Entrypoint: boot9strap

**Comment by piepie62** [comment]
Yeah, I can see exactly how this would happen in the code. Not quite sure how to fix it (dex code is the part I understand the least), but I'll see what I can do
