### ISSUE TITLE
Bug Report - PKSM Crashes when i change size of a new bank

### ISSUE THREAD

**Issue by Pachislot** [FlagBrew/PKSM#1111]
**Describe the bug**

I had created a second bank and wanted to change the size from 1 to 10, after that pksm closes and my console restarts, now I can't access the storage because the same thing happens when I want to enter.

**To Reproduce**

1. change size of the new bank
2. enter in the bank
4. it crashes

**Screenshots**

closes back to main menu, no error message

**Information about your environment**

 - OS version: 11.13.0-45U
 - PKSM version: 8.0.1

**Comment by piepie62** [comment]
Could you make a Checkpoint backup of your PKSM ExtData and send it here, please?

**Comment by Pachislot** [comment]
[Bank.zip](https://github.com/FlagBrew/PKSM/files/4115169/Bank.zip)

**Comment by piepie62** [comment]
Hmmm... I'm not quite sure what's going on there, actually. My best guess is that you can't use accented characters in ExtData paths. Let me see what I can do about that in code, but let's see if changing that manually fixes the problem here

**Comment by piepie62** [comment]
[NewBank.zip](https://github.com/FlagBrew/PKSM/files/4115177/NewBank.zip)
Try restoring this backup

**Comment by Pachislot** [comment]
when entering pksm throws me this error
![IMG_20200126_224405](https://user-images.githubusercontent.com/60329703/73145749-0f08f380-408e-11ea-86cd-ef285f20c49b.jpg)

**Comment by piepie62** [comment]
What version of Checkpoint are you using?

**Comment by Pachislot** [comment]
I didn't use checkpoint, pksm wasn't among the titles, so I used jk save manager

**Comment by GriffinG1** [comment]
Use checkpoint. Pksm is stored in extdata. Jksm doesn’t properly support pksm

**Comment by piepie62** [comment]
Make sure it's the latest version of Checkpoint; it has special support for PKSM

**Comment by Pachislot** [comment]
I already have the latest version, but the pksm still doesn't appear anywhere

**Comment by piepie62** [comment]
Well, first, for confirmation, the latest version is 3.7.4. Second, press X to go to the ExtData section, where it should come up. If it doesn't, scroll left and right through the pages to find it. It will be there if you're on the proper version.

**Comment by Pachislot** [comment]
Ok I get it now, I already restore with checkpoint the "newbank" save, still with the first problem.
The accented characters are not the problem.

**Comment by piepie62** [comment]
Well, that's good to know. Now I'm not certain what it could be, though

**Comment by piepie62** [comment]
Oh, now that I'm looking at the content of this bank... it's a mess. Let's see what happens if I set it all to the proper empty data

**Comment by Pachislot** [comment]
how? the bank that gave me the problem is empty

**Comment by piepie62** [comment]
[NewNewBank.zip](https://github.com/FlagBrew/PKSM/files/4115456/NewNewBank.zip)
Try this one, please. If it works, then I think I've already fixed the problem, but I'll check the code just to make sure

**Comment by piepie62** [comment]
It was empty, but I think that a different bug caused it to not be set to the "I am empty" data

**Comment by Pachislot** [comment]
it worked! Thank you so much!
Anyway, how could I prevent it from happening again?

**Comment by piepie62** [comment]
Unfortunately, I think that might only be fixed in the next update. I think I'm going to rush this one a little bit quicker than I originally planned because of that; that's a really bad bug

**Comment by piepie62** [comment]
Found and fixed the bug; leaving this issue open until next release
