### ISSUE TITLE
Storage bad transfer error

### ISSUE THREAD

**Issue by uhhhidknicole** [FlagBrew/PKSM#1112]
When I try to move a full box of Pokémon into storage using the button on the top right, I get an error that says MISSING: STORAGE_BAD_TRANSFER Impossible species, press A to continue. Pressing A does nothing, I have to press home and exit the app entirely to get out of the dialogue.

1. Have a box of Pokémon in your PC
2. Go to storage
3. Press the yellow box swap button on the top right
4. Error will pop up

I don't think this is normal, I've tried to move a box of pangoro first and then I tried a box of vivillon. Both give me the error and I can't get out of it until I press home.

I have PKSM version 8.0.1
3ds system version 11.13.0-45U

**Comment by piepie62** [comment]
"I have to press home and exit the app entirely to get out of the dialogue" That's actually untrue, it just pops up the dialogue for (I think) every empty slot. I believe I have actually fixed this already, let me check

**Comment by piepie62** [comment]
I have not, I'll get on that right now

**Comment by uhhhidknicole** [comment]
Awesome, thanks! :)

**Comment by FM1337** [comment]
err keep this open until it's fixed

**Comment by uhhhidknicole** [comment]
Ah sorry 😅

**Comment by piepie62** [comment]
Alright, fixed it in code. Still leaving the issue open until the next release, though

**Comment by uhhhidknicole** [comment]
Oo okay! I appreciate your work, I love this app 😄
