### ISSUE TITLE
OT legality

### ISSUE THREAD

**Issue by gordindoido** [FlagBrew/PKSM#1113]
When I am going to generate a Pokémon in pksm using my X save the pksm always says "invalid current handler cannot be past gen ot for transferred specimen" how do I resolve this to make the Pokémon legal?

**Comment by SkyBoltDom** [comment]
What pokemon are you trying to make?

**Comment by gordindoido** [comment]
> What pokemon are you trying to make?

Bulbassaur in x

**Comment by gordindoido** [comment]
But it happens to everyone I try to generate except in sun and moon but in x y alpha Shaphire and omega ruby ​​this message always appears

**Comment by piepie62** [comment]
Those are the errors that show up when you create a Pokémon without changing the met location to a proper place. Either look up valid values or use the auto-legalization once its issues are fixed, which should be fairly soon
