### ISSUE TITLE
Bug Report - Seg Fault from using Multi-Select to try to put a blank slot into a Game Box

### ISSUE THREAD

**Issue by josephmoyer** [FlagBrew/PKSM#1115]
**Describe the bug**
Seg Fault occurs when using Multi-Select to place a not full amount of Pokemon into a game box, or at least Pokemon Y, Omega Ruby, Moon, and Ultra Sun.

**To Reproduce**
1. Go to Storage.
2. Change cursor mode to multi-select.
3. Select a not full box of Pokemon.
4. Attempt to place the Pokemon into an empty Game box.
5. Crashes PKSM with a Seg Fault requiring the system to shutdown.

**Expected behavior**
Pokemon get placed in the box.

**Screenshots**

**Information about your environment**
 - OS version: 11.13.0-45U
 - PKSM version: 8.0.1-334f6f0d
 - Entrypoint: Luma 10.0.1-c913de1

**Additional context**
This might be related to the already fixed issue about the MISSING: impossible species error that was also related to empty slots. Also, doesn't crash when placing into the PKSM Storage boxes, but I think it's related to the program treating empty slots as Pokemon. I can upload crash dumps tomorrow.

**Comment by GriffinG1** [comment]
See #1107

**Comment by piepie62** [comment]
Yep, already known and fixed. Will be fixed in the next version
