### ISSUE TITLE
Alpha Sapphire crashing after injecting events and transferring Pokemon from storage. 

### ISSUE THREAD

**Issue by Zezuca** [FlagBrew/PKSM#1118]
So, today I got my old Pokémon Diamond cartridge and cloned my Pokémon to the PKSM storage, so I could transfer to my Alpha Sapphire Save. Problem is I tried to inject the Shiny Charizard English event and dragged my whole gen IV box (prompted the message warning about the Gen 6 changes), and everything seemed good.

Then I tried to open my game, it crashed after the initial cut-scene, before title screen. I was prompted to turn off the 3ds and so I did. Right now, I cannot inject my save file back because the game crashes. Tried deleting it via JKSM, but then the game won't launch because it says save file os corrupted. 

The Alpha Sapphire is running from my SD card. No physical copy. 
I can open my save and its backup via PKSM, but I cannot launch the game anymore.

Thank you in advance. 

I'm currently running the latest 3ds Firmware (11.13.045U) and Luma 10.1
PKSM is version 6.2.1-f8657b3

**Comment by GriffinG1** [comment]
Your PKSM is two major versions out of date. Please update to the [latest version](https://github.com/FlagBrew/PKSM/releases/latest). In addition, use [Checkpoint](https://github.com/FlagBrew/Checkpoint/releases/latest) instead of JKSM. Also, please upload the crash dump.

**Comment by piepie62** [comment]
I can't do anything with a crash dump from 6.2.1, lol. Update to the latest version as Griffin suggested, and if it occurs again, open a new issue. I quite doubt it will.
