### ISSUE TITLE
I use SteelHax on my new 3DS and also use homebrew. I placed the PKSM.3dsx file in the 3DS folder but everytime I start PKSM up, it just shows me a red screen.  How do I fix this?

### ISSUE THREAD

**Issue by TheRealPhoenixx** [FlagBrew/PKSM#1119]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Information about your environment**
 - OS version:
 - PKSM version:
 - Entrypoint:

**Additional context**

**Comment by piepie62** [comment]
PKSM is only usable via Luma3DS. A guide to help you install Luma exists [here](https://3ds.hacks.guide/)

**Comment by piepie62** [comment]
Also, actually use the template instead of trying to shove your entire issue into a single subject line next time.
