### ISSUE TITLE
pksm.cia error

### ISSUE THREAD

**Issue by jslinkard7890** [FlagBrew/PKSM#1120]
when i open a pksm.cia file on my 3ds it has an archive: init failed error how do i fix this?

**Comment by Louprenard** [comment]
Are you trying to install it through an installer (ie: FBI) or to open it, like a folder or a zip archive ?
Because it is a special type of file and it needs an appropriate software to extract the components.

**Comment by GriffinG1** [comment]
Lou, please do not try and assist if you don't know what causes the error.

@jslinkard7890 back up your pksm extdata using [Checkpoint](https://github.com/FlagBrew/Checkpoint/releases/latest), then immediately restore it. This has solved the issue 9/10 times. In addition, make sure that you're using [v8.0.3](https://github.com/FlagBrew/pksm/releases/latest) of pksm. Finally, next time you open an issue, please fill out the provided template.

**Comment by piepie62** [comment]
If the above does not work, then please join [our Discord server](https://discord.gg/bGKEyfY) so we can figure out what's going on

**Comment by jslinkard7890** [comment]
i installed pksm to my 3ds and it had an error when it opened i wanted to
know how to fix that error.







2020年2月3日(月) 7:30 Chris Feger <notifications@github.com>:

**Comment by GriffinG1** [comment]
I have told you how. If that doesn’t work, do what pie said.
