### ISSUE TITLE
PKSM keeps Dumping when I try to move/edit my Pokémon

### ISSUE THREAD

**Issue by Joshua-Parker** [FlagBrew/PKSM#1121]
What do I do to stop PKSM from dumping and telling me to save file or shutdown. I can’t edit my Pokémon's due to it.

**Comment by piepie62** [comment]
I cannot help you without more information. Also, "dumping" makes no sense in this context

**Comment by piepie62** [comment]
Fixed in the Discord: user was running a non-current version
