### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by emanrdesu** [FlagBrew/PKSM#1122]
**Is your feature request related to a problem? Please describe.**
I don't like how I have to use netcat to edit .sav files.

**Describe the solution you'd like**
I'd like for local .sav files to be able to be edited. Maybe require them to be in a specific directory and then have them show up like games do.

**Describe alternatives you've considered**
Also, why does the console freeze during wireless transfer? Maybe fix that too?

**Comment by GriffinG1** [comment]
You can already edit them. Please read the [wiki](https://github.com/FlagBrew/pksm/wiki).

**Comment by piepie62** [comment]
Specific page is [here](https://github.com/FlagBrew/PKSM/wiki/Configuration#extra-saves).
As for wireless transfer not freezing the console, the attempts we've made to make the network operations non-blocking have not worked.
