### ISSUE TITLE
PKSM not updating and forcefully shutting down 3DS.  

### ISSUE THREAD

**Issue by Rcxd999** [FlagBrew/PKSM#1124]
Hi. I decide to boot up PKSM today, since Pokemon Home came out, and when I opened it up, it tried to update but keeps getting stuck at 662KB every time. After a few tries, I said F*** it and closed the screen and reopened it and forced it to skip the update. But now every time I try to use PKSM, it somehow forces my 3DS' energy bar to flash red and then forcefully shuts down my 3DS. Is there anything anyone can recommend to fix either the update issue or the shut down issue or is it just PKSM in need of a serious fix?

**Comment by piepie62** [comment]
"it somehow forces my 3DS's energy bar to flash red and then forcefully shuts down my 3DS"
That behavior is literally impossible to be caused via PKSM's code. My guess is that your battery might be loose in your 3DS. As for updating not working, try using FBI and scanning the QR code in the release page.

**Comment by Rcxd999** [comment]
Sorry for the slow reply, I was just trying a few things. Firstly, the download seems to working fine now. Secondly, the battery seems to be for everything I turn the 3DS on and it displays 100% or 75% power and then in about a minute or two it starts flashing red and says battery is low and then shuts down but when I turn it back on, it displays 100% or 75% battery again. I seem to have managed to prevent it shutting down by plugging it into the charger but the issue doesn't seem to PKSM and could be old battery (it is an old 3DS XL, the one with Yveltal and Xerneas on the front) or it could be some kind of virus, based on how fast the power drops and then shuts the 3DS off but the battery itself still has charge when I turn it back on. If that's the case, not sure how to fix it sadly.

Edit: Download just finished and it seems to work fine, at least while in the charger. The issue definitely seems to be one of the two previously mentioned issues.

**Comment by piepie62** [comment]
That does sound like a bad battery, yep. Sorry about that, but glad that PKSM is working properly, at least
