### ISSUE TITLE
Only showing 50 boxes in storage

### ISSUE THREAD

**Issue by TheFloosh** [FlagBrew/PKSM#1125]
Opened up PKSM, went to move Pokemon in my bank and could only see 50 boxes in the storage, Pokemon are there it just cuts off at the 50th box.

**To Reproduce**
1. Open PKSM
2. Click on Pokemon Ultra Sun
3. Selected Storage
4. Only 50 Boxes show up

**Expected behavior**
All my bank boxes should show up

**Screenshots**

**Information about your environment**
 - OS version: 11.13.0-45U
 - PKSM version: 8.0.3-ba2a8bdc
 - Entrypoint: Don't know

**Additional context**

**Comment by piepie62** [comment]
So, quick confirmation: You had a bank with Pokémon in it past the 50th box, then it got cut off to 50 boxes?

**Comment by piepie62** [comment]
If the above is true, then this behavior can only happen during upgrades. What version of PKSM did you upgrade from?

**Comment by TheFloosh** [comment]
Yeah

**Comment by TheFloosh** [comment]
I can't remember exactly the version but is was fairly outdated.

**Comment by piepie62** [comment]
Was it before or after v6.0.0?

**Comment by TheFloosh** [comment]
Not sure, it was probably a little over a year old.

**Comment by TheFloosh** [comment]
i did also have the issue on 8.0.0 where my pokemon didn't show up at all.

**Comment by piepie62** [comment]
Hmm... not quite helpful. Could you send three files from your SD card? I need `/3ds/PKSM/backups/bank.bin` if it exists, `/3ds/PKSM/backups/<your bank name, defaulting to pksm_1>.bnk.bak`, and `/3ds/PKSM/backups/<your bank name, defaulting to pksm_1>.bnk.bak.old`

**Comment by TheFloosh** [comment]
how do i send you the files?

**Comment by piepie62** [comment]
If you don't mind having your Pokémon public, you can upload them here (probably zipped together; I don't think GitHub likes custom extensions). If you would rather keep them private, then you can join [our Discord](https://discord.gg/bGKEyfY) and DM me with them. My Discord username is `piepie62#3412`, should you choose that route

**Comment by TheFloosh** [comment]
[My PKSM Files.zip](https://github.com/FlagBrew/PKSM/files/4193288/My.PKSM.Files.zip)

**Comment by piepie62** [comment]
Oh, actually, one more question. Does the bank have 50 boxes, or does it still have 150? (it looks like that was your original size, if not, please tell me what it was)

**Comment by TheFloosh** [comment]
50 wasn't the original, i had about over1680 pokemon, so about 56

**Comment by piepie62** [comment]
I meant 150 looks like your original size

**Comment by TheFloosh** [comment]
oh the bank only has 50 boxes sorry

**Comment by TheFloosh** [comment]
when i go to storage and hit L from "Storage 1" it goes straight to "Storage 50".

**Comment by piepie62** [comment]
Alright, I think your Pokémon are in your backup. Unfortunately, I have to go to a class right now, but once I'm back I'll walk you through the steps to restore it (it's not going to be a simple copy-paste, before anyone else chimes in).

**Comment by TheFloosh** [comment]
No problem, take care and thanks for helping.

**Comment by piepie62** [comment]
Alrighty, I'm back. You'll need to install the **latest version** (3.7.4) of [Checkpoint](https://github.com/FlagBrew/Checkpoint/releases) if you haven't already.
So, first thing to do is make a Checkpoint backup of your PKSM ExtData. Once you have that, you'll need to copy `/3ds/PKSM/backups/pksm_1.bnk.bak` to `/3ds/Checkpoint/extdata/0xEC100 PKSM/<new backup name>/banks/pksm_1.bnk`, overwriting the file that is there. After that, you'll need to edit `/3ds/Checkpoint/extdata/0xEC100 PKSM/<new backup name>/banks.json`. Change the line `"pksm_1": 50` to `"pksm_1": 150`. If there is a comma at the end of that line, leave it there. If there is no comma at the end of that line, do not add one. Once you've done that, open Checkpoint back up and restore the Checkpoint backup. After checkpoint is done restoring, you can close Checkpoint and open PKSM; your Pokémon should be there

**Comment by TheFloosh** [comment]
It worked, you're a life saver, thank you so much for your help.

**Comment by piepie62** [comment]
No problem! Sorry that happened in the first place, that's a really weird logic error that I'll have to look into

**Comment by ShadowSlayerFX1** [comment]
thanks

**Comment by GriffinG1** [comment]
Hi @ShadowSlayerFX1. This issue has been closed for over a year and a half, and you weren't involved in this issue. If you're having issues with PKSM, please open a new issue, or join the [discord server](https://discord.gg/bGKEyfY). Thanks.
