### ISSUE TITLE
Bug Report - PKSM Not Opening on Homebrew

### ISSUE THREAD

**Issue by WhopsInc** [FlagBrew/PKSM#1126]
I don't really know if this is a bug, it might just be my inexperience with these types of things, but when i installed PKSM.3dsx i just threw it in my 3ds folder for homebrew with nothing else, don't know if i did something wrong (probably) butIi can't seem to find good tutorials that i can actually understand. So when I try to open it through my homebrew the bottom screen is just red and nothing else happens. Honestly it probably is because i'm inexperienced but help would be appreciated either way.

 - 3DS Version: 11.13.0.45U
 - PKSM Version: 8.0.3
 - Entrypoint: Steelhax

Apologies if this info is incorrect.

**Comment by GriffinG1** [comment]
This is not a bug. All flagbrew apps ***require*** cfw. You can install cfw by following [this guide](https://3ds.hacks.guide). If you run into issues installing cfw, join [this discord server](https://discord.gg/C29hYvh).

**Comment by WhopsInc** [comment]
> This is not a bug. All flagbrew apps _**require**_ cfw. You can install cfw by following [this guide](https://3ds.hacks.guide). If you run into issues installing cfw, join [this discord server](https://discord.gg/C29hYvh).

Yeah it works now which is no surprise since I have no idea what i'm doing, so thanks
