### ISSUE TITLE
Scanning PKHeX QR Code doesn't seem to work

### ISSUE THREAD

**Issue by Aaeeschylus** [FlagBrew/PKSM#1127]
**Describe the bug**
So I am not sure if I am doing things incorrectly but according to the wiki, (https://github.com/FlagBrew/PKSM/wiki/Editor) I can scan codes generated from PKHeX straight into the box. I am trying to do this yet when I go to scan the code, it just sits there with the camera on as if it doesn't recognize the QR code. I have tried changing the distance between the 3DS and the code as well as putting the code on different displays (2 different PC monitors, one curved, one not + tablet) and it still doesn't seem to recognize the QR codes. However, the GPSS codes are working (when in the right spot and even when in the editor, though it says the code is in the incorrect format there).

**To Reproduce**
1. Go To editor
2. Press L+R
3. Doesn't scan PKHeX code in view (an example code: 
![image](https://user-images.githubusercontent.com/7753205/74587638-64a93e00-5045-11ea-92d2-fabdb9b5d384.png)

**Information about your environment**
 - OS version:
 - PKSM version: v8.0.3-ba2a8bdc
 - Pokemon Game (if necessary): Ultra Moon 

I did see another post about this ( #560 ) and saw that BernardoGiordano mentioned to "follow the guidelines precisely" but have been unable to find whatever guidelines that relate to the QR Scanner are.

**Comment by GriffinG1** [comment]
Gen 7 codes are right on the edge of what the 3ds camera can handle. Just keep trying.

**Comment by piepie62** [comment]
Yep, Griffin is right. Can't do anything else, unfortunately; I can't just magic resolution that isn't there into existence.
