### ISSUE TITLE
Bug Report - Issues with Gen IV Wonder Card

### ISSUE THREAD

**Issue by AnimeSaranWrap** [FlagBrew/PKSM#1128]
I recently downloaded this application, mostly for use in challenges, and experiencing wonder card events that I could never experience. Well, I started a new file on Pokémon Platinum, and decided to try to get the wonder cards for the Member Card, and the Secret Key. I have Wonder Card unlocked, but, they don't show up, at all.

1. Insert Pokémon Platinum
2. Go to ‘Events’
3. Find Member Card and Secret Key wonder card events
4. Open Pokémon Platinum
5. Navigate to Mystery Gift

**Expected behavior**
The Wonder Cards shouldn't appear in the selection, or in my case, the option to view won't even appear.

**Screenshots**
![20200215_125811](https://user-images.githubusercontent.com/61093232/74593739-115acf80-4ff4-11ea-9be9-2dea39e499b0.jpg)
![20200215_125821](https://user-images.githubusercontent.com/61093232/74593740-19b30a80-4ff4-11ea-8bce-89e94aeace7b.jpg)
![20200215_130510](https://user-images.githubusercontent.com/61093232/74593743-233c7280-4ff4-11ea-97dd-b2b3f7115056.jpg)

 - PKSM version: v8.0.3-ba2a8bdc

**Comment by GriffinG1** [comment]
You need to actually pick them up from the delivery man in the pokemart

**Comment by AnimeSaranWrap** [comment]
> You need to actually pick them up from the delivery man in the pokemart

It's been a while since I did Gen IV, but I don't see a delivery man, at all, even after injecting—

OH, I'M AN IDIOT

I'm so sorry, I kept going to the Pokémon Center, I remembered it wrong!
