### ISSUE TITLE
What happened to the old living dex script?

### ISSUE THREAD

**Issue by Barone23** [FlagBrew/PKSM#1129]
The old living dex script would inject the full living dex at level 100 with 6 IVs if I remember correctly. The universal script now included gives all Pokemon at level 1. Is there a link to the old script?

**Comment by piepie62** [comment]
The old script had multiple things wrong with it, including inconsistent legality and being huge sizewize, with one huge script for each game group. The current one is much smaller than all of them put together, works on every game, and at least nearly every Pokémon is consistently illegal, making it far better, in my opinion. I'm currently seeing what I can do about making one that's smaller yet has more useful functionality

**Comment by piepie62** [comment]
See https://github.com/FlagBrew/PKSM-Scripts/pull/20; this will likely be merged soonish
