### ISSUE TITLE
I have to save twice to access boxes 

### ISSUE THREAD

**Issue by mrex999** [FlagBrew/PKSM#1131]
I have an issue with pksm regarding access boxes with Pokemon Pearl, I tested something, I first open my game, then save the game, after that I exit the game and reopen it, then I save again, and open pksm, and finally I can edit my boxes content, if I don't do this, I can't edit anything in my boxes, hope there's a solution to this soon, there's another issue with platinum, I can use well pksm with Pokemon games from 5th to 7th generation

**Comment by piepie62** [comment]
What version of PKSM? What exact behavior is observed with "I can't edit anything in my boxes"? I need more information; that simply isn't enough.

**Comment by piepie62** [comment]
As no more information has been given, I'm closing this issue.
