### ISSUE TITLE
All Pokémon are shown as Giratina (Origin) sprites

### ISSUE THREAD

**Issue by mikelandzelo173** [FlagBrew/PKSM#1132]
**Describe the bug**
All Pokémon are suddenly shown as Giratina (Origin) sprites. The Pokémon themselves are perfectly fine when inspect them in PKSM or boot up the game. A reboot of the 3DS or PKSM itself does not change anything. It worked fine the last time I used PKSM on version 8.0.3 so there was no update since then. The last action I did before Giratina took over was "cloning Pokémon" from the PKSM bank to the module.

**To Reproduce**
On my 3DS it's the default behavior whenever I start PKSM. I'm not entirely sure how this got activated.

**Expected behavior**
All Pokémon should show the correct sprites.

**Information about your environment**
 - OS version: 11.9.0-42E
 - PKSM version: 8.0.3

**Additional context**
Please tell me which files you need to investigate this issue and I'll upload them here.

**Comment by piepie62** [comment]
Hehehehe... Check your system date

**Comment by mikelandzelo173** [comment]
> Hehehehe... Check your system date

wow, I never thought I get rolled that easily 😅 I'll give you that one 🙈

**Comment by Gabittee** [comment]
Hey i have the same problem someone can help me ? :(

**Comment by mikelandzelo173** [comment]
> Hey i have the same problem someone can help me ? :(

It's an April fools' joke. Your 3DS' date is on April 1st.

**Comment by Gabittee** [comment]
Oh okay i understand XD thanks for the help :)

**Comment by Zenhaa** [comment]
Well hahaha, nice one xD
