### ISSUE TITLE
Bug Report - red screen freeze

### ISSUE THREAD

**Issue by Wesistopheles** [FlagBrew/PKSM#1134]
Just did a fresh install of the latest version and I keep getting stuck on the red screen after launch, causing me to force restart my 3ds.

**Comment by piepie62** [comment]
PKSM *requires* Luma3DS to be installed. You cannot start it with *hax methods of loading homebrew. If you wish to use PKSM, install Luma3DS via [this guide](https://3ds.hacks.guide/)
