### ISSUE TITLE
Event (Mystery Gift) missing in database

### ISSUE THREAD

**Issue by CornFlakes999** [FlagBrew/PKSM#1135]
Hi
I looked all over the place in the "events" but there seems to be that these two Wondercards are missing:
Own Tempo Rockruff with "Thunder Fang" for Ultra Moon (UM) [Only the one with "Fire Fang" for UltraSun is in the list)
Paris Vivillion for X/Y [Only a similar one is in the list from Summer 2014]
Here are the Wondercards on Project Pokemon:
Rockruff (select the Thunder Fang one) >> https://projectpokemon.org/home/files/file/2385-own-tempo-rockruff-dusk-lycanroc/
Paris Vivillon >> https://projectpokemon.org/home/files/file/943-0511-xy-paris-pkmn-center-6014-vivillon-pokeball-forme-fre-m/

I hope its possible to add them to the database and it's not too much to ask.
In case it is difficult to do, I'm also happy to send a $5 compensation for the work with Paypal (:

Thanks!!

**Comment by GriffinG1** [comment]
PKSM pulls mystery gift data from [this repo](https://github.com/projectpokemon/EventsGallery/tree/master/Released). Any issues with missing mystery gifts should be brought there.

**Comment by CornFlakes999** [comment]
Thanks for the fast reply!!!
I just check on that repo. According to this, it should have both, but in PKSM I only see one :(
By chance am I just stupid here and missing something I should enable first?
I attached the screen for the repo saying they have both Rockruff for US and UM, but also a screen of the Event Database shown in PKSM when I have Ultra Moon inserted. It only has the one and selecting it says "Fire Fang" and Game US
![DSC_1538](https://user-images.githubusercontent.com/61567671/75500963-621ee080-5983-11ea-80f7-1786a593a6e2.JPG)
![DSC_1540](https://user-images.githubusercontent.com/61567671/75500967-66e39480-5983-11ea-87c5-3e81cdbacdc3.JPG)

**Comment by piepie62** [comment]
That's... disgusting. Game Freak, why the *hell* did you clone your Wonder Cards?

**Comment by piepie62** [comment]
The way that we mash the mystery gifts into a couple files is completely automated, and doesn't take receiving game into account as part of the metadata. To the tool we use, those two cards are identical.

**Comment by piepie62** [comment]
As for the Vivillon, is there something that's showing up that's similar in the same way?

**Comment by CornFlakes999** [comment]
I'm not a coder, so the following comment is either complete nonsense to you or a helpful hint. it seems on the Gen 6 (X/Y/OR/AS) PKSM is able to show multiple entries, even if the Wondercard is identical. Example here the "Arceus" with 0081. It shows all variants. (Shiny with Silk Scarf and all the Non Shiny with a random plate.
Depending on which one I would select for the Arceus, I get either "Shiny, holding Silk Scarf" or "Regular, Holding xxx Plate" (16 WC with 0081 ID in Total)
I think I seen some other wondercards with the same ID showing side by side, but would have to check before making a definitive statement
![DSC_1541](https://user-images.githubusercontent.com/61567671/75505082-2be75e00-598f-11ea-8914-67a9086e548c.JPG)

**Comment by piepie62** [comment]
The tool works by taking the ID, species, form, and maybe gender (don't remember on that one) into account when it's building the database. Arceus's typed variants are actually different forms, though nothing in-game tells you that

**Comment by piepie62** [comment]
Yes, the gender is taken into account

**Comment by CornFlakes999** [comment]
> As for the Vivillon, is there something that's showing up that's similar in the same way?

Yup, according to the Mystery Gift Repo, Paris Vivillon shares the same ID with the "Summer 2014" event.
Which also made me notice another WC missing due to shared ID (In PKSM is the "0518 Pinsirite" is 
available, but the 0518 Heracrossite" not)
But then again, Wondercard ID 0504 which gives either Electabuzz for Y or Magmar for X seems fine
![DSC_1542](https://user-images.githubusercontent.com/61567671/75505520-42da8000-5990-11ea-8b9b-16bd70ed521e.JPG)![DSC_1543](https://user-images.githubusercontent.com/61567671/75505529-4a9a2480-5990-11ea-9e77-ee8ae56342e0.JPG)

**Comment by CornFlakes999** [comment]
> The tool works by taking the ID, species, form, and maybe gender (don't remember on that one) into account when it's building the database. Arceus's typed variants are actually different forms, though nothing in-game tells you that

I see.
Yeah, the Rockruff event is identical. only that for US it has "Fire Fang" as Move 3 and "Thunder Fang" on UM

**Comment by piepie62** [comment]
Hmph... the item brought up a good point that I was about to ask you about, actually. I'm thinking I might completely overhaul the way the packing tool works; it's currently a custom Python thing, but if I used PKSM's code itself then I wouldn't have any issues with taking all of this into consideration

**Comment by CornFlakes999** [comment]
> Hmph... the item brought up a good point that I was about to ask you about, actually. I'm thinking I might completely overhaul the way the packing tool works; it's currently a custom Python thing, but if I used PKSM's code itself then I wouldn't have any issues with taking all of this into consideration

I can see if maybe I find more missing events due to the ID thing being the same. If that is helpful to have a list on it?
By the way, just for your effort on this, I started a pledge on Patreon! That one should help general development I hope (:

**Comment by piepie62** [comment]
A list actually wouldn't be all that helpful, no. Thank you for the offer, though

**Comment by CornFlakes999** [comment]
> Hmph... the item brought up a good point that I was about to ask you about, actually. I'm thinking I might completely overhaul the way the packing tool works; it's currently a custom Python thing, but if I used PKSM's code itself then I wouldn't have any issues with taking all of this into consideration

Maybe if the tool considers difference in the OT Name that would sort out a few missing events I guess.
For example the 0511 Vivillon is mostly the same, but for the Paris one it has OT "Paris", while the other one has "SUM2014"
But rockruff has the same OT (at least technically, because it gets set by the game after receiving). so only the move #3 is different here...

**Comment by CornFlakes999** [comment]
> A list actually wouldn't be all that helpful, no. Thank you for the offer, though

Okay, sure.
Maybe it wouldn't even that big of a list anyway if nobody has noticed missing events so far

**Comment by piepie62** [comment]
So, I've actually run into a bit of an issue. The way that PKSM builds would mean that using PKSM's code for the packer would require dependencies that I don't think are even available on the default devkitPro-updater provided environment. That would... not be great, to say the least, as then people would have to go through more complicated setup to build PKSM than "just install these packages"

**Comment by piepie62** [comment]
I'm not entirely certain how I should handle this without that, though.

**Comment by CornFlakes999** [comment]
> I'm not entirely certain how I should handle this without that, though.

Hmm, I see. Well there is one thing I could think of. But I'm not sure if it's a valid idea or even more complicated. What if PKSM did a local storage for some of the missing events? You know like the scripts are included in the PKSM (without extra installs). What if something similar would be used for for mystery gifts. By default it would still access the online library but there would also be some menu or button to access "local files". This would probably also have the side effect that users could place their own files into that directory

**Comment by piepie62** [comment]
Actually, PKSM basically does do that. Problem is, it still expects the packed format, and while you *could* shove everything into the packed format without the aliasing of different-language duplications to each other (that's the real point of the packer, by the way: that way we don't have to make some ridiculous hardcoded map that relates files to each other), that's not very easily doable

**Comment by piepie62** [comment]
The current general solution is to use the `inject.c` script to actually inject wonder cards of a user's choosing (from `/3ds/PKSM/inject`) into games, but I don't like having events that aren't actually duplicates being treated like they are duplicates, which is why I didn't just instantly send you to that solution and close this issue

**Comment by CornFlakes999** [comment]
I see... In an earlier message you mentioned, that your packer see wondercards as different, by taking species, form and gender into account. Wouldn't it be possible, by using that approach to also compare what moves a Pokemon has? Or the OT? for example the "Rockruff" is mostly the same, but the move3 is different. The wondercard is also game specific (One for US and one for UM), so there are some slight differences here. On the missing vivillon, I think its the Trainers name and OT that is different from the one currently being listed in PKSM

**Comment by CornFlakes999** [comment]
So if I understand coding right, we would need to find something in the wondercards, that tells your packer "This is different" without being completely rewritten, so it sees some of the wonders cards as 2 not 1.
Right?

**Comment by piepie62** [comment]
"Wouldn't it be possible by using that approach to also compare what moves a Pokémon has?" That one would be fairly easy, yes. The OT would be more difficult, but also doable.

**Comment by piepie62** [comment]
The problem with things like the OT, though, is that if I were to *just* say "if the OTs are different, then the Wonder Card is different", then certain wonder cards that I would want to be considered the same, such as ones that have an OT difference between languages but everything else is the same, would be considered different

**Comment by CornFlakes999** [comment]
> That one would be fairly easy, yes.
That one would add a whole bunch of events for GEN7 to start with. I just checked a few minutes ago on PKSM (because I got curious) For the 2018Legends events is a similar issue as with Rockruff. The Wondercard IDs are reused, but the Pokemon is supposed to be different depending on receiving game. Example: 2018 Legends Dialga. On UM it is level 100 and has a gold bottle cap along with different moves. But regular Moon got it at Lv. 60 with different moves, level and item. This applies to almost all 2018 Legends: Ultra games got higher levels and different moves of the same Pokemon
<img width="718" alt="Screen Shot 2020-03-03 at 1 42 02 PM" src="https://user-images.githubusercontent.com/61567671/75822431-cdd2c600-5d54-11ea-9cca-52231f956bb6.png">

**Comment by CornFlakes999** [comment]
> The problem with things like the OT, though, is that if I were to _just_ say "if the OTs are different, then the Wonder Card is different", then certain wonder cards that I would want to be considered the same, such as ones that have an OT difference between languages but everything else is the same, would be considered different

Yeah! That makes sense! It would get cluttered if the multi-language cards would show up as duplicates in the default list (They would probably don't show duplicate if someone selects the language sorting at the bottom, but I'm not sure how frequently that is used, I myself usually just use the default list)

**Comment by CornFlakes999** [comment]
> The problem with things like the OT, though, is that if I were to _just_ say "if the OTs are different, then the Wonder Card is different", then certain wonder cards that I would want to be considered the same, such as ones that have an OT difference between languages but everything else is the same, would be considered different

I think I also found a possible solution, regarding Vivillon (and maybe some others that are affected the same way). Don't compare the OT name, but rather the OT ID. That should avoid the issues of un-grouping wondercards that belong together, but still add other events as different. (I attached the Vivillon details for example)
<img width="690" alt="Screen Shot 2020-03-03 at 2 05 40 PM" src="https://user-images.githubusercontent.com/61567671/75824420-54d56d80-5d58-11ea-8256-abdec033d85a.png">
<img width="690" alt="Screen Shot 2020-03-03 at 2 05 13 PM" src="https://user-images.githubusercontent.com/61567671/75824427-59018b00-5d58-11ea-8c36-64886c96ce5e.png">
<img width="690" alt="Screen Shot 2020-03-03 at 2 05 26 PM" src="https://user-images.githubusercontent.com/61567671/75824428-599a2180-5d58-11ea-981e-9c5a97e3536e.png">

**Comment by CornFlakes999** [comment]
Hi
Just checking in, are there any updates on this? Thanks!

**Comment by piepie62** [comment]
Honestly, still trying to think of a good way to handle this. I wouldn't be surprised if different-language WCs had different TIDs, given that the OT name is different, which means they wouldn't merge together if I tried that. Moves and items (including items on their own) should be fairly doable, but that doesn't solve your Vivillon problem.

**Comment by CornFlakes999** [comment]
I understand. Yes, if different-language WCs would be split up by this, it wouldn't be ideal. /:
The Moves and Items check/comparison would probably bring around 99% of the currently missing events into it (like Rockruff, or the 2018Legends which re-use the ID but are different in Level and Moves between regular S/M and US/UM.)

I just tried to check on the TIDs. If the preview in PKSM is any indication it appears to stay the same when I tap on the available languages in the bottom screen. (I checked some 2018Legends and US/UM events)
I try to be as helpful as possible here, so if it helps I have a spare X and a spare Ultra Moon that I could restart the game on and play it in a different language than English to see if events received there get the same TID like they get when I receive them on the English one or if they show as different? 
From my experience with most events, the visible Trainer ID is always the same, even if a different language or trainers name. If the ID is different, it's usually a different event. But I know that there are also some invisible IDs and numbers, so these could be different then...
Also attached are some screen examples as shown in PKSM regarding the TID/SID shown, when changing the language on the bottom screen.
![DSC_1919](https://user-images.githubusercontent.com/61567671/77488702-357bae80-6df3-11ea-95ba-014abb0ca289.JPG)
![DSC_1920](https://user-images.githubusercontent.com/61567671/77488704-36acdb80-6df3-11ea-861e-42f6a666f27a.JPG)
![DSC_1921](https://user-images.githubusercontent.com/61567671/77488706-37457200-6df3-11ea-9246-5a073e0f289e.JPG)
![DSC_1922](https://user-images.githubusercontent.com/61567671/77488707-37de0880-6df3-11ea-9bae-1b39216f2b21.JPG)
![DSC_1923](https://user-images.githubusercontent.com/61567671/77488708-38769f00-6df3-11ea-8896-73953ed8a5ae.JPG)
![DSC_1924](https://user-images.githubusercontent.com/61567671/77488709-390f3580-6df3-11ea-957c-08862fe654c0.JPG)
![DSC_1925](https://user-images.githubusercontent.com/61567671/77488712-39a7cc00-6df3-11ea-8186-1482f386f098.JPG)
![DSC_1926](https://user-images.githubusercontent.com/61567671/77488713-3a406280-6df3-11ea-9144-e423d844876b.JPG)








![DSC_1918](https://user-images.githubusercontent.com/61567671/77488694-314f9100-6df3-11ea-8258-96ef53cc63a9.JPG)

**Comment by piepie62** [comment]
Okay, I've gotten a program working with the proper formatting. It's a native application, though, so I'll have to figure out a good way to distribute it for building PKSM.

**Comment by CornFlakes999** [comment]
> Okay, I've gotten a program working with the proper formatting. It's a native application, though, so I'll have to figure out a good way to distribute it for building PKSM.

Nice! That sounds promising. Thanks for the update. (:
If there is anything I can check/test on my side, let me know.
I got all XY Omega Ruby and a Alpha Sapphire along Moon, Sun and the Ultra games, so I can do further research on certain events if needed. Especially on those that appear the same but have slight differences between game version or like 2018Legends that are even more different between SM games and USUM games

**Comment by piepie62** [comment]
I have now integrated that program into PKSM's build system. I'll be uploading the changed database files to FlagBrew's website soon, which should change them for you via the automatic database updating (assuming you have automatic updates enabled).

**Comment by CornFlakes999** [comment]
Oh, wow! That is amazing!
Yes, I can check it out now or as soon as you say it's updated.
And yes, I think I have automatic updates enabled, it does say "Checking for updated event database" (or similar) every time on start up

**Comment by CornFlakes999** [comment]
> which should change them for you via the automatic database updating (assuming you have automatic updates enabled).

I just checked in PKSM with Ultra Moon, to see about Thunder Fang Rockruff, but I still don't see it /:
Am I doing something wrong here? At the start it does say "Checking for Update" and "Checking for updated gift database" and in settings it says "Automatically Update PKSM = Yes"
Or is it better to go to the releases Page here and get the most recent one?
in PKSM it says PKSM v8.0.3-ba2a8bdc

**Comment by piepie62** [comment]
Nope, I just haven't updated the database yet. I don't actually remember the process (whoops) and I'm waiting for our site programmer to get back to me on how to do that. Sorry about that!

**Comment by CornFlakes999** [comment]
Ah, I see. Well no rush then :)
I just thought I had setup something wrong here on my end...

**Comment by FM1337** [comment]
Closing this issue now has it appears to have been resolved, if it is not please feel free to re-open!
