### ISSUE TITLE
Pokemon levels aren't edited on team

### ISSUE THREAD

**Issue by mrex999** [FlagBrew/PKSM#1136]
Today, when I was trying to edit a Wartortle from Pokemon Blue on my team, I noticed that the level didn't change on the game, then I exited the game and reopen pksm to check if I forgot to change this Pokemon level, but I saw that the level was exactly as I changed it, then I reopen Pokemon Ultra Sun and swap my Pokemon to the boxes and magically its level changed from 32 to 49, any idea on how to fix this?

**Comment by piepie62** [comment]
Not entirely certain what you're saying. Did you change level in PKSM, had it look fine, put it in the box, and the changes were reverted, or did you change level in PKSM, and it looked unchanged, then you put it in the box and the changes took effect?

**Comment by mrex999** [comment]
I changed a level 32 wartortle to level 49, when I checked this Pokemon on Ultra sun its level was 32 even after I changed on plan, when I put it in a box, it's level magically changed to 49

**Comment by piepie62** [comment]
Okay, that sounds like party data not being updated. I'm fairly certain I actually noticed that and fixed it recentlyish, so that fix should be there in the next version

**Comment by mrex999** [comment]
Hmmm it's pretty strange because I was able to change levels of my Party Pokemon, this is the first time this happens, or maybe I think that without knowing

**Comment by mrex999** [comment]
For now I will edit my Pokemon in the boxes

**Comment by piepie62** [comment]
This is now definitely fixed
