### ISSUE TITLE
Cant see server IP in any way

### ISSUE THREAD

**Issue by somethingtorage** [FlagBrew/PKSM#1137]
running  v8.0.3-ba2a8bdc and i cant find server ip in any way, when i click y cursors color changes and thats it, if i click on wifi it opens the gpss pokemons and thats it, Because of it I cant transfer some of my pokemon from pc to my 3ds. Im probably doing something wrong, but no matter what button i press server Ip doesnt appear in the bottom like its suppose to.

**Comment by FM1337** [comment]
I'm sorry, but there is some confusion here:

In storage the wireless button is used for enabling GPSS mode, if you're attempting to use "servepkx" it is no longer supported (in fact servepkx was removed a few versions ago). You can use PKHeX (with PKHeX plugins) to upload your Pokemon from your desktop to GPSS and then download them from GPSS onto your 3DS.
