### ISSUE TITLE
Invalid Location - Transferring Between AS to UM

### ISSUE THREAD

**Issue by RedNova888** [FlagBrew/PKSM#1140]
When I transferred to UM my Deoxys from the Sky Pillar in AS, I checked to see where it was met, and it said invalid location in PKSM. There was legality before transfer and after transfer. When I loaded that save with the transfer into my game, the game recognized that it traveled from Hoenn. I edited in PKSM the data to see if I could put “Hoenn” without any problems, but the Pokemon was then marked as illegal. When I go into PKHeX with the Deoxys before I changed it in PKSM, PKHeX correctly identifies its original met location, Sky Pillar, even when I transferred it to a Pokémon ultra moon save and made the pk6 file a pk7 file. Because of this, I wonder if PKSM has an incomplete database of possible met locations for a Pokémon for each game.

Reproduction:
-catch Deoxys from Sky Pillar in AS
-transfer the Deoxys from AS to UM using PKSM
-also, load the file for Deoxys into PKHeX and make it a .pk7 file
-the Deoxys will give the met location of Sky Pillar in PKHeX, but it will give the met location of Invalid Location in PKSM

Expectation:
I expected that the met location of Deoxys in PKSM and PKHeX will be Sky Pillar

Screenshots Attached:
-Deoxys Data in PKSM
-Deoxys Data in PkHeX (before modifying met location data)

 - OS version: 11.13.0-45U
 - PKSM version: 8.0.3
 
Additional Context:
-Deoxys has been modified to have Perfect IVs
-Deoxys’s OT_Name, TID, and SID have been changed to prevent Nintendo from banning my AS Trainer
![87E1441F-784F-47C6-9F60-5A0F8C7E33FC](https://user-images.githubusercontent.com/30453795/76812961-e4553480-67cc-11ea-8a4b-664158a39518.jpeg)

![B17FE64F-9D9E-49ED-94F5-8CC23C373BA8](https://user-images.githubusercontent.com/30453795/76813079-38601900-67cd-11ea-9200-cdfe78d4ca82.jpeg)

**Comment by piepie62** [comment]
This was a (valid, in my view) difference between PKSM and PKHeX. As there have been multiple complaints, I think I'll change it to the way PKHeX works. Do note, though: there isn't actually a met location difference. I simply interpreted locations with regard to the currently loaded save, where PKHeX did it with regard to the origin game.

**Comment by RedNova888** [comment]
Thank you for the explanation.

**Comment by GriffinG1** [comment]
Ah, this was left open for a reason — anything fixed is not closed until the next release, to attempt to mitigate duplicate issues being opened

**Comment by piepie62** [comment]
Yep, going to reopen because of the reason above. Thank you for trying to help, though
