### ISSUE TITLE
PKSM v8.0.3 Will Not Load 

### ISSUE THREAD

**Issue by WarriorCatBluestar** [FlagBrew/PKSM#1144]
Hello there! I'm a relatively old user of PKSM; my friend got it on my New 3DS for me back in 2018. Obviously, new updates have occurred, and I was unaware of these, so my PK was at v5.1.4. I was guided by the owner of FBI on how to properly update that app and use the QR reader to get the newest addition of PKSM on my 3DS. I got it, the app disappeared for a second along with FBI, but then they both came back. I noticed that PK had a more updated look to it, so naturally I thought it worked. Thing is, when I clicked on it, the app loaded like normal, with the Homebrew icon/words on the bottom and top of the screen, but then both screens went dark. Then, the top portion had the same PKSM icon as before on the menu screen, and was bouncing around like how the old DVD icons used to do. I couldn't do anything, like press buttons or move around, and I had to turn off my 3DS in order to get it off. This happened when I had my Ultra Sun copy in the card slot and without. Any help is appreciated!

**Comment by GriffinG1** [comment]
Your old files are being completely converted. Let it sit for 10 minutes or so, and if issues continue, join [this discord server](https://discord.gg/bGKEyfY).

**Comment by WarriorCatBluestar** [comment]
> Your old files are being completely converted. Let it sit for 10 minutes or so, and if issues continue, join [this discord server](https://discord.gg/bGKEyfY).

Ah, ok. I'll come back or join if it persists.

**Comment by WarriorCatBluestar** [comment]
I figured it out, just did exactly as you said. Thanks!

**Comment by CreativeUsername69** [comment]
I am having this issue, and I am not updating, this is my first time using it. It has been going for 20+ minutes.

**Comment by GriffinG1** [comment]
@CreativeUsername69 please join the discord linked in my prior message for further help. This problem is too in-depth to be solved on GitHub issues.

**Comment by CreativeUsername69** [comment]
Never mind. I intended on using it to edit my platinum ROM for twilight menu, using the direct file feature, and it wasn't loading past the DVD screen, but now I inserted a cartridge of a game and it loaded.
