### ISSUE TITLE
Event pokemon database error message

### ISSUE THREAD

**Issue by southboston** [FlagBrew/PKSM#1146]
When i try to bring up the events on ultra moon i get this error message that i provide in the picture that i had taken.
![20200329_024722](https://user-images.githubusercontent.com/18722400/77843248-487edd80-7169-11ea-99f8-3b175bbd5d67.jpg)

**Comment by piepie62** [comment]
What is in your `/3ds/PKSM/mysterygift` directory?

**Comment by southboston** [comment]
Absolutely nothing, might be why im getting that error message lol.

**Comment by southboston** [comment]
Should i uninstall then reinstall?

**Comment by piepie62** [comment]
That will do nothing. What is your auto-update setting set to?

**Comment by southboston** [comment]
It was on and then i turned it off, if i need it to be on then ill change it back.

**Comment by piepie62** [comment]
WAIT, I just remembered what caused this in another user. What is your bank size?

**Comment by piepie62** [comment]
Also turn it on, I was thinking you had it off

**Comment by southboston** [comment]
On one of them its at 2000 and the others are all the same, and alright ill turn it back on and keep it on.

**Comment by piepie62** [comment]
That's the problem, then. Recentlyish (when I added multibank support), I shrunk the maximum down to 500. Overlarge banks are still grandfathered in, but that is an issue that is known to be caused by them: the gifts stop working. If you have Pokémon in boxes 501-2000, DON'T just resize the bank to 500. Instead, move them all to the first 500 boxes, then resize

**Comment by southboston** [comment]
Alrighty and after i do that what do you think i should to be able to get the mystery gift database to work again?

**Comment by piepie62** [comment]
Yes, that should fix it.

**Comment by piepie62** [comment]
As it's been four days, I'm going to assume this was fixed by my suggestion.

**Comment by AvarageUMenjoyer** [comment]
where the heck can i find the bank that you guys talked about
