### ISSUE TITLE
Bug Report - Pokemons with giratina icon

### ISSUE THREAD

**Issue by jonnydv** [FlagBrew/PKSM#1147]
Hey guys, about 2 months I’m using the PKSM normally without any problems but suddenly today when I started, all my Pokémon’s appears with the Giratina icon. Anyone can tell what probably happened? Thanks!
![0A4C6ED5-2CBA-44F6-995F-7329517147C6](https://user-images.githubusercontent.com/62977968/78098778-5f663f80-73b6-11ea-8331-77b7f4bd3d55.jpeg)

**Comment by GriffinG1** [comment]
Check your console date

**Comment by jonnydv** [comment]
LOL, sure 
Thanks

**Comment by SnekJr** [comment]
hello, check the date on my console and it's still the same, delete and reinstall pksm and it won't remove
![IMG-20200401-WA0001](https://user-images.githubusercontent.com/62983850/78108641-077b0900-73b5-11ea-9440-5ec463ec8cf4.jpeg)

**Comment by EvenFlow1991** [comment]
I'm having the same problem, still didn't find how to solve the problem

**Comment by CrissInvierno** [comment]
I'm having the same problem, my data console it right and I reinstall PKSM, but the problem continue. Help please!

**Comment by Oreo639** [comment]
As was said before, check the date.
Then check the name of the discord linked in the `README.md`.
