### ISSUE TITLE
Bug giratina icon

### ISSUE THREAD

**Issue by SnekJr** [FlagBrew/PKSM#1149]
**Describe the bug**

**To Reproduce**

**Expected behavior**
![IMG-20200401-WA0001](https://user-images.githubusercontent.com/62983850/78109152-ecf55f80-73b5-11ea-9baa-b41358966196.jpeg)

**Information about your environment**
 - OS version:
 - PKSM version:
 - Entrypoint:

**Additional context**

**Comment by piepie62** [comment]
Duplicate of #1147

**Comment by SnekJr** [comment]
Podrían darme una solucion???
Lo de la fecha no sirve

**Comment by piepie62** [comment]
There's something special about your console's date
