### ISSUE TITLE
Pokemon thumbnails changed OR

### ISSUE THREAD

**Issue by Legato1911** [FlagBrew/PKSM#1150]
The Thumbnails used to work for each individual Pokemon. That changed somehow to Giratina
It shows up right after launching PKSM. In the Game everything works normal
**Expected behavior**

![IMG_20200401_113049](https://user-images.githubusercontent.com/36283886/78123033-dda20080-740d-11ea-801c-8f8a33327508.jpg)

Sorry for bad Quality
 - OS version: 11.13.0
 - PKSM version: 8.0.3

**Comment by FM1337** [comment]
What is today?

**Comment by Sherlock1024** [comment]
Me too

**Comment by Sherlock1024** [comment]
from yesterday, all pokemon icon change to Giratina, what happend?

**Comment by Sherlock1024** [comment]
OK April fool

**Comment by Sherlock1024** [comment]
i reinstalled PKMS a lot of times, and reset my 3DS...

**Comment by Legato1911** [comment]
> OK April fool

That could be
