### ISSUE TITLE
slot 2 ability bug

### ISSUE THREAD

**Issue by paf2014** [FlagBrew/PKSM#1152]
To Reproduce

Go to pksm
Click on Edit after loading a white2/black2 save
go to the described above pokemon species
See error
Problem
I cannot edit properly some pokemons of mine in last update of pksm in gen 5 savs.I cannot edit my shelmet,karrablast to have their slot 2 ability(only slot 1 aand HA are available in edit mode).I cannot also edit my slot 2 ability ralts and poliwag to slot 2 ability gardervoir,politoed because only slot 1 and HA are available to the evolved species

Information about your environment
OS version:last
PKSM version:last
Entrypoint:cia installed

**Comment by piepie62** [comment]
This is actually already fixed in commits. It'll be included in the next release
