### ISSUE TITLE
Bug Report - Brief Description/Name of issue

### ISSUE THREAD

**Issue by zongren** [FlagBrew/PKSM#1153]
**Describe the bug**
Nickname is Korean

**To Reproduce**
Pokemon Editor

**Expected behavior**
Nickname is English

**Screenshots**
![top_0000](https://user-images.githubusercontent.com/4525819/78468511-51fcdc80-774b-11ea-83be-da5af3f4be42.jpg)
![bot_0000](https://user-images.githubusercontent.com/4525819/78468512-545f3680-774b-11ea-88a7-466ce7ae92f1.jpg)

**Information about your environment**
 - OS version:11.13.0-45U
 - PKSM version:8.0.3
 - Entrypoint:

**Additional context**
I am using twilight menu playing diamond
rom is Japanese version

**Comment by piepie62** [comment]
The nickname is shown as it is in-game. That isn't Korean, it's Japanese, the language you're playing in.

**Comment by zongren** [comment]
it's definitely Korean

**Comment by piepie62** [comment]
Okay, either way, that's the language it should be. The nickname should not be changed from the in-game nickname, and I am certain that at least English works properly. It is possible, though unlikely (as I've had to fix it before) that Japanese is not properly parsed out

**Comment by zongren** [comment]
thanks
I will try a different rom
