### ISSUE TITLE
Box 2 Slot 2 Pokemon disappearing act bug.

### ISSUE THREAD

**Issue by RPGFAN128** [FlagBrew/PKSM#1154]
**Describe the bug**
The Pokemon in the 2nd slot on Box 2 will disappear -- this happens when doing the following steps below on a different box.  But as an interesting demo even if you are doing these steps in Box 2 you get to see the slot 2 Pokemon disappear!

**To Reproduce**
0. Necessary context:  Must have a Pokemon in storage that has been stored from a Gen 6 game. (Untested on Pokemon stored from a Gen 4-5 game)
1. Load Ultra Moon save.
2. Open Storage
3. Press the 'Y' button to go to the 2nd and 'blue' cursor.
4. Find Pokemon from step 0, and press the "Clone" button.
5. Try depositing it in the save file.  It will disappear without causing the message "The generation change will edit your Pokemon. Continue?"
6. Now go to Box 2 to see the Pokemon in the 2nd slot is gone!
6B. If you try this whilst on Box 2 you can see both the Pokemon you are holding and the slot 2 Pokemon disappear!

**Expected behavior**
The Pokemon in Box 2 slot 2 should not disappear.

**Screenshots**
My phone is not yet on this morning, but if you would like me to I can record a continuous video that demonstrates this hilarious glitch.  

**Information about your environment**
 - OS version:  11.13.0-45U
 - PKSM version: 8.0.3
 - Entrypoint:  Luma CFW

**Additional context**
Here are more details that probably do not matter.
The Pokemon Ultra Moon save is a backup from Checkpoint -- not an active "game save file" from cart or installed title.
The Box 2 in the save file contains 30 copies of the same pokemon.  Likely doesn't matter due to the fact that if you release one not in slot 2 (and hence only 29 Pokemon) you can see slot 2 disappear by trying to place the clone in the empty slot.
Final note --  if I accidentally left out any pertinent information please let me know.

**Comment by piepie62** [comment]
Ah, shit. You're not supposed to be able to clone while in blue-cursor mode, so that's the problem. Thank you for pointing this out.

**Comment by piepie62** [comment]
This should be fixed with the latest commit
