### ISSUE TITLE
TID SID

### ISSUE THREAD

**Issue by SuperBubbleGumHaZe** [FlagBrew/PKSM#1156]
Hey so I'm playing ultra sun when I want to edit the default SID/TID it only allowse to enter 5 digits when my ID has 6 please help thank you

**Comment by piepie62** [comment]
This is how PKSM is designed. There may be a different way that defaults work in the future, but for now, you can convert your TID/SID pair using these formulae:
`SID = (G7SID * 1000000 + G7TID) / 65536`
`TID = (G7SID * 1000000 + G7TID) % 65536`

**Comment by SuperBubbleGumHaZe** [comment]
Sorry what? There is only 5 places I can put digits

**Comment by GriffinG1** [comment]
Read exactly what pie sent.

**Comment by piepie62** [comment]
The latest commits just completely changed the way that SID/TID defaults work. In the next update, you'll have a Pokémon that is your default. For now, though, the formulae that I gave make a 5-digit TID/SID pair from a G7 TID/SID pair.
