### ISSUE TITLE
Unable to inject Event Pokemon/Wonder Cards into Pokemon Diamond

### ISSUE THREAD

**Issue by Aadhitya-T** [FlagBrew/PKSM#1157]
**Describe the bug**
I am not able to inject any event Pokemon or their wonder cards into Pokemon Diamond. When I press start to inject it, it immediately backs out without any confirmation message.

**To Reproduce**
1. Go to 'Pokemon Diamond'
2. Select a save file
3. Select 'Events'
4. Select an event
5. Press 'start'
6. Press 'B' twice to go back to menu
7. Press 'Download' button on bottom-right
8. Exit PKSM

**Expected behavior**
Expected Wonder Card to be present in Mystery Gift Menu and Event Pokemon to be available to pick up.

**Screenshots**
N/A

**Information about your environment**
 - OS version: 11.13.0
 - PKSM version: 8.0.3
 - Entrypoint: Launched via CIA

**Additional context**
N/A

**Comment by piepie62** [comment]
Does this happen for every event or just some of them?

**Comment by Aadhitya-T** [comment]
This happens for every event I have tested.

**Comment by piepie62** [comment]
And, just to make sure, something like a simple Pokémon edit does stick?

**Comment by piepie62** [comment]
Do note that party editing of stats and some other things are currently bugged; I'd suggest using a boxed Pokémon for testing instead

**Comment by Aadhitya-T** [comment]
Yeah editing a Pokemon still works. Not sure if it's relevant but I don't have any wonder cards in the game, so the injected one should be my first.

**Comment by Aadhitya-T** [comment]
Okay so I tried it again and I can recieve the Pokemon, but I still can't see the wonder cards.

**Comment by piepie62** [comment]
As in the Wonder Card menu on the very first menu screen is not showing up?

**Comment by piepie62** [comment]
Or the cards themselves are not showing up?

**Comment by Aadhitya-T** [comment]
The Wonder Card menu doesn't show up in the first menu screen.

**Comment by piepie62** [comment]
This is fixed for the next release.

**Comment by ccfman2004** [comment]
I too have this issue on 9.2.0.  If the save never received an official wonder card through Nintendo, the injector doesn't work and the game crashes when you talk to the guy in the PokeMart. Also the injected Wonder Cards don't show up in the card album from the main title screen.

**Comment by GriffinG1** [comment]
Please do not post on closed issues @ccfman2004.
