### ISSUE TITLE
Cant access downloaded gen 4 and 5 games

### ISSUE THREAD

**Issue by EYEMONSTERS** [FlagBrew/PKSM#1158]
i have all of the gen 4 and 5 games downloaded, but pksm can't detect them.

**Comment by piepie62** [comment]
Piracy is not supported here.

**Comment by EYEMONSTERS** [comment]
i didn't pirate the games, i ripped them from a cart so my little brother could play them. if that is piracy, then I'm sort for causing a fuss.

**Comment by piepie62** [comment]
What you said was "downloaded". Downloading games in any form is piracy. That said, have you tried reading [the wiki](https://github.com/FlagBrew/PKSM/wiki/Configuration#extra-saves)?

**Comment by EYEMONSTERS** [comment]
sorry for the misconception, i can see how that would have made it sound like piracy. i looked at the wiki, and I added a HeartGold save, it said that the save wasn't valid. is there a setting that I missed or something like that?

**Comment by piepie62** [comment]
You likely pointed PKSM at the ROM, not the save. It needs to point to the .sav file

**Comment by EYEMONSTERS** [comment]
i used the .sav, that i know. anything else it could be

**Comment by piepie62** [comment]
If the save in question was ever used with an emulator like desmume, it likely has a footer that you need to get rid of

**Comment by EYEMONSTERS** [comment]
i WAS using an emulator, but it was TWL++, if that has the footer, would I need to delete the save in order to get rid of the footer?

**Comment by piepie62** [comment]
TWiLightMenu++ is not an emulator, and does not have a footer. Just to check, however, the save in question should be exactly 524288 bytes. In order to get rid of the footer, you would need a hex editing program. In it you would remove the last 122 bytes.
