### ISSUE TITLE
Storage lost?

### ISSUE THREAD

**Issue by FDWAG** [FlagBrew/PKSM#1160]
I cloned some pokemon from the storage to UM, after that I tried to moved some from moon to the storage and an error happen, it said that it couldn't make a backup for the storage and after that my storage was empty... I looked into the "backup" file but the backup was for the empty storage. What happend? Did I lose over 700 pokemon?

I speak Spanish so sorry if something was not clear.

**Comment by piepie62** [comment]
Could you send your bank backups either here or, if you want them private, by PM in our [Discord server](https://discord.gg/bGKEyfY)? I'd need both your .bnk.bak and .bnk.bak.old files.

**Comment by FDWAG** [comment]
This is my full folder
[PKSM.zip](https://github.com/FlagBrew/PKSM/files/4554709/PKSM.zip)

**Comment by piepie62** [comment]
Unfortunately, yes, you are correct. There are no Pokémon in either of your backups. I'm not quite sure what happened; there are several reasons a backup could fail, such as SD corruption and not enough space. I'm very sorry this happened, but I can't help you more than that.
