### ISSUE TITLE
PKSM freezes on update check

### ISSUE THREAD

**Issue by gummypancakes** [FlagBrew/PKSM#1161]
Hello.
This is a bug that started about a couple of days after i got Pokemon Ultra Moon. I only got it for the shinies, so i decided to switch out my save with one i found online. However, ever since then, even after deleting and downloading multiple different versions of PKSM and even reverting back to my original save, this continues to go on.

The program boots up fine and pretty quickly, too. However, when i get to "Checking for updates..." my entire 3DS freezes and stays frozen until i power it off.

I run the latest version of Luma3DS as of May 2nd, 2020. I am on the latest version of 3DS firmware, and own a North American 3DS.

This problem persists with 8.0.3 and 8.0.2, both the CIA and 3DSX version.

Thank you for any help you can provide.

**Comment by piepie62** [comment]
Do you have a custom DNS enabled? If so, disable it and see if that helps

**Comment by gummypancakes** [comment]
> Do you have a custom DNS enabled? If so, disable it and see if that helps

That worked! Thank you! I did also try out Sudomemo after i got Ultra Moon which requires custom DNS so that's what did it. Once again, thank you!
