### ISSUE TITLE
Exception occurred : std : : bad_a l l oc

### ISSUE THREAD

**Issue by Tadelcat** [FlagBrew/PKSM#1162]
This error occurred when I tried to open a HGSS save.
I looked for something about it and didn't find it.
![15886925401991048970302532839136](https://user-images.githubusercontent.com/64853984/81084304-111ff100-8ecc-11ea-8984-df6f151033af.jpg)
I'm sorry if it is a mistake that already has a solution.

**Comment by piepie62** [comment]
You're opening the ROM file, not the save file.

**Comment by Tadelcat** [comment]
Lmaoo
