### ISSUE TITLE
Bug Report - pokemon pc storage issue/ omega ruby

### ISSUE THREAD

**Issue by Alfonsolo111** [FlagBrew/PKSM#1165]
**Describe the bug**
Whenever i open the PC(omega ruby) to move the edited Pokemon around, multiple issues will happen. if i move the Pokemon and try to swap the locations of one it will just replace both Pokemon with the former selected pokemon. if i try to remove an item from a pokemon in the PC it will just give me a copy of the item, if i move a pokemon to an open space, it will fill both slots with the selected Pokemon.

**To Reproduce**
1. open omega ruby with eddied pokemon
2. open PC in pokemon center
3. try to move them around with organize boxes
4. aforementioned bug

**Expected behavior**
no cloning or anything of that nature

**Information about your environment**
 - OS version: 11.13.0-45
 - PKSM version: 8.0.3

**Comment by SpiredMoth** [comment]
If I'm understanding you correctly, this is happening in-game?

If this is in-game, then it sounds like something is messed up with the game and not a PKSM issue. Are you using any cheats, plugins, or a romhack?

**Comment by Alfonsolo111** [comment]
> If I'm understanding you correctly, this is happening in-game?
> 
> If this is in-game, then it sounds like something is messed up with the game and not a PKSM issue. Are you using any cheats, plugins, or a romhack?

No, ive checked and made sure there are no cheats enabled/saved atm. It only started happening after i installed pksm and use it

**Comment by piepie62** [comment]
This cannot be caused by PKSM
