### ISSUE TITLE
PID Randomises when transfering from a higher gen to lower

### ISSUE THREAD

**Issue by Therisingsean** [FlagBrew/PKSM#1167]
Hiya boys, ran into this bug when moving pokemon i transfered directly from gen 4 to 6.
The gen 4 pokemon (that are now 6), when transfered to gen 5, get their PID's randomised.
This is repeatable by simply: moving pokemon the following way: 
Gen 4 -> Gen 6 -> Gen 5 -> Gen 6.
This is an issue due to the fact it makes the once-legal pokemon illegal

Have a good day lads, hope your families are safe and healthy

**Comment by piepie62** [comment]
First off, backwards transfer legality is never guaranteed; I consider this not to be a bug for that reason.
Second, to explain why this happens: when transferring backwards, the "ability number" must be set. In G4 and G5, the ability number is tied to the PID, and thus changes the PID when it's set
