### ISSUE TITLE
the language of my game changed to Japanese

### ISSUE THREAD

**Issue by Perdioa** [FlagBrew/PKSM#1168]
I was playing pokemon AS, and I decided to get a ralts egg for the app events, so I picked it up normally and when I got back to the game, it was already in Japanese
![15898123052595715909418748213854](https://user-images.githubusercontent.com/65551810/82225180-3b75a380-98fb-11ea-9872-a7c74d0e181c.jpg)
I used a saves management app, uninstalled the game, reinstalled but when I restored the save, it went back to Japanese, I don't know what to do.

**Comment by SpiredMoth** [comment]
You probably injected a Japanese event and left the "Adapt language to WC" option set to "Yes"

To fix your save: open the file in PKSM, go into Scripts, press `Y` and run `save-language.c`

**Comment by Perdioa** [comment]
I didn't click on "adapt the language for WC", I may have accidentally clicked it, but mainly because the 3ds touch is horrible to the finger, I believe this has not happened, It may be a bug that occurred only in mine, but due to not having found anything similar to this, I will close the issue, I managed to resolve as you said, thanks anyway.
