### ISSUE TITLE
Feature Request - sort wonder cards by region

### ISSUE THREAD

**Issue by Linkinworm** [FlagBrew/PKSM#1174]
So while looking through wonder cards for ORAS I realised that most of them would be for out of region for my game or largely unobtainable by most means, bar buying off ebay, or traveling to another country. having lost my save data recently I'm trying to add all the event pokemon back that I originally got through wifi events and serial codes.

**Describe the solution you'd like**
sort wonder cards by region, so UK/DE/Portugal etc only variations, AND how they were originally distributed, so for instance.
Volcanion - serial - distribution (filtered by country code) - Game (uk)
so then we would know how they were distributed in our specific location if any, as some of the cards have been set as english, but they are only for say germany for some reason.

**Describe alternatives you've considered**
set a global filter just to only show wonder cards that were legitimately obtainable, again so in the UK most serial events would have only been obtainable through smyths or game. maybe somehow parse serebii.net event data as they show exactly how every event pokemon was obtainable and then match them to the wonder card data including OT/ID, so far the zygarde ive seen the ORAS has an OT of XYZ which doesnt match the official legit zygarde even though he has the correct ID number / moves etc.

**Comment by piepie62** [comment]
Unfortunately, that data is not easily available from the wonder card data itself, which you seem to have gathered yourself, given that you mentioned parsing serebii. The wonder card database has also gotten so large that we pack them automatically, and trying to add that data manually would be very difficult. Parsing external HTML for data is also a really, really terrible option; even a small change in serebii's layout could very easily completely break any parser we build. I'm sorry, but this simply isn't possible in any reasonable way, and the fact that there's no legality issue (see "traveling to another country") makes doing that a huge amount of work for very little gain
