### ISSUE TITLE
Pksm 8.0.3 error during startup 0xC8804464

### ISSUE THREAD

**Issue by mhshehri** [FlagBrew/PKSM#1179]
Hello guys 

I have problem with Pksm 

When i Go to Download pksm.cia and put the file in cia folder and i open fbi to install the pksm.cia after i open the pksm in home menu this error show up :)

Photo Preview : https://ibb.co/ynyTVVS

**Information about your environment**
 - OS version: 3DSXL SYS 11.13.0-45U
 - PKSM version: 0xC8804464
 - Entrypoint:

**Comment by GriffinG1** [comment]
Back up your PKSM extdata using [Checkpoint](https://github.com/FlagBrew/Checkpoint), then restore it.

**Comment by mhshehri** [comment]
Can u told me how?

**Comment by piepie62** [comment]
Use Checkpoint's simple in-app interface to figure it out
