### ISSUE TITLE
Bug Report - Listing absent games in the VC Menu makes the system crash

### ISSUE THREAD

**Issue by gabmiral** [FlagBrew/PKSM#1182]
**Describe the bug**
When listing absent games in the Virtual Console menu of PKSM on 3DS, the system crashes.

**To Reproduce**
1. Open PKSM
2. Open VC menu
3. Press "Y"
4. System crashes

**Expected behavior**
A list of all Pokemon Games would show up

**Crash Report**
[Crash Report (packaged in a ZIP because GitHub wont let me send .dmp's)](https://github.com/FlagBrew/PKSM/files/4775238/crash_dump_00000000.zip)

**Information about your environment**
 - OS version: 11.13.0-45E, Luma v10.1.3
 - PKSM version: 9.0.0
 - Entrypoint: unSafeMode

**Additional context**
Updated PKSM with PKSM

**Comment by piepie62** [comment]
This should be fixed in commits. Recovery release will include it.

**Comment by Scmsr** [comment]
Any solution?
