### ISSUE TITLE
Gen4 catridge injection

### ISSUE THREAD

**Issue by Alextar1394** [FlagBrew/PKSM#1184]
When I inject a new Pokémon, as trying to copy the OT of my save file, writes nickname an OT name in japanese, i tried to change it but it is also in japanese.
![15921056408208787694688160128645](https://user-images.githubusercontent.com/66894510/84584088-08251800-adc6-11ea-8b75-233b3ca2938c.jpg)

**Comment by piepie62** [comment]
Yep, this is generation 4 text setting being broken. I'll have a fix for it up in a bit.

**Comment by Pedr0-o7** [comment]
It really is annoying.

**Comment by GriffinG1** [comment]
This has already been fixed in latest commits. If you’re so impatient that you can’t wait for the next release, you are free to compile PKSM yourself by following the instructions in the README, but please stop cluttering up the issue.
