### ISSUE TITLE
Qrスキャン落ちる

### ISSUE THREAD

**Issue by aiueo0721** [FlagBrew/PKSM#1185]
1編集を押す
2R+Ｌを押す
3エラーが発生
Osver.
Pksmver.
![IMG00027](https://user-images.githubusercontent.com/66917584/84599966-db016400-aeb0-11ea-985e-b72e586d5c45.jpg)
このバグが治らないとqrスキャンが実行できません、対処可能でしたらお願いします
Pksmver.9.0.1
より良いツールになることを陰ながら応援しています。

**Comment by FM1337** [comment]
Support is only possible in English please use a translator site and please use the provided bug template when reporting an issue.

**Comment by GriffinG1** [comment]
We don't speak Japanese, please use some [translating site/app](https://translate.google.com) to report an issue. Also, please actually use the issue template
