### ISSUE TITLE
Error during startup: 0xC92044E6

### ISSUE THREAD

**Issue by Artrios** [FlagBrew/PKSM#1187]
I've just updated to v9.0.1 but get an error when starting PKSM.

Error during startup: 0xC92044E6
Description: Archive::init failed.

**Information about your environment**
 - OS version: 3DSXL 11.13.0-45E
 - PKSM version: v9.0.1-fbb06ca6
 - Entrypoint:

**Comment by piepie62** [comment]
Try backing up and restoring your PKSM ExtData with [Checkpoint 3.7.4](https://github.com/FlagBrew/Checkpoint). If that doesn't work, I'll help in our [Discord server](https://discord.gg/bGKEyfY).

**Comment by scienceguy88** [comment]
I’m getting the same issue 
New3DSXL OS: 11.13.0-45U
PKSM : 9.1.0-70857380
I have already tried the backup and restore with checkpoint

**Comment by GriffinG1** [comment]
> If that doesn't work, I'll help in our [Discord server](https://discord.gg/bGKEyfY).
