### ISSUE TITLE
Start up error:0xFFFFFF95,when i open the vpn ,error :0xFFFFFFFF.Is my net has any problem?

### ISSUE THREAD

**Issue by Gygert** [FlagBrew/PKSM#1188]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Information about your environment**
 - OS version:
 - PKSM version:
 - Entrypoint:

**Additional context**

**Comment by GriffinG1** [comment]
Please actually fill out the issue template instead of filling up the title with hard to understand info

**Comment by Gygert** [comment]
I always connect internet but show me that "Add assets download failed,make sure ur connected to the internet"

**Comment by GriffinG1** [comment]
Are you using some form of proxy or custom dns?

**Comment by Gygert** [comment]
Maybe custom dns?

**Comment by GriffinG1** [comment]
Disable the custom dns then and try again

**Comment by Gygert** [comment]
emmmm...useless

**Comment by GriffinG1** [comment]
Fine. [Link here](https://github.com/piepie62/PKResources)
![5472E434-8D67-4C65-A421-FD1F7E6D06AF](https://user-images.githubusercontent.com/28538707/84730620-e9ed2280-af53-11ea-967e-83ff644c8bf1.jpeg)

**Comment by Gygert** [comment]
It'OK,thanks a lot!
