### ISSUE TITLE
Bug Report - Injector script error

### ISSUE THREAD

**Issue by Chaz777** [FlagBrew/PKSM#1189]
**Describe the bug**
When I try to use the injector.c script to inject a pk7 file located in 3ds/PKSM/inject I am getting an error message every time.

**To Reproduce**
1. Go to 'Scripts'
2. Click on 'Y for universal scripts'
3. Scroll down to 'Injector.c, select pk7 file'
4. See Error: Error Executing script! romfs:/scripts/universal/injector.c "press A to continue" which takes me to a screen that displays some code, and it says romfs:/scripts/universal/injector.c:33:38 
VariableGet Ident: 'strcasecmp' is undefined

**Expected behavior**
Expected it to inject the pk7 file into save. I am new to the process so maybe I am doing something wrong, but I am getting this error without fail. Not sure if it's the file structure, the script, or the file itself that is the problem.

**Screenshots**
None

**Information about your environment**
 - OS version: 11.13.0-45U
 - PKSM version: 9.0.1
 - Entrypoint: Homescreen app

**Additional context**
I am new to this whole process of using PKSM so I apologize if this is an error on my part or misuse of the program but I would appreciate some help in figuring this out. Thank you very much.

**Comment by piepie62** [comment]
Right, yep. That was part of a picoC upgrade, just forgot to re-add that function. Just pushed a fix; it'll be in the next version.
