### ISSUE TITLE
a Freeze Issue

### ISSUE THREAD

**Issue by YeetFeet5** [FlagBrew/PKSM#1190]
So I have the latest Version, I don’t remember the latest Version thing But here is the issue, When I Went To scripts and Saw Edit Trainer ID info, I Wanted to see what it did, So I used It and It Froze Saying: GameSync ID found: Editing Trainer info May Get You banned, What Do I do?
The Blue led Light is still on btw

**Comment by piepie62** [comment]
That's... not a freeze, it's a GUI popup with instructions.
