### ISSUE TITLE
Bug Report - PKSM doesnt update Latest Handler

### ISSUE THREAD

**Issue by Therisingsean** [FlagBrew/PKSM#1191]
PSKM doesnt seem to update the latest handler when transfering from one gen 6 save to another different one (lets use Y and OR as an example)

**To Reproduce/Confirm bug**
1. Catch a pokémon in one save
2. Use PKSM to transfer that pokemon to a different savefile (one with different PID and SID of course)
3. Backup the save and move to your pc (we're gonna use PKHEX to confirm)
4. view the caught pokemon in PKhex

PKhex ideally doesnt even need to be used to confirm this, if you check with the memory girl in OR she will use the name of the original OT (In this case Navi - the OT from Y)  when the name used should be that of the Latest Handler (The trainer currently holding the pokémon - in this case 'Seannie') 

I understand this isnt a major issue and can be solved easily (heck PKHEX doesnt even flag it as an illegal) but it may cause problems in terms of legitimacy, as well as it being an easy issue to solve (using PKHEX) its still a tedious task for those - like in my case, just transfered all 721 pokemon to their save. Any questions please ask further 
![its evidence](https://user-images.githubusercontent.com/34803333/85077691-c5df4a80-b1ba-11ea-9fbf-21db8c6813f9.JPG)

**Comment by piepie62** [comment]
That's what the "edit during transfer" option is for. With that set to "No", this doesn't happen.

**Comment by Therisingsean** [comment]
Would setting the option to "No" also solve the issue with the program not updating and setting the past residencey?

**Comment by piepie62** [comment]
I don't understand the question. "No" should be what *causes* the behavior you're experiencing, and I simply don't know what you mean by "past residency".
