### ISSUE TITLE
PKSM "error during startup: 0xC8804478" Please help

### ISSUE THREAD

**Issue by redired** [FlagBrew/PKSM#1192]
**Describe the bug**
i open pksm, and an advice apear saying
"error during startup: 0xC8804478" 
"description: archive:: init failed"
"press start to exit"

**To Reproduce**
1. Go to home menu/ homebrew
2. Click on 'PKSM'

**Expected behavior**
i open PKSM, see the pksm logo scroll move in an oblique direction only 3 seconds and see "error during startup: 0xC8804478 

**Screenshots**
![error pksm](https://user-images.githubusercontent.com/67134824/85095118-e3b2ac80-b1c6-11ea-95e9-83c169411c28.jpg)

**Information about your environment**
 - OS version: sys 11.13.0-45U
 - PKSM version: 9.0.1
 - Entrypoint: i dont know what does it mean :(

**Additional context**
before this i had another inferior version of pksm, y wanted to update it to 9.0.1, so i instaled the new cia, already having the old one instaled, so i deleted it from the 3ds folder, and the fbi title list. wen I instaled the new pksm it doesnt worked. i also tried with a 3dsx file instead of a cia but everything still the same.

**Comment by piepie62** [comment]
Try backing up and immediately restoring your PKSM ExtData with Checkpoint 3.7.4 (YES, the version matters.) If that doesn't work, please join our [Discord server](https://discord.gg/bGKEyfY) for more help.
