### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Pedr0-o7** [FlagBrew/PKSM#1193]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
This is really stupid but I would like for there to be music playing in the backround. It is just a stupid idea but it would be nice.

**Describe alternatives you've considered**
I would be fine with sound effects too.

**Additional context**
N/A

**Comment by SpiredMoth** [comment]
See [this FAQ](https://github.com/FlagBrew/PKSM/wiki/FAQs#how-do-i-add-custom-music) on the wiki

**Comment by piepie62** [comment]
The framework is also pretty much already in place for sound effects. I simply haven't found any ones that I consider "appropriate" for PKSM's usage. If you happen to have some in mind, I'd be happy to review them and either add them or tell you why I don't consider it appropriate in our [Discord server](https://discord.gg/bGKEyfY)
