### ISSUE TITLE
Bug Report - VC games are non existent on the VC games option despite having them installed

### ISSUE THREAD

**Issue by Pearl8520** [FlagBrew/PKSM#1194]
**Describe the bug**
When going to the menu to Open your save files and choose VC games option, no games are available despite having VC games

**To Reproduce**
1. Open pksm on your 3DS
2. Click on 'VC games'

**Expected behavior**
The list of available VC games that are installed on the console should show up on the screen

**Screenshots**
![IMG20200621214133](https://user-images.githubusercontent.com/35458274/85233649-316a2780-b408-11ea-9e91-1bd427196508.jpg)
![IMG20200621214147](https://user-images.githubusercontent.com/35458274/85233650-3333eb00-b408-11ea-95c7-7844c555b278.jpg)

**Information about your environment**
 - OS version: 11.13.0
 - PKSM version: 9.1.0-70857380
 - Entrypoint: 2DS XL

**Comment by piepie62** [comment]
You need to configure PKSM to point to their title IDs. This step is unavoidable because of the variability in title IDs.
