### ISSUE TITLE
Invalid: Geolocation: Country is not in 3DS region.

### ISSUE THREAD

**Issue by mikecbone** [FlagBrew/PKSM#1195]
When creating a new pokemon in a box, checking the legality of it always returns 'Invalid: Geolocation: Country is not in 3DS region.'. 

I can't find any way to change the geolocation, am I missing something?

PKSM v9.1.0-70857380

Edit:

Additionally, I'm also getting "Invalid: Mystery Gift cannot be received by this version" when injecting a wonder card pokemon (same language as game and 3ds)

**Comment by piepie62** [comment]
A valid geolocation triplet: Country set to 1, region set to 2, and console region set to 0. You can set these via the hex editor.
