### ISSUE TITLE
gen 3 virtual console games

### ISSUE THREAD

**Issue by paf2014** [FlagBrew/PKSM#1196]
I have all gba games installed as VC in my 2ds but when I open pksm in VC games tab none of them appear as installed games.is there something wrong? or is there anything that I should do when creating .cia files of this kind of titles so as that the last versoin of PKSM can edit my savs?

**Comment by GriffinG1** [comment]
Please read the [wiki](https://github.com/FlagBrew/PKSM/wiki).

**Comment by piepie62** [comment]
Also note that the VC injects must be created with save size of 1024kbit, aka 1mbit. Any other size is not supported by PKSM, and will register as an invalid save.

**Comment by paf2014** [comment]
thanks.I could get the way.Is there a limit to the quantity of titles IDs I can configure?I could type and configure my emerald,ruby,sapphire and fire red games but I could configure my Leaf green game that was the last I configured.I typed the ID right though.also PKSM crashes if there is not a sav file in ruby game

**Comment by piepie62** [comment]
I'll look into that crash, but you can have one title ID per game

**Comment by paf2014** [comment]
so you can have 5 title ID configured.but my leaf green does not appear.I configured as the last one in the sequence that is above

**Comment by piepie62** [comment]
If it doesn't have a save in it, that could easily be the reason. PKSM *should* require a save in all cases; the fact that that unsaved Ruby even shows up is abnormal.
