### ISSUE TITLE
Shedinja HP is more than one after editing

### ISSUE THREAD

**Issue by LCeviche** [FlagBrew/PKSM#1197]
**Describe the bug**
I was editing my Shedinja's moves in PKSM as usual with no issue. I booted the game up as usual and found that my Shedinja had more than one HP. Editing the Shedinja's IVs and EVs caused the HP to scale. It had 11 HP at level one with zero IVs and EVs. I generated a brand new Shedinja in my PC (within PKSM) and experienced the same problem.

I was not having this issue earlier while editing the Shedinja when it was within my in-game PC. I am pretty sure it was in my party at the time when the editing bug started appearing. Moving the Shedinja in and out of the in-game PC boxes resets the HP back to one and fixes this issue.

**To Reproduce**
1. Place a Shedinja in your party
2. Edit the stats or moves
3. See error with HP

**Information about your environment**
 - OS version: 11.13.0-45U
 - PKSM version: v9.1.0-70857380
 - Entrypoint: Luma 10.1.3

**Comment by piepie62** [comment]
Just putting my thoughts here for right now: I don't know how to handle this gracefully. I'd need an exception somewhere, but I don't want to propagate it through the entire P[BK][345678] set of classes. If anyone has an idea for a good API for that, please tell me.

**Comment by GriffinG1** [comment]
This has been fixed in latest commits, and will be present when the next release is ready.

**Comment by GriffinG1** [comment]
Fixed in [v10](https://github.com/FlagBrew/PKSM/releases/latest).
