### ISSUE TITLE
Bug Report - I can't autolegalize my pokemon

### ISSUE THREAD

**Issue by Simondomino** [FlagBrew/PKSM#1198]
**Describe the bug**
I already fixed the geolocation issue, but when I select the origin game and try to autolegalize the pokemon it doesn't work, in the past version it worked, but I don't know why it doesn't work now in this new version.

**Information about your environment**
 - OS version:11.13.0-45U
 - PKSM version:9.1.0-70857380
 - Entrypoint: I don't know that information, sorry.

**Comment by piepie62** [comment]
Auto-legalization will not always work. This is a property of how it works: you must have some information set properly in order for it to find a valid match. This information includes moves, nature, ability, and item, for example. If any of the information required is impossible, then the legalization will be impossible.
