### ISSUE TITLE
Champion Ribbon erased on VI generation

### ISSUE THREAD

**Issue by mrex999** [FlagBrew/PKSM#1200]
This bug happened recently, Expected result: Pokemon transferred from Pokemon White over Pokemon X have the Champion Ribbon from Pokemon Leafgreen.

Result: Pokemon transferred from Pokemon White over Pokemon X didn't have the Champion Ribbon from Pokemon LeafGreen.

This didn't happen with my starter, I transfer it from Leafgreen to Pokemon X and it actually had the Champion Ribbon, now, My Vileplume from Leafgreen doesn't have the ribbon on Pokemon Ultra Sun, is there some way to fix this bug?

Pd: This doesn't happen when I transfer Pokemon from III over IV generation

**Comment by piepie62** [comment]
Yep, I see the problem. Fixed for the next version

**Comment by mrex999** [comment]
Jejejeje, lol mr. Pie I used the bytes option and I added the ribbon to the vileplume, thanks for your amazing job tho

**Comment by piepie62** [comment]
I like keeping fixed issues open until they make it into release. Thanks for trying to help, though

**Comment by GriffinG1** [comment]
Fixed in [v10](https://github.com/FlagBrew/PKSM/releases/latest).
