### ISSUE TITLE
Error during startup

### ISSUE THREAD

**Issue by Overide-sys** [FlagBrew/PKSM#1201]
**Describe the bug**
The pksm cia lum3ds crashes with the message:
Error during startup: 0xC92044E6
Description: Archive::init failed.
                Press start to exit

**To Reproduce**
1. Go to Pksm
2. Wait for it to load
3. See error

**Expected behavior**
The app would boot as normal.

**Screenshots**
n/a

**Information about your environment**
 - OS version: Windows
 - PKSM version: 9.0.0-cfdfca74
 - Entrypoint: Boot9strap

**Additional context**

**Comment by GriffinG1** [comment]
Try backing up and immediately restoring your PKSM ExtData with Checkpoint 3.7.4 (YES, the version matters.) If that doesn't work, please join our [Discord server](https://discord.gg/bGKEyfY) for more help.
