### ISSUE TITLE
Pokemon Home Transfer

### ISSUE THREAD

**Issue by SkyBoltDom** [FlagBrew/PKSM#1202]
Hello, I am just wondering if it is possible to add a transfer feature to the Nintendo switch. Pokemon Bank already has this feature and I think it would come in handy instead of Nintendo ripping us off for some stupid bank. It would need to use the pin from home to work and only transfer legal pokemon. Thank you and have a great week.

**Comment by piepie62** [comment]
No. That would require interfacing directly with Game Freak/Nintendo servers, which could easily break at any time and paves the path for a cease and desist from them.

**Comment by FM1337** [comment]
No this is not possible

**Comment by SkyBoltDom** [comment]
Oh I was not aware it was a communication between servers but rather a local connection thank you for explaining.
