### ISSUE TITLE
Bug Report - Archive::init failed

### ISSUE THREAD

**Issue by unlegitmare** [FlagBrew/PKSM#1203]
**Describe the bug**
This bug happens on the 3dsx version and the Cia version. When i try to start pksm on my 3ds, it says: 
Error during startup: 0xC92044e6

Description: Archive::init failed

**To Reproduce**
1. Go to 'PKSM' in the Homebrew menu 
2. Open it.
3. See error

**Expected behavior**
It would start normally

**Information about your environment**
 - OS version: 11.13
 - PKSM version: v.9.1.0
 - Entrypoint: Homebrew and Cia

**Comment by GriffinG1** [comment]
Try backing up and immediately restoring your PKSM ExtData with Checkpoint 3.7.4 (YES, the version matters.) If that doesn't work, please join our [Discord server](https://discord.gg/bGKEyfY) for more help.
