### ISSUE TITLE
Script to redirect IV Generation games to Pokemon Dream Radar

### ISSUE THREAD

**Issue by mrex999** [FlagBrew/PKSM#1204]
Today, I recently discovered 2 amazing scripts on PKSM; Pokemon Transporter and Dream Radar redirect script for BWB2W2 and I must say they're awesome, I've already caught a lot of Pokemon on Dream Radar and Pokemon Transporter is working fine with both of my versions on Twilight Menu++, but it'd be amazing if you make another one to redirect Pokemon DPPt and HGSS games to Pokemon Dream Radar so we can catch those legendaries, thanks for all the work you've been doing developing this cool app.

**Comment by piepie62** [comment]
Neither Dream Radar nor Transporter is compatible with DPPt or HGSS, so that's not possible

**Comment by mrex999** [comment]
Yes they are, when you play Dream Radar with a cartridge of DPPt or HGSS inserted on your 3 ds, after you beat Landorus you can catch a different Pokemon depending on the version inserted:
Palkia (Pearl)
Dialga (Diamond)
Giratina (Platinum)
Ho-Oh (HeartGold)
Lugia (SoulSilver)

**Comment by SpiredMoth** [comment]
It is true that Dream Radar has functionality dependent on Gen 4 carts.

The big hurdle with your suggestion is that I'm not sure if anyone has done the research into what Dream Radar looks for to detect Gen 4 carts. For the Gen 5 games, Transporter and Dream Radar look for the save file which is an easily determined location.

**Comment by piepie62** [comment]
I did not realize that at the time I wrote this. However, my guess, not having looked at Dream Radar's myself, is that it relies on the ROM header instead of the save: it's much easier to determine what game is inserted through that. That would be much, much harder for a PKSM script to swap than a save redirection.

**Comment by mrex999** [comment]
Ohhh, well, it doesn't matter tho, thanks tho, I'm definitely satisfied with the current scripts, after all I only need to transfer from BWB2W2 over Pokemon Transporter and Dream Radar

**Comment by SpiredMoth** [comment]
As has been pointed out on our Discord server, the [latest version of Checkpoint](https://github.com/FlagBrew/Checkpoint/releases/latest) contains cheats for Dream Radar that simulate the Gen 4 games being inserted

**Comment by zaksabeast** [comment]
I made the original patch for Dream Radar that redirects Gen 5 save reading/writing to the SD card, as well as the cheats that spoof a Gen 4 cart being inserted, so I can speak to this pretty well.

Dream Radar reads the game ID from the nds cart and also checks to see if a cart is inserted.  Both of these can't be done with PKSM, so the cheats with Checkpoint are the best way to go.

**Comment by mrex999** [comment]
Thanks, I didn't know about the cheats, now I can complete dream radar
