### ISSUE TITLE
Not booting

### ISSUE THREAD

**Issue by xylusmc** [FlagBrew/PKSM#1205]
When I open pksm I get the homebrew panel then I seen the logo for half a second then I get an error screen
Error during startup: 0xC92044E6
Description: Archive: : init failed.

**To Reproduce**

1. Open pksm
2. Wait one second
3. See error

**Expected behavior**
To open and work

**Information about your environment**
 - OS version: luma3DS 10.1.3
 - PKSM version: 9.1.0-70857380
 - Entrypoint: pksm

**Additional context**

**Comment by piepie62** [comment]
This has been fixed for the next version. For now, if you'd like to solve it, I have several steps that I walk people through on [our Discord server](https://discord.gg/bGKEyfY).

**Comment by GriffinG1** [comment]
Fixed in [v10](https://github.com/FlagBrew/PKSM/releases/latest).
