### ISSUE TITLE
I am unable to access soulsilver

### ISSUE THREAD

**Issue by Seano992** [FlagBrew/PKSM#1206]
Soulsilver doesn’t show up when I access the app and the cartridge is inserted. Platinum works just fine. Soulsilver does show up in checkpoint.

**Comment by piepie62** [comment]
The cartridge in question is likely a bad fake. You can send a Checkpoint backup here so I can check it if you'd like, but that's the only reason this has happened, especially with Heart Gold and Soul Silver in months.
