### ISSUE TITLE
Android Support for Citra

### ISSUE THREAD

**Issue by Foxergamer1** [FlagBrew/PKSM#1209]
Please make this a feature!

**Comment by FM1337** [comment]
1. Use the template
2. We don't support Citra
3. Citra on Android is still in beta afaik

**Comment by piepie62** [comment]
More information on that: Citra support is difficult for a couple reasons. The main issue is that they don't implement any Luma extensions, so a bunch of stuff that I do specifically with those extensions is not possible. There are also some inaccuracy concerns, especially where more exotic services are necessary. You can compile PKSM yourself with untested "citra support", but we will not be providing those builds as they remove some checks that are important for hardware.
