### ISSUE TITLE
Crashes after loading storage 

### ISSUE THREAD

**Issue by staticcrx** [FlagBrew/PKSM#1211]
Now whenever I load pksm it crashes when it says it loading storage 

1. Go to pksm 
2. wait until loading storage
3. Then crashes 

**Expected behavior**
For it to not crash after loading storage 

**Information about your environment**
 - OS version: 11.13.0-45U
 - PKSM version: 9.1.0
 - Entrypoint: pksm

**Comment by GriffinG1** [comment]
What do you mean by "crash". Generic exit? A full arm11 crash screen? This is very vague...

**Comment by staticcrx** [comment]
Yeah just a generic exit, no error code nothing

**Comment by piepie62** [comment]
Do you happen to know your PKSM bank size? And do you have anything in it?

**Comment by staticcrx** [comment]
I had some then I just deleted it and still had the same problem

**Comment by piepie62** [comment]
It's almost certain that you didn't actually delete your bank; very few people get the location correct (hint: it's not in /3ds/PKSM by default). Do you know the size in boxes?

**Comment by staticcrx** [comment]
I don’t remember but your probably right though

**Comment by piepie62** [comment]
Fair enough. Alright, first off, use [Checkpoint 3.7.4](https://github.com/FlagBrew/Checkpoint/releases/tag/v3.7.4) (yes, the version is important) to back up your PKSM ExtData. Once you've done that, use FBI to delete it (from the main menu, Ext Save Data->PKSM->Delete Save Data). PKSM should probably open after you've done that. If care enough about the Pokémon that were in the bank and would like help restoring it after that, please join [our Discord server](https://discord.gg/bGKEyfY), that way your Pokémon are not made unintentionally public.

**Comment by staticcrx** [comment]
Oh it worked thank you
