### ISSUE TITLE
Fateful Encounter flag erased 

### ISSUE THREAD

**Issue by mrex999** [FlagBrew/PKSM#1212]
Expected Behavior

Pokémon flagged with the ''fateful encounter'' on a Pokémon transferred over IV generation from III generation

Current Behavior

Pokémon doesn't have the fateful encounter flag when it's transferred over IV generation from III generation

This bug usually happens with PCNY Pokémon collection and other different events

**Comment by piepie62** [comment]
I am nearly certain this cannot be the case. The code that transfers from a PK3 to a PK4 has that flag set explicitly. Are you certain that the PK3s you're transferring actually have the flag set?

**Comment by mrex999** [comment]
Whenever I transfer a PK3 over a Gen 4 game I check the Pokémon Bytes, and it always have the fateful encounter byte unchecked

**Comment by piepie62** [comment]
And you're absolutely, completely certain that the original Pokémon, before transferring, have that bit set? How did you check, if so?

**Comment by mrex999** [comment]
It doesn't have it, but on 3rd generation games their description says: ''in a fateful encounter''

**Comment by mrex999** [comment]
In fact, you can't change a Pokémon Bytes on pksm when you are editing on 3 generation games

**Comment by piepie62** [comment]
I know you can't, and that will be fixed with the next version. That's why I'm asking how you know that the fateful encounter flag is set. G3 has a specific location for fateful encounters, as far as I can tell, so the location may be set to that without the fateful encounter flag

**Comment by mrex999** [comment]
When I'm editing a Pokémon on gen III with Pksm, I always check the misc option, and there's a part that says '''fateful encounter''

**Comment by piepie62** [comment]
Yes, that would be the met location, not the fateful encounter flag

**Comment by mrex999** [comment]
Yep, but once I transfer the mon over gen IV, the fateful encounter byte gets unchecked, it doesn't happens with certain Pokémon like Mew or Deoxys, but I pal parked some 10ANIV mons with Drastic and those mons had the fateful encounter byte checked when I edit them with PKSM on my Pokémon Pearl save file

**Comment by piepie62** [comment]
You're not listening. The met location being set to "fateful encounter" *does not mean* the fateful encounter bit is set. They are separate values.
