### ISSUE TITLE
Bug Report - Brief Description/Name of issue

### ISSUE THREAD

**Issue by Terumoc** [FlagBrew/PKSM#1217]
**Describe the bug**
After doing an automated legality fix on a pokemon, their Markings and Ribbons get modified to a seemingly random but consistent state. I would expect legality checks should not modify these.

Specifically: after auto-legalizing:
|Pokemon Byte|Set Value|
|-|-|
|0x16 (markings 1)|0x55|
|0x17 (markings 2)|0x05|
|0x30 (ribbons 1)|0x88|
|0x32 (ribbons 3)|0x08|
|0x35 (ribbons 6)|0xC0|
|0x36 (ribbons 7)|0x03|

**To Reproduce**
1. Go to the editor for a USUM save
1. Create/modify a pokemon with an issue that can be auto-legalized (invalid met location or missing base egg move). Check its markings and ribbons in the raw data view.
1. Go to MISC and press the legalizer then auto-legalize it to get the message "Your pokemon is now legal!"
1. Now go recheck its markings and ribbions in the raw data view; they've been set as above for seemingly no reason.

**Expected behavior**
No modification to ribbons or markings when auto-legalization function is used.

**Information about your environment**
 - OS version: New3DS w/ Luma3DS
 - PKSM version: v9.2.0-656eb68a
 - Entrypoint: custom firmware (not sure if this is applicable)

**Comment by GriffinG1** [comment]
This is not a PKSM issue, as the legalizer is implemented via an API using @architdate's [Auto Legality Mod plugin](https://github.com/architdate/PKHeX-Plugins) for PKHeX. As such, I advise you to either open an issue there, or join their discord server, linked in that repo's README.

**Comment by Terumoc** [comment]
gotcha, thanks!
