### ISSUE TITLE
Soy muy novato en esto

### ISSUE THREAD

**Issue by Andres10xz** [FlagBrew/PKSM#1218]
Hola, los juegos de 3ds me funcionan bien en la aplicacion, pero necesito ayuda, tengo instalados juegos de ds en 3ds y de game boy y nose como utilizar el programa con esos juegos, tambien tengo la switch hackeada pero tampoco se como utilizar el programa en la switch o para modificar pokemon espada y escudo, agradezco si alguien me puede ayudar

**Comment by melsbacksfriend** [comment]
En inglés por favor.

**Comment by GriffinG1** [comment]
Solamente ingles aqui por favor. También, usas la plantilla.

**Comment by xanaks27** [comment]
Hello, the games of 3ds are working for me without application, I need help, try the games of the 3ds with the nose and how to use or program with games, I also changed to the hacked option to use how to use or the program does not switch ou To modify pokemon sword and shield, I appreciate that someone can help me

**Comment by piepie62** [comment]
I honestly cannot tell what you are asking. The only thing I understood from that was "modify Sword and Shield", which will be more easily possible once [Checkpoint](https://github.com/FlagBrew/Checkpoint) updates. It is currently possible using [these instructions](https://github.com/FlagBrew/PKSM/wiki/Basics#loading-a-save-over-a-network), but they are far more complicated than what the Checkpoint update will require. As such, I'd recommend waiting for it.
