### ISSUE TITLE
Pokemon Y - EON Ticket Crash

### ISSUE THREAD

**Issue by ccfman2004** [FlagBrew/PKSM#1219]
**Describe the bug**
After receiving a ? item from the PokeCenter lady, upon going to view the item the game crashes

**To Reproduce**
Inject the EON Ticket using PKSM into Pokemon Y.
Go to the Pokemon Center and speak to the lady.
She will give you a mystery item that goes to the Key Item slot.
Upon going to view that item the game with crash forcing you to hold the power button to turn the system off.

**Information about your environment**
 - OS version: 11.13.0-45U
 - PKSM version: 9.2.0
 - Entrypoint: BS9

**Additional context**

The EON Ticket is not for Pokemon X/Y then it shouldn't appear in PKSM for Pokemon X/Y.

**Comment by GriffinG1** [comment]
That’s because the eon ticket doesn’t *exist* in X/Y. PKSM makes automatic backups, so either restore one of those, or overwrite the mystery ticket by injecting a new one over it.

**Comment by ccfman2004** [comment]
PKSM shouldn't allow me to inject it then.

**Comment by GriffinG1** [comment]
The wonder cards don’t carry game info, so that’s impossible. Common sense should keep you from injecting it.

**Comment by ccfman2004** [comment]
I didn't know until I looked into it after my game crashed.  Still there should be some check to prevent it from showing to stop people who don't know.

**Comment by piepie62** [comment]
There are very few Wonder Cards that actually have this requirement, and receivable information isn't easily accessible, if it is at all (some formats do include it). Overall, there's just no good way to do that filtering.

**Comment by ccfman2004** [comment]
Even if it's hard to code it' still considered bad coding to leave something that can cause something to crash.

**Comment by SNBeast** [comment]
If I can butt in here, couldn't you [devs] just specifically hardcode in a check against showing the Eon Ticket on XY?

**Comment by ccfman2004** [comment]
Every Wonder Card I've seen in PKSM has game data relating to what game it was for.

**Comment by GriffinG1** [comment]
Yes, go ahead and tell the dev (who knows what the contents of the wonder cards are) what the wonder card has and doesn’t have.

This issue has been closed, please drop it.
