### ISSUE TITLE
Compatibility with Twilight Menu

### ISSUE THREAD

**Issue by AdrianMonky** [FlagBrew/PKSM#1220]
Is there any way to make it possible to edit save files of the 3DS DS emulator Twilight Menu?

Thanks in advance!

**Comment by piepie62** [comment]
Already done via [Extra Saves](https://github.com/FlagBrew/PKSM/wiki/Settings#extra-saves)

**Comment by AdrianMonky** [comment]
Thanks, didn't knew about this!
Sorry for asking!
