### ISSUE TITLE
Why my VC games do not show up?

### ISSUE THREAD

**Issue by AdrianMonky** [FlagBrew/PKSM#1221]
Basically the title.
I go to the VC tab and it does not show nothing.
I need to do something first?

**Comment by SpiredMoth** [comment]
You need to [tell PKSM](https://github.com/FlagBrew/PKSM/wiki/Settings#title-ids) what title IDs your GBA VC games use

**Comment by Superfraggerjin** [comment]
Where can I get the id of the Vc games ?!
