### ISSUE TITLE
Problems with GPSS

### ISSUE THREAD

**Issue by AdrianMonky** [FlagBrew/PKSM#1222]
When I try to upload a QR code the GPSS app crashes.
I don't know how to get the QR code of already existing pokémon in app.
And can I make the pokémon in the GPSS and then transfer to the 3DS?

Sorry for the spam, but I'm dumb and can't figure things for myself.
Thanks in advance!

**Comment by piepie62** [comment]
This is not the place to bring up issues with the GPSS Mobile app. This issue tracker is for PKSM specifically, not what it interfaces with. Please bring up issues with the GPSS Mobile app in the appropriate channel in [our Discord server](https://discord.gg/bGKEyfY).
