### ISSUE TITLE
Gen 3 Wonder Cards

### ISSUE THREAD

**Issue by ccfman2004** [FlagBrew/PKSM#1223]
**Is your feature request related to a problem? Please describe.**
Is it possible to add Gen 3 Wonder cards?

**Describe the solution you'd like**
To be able to use PKSM to inject Gen 3 Wonder cards like EON Ticket

**Describe alternatives you've considered**
I know there is a Windows app to do this but it's a pain to have to extract the VC game save, inject wonder card then import the save back using GodMode9.

**Comment by piepie62** [comment]
The WC3 format is made up and will not be supported. There is a work-in-progress script in [our Discord server](https://discord.gg/bGKEyfY) that injects item gift cards, and all Pokémon are distributed as PK3s that can be used with the script `injector.c`.

**Comment by ccfman2004** [comment]
That item script is not for Ruby or Sapphire.

**Comment by ccfman2004** [comment]
I figured out how to use the script but there is no EON Ticket.
