### ISSUE TITLE
Pokemon trainer given name ("nickname") string in editor gets trimmed to 11 characters...

### ISSUE THREAD

**Issue by Galenmacil** [FlagBrew/PKSM#1224]
...instead of the in-game supported 12 characters.

The input box allow for 12 characters input but strip the last one on OK/Confirm.

**Comment by piepie62** [comment]
Please don't use the title as part of the issue message, and instead use the templates. That said, this should be fixed for the next version.

**Comment by GriffinG1** [comment]
Fixed in [v10](https://github.com/FlagBrew/PKSM/releases/latest).
