### ISSUE TITLE
(Feature Request) Highlight stats affected by nature in red or blue in the Viewer/Editor

### ISSUE THREAD

**Issue by Galenmacil** [FlagBrew/PKSM#1225]
This would match the post SoulSilver/HeartGold in-game behaviors where the reduced stat is shown in blue and the augmented stat is shown in red.

Example:
![tumblr_oxbo3x64Ge1w5miaho1_1280](https://user-images.githubusercontent.com/19394274/89848611-90206780-db54-11ea-8b17-2c1f9b443b0a.png)
![XxOyXnXT5Q44Pnbo_Tf63sXQxoAryiRA_iQh04Syxs0](https://user-images.githubusercontent.com/19394274/89848613-91519480-db54-11ea-8df6-a0d0e81ed73f.jpg)

**Comment by piepie62** [comment]
That's a pretty good idea. I'll try to figure out a good way to do this codewise.

**Comment by piepie62** [comment]
This has been added for the next release

**Comment by GriffinG1** [comment]
Fixed in [v10](https://github.com/FlagBrew/PKSM/releases/latest).
