### ISSUE TITLE
Bug with Virtual Console save files - It isn't recognized

### ISSUE THREAD

**Issue by AdrianMonky** [FlagBrew/PKSM#1226]
**Describe the bug**
I am playing pokémon Leaf Green, I already chose a starter and got the pokédex, but when I try to load the save it says "First save absent" and "is not a valid save file. Error 0xFFFFFFFF"

**To Reproduce**
I don't know, try editing a save maybe.

**Expected behavior**
Load the save

**Screenshots**
![WhatsApp Image 2020-08-11 at 10 28 09 AM](https://user-images.githubusercontent.com/17505052/89902997-81ba6600-dbbd-11ea-9d0b-c054958e38b8.jpeg)
![WhatsApp Image 2020-08-11 at 10 28 09 AM (2)](https://user-images.githubusercontent.com/17505052/89903000-8252fc80-dbbd-11ea-856e-e5fb17c78fcf.jpeg)
![WhatsApp Image 2020-08-11 at 10 28 09 AM (1)](https://user-images.githubusercontent.com/17505052/89903001-82eb9300-dbbd-11ea-9b17-1910433a773e.jpeg)

**Information about your environment**
 - PKSM version: Latest version

**Comment by GriffinG1** [comment]
The save file type you selected when injecting your leafgreen backup is not correct. Reinject using a 1024kbit save type.

**Comment by AdrianMonky** [comment]
How do I do that?

**Comment by GriffinG1** [comment]
Use [this injector](https://gbatemp.net/threads/discussion-new-super-ultimate-injector-nsui.500376/) and select 1Mbit + RTC for the ROM Save Type field. Otherwise, same steps you used to inject last time.

**Comment by Herothegeek** [comment]
my black 2 save when i load up but it says wrong save

**Comment by GriffinG1** [comment]
@Herothegeek please do not post on closed issues, especially not unrelated questions.
