### ISSUE TITLE
Bug Report - Pokemon Emerald Script (nonissue) and Item Count Problems

### ISSUE THREAD

**Issue by HenryHeliolisk** [FlagBrew/PKSM#1227]
Every time I use Pokemon emerald on PKSM, the only thing that works is the Pokemon editing, and even then it only works with ones I all ready have. The universal scripts won't work, and whenever I edit bag items, the item quantity freaks out and goes to a random number.

This is on the latest version of PKSM and I have used it to edit Emerald ROM hacks before.

**Comment by piepie62** [comment]
Item quantity is a known problem, and will be fixed for the next version. Scripts have to be updated by their respective creators to support games, so that's expected. Pokémon generation should work; I'd need more detail into your actual problem to tell you more.

**Comment by HenryHeliolisk** [comment]
For some reason, the all tms script doesn't work for me on Pokemon emerald. I don't know why it is like this.

**Comment by GriffinG1** [comment]
> Scripts have to be updated by their respective creators to support games, so that's expected.

**Comment by bc9** [comment]
any updates or workarounds for the item quantity? still having issues with this on v9.2.0-65eb68a

**Comment by GriffinG1** [comment]
Build the latest commit yourself following the instructions in the readme, or just ignore it.

**Comment by GriffinG1** [comment]
Fixed in [v10](https://github.com/FlagBrew/PKSM/releases/latest).
