### ISSUE TITLE
Zarude in PKSM

### ISSUE THREAD

**Issue by CazAttack** [FlagBrew/PKSM#1229]
I've seen people adding Zarude onto the PKSM cloud. Is there any way I can get him into SwSh through the 3ds???

**Comment by WarriorCatBluestar** [comment]
I don’t think you can get him through the 3DS, but maybe if you Homebrewed your Switch? I don’t recommend doing that though, as Nintendo is being a little crazy about Switch hacking. 😅 I know someone will say this, so I’ll put it here for you anyways; you can hack a Switch, and you can go online with it, but it’s VERY risky to do so. I think your safest bet is to maybe go on YouTube and look for someone doing a giveaway of it. Sorry, I’m not much help 😂

**Comment by piepie62** [comment]
You can edit SWSH saves with PKSM. The main supported method, through using Checkpoint for the Switch, will be available once Checkpoint updates.
