### ISSUE TITLE
Filter Wonder Cards based on currently loaded save

### ISSUE THREAD

**Issue by ccfman2004** [FlagBrew/PKSM#1233]
**Is your feature request related to a problem? Please describe.**
Since Wonder Cards are generally game specific and this info is in them add a way so that Wonder Cards that are not for the currently loaded save to not appear like Eon Ticket for Pokémon X/Y and Oak's Letter for Diamond/Pearl.

**Describe the solution you'd like**
A way to toggle the Wonder Cards so that only cards for the currently loaded save are shown.

Injecting Wonder Cards to games other than what's listed in them can cause legality issues or the game simply crashes.

**Comment by GriffinG1** [comment]
You were already told why this is not possible. To quote @piepie62's message from #1219,
> There are very few Wonder Cards that actually have this requirement, and receivable information isn't easily accessible, if it is at all (some formats do include it). Overall, there's just no good way to do that filtering.

**Comment by ccfman2004** [comment]
Every wonder card that I've seen in PKSM has what game it was intended for.

**Comment by GriffinG1** [comment]
No, they have the *generation* they are for. They do not have the *game* they are for. Why do you insist on arguing a falsehood?

**Comment by piepie62** [comment]
All of those intended game fields are strings that are not taken from the wonder card data themselves, but instead the names of the files in the EventsGallery repository. The cards themselves do not have this data, and filtering them out with those strings would be both error-prone (what if a file happens to not follow the naming convention properly?) and difficult.

**Comment by piepie62** [comment]
We do not control EventsGallery and their naming conventions, so I refuse to depend on them for something that is not cosmetic, as they could change at any time.
