### ISSUE TITLE
Feature Request - Show what stats are Hypertrained

### ISSUE THREAD

**Issue by FullMetalKirby** [FlagBrew/PKSM#1235]
**Is your feature request related to a problem? Please describe.**
As it currently stands, there's no (easy) way to tell if a stat is hypertrained or not, without having to look at the hex data.

**Describe the solution you'd like**
Having the IV's value be a different color (ex: gold) should be more than enough to signify that it's hypertrained, without any additional space taken up and without hiding the info of what the original IV is.

**Describe alternatives you've considered**
Just so I don't need to create a second issue for essentially the same thing: Would be nice if something similar could be done to indicate whether a Pokemon has its HA or not, too, so one doesn't need to remember / look them up elsewhere.

**Additional context**
N/A

**Comment by WarriorCatBluestar** [comment]
HA, as in Hidden Ability? I believe you can check that right on the Pokémon’s main page, where you see how to name it, it’s gender, the little icon of it in the right hand corner, esc... May I ask what version you’re using? And I too agree on the Hyper Training differentiation being a little more pronounced; I forgot you could look to see if it was even Hyper Trained in the hex data.

**Comment by piepie62** [comment]
There's nothing that says whether or not the currently selected ability is a hidden ability or not, though I don't see why that would be important. If I'm given a reason why that's at all useful, I'll consider it. That said, text color changing for the hyper trained stats seems like a fair idea, if a little annoying to do programmatically. I'll see what I can do there.

**Comment by FullMetalKirby** [comment]
It's relevant to know if a Pokemon has its hidden ability or not for breeding/organization purposes, mostly, since they're the only ones capable of passing said ability down. Even in the actual games, there's no _direct_ indication of whether or not a Pokemon has their hidden ability, short of actually knowing what the hidden ability is, or attempting to use an ability capsule and it failing.

Perfectly understandable if it's not worth the effort though, since it's not that much additional work to look up hidden abilities on a site of choice. But it would be significantly more convenient to have the info in a more accessible location.

**Comment by piepie62** [comment]
Both have been done, and display in red. I was unable to find a satisfactory gold color that actually showed up against the blue of the background.

**Comment by GriffinG1** [comment]
Fixed in [v10](https://github.com/FlagBrew/PKSM/releases/latest).
