### ISSUE TITLE
Bug Report - PKSM not reading exported saves from DraStic

### ISSUE THREAD

**Issue by PsychicPersona** [FlagBrew/PKSM#1236]
**Describe the bug**
PKSM does recognize, but doesn't open save files which have been exported from DraStic.

**To Reproduce**
1. Have a DraStic save file of any pokemon game.
2. Change the file extension from .dsv to .sav.
3. Upload your save file to your 3ds.
4. Try to open it with PKSM over the Extra Saves option.

**Expected behavior**
The save file should've loaded.

**Screenshots**
No screenshots available.

**Information about your environment**
 - OS version: Luma3DS v10.2; 11.13.0-45E
 - PKSM version: 9.2.0

**Additional context**
The save type was edited in order to work with TwilightMenu++. It's working just fine there.

**Comment by piepie62** [comment]
DraStic adds a 122-byte footer to the save. Delete it and the save will work.

**Comment by LordMarsh** [comment]
what is a 122-byte footer?

**Comment by Masamune3210** [comment]
It's a chunk of data 122 bytes long at the end of the file that is used only for the emulator. You can remove it using any hex editing program

**Comment by LordMarsh** [comment]
thanks

**Comment by Zein1112** [comment]
I have a same problem
I try to change my pokemon black2 .dsv to. sav but the other save file from hg and platinum it load
The hex editor i don't know how to use it or remove the byte footer here's the file of my black2 savefile [https://drive.google.com/file/d/1-0Q-U1WQWZ6M4plZQwBX_xtO_10eOQ1P/view?usp=drivesdk]()
