### ISSUE TITLE
Feature Request - Add support for 00040000001a8a00 (Debug US/S)

### ISSUE THREAD

**Issue by Nuts-deez** [FlagBrew/PKSM#1238]
**Is your feature request related to a problem? Please describe.**
Hello, I would like the support for the debug version of the beta Sun / Ultra Sun

**Describe the solution you'd like**
The ability to select it in the game selection to edit the save

**Describe alternatives you've considered**
The possible ability to specify a title id and/or something like that

**Additional context**
There is more debug/beta builds like this
![debug US - Copy](https://user-images.githubusercontent.com/73542876/97320431-2acf3f00-1844-11eb-9202-f39aae07753b.png)
Sorry, my english is not the first language

**Comment by piepie62** [comment]
No. Obtaining these versions is necessarily piracy.
