### ISSUE TITLE
Bug Report - Markings don't transfer correctly

### ISSUE THREAD

**Issue by Fizibiz** [FlagBrew/PKSM#1239]
**Describe the bug**
When transfering pokemon with markings (star,square etc.) from Gen 6 or below to Gen 7 the hexvalues of the older games don't match the equivalent of the newer games and therefore get corrupted (in my specific case from AS to UM).

**To Reproduce**
Transfer a pokemon with selected marks (in my case all 6 selected) from Gen 6 (or below) to storage and from there to Gen 7.
The transfered pokemon now has markings that don't match the ones they had before (in Gen 6).
And because the old hexvalue that doesn't get converted properly you can not edit them properly ingame.

**Information about your environment**

- PKSM version: 9.2.0

**Additional context**
I have also noticed that the Hexeditor GUI does not work correctly for the two bytes that control these markings after Gen 6 (tested with UM).

**Comment by GriffinG1** [comment]
How exactly does Bank handle markings for intergenerational transfers?

**Comment by Fizibiz** [comment]
After transfering a pokemon from Gen 6 (AS) to Gen 7 (UM) with pokemon bank the byte for markings (all 6 selected) changed:

from value: 3F at byte: 2A
to value: 55 at byte: 16         and     value: 05 at byte: 17

It still had all the selected marks from Gen 6

**Comment by piepie62** [comment]
I'll look into that later today. I can't remember, did G6 have just blue/not selected or blue/red/not selected markings?

**Comment by Fizibiz** [comment]
In Gen 6 you only have two options, 'selected' and 'not selected'.
