### ISSUE TITLE
Bug Report - Gen3 save error/ Is Not a Valid Save File Error:0xFFFFFFFF 

### ISSUE THREAD

**Issue by gregolisan** [FlagBrew/PKSM#1241]
**Describe the bug**
I couldn`t edit my save file on pokemon leaf green. I installed the .cia using FBI and search the file in the PKSM but when i try to edit it an error occur saying ``Is not a vilid save file error: 0xFFFFFFFF``.

what have i done wrong?  

**Information about your environment**
 - OS version:  11.13.0-45U
 - PKSM version: 9.2.0
 - Entrypoint:

**Comment by piepie62** [comment]
Not a bug. This means that your save size is not 1024kbit. Reinject your ROM and install the new CIA.

**Comment by biglittlenuub666** [comment]
how

**Comment by SpiredMoth** [comment]
We have a handy guide on properly making the CIA in the PKSM wiki: [GBA Injection](https://github.com/FlagBrew/PKSM/wiki/GBA-Injection)
