### ISSUE TITLE
Quisiera que agregen las wonder cards y los scripts para Pokémon rojo fuego esmeralda rubí zafiro y verde hoja

### ISSUE THREAD

**Issue by Oliverx3x3** [FlagBrew/PKSM#1243]
La verdad esto está así desde julio que salió la última actualización les pido porfavor que terminen todos los scripts, wonder cards y también un problema que hay con la bolsa de objetos al agregar un objeto salen número aleatorios porfavor que terminen la 3 generación por completo gracias

**Comment by GriffinG1** [comment]
Wonder cards do not exist in generation 3. Any scripts for generation 3 are currently in beta, available on the FlagBrew discord, and will likely be available whenever the next update is released. Bag issue has been fixed since last release if I recall correctly, so again: wait for the next release.

**Comment by Oliverx3x3** [comment]
Lo de la bolsa de objetos es un problema raro osea al agregar un objeto en la tercera generación en cualquier parte de la bolsa al uno elegir por ejemplo la ultra ball a uno le sale uno de se a agregado una ultra ball pero uno quiere agregar más y al intentar agregar por lo menos dos poke balls el sistema se corrompe y empieza a salir un número determinado envés de salir dos  en el caso de la ultra ball sale 10442 y no avanza de ahí al darle a una más este se va a 0 pero en el caso de la ultra ball es de 0 a 10442 los demás van de 1 y así son diferentes números aleatorios y una pregunta cuando estima que salga la siguiente actualización gracias
________________________________

**Comment by GriffinG1** [comment]
The update will release when it releases.
