### ISSUE TITLE
Bug Report - PKSM Crashing in Storage and Editor with LGPE save

### ISSUE THREAD

**Issue by techmuse8** [FlagBrew/PKSM#1245]
**Describe the bug**
PKSM crashing when I moved my DPAD to the boxes and party after a received a LGE save.
**To Reproduce**
1. Follow steps 1-8 [here](https://github.com/FlagBrew/PKSM/wiki/Basics)
2. Click on 'Storage' or 'Editor'
3. Scroll down to your boxes or the party
[crash_dump_00000022.dmp.zip](https://github.com/FlagBrew/PKSM/files/5681473/crash_dump_00000022.dmp.zip)
**Expected behavior**
Being able to edit my box and party data.
**Screenshots**

**Information about your environment**
 - OS version: New3DS 11.14.0-46U, Switch 11.0.1 

 - PKSM version: 9.2.0
 - Entrypoint: Luma3DS 10.2.1 with the .cia, Atmosphere 0.16.1 prerelease with Checkpoint 3.7.4

**Additional context**

**Comment by piepie62** [comment]
Sorry about that, that's a known issue. It's already fixed for the next version

**Comment by GriffinG1** [comment]
Fixed in [v10](https://github.com/FlagBrew/PKSM/releases/latest).
