### ISSUE TITLE
Gen V has no species limits in base hex editor

### ISSUE THREAD

**Issue by SNBeast** [FlagBrew/PKSM#1250]
**Describe the bug**
When editing the species of a Pokemon in the normal hex editor in a Gen V game, there is no checking for species legality / existence. This is unlike in all other generations where you are not allowed to give a non-existant or illegal species in the normal hex editor.

**To Reproduce**
1. Go to Hex Editor in a Gen V save.
2. Go to the species offset
3. Try to set the species to an illegal value, like 0xFFFF
4. Note whether or not Step 3 was successful
5. Repeat Steps 1-4 in a save for any other generation (except III, because normal hex editor doesn't allow editing species there and higher privileges ignore the species bound in all generations)

**Expected behavior**
It's expected that the hex editor is consistent as to whether or not the species could be taken out of bounds across all generations or follow some logic (ie, the ones that would crash upon looking wouldn't let you).

**Screenshots**
(none)

**Information about your environment**
 - OS version: Luma3DS v10.2.1-3gxldr CFW, 11.14.0 Sys
 - PKSM version: 9.2.0 nightly
 - Entrypoint: CFW

**Additional context**
This was originally mentioned by someone else on the FlagBrew Discord.

**Comment by piepie62** [comment]
Thank you for reporting this, fixed it with the latest commit

**Comment by GriffinG1** [comment]
Fixed in [v10](https://github.com/FlagBrew/PKSM/releases/latest).
