### ISSUE TITLE
Expanded Storage?

### ISSUE THREAD

**Issue by CRNTheAlmightyDuck** [FlagBrew/PKSM#1251]
Will there be a future update which expands the amount of storage in PKSM? Maybe something closer to what Bank has with 3000 Pokemon slots, rather than the 1500 PKSM currently has?

**Comment by GriffinG1** [comment]
You can already create multiple banks, and it is unlikely that you will reach the max amount of slots filled in the max amount of boxes in the max amount of banks, since that’s 1.35 million slots (~90 max banks, 500 boxes per bank, 30 slots per box)

**Comment by piepie62** [comment]
Something not completely clear from Griffin's comment above is that you can resize your bank(s) to up to 500 boxes each using an in-app interface. Just wanted to explicitly state that

**Comment by CRNTheAlmightyDuck** [comment]
500?... O_O ... how do I access them?

**Comment by SpiredMoth** [comment]
If only someone would take the time to write up documentation on all the features of PKSM so users could read about them whenever they had questions...

...like maybe the link Griffin posted earlier
