### ISSUE TITLE
Please Support Chinese Input!

### ISSUE THREAD

**Issue by Counta** [FlagBrew/PKSM#1253]
Sorry, I don’t know English. I will use Google Translate to translate my words and write down the original Chinese content.
PKSM supports Chinese, which makes me very happy, but the search function also needs to enter Chinese to search for content. There is no Chinese input method on Nintendo 3DS, so this function is basically useless.
However, in November  @James-Makoto Use the Chinese input method on iQue 3DS (the special Chinese version of Nintendo3DS) on other versions of Nintendo 3DS, and then 3DS can use Chinese input.
However, this input method is not suitable for PKSM, because PKSM does not support the input association of the input method, I hope it will support it soon. Thanks.

PKSM支持中文，这让我很开心，但是搜索功能也要输入中文来搜索内容，而在Nintendo 3DS上并没有中文输入法，所以这个功能基本无用。
将 iQue 3DS（Nintendo3DS的中国特供版）上的中文输入法用在其他版本的Nintendo 3DS上，然后3DS可以使用中文输入了。
然而PKSM因为不支持输入联想，无法使用这个输入法，我希望它早日支持。

**Comment by piepie62** [comment]
I do not know how to access that. If they would like to provide guidance (and it doesn't require modification of anything other than what PKSM does to open up the keyboard), I'd be happy to add it

**Comment by Counta** [comment]
I think it is very simple to join it, you may not understand what "input association" is.

You only need to make the green button above the number line of the input method effective.

**Comment by piepie62** [comment]
You are correct, I have no idea what you're talking about. I don't see any green button on the keyboard

**Comment by GriffinG1** [comment]
Considering they said that this was something implemented from a clone console on official hardware, I’m guessing you’d need to ask the person they mentioned

**Comment by James-Makoto** [comment]
He's means that a book icon on the keyboard,only can be seem in some app like internet browser and friend list.

**Comment by Counta** [comment]
屑，我刚发图到仓库准备发链接
Please Check Out：https://raw.githubusercontent.com/Counta/blogts/main/images/2021-02-05_13-01-55.652_bot.bmp

**Comment by Rintim** [comment]
In iQue 3DS, There is a book icon on the keyboard to change chinese input, which provides chinese users the ability to input Chinese.
However, in PKSM, we can't see it now. So we hope to see its supports one day.
(In fact, my English is not pretty good. If there is something trobleming you, please understanding.)

**Comment by piepie62** [comment]
Okay, sure. I see what you mean. However, on normal 3DSes, that just changes the language of input completion between English, French, Spanish, and Portuguese, and I both don't know how to affect the available languages and am unsure whether the normal 3DS keyboard applet even supports languages other than those four

**Comment by piepie62** [comment]
Or even if changing the available languages is possible

**Comment by James-Makoto** [comment]
All region of 3DS have this function. Japanese 3DS used it to input Japanese Kanji,, and USA/European 3DS used to input quickly.
It can be seem in some app like Internet Browser.

**Comment by piepie62** [comment]
@James-Makoto If you managed to get this to display on a non-iQue 3DS, could you show me the code you used to do so? I'd be able to compare it with what I do to see what the differences are.

**Comment by piepie62** [comment]
And yes, I know that the word completion exists, but just enabling it won't help anything

**Comment by piepie62** [comment]
Just as a test, I tried just setting the predictive input setting to true. It doesn't change from the English, French, Spanish, and Portuguese choices

**Comment by Rintim** [comment]
Well, in different regions, the thesauruses are different, too.
System file: https://github.com/Theopse/Downloads/raw/Shared/Chinese_Input.zip
This is iQue 3DS system file to support chinese input

**Comment by piepie62** [comment]
Please don't try to share copyrighted system files here

**Comment by Rintim** [comment]
Ah, Sorry for that.
Well, anyway, if PKSM supports word completion, that's enough.

**Comment by piepie62** [comment]
PKSM could theoretically support word completion... for only English, French, Spanish, and Portuguese (assuming a US console, probably different options between different regions). Which isn't what you want

**Comment by James-Makoto** [comment]
Well XD, it can be used for Japanese Kanji or Chinese for JP console, We can use it to input Chinese by editing system input dictionary.(titleID 0004009B00011902) so that's enough.

**Comment by piepie62** [comment]
I don't understand why you aren't just sharing the code that you used to get that keyboard to show up. Doesn't the screenshot that @Counta shared have Chinese characters on it? Wouldn't causing that to display be a much better solution than editing system files to get a janky input method?

**Comment by Counta** [comment]
We are sorry, when changing from the Japanese Kanji input method to the Chinese Pinyin input method, we just copied and pasted a folder named 0004009B00011902 without changing any code. We don't know what is in that file.

**Comment by Counta** [comment]
If you need it, we can send out this file, but it may only apply to Nintendo3DS in Japan and China.

**Comment by piepie62** [comment]
That's the "Japanese small" dictionary archive, according to what I've found. It makes absolutely no sense that just doing a copy-paste of that archive would change the behavior of the system keyboard

**Comment by Counta** [comment]
At the beginning, we didn't believe this was feasible, but it does work, even the US version of Nintendo 3DS.

**Comment by piepie62** [comment]
The problem with this strategy is that it involves modification of system files, which PKSM cannot rely upon. There is no way that I can in good conscience recommend this "fix", which may cause unforeseen issues in normal 3DS applications and/or games, or even have consequences within the keyboard applet that have yet to manifest.

A dispute about my argument above may be that PKSM requires Luma, which is a modification of system files. While this is true, Luma is both the standard method to launch modern homebrew and required to actually do much of what PKSM does, and as such is not a valid comparison.

I will try to figure out a way to enable other-language input from PKSM that doesn't require this hacky workaround

**Comment by Counta** [comment]
We can't do that,but only share the system changes file.

**Comment by piepie62** [comment]
After a fair bit of testing, I have not found a way to enable Chinese input in the system keyboard. I also still don't believe the above workaround to be a good solution for the reasons stated. For that reason, I cannot fix this issue, and the best advice I have is to use the hex editor to input Unicode values for the characters directly
