### ISSUE TITLE
pksm corrupted my cartidge

### ISSUE THREAD

**Issue by paf2014** [FlagBrew/PKSM#1254]
After editting my pkm US save in PKSM I cannot start my game anymore.when I try do this I got the error in attchment.Is there any way of restoring my save?I tried using checkpoint and the list of savs of US did not appear, the game was in slot, though.In FBI  I got the image in attchment and In JKSM I got the msg this archive cannot be opened when I tried to erase the sav file.thanks for any help
![erro](https://user-images.githubusercontent.com/46760859/108068037-5a4ac700-7040-11eb-8dc3-d36f4d36208c.png)
![20210216_092729](https://user-images.githubusercontent.com/46760859/108068160-7e0e0d00-7040-11eb-9c9a-43637dca3460.jpg)

**Comment by piepie62** [comment]
Not going to lie, this really doesn't sound like something PKSM could have done. That error you showed is the home menu dying, which... shouldn't happen at all, no matter the contents of the save

**Comment by paf2014** [comment]
this error only happens when in my US in slot.and started after editing my save in pksm.My game is always read but I got the error of menu as you said when strating it.


I am neither lying nor complainng about Pksm, that is a useful tool.I'd like a way to recover my cartridge only
![5](https://user-images.githubusercontent.com/46760859/108553251-2d611300-72d1-11eb-915f-53cc2ac03258.png)

**Comment by piepie62** [comment]
Closing due to being out of scope and having no idea how I could help
