### ISSUE TITLE
Bug Report - Extra Saves link in Wiki leads to raw settings.md file

### ISSUE THREAD

**Issue by MechanicalDragon0687** [FlagBrew/PKSM#1258]
**Describe the bug**
clicking the extra saves link here: https://github.com/FlagBrew/PKSM/wiki/FAQs#can-i-use-pksm-on-my-twilight-menu-saves
will lead to the raw view of the settings.md file rather than the wiki page

**Expected behavior**
should link to https://github.com/FlagBrew/PKSM/wiki/Settings#extra-saves instead

**Comment by SpiredMoth** [comment]
Fixed
