### ISSUE TITLE
How to check and restore automatic backups from pksm?

### ISSUE THREAD

**Issue by wandalusy** [FlagBrew/PKSM#1259]
The same thing in the title

**Comment by GriffinG1** [comment]
This is incredibly vague. What do you mean "automatic backups"?

**Comment by wandalusy** [comment]
Pksm creates backups of the game i think?

**Comment by GriffinG1** [comment]
Ah, you're referring to those. Enable `Show backups` in Settings>Misc.

**Comment by wandalusy** [comment]
But can you delete those? becouse i messed up with events.

**Comment by GriffinG1** [comment]
In PKSM? No. In a file browser? Yes.

**Comment by wandalusy** [comment]
But where are those located?

**Comment by wandalusy** [comment]
Ok I found it. Thanks for help!
