### ISSUE TITLE
Bug Report - PKSM Exception Occurred（Translation-Section）

### ISSUE THREAD

**Issue by Aiyan0117** [FlagBrew/PKSM#1261]
**Describe the bug**
Set the default option ''generation:3'' error

**To Reproduce**
1. Open PKSM
2. Go to the default settings
3. Click the generation 3 button
4. An error interface appears

**Expected behavior**
I want to know the solution.

**Screenshots**
Screenshot when the error occurred.
![微信图片_20210323130151](https://user-images.githubusercontent.com/81208866/112096713-c7babc00-8bd9-11eb-96a8-6ab022f9a471.jpg)
![微信图片_20210323130200](https://user-images.githubusercontent.com/81208866/112096715-c8ebe900-8bd9-11eb-8756-7a828b183fbe.jpg)

**Information about your environment**
 - OS version:New3ds(B9s) Sys 11.14.0-46J
 - PKSM version:v9.2.0
 - Entrypoint:Don't know

**Additional context**
When running pksm without any game archives loaded, there is an error when you open generation 3 in the default option to modify, as shown in the figure.

**Comment by GriffinG1** [comment]
Can reproduce both with and without save archives. Dumps attached.
[gen 3 defaults crash dumps.zip](https://github.com/FlagBrew/PKSM/files/6187117/gen.3.defaults.crash.dumps.zip)

**Comment by GriffinG1** [comment]
Further testing leads me to believe the default `default.pk3` file is invalid, as deleting the file from `/3ds/PKSM/defaults/` allows me to set the default properly.

**Comment by Aiyan0117** [comment]
Now I try to open default.pk3 using PKHex, and get the following prompt:Move Index beyond range：38645，51489，38645，51489

发件人: ***@***.***>
发送时间: 2021年3月23日 13:46
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [FlagBrew/PKSM] Bug Report - PKSM Exception Occurred（Translation-Section） (#1261)


Further testing leads me to believe the default default.pk3 file is invalid, as deleting the file from /3ds/PKSM/defaults/ allows me to set the default properly.

―

**Comment by piepie62** [comment]
Yeah, not sure why that happened. Could you try deleting it, reopening, and tell me if it fixes it?

**Comment by Aiyan0117** [comment]
I delete default.pk3 After the document，The error is indeed resolved, but the same error still exists after closing the software

发件人: Chris ***@***.***>
发送时间: 2021年3月23日 13:55
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [FlagBrew/PKSM] Bug Report - PKSM Exception Occurred（Translation-Section） (#1261)


Yeah, not sure why that happened. Could you try deleting it, reopening, and tell me if it fixes it?

―

**Comment by piepie62** [comment]
Found the issue and pushed a fix; if you delete the default, change something in it on that first load and then save that change, you should be fine for any more loads to come

**Comment by Aiyan0117** [comment]
The problem has been resolved, thank you！

发件人: Chris Feger ***@***.***>
发送时间: Tuesday, March 23, 2021 2:19:01 PM
收件人: FlagBrew/PKSM ***@***.***>
抄送: Aiyan0117 ***@***.***>; Author ***@***.***>
主题: Re: [FlagBrew/PKSM] Bug Report - PKSM Exception Occurred（Translation-Section） (#1261)


Found the issue and pushed a fix; if you delete the default, change something in it on that first load and then save that change, you should be fine for any more loads to come

―

**Comment by GriffinG1** [comment]
Fixed in [v10](https://github.com/FlagBrew/PKSM/releases/latest).
