### ISSUE TITLE
Unable to access Leaf Green save

### ISSUE THREAD

**Issue by KidLycan** [FlagBrew/PKSM#1263]
**Describe the bug**
I did the whole, gba rom file patch job you have to do to play the main pokemon series games and found some icons for the main menu and game icons. Played until you can save the game so there is a save file to at least see, but there is nothing there.

**To Reproduce**
Once opening pksm, i do not see the save file for Leaf Green

**Expected behavior**
To see a save file

**Screenshots**
![20210326_140238](https://user-images.githubusercontent.com/75453922/112674569-79592780-8e3c-11eb-8026-b458fe8ad609.jpg)
![20210326_140248](https://user-images.githubusercontent.com/75453922/112674594-80803580-8e3c-11eb-81eb-16f2ba139410.jpg)
![20210326_140138](https://user-images.githubusercontent.com/75453922/112674603-8249f900-8e3c-11eb-9e66-9373858a15b6.jpg)

**Information about your environment**
 - OS version: current
 - PKSM version: 9.2.0

**Additional context**
Works just fine with cartage games.

**Comment by GriffinG1** [comment]
Read the wiki concerning setting up GBA titles.

**Comment by KidLycan** [comment]
thats vague. can you give me a link to the right page i need?

**Comment by GriffinG1** [comment]
Why not take a few minutes and look through the wiki, instead of asking for me to spoon feed you? I’ll give you a hint: it’s something you need to configure.

**Comment by KidLycan** [comment]
While trying to figure out what is going on, and using the link below, I found an issue trying to see if i can access the editor manually with said issue posted and i got these odd error messages.

https://github.com/FlagBrew/PKSM/wiki/Settings#tab-2-defaults


![20210326_165224](https://user-images.githubusercontent.com/75453922/112691806-3c009400-8e54-11eb-8181-704865eb5400.jpg)
![20210326_165229](https://user-images.githubusercontent.com/75453922/112691977-87b33d80-8e54-11eb-871a-6f485e56ddea.jpg)

**Comment by GriffinG1** [comment]
Known issue, fixed in latest commits, and not related to setting up gen 3 titles.

**Comment by kiasta** [comment]
Since it's not really clear in the wiki. Open up FBI and then Titles to find the Title ID of whichever game you are trying to load in PKSM (or find the Title ID of the game some other way). Then in the settings of PKSM under Misc -> Title IDs. Match the IDs and you should be fine.

**Comment by KidLycan** [comment]
thanks! I finally can play pokemon leaf green again!
