### ISSUE TITLE
Bug Report - Brief Description/Name of issue

### ISSUE THREAD

**Issue by ryuto2** [FlagBrew/PKSM#1265]
![221352F6-F581-409D-A2FE-CC92711AD720](https://user-images.githubusercontent.com/81542683/113251614-8f179280-92fd-11eb-94f2-112ff75744ef.jpeg)

All Pokemon will be displayed as Eevee ❗
Please fix (Japan)

**Comment by piepie62** [comment]
https://github.com/FlagBrew/PKSM/wiki/FAQs#all-the-sprites-in-pksm-have-been-changed-what-went-wrong
