### ISSUE TITLE
April fool bombs

### ISSUE THREAD

**Issue by carcaschoi** [FlagBrew/PKSM#1266]
![16172706629888930874361250701996](https://user-images.githubusercontent.com/64573431/113276968-df4d1f80-9312-11eb-82a9-94e4ae5f0eeb.jpg)

all pokemon change to eevee. Imao

**Comment by Masamune3210** [comment]
Looks like a perfectly normal Bidoof to me

**Comment by thecompi** [comment]
at first, i thought the whole thing got messed up, but now i hope its just for april fools lol

**Comment by GriffinG1** [comment]
https://github.com/FlagBrew/PKSM/wiki/FAQs#all-the-sprites-in-pksm-have-been-changed-what-went-wrong

**Comment by mai2299** [comment]
How i can fix this??

**Comment by thecompi** [comment]
> How i can fix this??

dude, this is april fools joke, it will go away on april 2 i guess

**Comment by johjan** [comment]
mine is the same way too.  today it happened!  yesterday was normal.

**Comment by carcaschoi** [comment]
We live in different time zones since yesterday HK is 1/4😏
