### ISSUE TITLE
LeafGreen - Setting Item Quantity in Bag

### ISSUE THREAD

**Issue by ProfessorCypress** [FlagBrew/PKSM#1268]
Recently started using PKSM 9.2.0 to modify my LeafGreen save, and when I change the quantity of an item in the bag, it doesn't show the number I set. For example, when I type in 5, hit Ok, I now have 6541 of that item. When I type in 6541, it gives me 5. If I use the plus and minus to incrementally increase it, from 5 it jumps to 36898 (could be 86898 but the minus button blocks the left side so I'll say 36898), then to random odd numbers or with a 5-digit number in between. I took a video and it doesn't seem to be possible to upload it here.

**Comment by GriffinG1** [comment]
Has already been fixed for the next version.
