### ISSUE TITLE
Bug Report - Music not playing

### ISSUE THREAD

**Issue by Mewthree3** [FlagBrew/PKSM#1269]
**Describe the bug**
When I boot PKSM (and have mp3 music in 3ds/PKSM/songs), music does not play, even if I toggle "randomize music" on/off.

**To Reproduce**
1. Boot PKSM, with music in the correct directory
2. Turn volume up
3. There shouldn't be music playing.

**Expected behavior**
Music plays when PKSM boots

**Information about your environment**
 - OS version: SysNAND 11.14.0-46J
 - PKSM version: v9.2.0-656eb68a
 - Entrypoint: Luma3DS

**Additional context**
50 songs in the folder, they're all in mp3 format. The folder is 255 MB in size. Is it possible that PKSM is just taking a long time to load/choose which file to play?

**Comment by piepie62** [comment]
You very likely do not have your DSP firm dumped. This is a required step for any homebrew to play music. See <https://3ds.hacks.guide/finalizing-setup#section-v---dsp-dump> for instructions.

**Comment by Mewthree3** [comment]
I dumped it again (music playing HB worked before redumping), and I still encounter the issue

**Comment by GriffinG1** [comment]
Double check that your files fit within the recommendations listed [on the wiki](https://github.com/FlagBrew/PKSM/wiki/FAQs#how-do-i-add-custom-music). If they don’t, nothing we can do.
