### ISSUE TITLE
PKSM Pokemon Leaf Green issues

### ISSUE THREAD

**Issue by Pokemonbasher** [FlagBrew/PKSM#1270]
When I press evens I am prompted 'No wonder cards present Use the universal script "injector.c"'
![20210430_040821](https://user-images.githubusercontent.com/83440012/116643805-bcda1080-a969-11eb-86a5-1ae2ef01fc43.jpg)

When I enter scripts it days "Folder does not exist" and when I go to universal scripts and go to injector.c and accept it says "There are no files in '/3ds/PKSM/inject'! Place wondercard or pokemon files there"
![20210430_041007](https://user-images.githubusercontent.com/83440012/116643928-032f6f80-a96a-11eb-8f79-5b94549348c9.jpg)

Finally, my item numbers do no work when I type in a number it becomes a much larger one.
![20210430_041148](https://user-images.githubusercontent.com/83440012/116644036-3d990c80-a96a-11eb-93b2-177c57dc5edb.jpg)
![20210430_041152](https://user-images.githubusercontent.com/83440012/116644038-3eca3980-a96a-11eb-9153-18a4a8ab0c04.jpg)

**Comment by GriffinG1** [comment]
![image](https://user-images.githubusercontent.com/28538707/116644122-ce9ec200-a92f-11eb-908c-ca94e608a6fe.png)

re: item numbers - already fixed for next version.

**Comment by Pokemonbasher** [comment]
![20210430_041758](https://user-images.githubusercontent.com/83440012/116644381-1abb2800-a96b-11eb-9fab-e9bc3e6bbf3b.jpg)
![20210430_041804](https://user-images.githubusercontent.com/83440012/116644382-1bec5500-a96b-11eb-8f1a-76d2ecccae2f.jpg)

Also when I press generation 3 on this menu the following happens^

I am running lastest PKSM and 3ds update.

**Comment by GriffinG1** [comment]
See #1261. Again, already fixed for next version.

**Comment by Pokemonbasher** [comment]
> ![image](https://user-images.githubusercontent.com/28538707/116644122-ce9ec200-a92f-11eb-908c-ca94e608a6fe.png)
> 
> re: item numbers - already fixed for next version.

Where can I find this events gallary?
