### ISSUE TITLE
Bug Report - PKSM doesn't detect Soul Silver in slot

### ISSUE THREAD

**Issue by drislands** [FlagBrew/PKSM#1275]
**Describe the bug**
When in PKSM, the "Game Card" section remains empty despite a copy of Soul Silver being there, and the 3DS itself recognizing that it is there and playable.

**To Reproduce**
1. Open PKSM
2. Insert Soul Silver
3. The software seems to hiccup for a moment, as if recognizing something is in the slot, but otherwise there is no change

**Expected behavior**
Soul Silver is selectable and its save editable.

**Information about your environment**
 - OS version: 11.7.0-40U
 - PKSM version: 9.2.0

**Additional context**
The 3DS has been telling me for a while now that it is due for a system update, which I have been ignoring. I'm not sure how out of date the OS is and am unsure if I should update it or if that would break the CFW.

**Comment by piepie62** [comment]
Heart Gold and Soul Silver are the two games that we have noticed have the worst bad fakes; it is my guess that this is one of them. You can take a Checkpoint backup and toss it here to confirm that that is the case, but given that these are the exact symptoms of that, I'm going to close this.

**Comment by drislands** [comment]
> the worst bad fakes

Can you clarify what you mean? Is my cartridge possibly not legitimate? I'm sorry, I'm not familiar with this terminology...

**Comment by Masamune3210** [comment]
Yeah, your cart is likely not legit

**Comment by Mewthree3** [comment]
I think he means “most convincing fakes in looks, but they don’t properly function as the game when detected”?

**Comment by drislands** [comment]
Damn, I didn't even think that would be a possibility...I'll see about getting the Checkpoint to confirm.

**Comment by piepie62** [comment]
Just "don't function properly", yeah. Saves accessed using proper methods for these seem to be garbage dumped from a random region of memory for these

**Comment by drislands** [comment]
[POKEMON SS.zip](https://github.com/FlagBrew/PKSM/files/6463053/POKEMON.SS.zip)

Save file attached. I'll admit I don't know what a legit cartridge ought to look like, though the one I received looks like the other non-pokemon games I own.

**Comment by piepie62** [comment]
Yep, very clearly a fake. It has the right size, sure, but here's a screenshot of the contents. Very obviously some memory from Checkpoint

![image](https://user-images.githubusercontent.com/8108982/117911889-888d1b00-b2ac-11eb-9e8c-0df1e5359666.png)

**Comment by drislands** [comment]
Well shit. That means using PKSM is out of the question then, I assume. :( I'm not sure if I have any recourse since I bought it used on Amazon, but do you happen to know if I'm likely to run into other issues with the game? Sorry for the off-topic question, I'm just kind of blown away this happened at all.

**Comment by piepie62** [comment]
Nope, absolutely no idea if you're likely to run into any other issues.

**Comment by Mewthree3** [comment]
Technically you can load saves from TWiLIGHT Menu using PKSM, so if you decide to get the rom file by...using certain websites, it’s very possible to make it work out all right. Of course if you’d like to use a cartridge (I like digital-only myself), you’re basically out of luck sadly.

**Comment by Mewthree3** [comment]
Also, LUMA3DS supports the newest system firmware/update. If you’re that nervous about it, you could make a system backup using GODMODE9, and restore it if anything goes wrong

**Comment by piepie62** [comment]
I would appreciate it if you would not recommend piracy in our issue tracker
