### ISSUE TITLE
Saves unreadable in PKHeX

### ISSUE THREAD

**Issue by Tenkomanker** [FlagBrew/PKSM#1276]
Basically, I'm trying to dump the saves for the Virtual Console roms I have installed. What I do is I go to edit one of the VC titles, and when PKSM makes a backup of it, I take the 000000001.sav or whatever off of 3ds/PKSM/backup from my card using FTBDB but when I throw it into PKHeX it says that the binary is not compatible. This is the only way I've found to dump saves and it doesn't work at all. Probably not a bug but I've read through a good chunk of the wiki so unless I'm missing something painfully obvious, I can't find any way to dump the VC rom saves into an editable file for PKHeX.

**Comment by piepie62** [comment]
That's interesting. Could you zip up your save and toss it here? That should be a valid backup, and that it's not is concerning, to say the least

**Comment by piepie62** [comment]
It could also be useful to know the PKHeX version you're using

**Comment by Tenkomanker** [comment]
I'm using the latest version of PKHeX, exact version I think would be 20210521?
For reference, here's what I do to get the backup step-by-step;
VC Games -> Pokemon FireRed -> Select VC and load Game Save File. This makes a backup.

I back out (B) and note the name of the latest backup (2021-5-27_2-6-20 since I'm making it right now).

Go to homescreen -> FTPDB -> Connect using FileZilla and navigate to 3ds/PKSM/backup/titleID(one I found using FBI, displays as 00E5C400 in PKSM, 0x0E5C4 in the backups folder) and find the latest backup in 3ds/PKSM/backup/0x0E5C4/2021-5-27_2-6-20 labelled as 00000001.sav in the folder.

I toss 00000001.sav into PKHeX and nothing. Just shows up as binary not compatible. I've only tried it with FireRed as it's the only one I've been playing so far, so I don't know if it's a recurring problem or not or even if it's just me doing something incorrectly.

Here's a .rar of my save file. With my luck I bet you'll be able to get it to work.
[00000001.zip](https://github.com/FlagBrew/PKSM/files/6551527/00000001.zip)

**Comment by GriffinG1** [comment]
I can access the save fine on the same version (which is latest stable). Make sure you're loading it in as a proper FireRed save.

You can also backup your save a more sensible way via [GodMode9](https://3ds.hacks.guide/dumping-titles-and-game-cartridges#backup-gba-vc-saves).

As this does not seem to be on PKSM's side, I shall be closing this.
