### ISSUE TITLE
Bug Report - citra and pksm

### ISSUE THREAD

**Issue by crocodama** [FlagBrew/PKSM#1278]
**Describe the bug**
i installed pksm 9.2.0 on citra and it doesn't work.

**To Reproduce**
1. open citra
2. open pksm
3. see error 0xD88007FA "Rosalina sysmodule has not been found"

**Expected behavior**
open pksm
**Screenshots**
![image](https://user-images.githubusercontent.com/86365509/123116575-b20f9980-d449-11eb-92d6-3376124a776a.png)
**Information about your environment**
 - OS version: 
 - PKSM version: 9.2.0
 - Entrypoint:

**Additional context**

**Comment by GriffinG1** [comment]
You need to manually compile PKSM with a specific flag to work with Citra. Not a bug.

**Comment by Wolf-lbh** [comment]
> You need to manually compile PKSM with a specific flag to work with Citra. Not a bug.

How? This is not covered anywhere in the documentation which simply says to put the assets needed in /sdmc/3ds/PKSM/assets/ ? If there is no instruction on how to get it working in emulators that is either a bug or a drastic oversight.

**Comment by GriffinG1** [comment]
> > You need to manually compile PKSM with a specific flag to work with Citra. Not a bug.
> 
> 
> 
> How? This is not covered anywhere in the documentation which simply says to put the assets needed in /sdmc/3ds/PKSM/assets/ ? If there is no instruction on how to get it working in emulators that is either a bug or a drastic oversight.

Citra support has been dropped in the 3 years since this comment. Please do not post on years old closed issues.
