### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by darealoctoham** [FlagBrew/PKSM#1279]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Support for gen IV-V games that have been forwarded to the home menu using a nds forwarder

**Describe alternatives you've considered**
I can't think of any

**Additional context**
I personally use NDSFowarder ([https://db.universal-team.net/3ds/ndsforwarder](https://db.universal-team.net/3ds/ndsforwarder))

**Comment by piepie62** [comment]
Already done, try reading [the wiki](https://github.com/FlagBrew/PKSM/wiki/FAQs)

**Comment by darealoctoham** [comment]
thanks @piepie62 sometimes i dont read enough
