### ISSUE TITLE
Help: Gen 4 HackedMons and Modded Pokémon not legalized in PKSM

### ISSUE THREAD

**Issue by Sieg9** [FlagBrew/PKSM#1281]
Hello, I have a problem when using PKSM on the 3DS to generate or modify Pokémon in Gen 4, specifically Pokémon SoulSilver. I’ve tried to list the problems I encountered with each below.

- Modded Pokémon: 

When I attempt to change IVs, abilities, or nature I receive an error telling me, “Invalid: Type PID mismatch” or another error similar.

- HackedMons:

When I attempt to generate a Pokémon (ex. making a starter with the met location and encounter appear identical to a starter given to you in the game) I get legalization errors saying, “Invalid: Encounter Type PID mismatch,” and, “Invalid: Encounter Type does not match.” 

I’m not aware if this is because the Pokémon’s bytes aren’t updating to match with the changed information or something else. If anyone reading this post is confused I am happy to clarify and try to explain it again as best as I can.

**Comment by GriffinG1** [comment]
You need to properly adjust the PID yourself in the hex editor. Refer to the wiki for how.

Alternatively:
![AE945354-97D8-49D9-B270-8750B444C279](https://user-images.githubusercontent.com/28538707/123526659-a2d15b80-d696-11eb-961f-662268185294.jpeg)

**Comment by Sieg9** [comment]
Thank you for your help. I had a feeling I needed to update the PID but I wanted to post just to verify it wasn’t anything else.
