### ISSUE TITLE
Help and tips with modifying PID

### ISSUE THREAD

**Issue by Sieg9** [FlagBrew/PKSM#1282]
Does anyone have any advice or tutorials they can show/recommend for modifying PID to legalize my Pokémon? I've looked to the wiki but I haven't found much help. I'm currently legalizing genned starter Pokémon and modified caught Pokémon in the Gen 4 DS games.

**Comment by piepie62** [comment]
That's not really a PKSM-specific question. I also don't know much about the PID-IV-whatever else is relevant relationships. You can try looking in other places like [ProjectPokemon](https://projectpokemon.org/)
