### ISSUE TITLE
Support For ROM Hack Cia's

### ISSUE THREAD

**Issue by Luigi-Clan** [FlagBrew/PKSM#1283]
It's just a mild inconvenience that you can do it with all the other installed VC runs of the game, but not the ROM Hack one's.

Just the ability to dable with the Pokémon in these games is all I request.

The simplist idea I can think of is a third tab next to "VC Games" that looks for registered ROM Hacks

Thank you for your time, and sorry if I came off a bit demanding, this is my first time submitting something like this.

**Comment by GriffinG1** [comment]
Lack of ROM hack support is intentional due to differences in the save which would make it difficult to implement.

You can try to load in the hack as a normal save. It will either work, or it won't. But no dedicated support will ever be implemented.
