### ISSUE TITLE
[Feature Request] - GameCube Gen 3 to PKSM Bank Migration Support

### ISSUE THREAD

**Issue by ThisNekoGuy** [FlagBrew/PKSM#1285]
**Is your feature request related to a problem? Please describe.**

PKHeX, which is a Windows exclusive program and supports this feature, doesn't work on non-Windows operating systems (and doesn't aim to cover support for alternative operating systems at all).

Emulators are supported on basically every OS, including Linux (and as a Linux user myself), bringing Pokemon from the GameCube games without Windows (through Dolphin) basically requires that you trade it over to a GBA game in a painstakingly slow process to transfer it over to the modern games.

**Describe the solution you'd like**

Ideally, having something like PKHeX available on non-Windows systems would be great (as it doesn't work properly in Wine) but, considering that PKSM is the next closest thing to PKHeX, having PKSM be able to find and read a Dolphin's memory card implementation to transfer Pokemon to PKSM's banks would also be an effective solution for moving Pokemon over to the games on original hardware.

**Describe alternatives you've considered**

The PKHeX project has no interest in supporting non-Windows users and the only other viable way to move Pokemon from the GameCube games is through physical hardware and the tedious genrational migration processes from over the years.

**Comment by GriffinG1** [comment]
PKSM will not at any point support non-mainline games. Furthermore, you can use PKHeX via Mono or Wine on Linux. As an advance note, this is not the place to ask how. There is no doubt a guide on ProjectPokemon.

**Comment by ThisNekoGuy** [comment]
@GriffinG1 Fyi, this is what PKHeX looks like in Mono:
![image](https://user-images.githubusercontent.com/28468662/131265896-438fd802-8c85-41dd-aca4-42eaeb5133a5.png)

And you basically can only even get this far with Wine with concerning errors
