### ISSUE TITLE
Bug Report - Updated PKSM. Sits on "Converting storage" for ~2 mins then "Bank backup failed" save the bank anyway?

### ISSUE THREAD

**Issue by LasagneCat** [FlagBrew/PKSM#1286]
I updated PKSM from an old version to the current version (used the QR code) I don't know what the old version was.

When I launch PKSM I get the bouncy pokemon logo and then it says "Converting Storage" for 2-3 minutes. It's a really long time. After that it says "Bank Backup Failed! Save the bank anyway?" I click B to cancel cause I don't know what it's saving and don't wanna risk losing my 150 pages of saved pokemon. After that I can use the app as normal and see my pokemon. 

This happens every time I launch he app. I don't know what to do. If there's a way I can backup my saved pokemon besides copying them all to various games I would have risked clicking A to overrite save. I just haven't done it for fear of losing my existing storage. I was using this program for months before I figured out I could update it.

 - OS version: Latest. Just updated
 - PKSM version: Latest. I just updated this too. Also luna updater
 - Entrypoint: I don't know what this is

**Comment by piepie62** [comment]
If you see no problems after that menu, you're good to save the bank anyway. The backup failure just means that the old-format bank couldn't get saved to the SD for some reason. THAT SAID, if you want to be extra safe about it, I'd suggest making a Checkpoint backup of PKSM's ExtData first. I'll see if there's anything that would cause the bank backup to fail in the general case, but my first guess is that you're out of storage space or something

**Comment by LasagneCat** [comment]
Thank you. I was very worried, but overwriting didn't cost me my saved pokemon

**Comment by piepie62** [comment]
Uhhh, honestly, that's possible; I expected that you checked everything was there. I can't remember where bank backups were before the point where that would have happened is to check if I can restore it, though... could you zip up your entire `/3ds/PKSM` folder and send it to me either here or through Discord (I'm piepie62#3412 in [our server](https://discord.gg/bGKEyfY))? Doing it through Discord would be a privacy measure in case you don't feel comfortable sending your save/bank backups in a public space so feel free to DM me the ZIP if you follow that route

**Comment by LasagneCat** [comment]
[PKSM.zip](https://github.com/FlagBrew/PKSM/files/6871091/PKSM.zip)

Thank you for helping me with this

**Comment by piepie62** [comment]
No, downgrading like that will not work (and wouldn't fix the boxes being gone)

**Comment by piepie62** [comment]
I've got good news for you: this backup appears to contain everything. Could you now make a Checkpoint backup of your PKSM ExtData, zip it up, and send it to me? I'll send you back a fixed zip to restore

**Comment by LasagneCat** [comment]
I don't see pksm in checkpoint (3.7.4) though I do have Pokemon Bank. I don't remember downloading that but it's possible I did and forgot.

**Comment by GriffinG1** [comment]
Make sure you're checking the ExtData, not main saves (press X).

**Comment by LasagneCat** [comment]
[20210724-075539.zip](https://github.com/FlagBrew/PKSM/files/6871151/20210724-075539.zip)

**Comment by piepie62** [comment]
[20210724-075539-fixed.zip](https://github.com/FlagBrew/PKSM/files/6871284/20210724-075539-fixed.zip)
Here you go

**Comment by LasagneCat** [comment]
Thank you so much, you're a deadset legend. Thank you thank you.

**Comment by Mewthree3** [comment]
Ok this is wholesome 
Good work PKSM team, thanks for your awesome contributions ⚡️⚡️
