### ISSUE TITLE
Error 0x08000000

### ISSUE THREAD

**Issue by PressPrexx** [FlagBrew/PKSM#1287]
I'm getting error 0x08000000 on PKSM with all of my DS roms from Twilight Menu++. I have never used PKSM before and none of the solutions online work. Can anyone help me out?

**Comment by piepie62** [comment]
About 99% certain this is you having pointed PKSM to the ROM instead if the save.

**Comment by Mewthree3** [comment]
(BTW the save directory is found in (your roms thingy where your DS roms are)/saves)
So for example, sd:/roms/DS/saves
