### ISSUE TITLE
Feature Request: Add instructions to download assets manually

### ISSUE THREAD

**Issue by LabregoPT** [FlagBrew/PKSM#1292]
**Is your feature request related to a problem? Please describe.**
PKSM Requires the console to be connected to the internet before its first launch to download required assets and files, however, such requirement can not always be fullfilled. My New 3DS, for example, has a faulty network chip that basically disables all kind of wireless connection, thus rendering me unable to connect my console to the internet and, in turn, unable to use PKSM. I recently learned that you can install the required assets manually, but I could only find it beacuse someone else pointed me so.

**Describe the solution you'd like**
A set of instructions to manually download the required assets, or a message pointing to [this Wiki page](https://github.com/FlagBrew/PKSM/wiki/Basics#additional-assets) on the error screen shown after assets' download fails.

**Describe alternatives you've considered**
Going to GitHub and opening an issue to find out you can actually install manually? This could help reduce creation of these things

**Comment by SpiredMoth** [comment]
The wiki already has instructions for getting the additional assets [here](https://github.com/FlagBrew/PKSM/wiki/Basics#additional-assets).

I would say that having the instructions in PKSM in some way would be nice for new users, but adding them is a non-trivial problem I'm not sure the devs of the app want to tackle.

**Comment by LabregoPT** [comment]
Yeah, thanks for the heads up, I had no idea the project had a Wiki with this kind of info. Usually this kind of homebrew is just like "install and use", which makes finding it somewhat of a problem.
Gonna edit the issue, I believe a message on the error screen that throws when PKSM can't download the assets stating you can manually download the files and how to do so, either by having the steps on the same screen or pointing to the wiki, could be a better approach.
Thanks anyway!

**Comment by Mewthree3** [comment]
Or I’d suggest, maybe like something in the readme? Copy and paste the asset instructions

**Comment by LabregoPT** [comment]
I think this issue is way too specific to make it to the front description page of the project. How many 3DSs out there can not connect to the internet nowadays compared to those who can?

**Comment by Mewthree3** [comment]
Fair enough. I only know one other person really—I agree. Apologies for an unoptimal suggestion
