### ISSUE TITLE
Attempting to edit Gen III defaults results in the app/3DS crashing

### ISSUE THREAD

**Issue by RealKGB** [FlagBrew/PKSM#1293]
**Platform**
New Nintendo 3DS XL

**Describe the bug**
When attempting to edit the default Pokemon for Gen III  the app/3DS crashes immediately upon clicking the 3 bars that corresponds with editing the defaults.

**To Reproduce**
1. Open PKSM
2. Push X
3. Click Defaults
4. Select the 3 lines next to Generation: 3
5. Watch your DS crash

**Expected behavior**
Me to be able to edit the Gen 3 defaults

**Screenshots**

**Information about your environment**
 - OS version: Luma3DS 10.2.1
 - PKSM version: 9.2.0
 - Entrypoint: ???

**Comment by GriffinG1** [comment]
#1261 duplicate.
