### ISSUE TITLE
QR code doing nothing 

### ISSUE THREAD

**Issue by supermotarddu80** [FlagBrew/PKSM#1294]
Hello, whenever I scan a QR code made from PKHex with the lunar cookie tool, or any QR code I try, I just end up on my boxes, as nothing happened, the 3Ds reads it (with that little freeze meaning that it reads something), but absolutely nothing happens. 

The tool is: http://lunarcookies.github.io/upload.html
I am scanning any QR code made from this, or found on the internet, pressing L and R and letting my 3DS read it, repeating it several times, nothing ever happens, only that small freeze and me returning back to the menu. I tried with X and Y, as well as USUM, nothing changes. 

PKSM Version is v6.2.1
3DS is Sys 11.14.0-46E, using Luma

I don't know if it's a known issue or if I am doing something wrong, but thank you in advance !

**Comment by GriffinG1** [comment]
Haven't heard back on this in over a month, closing.
