### ISSUE TITLE
Region Setting Id's

### ISSUE THREAD

**Issue by KentuckyFriedKen** [FlagBrew/PKSM#1295]
Hello, lemme cut right to the chase.
So basically, I wanna assign different regions to pokemon. I already figuered out how to edit them to be japanese (I had a japanese pokemon to reference)
However, I have a hitmonlee I'd like to make chinese (cuz bruce lee, ya get it?)
I couldnt figure the region ID out.
For this problem and for future problems, could someone make a table listing all region ID's for convenience?

If you can help me out with this, thanks in advance!

**Comment by piepie62** [comment]
If by "region IDs", you mean the geolocation, that's not a simple edit. That's the only thing I can think of if you don't mean language, which you said that you figured out. If you DID mean language, that'll be either 9 or 10 (aka 0A in hexadecimal); those are Chinese Simplified and Chinese Traditional, respectively. I'll think about putting that on the wiki; it just doesn't seem like a great place for it, as it's not PKSM-specific knowledge, it's general Pokémon format knowledge
