### ISSUE TITLE
Bug Report - Misspelled move 'Faint Attack'

### ISSUE THREAD

**Issue by Meryl** [FlagBrew/PKSM#1296]
**Describe the bug**
The attack 'Faint Attack' is spelled 'Feint Attack' in PKSM.

**To Reproduce**
1. Select any save file, then go to 'Editor'.
2. Edit any Pokémon.
3. Edit any of the Pokémon's moves. 
4. Look for 'Faint', no results.
5. Look for 'Feint', you'll find the move 'Feint' and 'Feint Attack'.

**Expected behavior**
The move is called 'Faint Attack'.

**Screenshots**
I didn't take any screenshots, but the problem should be obvious.

**Information about your environment**
 - OS version: 11.15.0-47E
 - PKSM version: 9.2.0
 - Entrypoint: I don't know, but I don't think it's relevant.

**Additional context**
The game I've found this out with is Soul Silver.

**Comment by GriffinG1** [comment]
Feint Attack is the correct spelling, and has been since generation 6.

**Comment by Masamune3210** [comment]
For reference 
![image](https://user-images.githubusercontent.com/1053504/132100444-0c99d017-0f0f-46f8-b9a9-6fc53bd05611.png)

**Comment by FM1337** [comment]
https://bulbapedia.bulbagarden.net/wiki/Feint_Attack_(move)
