### ISSUE TITLE
Idioma

### ISSUE THREAD

**Issue by DenisWilliam0097** [FlagBrew/PKSM#1298]
Mudei o idioma e não consigo voltar para o inglês

**Comment by GriffinG1** [comment]
Solamente ingles aqui por favor.

**Comment by DenisWilliam0097** [comment]
Well my pokemon is in Japanese instead of English after use

Em dom, 19 de set de 2021 22:51, Griffin ***@***.***>
escreveu:

**Comment by GriffinG1** [comment]
Your Pokémon... as in your game?

**Comment by DenisWilliam0097** [comment]
Ultra moon


Em dom, 19 de set de 2021 23:14, Griffin ***@***.***>
escreveu:

**Comment by GriffinG1** [comment]
I'm assuming you injected a different language event. Either inject an event that uses your language, or use the universal language change script.

**Comment by DenisWilliam0097** [comment]
Okay but how am I going to replace the injector

Em dom, 19 de set de 2021 23:28, Griffin ***@***.***>
escreveu:
