### ISSUE TITLE
Bug Report - Additional Assets Download failed

### ISSUE THREAD

**Issue by InternalLoss** [FlagBrew/PKSM#1299]
**Describe the bug**
When trying to open the PKSM app on my 3DS, it continuously fails to communicate with GitHub to download additional assets. 
Error code: 0XFFFFFF80
**To Reproduce**
1. Launch PKSM for the first time.

**Expected behavior**
Assets download, app launches.

**Screenshots**

**Information about your environment**
 - OS version: 11.15
 - PKSM version: 9.2.0-656eb68a
 - Entrypoint: Luma3DS (CIA from Home Menu)

**Additional context**
When viewing communication through Wireshark, the 3DS seems to stop communicating shortly after it starts the actual TLS session with the server - since PKSM does not respect proxy settings [unlike other home-brew such as FBI], I am unable to check what error is occurring.

**Comment by piepie62** [comment]
I literally do not know how to do proxy settings; the FBI logic branch that works with libcurl doesn't seem to have any explicit proxy handling. I can't fix an issue that I don't understand. Download the assets manually as stated here, or disable your proxy.
![here](https://user-images.githubusercontent.com/8108982/134582623-f602b5b6-97cf-43db-b7c1-f609d94e9f13.png)

**Comment by InternalLoss** [comment]
I'd like to reopen this - I explicitly stated that this occurs **without a proxy** too.

**Comment by piepie62** [comment]
Just checked the error code. That's the timeout expiring. I don't know *why* the timeout is expiring before any data is sent back, but it is. If it's become a common issue, I'll look into that, but as of right now, you're the only person I know of this happens for; I just tried it myself and it worked fine.
