### ISSUE TITLE
Precise External Abort

### ISSUE THREAD

**Issue by Ninjabear89** [FlagBrew/PKSM#1302]
After loading the Pokemon Fire Red save it pops up

**To Reproduce**
Load a save from FireRed which is absent

**Expected behavior**
I've never seen what this app can do, but i expected to see my Pokes from FireRed.

**Screenshots**
![IMG_20211024_184408_002](https://user-images.githubusercontent.com/93091816/138604424-41741de5-170f-4a59-850d-3cba62f1c750.jpg)

**Information about your environment**
 - OS version: 11.7.0-40e
 - PKSM version: 9.2.0
 - Entrypoint:

**Additional context**
Followed 3ds.hacks.guide to bring my 3ds up to date. Before that update Pksm only started with a black screen and an error.

**Comment by GriffinG1** [comment]
How are you running the game (if emulator, which one)? If you're using a virtual console inject, how did you obtain the save?

**Comment by Ninjabear89** [comment]
I must have missed a step in the startup phase. Stumbled upon a thread on reddit explaining how to add vc titles and now it works.
