### ISSUE TITLE
Can't access to unreleased wonder cards

### ISSUE THREAD

**Issue by Alalramrod** [FlagBrew/PKSM#1308]
Dear Team,

Thanks for the amazing work, big fan in here!
I can see on the 9.0.0 update you added the unreleased wonder cards, such as the azure flute. I'm playing on platinum on an official cartridge, and I don't seem to be able to find those unreleased cards. I'm using PKSM 9.2.0, the most recent version. Is there anything I might be missing? I can inject without any problems all the other events, and my system recognizes a total of 311 events (including all regions).

I'll appreciate any kind of imput you can give me on the topic. Thanks a lot for your time!

**Comment by GriffinG1** [comment]
Azure flute has a Japanese name iirc, and it's near the end of the list. I recommend looking through [EventsGallery](https://github.com/projectpokemon/EventsGallery/) for info on any other unreleased events.
