### ISSUE TITLE
GBA titles are not working correctly with pksm

### ISSUE THREAD

**Issue by pokemonfan6498** [FlagBrew/PKSM#1309]
I had updated to latest version of PKSM being version 9.2.0 so i made injects of ruby sapphire and emerald but something was wrong at first when i entered title the keyboard just disappeared after i pressed confirm the screen was been without keyboard until i pressed any button what thrown me back to Settings menu i decided to check VC games list and i found that there was pokemon ruby inject i added but when i tried to open save file it said first save absent I didn't known what it means but it allowed me to open my save file everything seemed normal until i tried to make a pokemon for some reason it was level 100 by default with pokerus and max friendship plus it had 2 scale shot moves and hidden power as dragon type i also found out that i cannot change date of recieving and hidden power i also tried to edit amount of items in bag but the numbers were jumping to so bug amount than gba can handle and there are no mystery gifts maybe the update was a lie
![16413267151973560241103277500678](https://user-images.githubusercontent.com/72076326/148117245-13349e28-84a0-4816-b172-7553c5b46dfa.jpg)
![16413267288847999903263097458971](https://user-images.githubusercontent.com/72076326/148117290-82659b9b-5318-444f-b9ae-74e7ccc2a433.jpg)

**Comment by GriffinG1** [comment]
> but the numbers were jumping

this is a known bug, see #1268.

> there are no mystery gifts

Wc3 is a fake format, any events are handled via scripts or injecting the Pokémon released manually. See [the wiki](https://github.com/FlagBrew/PKSM/wiki/FAQs#how-do-i-use-generation-3-wondercards).

with regards to your input issues, I suggest providing more info; afaik no issues like that have been reported, and you're also missing a bit in general (ruby, and any other gba games, will not show up on their own. You *must* input them manually)

**Comment by pokemonfan6498** [comment]
> > but the numbers were jumping
> 
> this is a known bug, see #1268.
> 
> > there are no mystery gifts
> 
> Wc3 is a fake format, any events are handled via scripts or injecting the Pokémon released manually. See [the wiki](https://github.com/FlagBrew/PKSM/wiki/FAQs#how-do-i-use-generation-3-wondercards).
> 
> with regards to your input issues, I suggest providing more info; afaik no issues like that have been reported, and you're also missing a bit in general (ruby, and any other gba games, will not show up on their own. You _must_ input them manually)
> 
> In addition, please provide your luma version, the full version string PKSM shows in app, and your system version.

**Comment by pokemonfan6498** [comment]
And scripts are only needed if you wanna to inject event pokemon

**Comment by pokemonfan6498** [comment]
As for luma im using latest version of luma3DS

**Comment by SpiredMoth** [comment]
For the unexpected values of that generated Bulbasaur, that's down to the contents of your Generation 3 default. As explained in [this wiki section](https://github.com/FlagBrew/PKSM/wiki/Settings#tab-2-defaults), PKSM uses those defaults as the starting point for generating *any* Pokémon of the corresponding generation. If you want something different than those defaults your options are to either edit the default template or edit the Pokémon after you generate it.
