### ISSUE TITLE
DS cartidges? 

### ISSUE THREAD

**Issue by Nsolos** [FlagBrew/PKSM#1311]
My Platinum cartidge isnt recognized by the app

**Comment by GriffinG1** [comment]
Can you try making a backup of it in Checkpoint and upload that save here please

**Comment by Nsolos** [comment]
I made a backup but i just realized that this isnt the only problem. I cant go to the SD card storage on absent games.

**Comment by GriffinG1** [comment]
Closed due to inactivity (save never shared)
