### ISSUE TITLE
Question about Save Injection

### ISSUE THREAD

**Issue by mdluffy1234** [FlagBrew/PKSM#1312]
Using Black 1 as an example, can you get a save file from a playthrough of that game that was played on a ROM and put it on a physical copy of Black 1?

I'm sorry for asking this in the issues tab,  but I have to ask it here because I can't join the Discord fsr...

**Comment by GriffinG1** [comment]
Use [Checkpoint ](https://github.com/FlagBrew/Checkpoint/releases) to manage your saves.
