### ISSUE TITLE
Optimization for Opening Camera

### ISSUE THREAD

**Issue by LegoEngineer003** [FlagBrew/PKSM#1313]
An issue I’m having with opening the camera is that you need to basically perfectly time both presses, otherwise you end up moving one box over to the right or left of where you want to put the Pokémon. This isn’t too bad if you have empty spaces in the right and left boxes at the same position, but if the boxes on either side aren’t empty, you can accidentally override the Pokémon there. Is it possible to find a way to account for a small delay between pressing L+R to avoid changing boxes when opening the camera?

**Comment by LegoEngineer003** [comment]
I’d like to add that I’m aware of pressing the icon on the bottom screen to open the camera, but my touch screen is often unresponsive

**Comment by piepie62** [comment]
Just added a 10-frame grace period, which is 1/3 of a second. Seems pretty good to me.

**Comment by GriffinG1** [comment]
Fixed in [v10](https://github.com/FlagBrew/PKSM/releases/latest).
