### ISSUE TITLE
crash on script 3rd gen

### ISSUE THREAD

**Issue by breakgon** [FlagBrew/PKSM#1314]
**Describe the bug**
PKSM freezes when trying to load scripts (Pokemon Emerald USA VC inject)

**To Reproduce**
1. Open PKSM
2. Choose VC Pokemon emerald to edit
3. Go to "Scripts" 

**Expected behavior**
See the scripts and universal scripts for that save.

**Screenshots**

![WhatsApp Image 2022-03-09 at 7 20 57 PM](https://user-images.githubusercontent.com/101295218/157555713-bcf7ab29-a4cb-4cdf-b238-e4cfd7c29b64.jpeg)

**Information about your environment**
 - OS version: 11.15.0
 - PKSM version: 9.2.0
 - Entrypoint: HBL

**Additional context**
The program seems to run fine on other saves like heartgold, not tested on R S nor FrLg.

**Crash Dump**

[crash_dump_00000003.zip](https://github.com/FlagBrew/PKSM/files/8218912/crash_dump_00000003.zip)

**Comment by GriffinG1** [comment]
Could not be reproduced by @piepie62, as such closing. I recommend testing on another console. If it continues to crash, please join the [Discord server](https://discord.gg/bGKEyfY) so we can look into the issue further.
