### ISSUE TITLE
Modify the game's dex according to the pokemons you possess on the game's boxes

### ISSUE THREAD

**Issue by Alalramrod** [FlagBrew/PKSM#1315]
Hi there! Kinda of new in this so my apologies if what I am asking has been already done/discussed. It didn't come across in any of my searches.

I'm playing ORAS, and I applied the "complete owned national pokedex" script, so my pokedex now counts with 706. I was wondering if there is another script that allows you to "undo" this script, or alternatively any way to manually modify your pokedex (both seen/owned).
If there is none, I assume that the easiest would be a script that reads the game's boxes and checks which pokemons are inside, then overwriting the full pokedex with a reduced selection of pokemon.

Thank you a lot in advance, and once again my apologies if this has been already discussed/this is not the proper way to ask for it.

Cheers!

**Comment by GriffinG1** [comment]
If you want to undo the script, load a backup prior to when you used the script. PKSM makes auto backups by default, which are stored at `~/3ds/PKSM/backups/`.

**Comment by Alalramrod** [comment]
Thanks a lot for your quick response, and my apologies then, I will try to move the post there. 

Well,the thing is I did apply the fill dex script in order to achieve the shiny charm. However, if I would load a backup I would of course lose it together with any progress I might have done ever since. I just couldn't find a better way to get the shinny charm than by filling the pokedex, but still, I would like to have the chance of keep adding entries to the dex.

**Comment by GriffinG1** [comment]
Just... leave the full dex? The only thing it'll affect is not showing the dex entry on catch.
