### ISSUE TITLE
Feature Request: Level in hex editor and level 999 pokemon + mega evolve

### ISSUE THREAD

**Issue by Saturn345** [FlagBrew/PKSM#1319]
**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
The level of the Pokemon in the hex editor
**Describe alternatives you've considered**
I dont really have any alternatives
**Additional context**
Oh, and I love making glitched Pokemon and i want to make a level 999 pokemon and mega evolution if its possible

**Comment by GriffinG1** [comment]
Refer to [the wiki[(https://github.com/FlagBrew/PKSM/wiki/Hex-Editor) for how to adjust your pokemon's level using the hex editor. We will not support making excessively glitched pokemon.
