### ISSUE TITLE
PKSM 9.2.0 doesn't support nds save files such as .sav or .dsv pls fix

### ISSUE THREAD

**Issue by Ppapapati** [FlagBrew/PKSM#1320]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Information about your environment**
 - OS version:
 - PKSM version:
 - Entrypoint:

**Additional context**

**Comment by SpiredMoth** [comment]
PKSM does support `.sav` save files (see [this wiki section](https://github.com/FlagBrew/PKSM/wiki/Settings#extra-saves))

`.dsv` saves are not supported, but can be converted to `.sav` (see [this FAQ entry](https://github.com/FlagBrew/PKSM/wiki/FAQs#im-attempting-to-use-a-save-that-was-used-in-an-emulator-at-some-point-and-it-wont-load-what-do-i-do))
