### ISSUE TITLE
Bug Report - Random values in bag FR/LG

### ISSUE THREAD

**Issue by GitHubeMail1ASIR** [FlagBrew/PKSM#1322]
**Describe the bug**
When trying to edit the quantity of any item in the bag in my Fire Red spanish save it just jumps to (what it looks like) a random number.
Doesnt matter if i do it with the + and - buttons or setting a number.

**To Reproduce**
1. Open PKSM in a 3DS
2. Press Y to go to absent games saves
3. Select FR/LG
4. Choose your save
5. Go to Bag -> Try to edit any item quantity or add a new item and set a quantity.

**Expected behavior**
I was expecting to get a normal number, not a random one.

**Screenshots**
![2022-06-09_14-58-07 193_bot](https://user-images.githubusercontent.com/98745368/172853195-175ea932-137b-4b08-ba5f-cd93159e73fc.png)
![2022-06-09_14-58-07 194_bot](https://user-images.githubusercontent.com/98745368/172853215-94df3e6c-d337-439e-b181-ce51b5c6a41f.png)

**Information about your environment**
 - OS version: 11.15.0-47E
 - PKSM version: 9.2.0
 - Entrypoint: I dont know what this refers to, can add if needed and someone explains it

Thanks a lot in advance!

**Comment by GriffinG1** [comment]
#1227 duplicate.


For future reference, entrypoint refers to how you open PKSM; CIA or 3dsx.
