### ISSUE TITLE
.jar version wont send .pk6 files to 3ds 

### ISSUE THREAD

**Issue by snappyv** [FlagBrew/PKSM#1323]
I've been trying to send .pk6 files to my 3ds PKSM and when executing a transfer via the .jar gui version I am greeted by a message that shows no files being sent and pksm on my 3ds receives nothing. Unsure if bug or user error, but cannot get this working.

**Comment by GriffinG1** [comment]
I assume you're referring to ServePKX. It has been deprecated for at least 4 years now. You can currently use one of these options:
![94569B8B-6CF9-4740-9D7E-A7375BB26FF3](https://user-images.githubusercontent.com/28538707/174272148-e19d474a-2d60-41d2-93ef-4001dc0e9725.jpeg)

**Comment by snappyv** [comment]
thanks! really appreciate the help
