### ISSUE TITLE
Add .dsv support please Feature Request

### ISSUE THREAD

**Issue by Ppapapati** [FlagBrew/PKSM#1325]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by GriffinG1** [comment]
@piepie62 has *specifically* chosen not to support emulator-exclusive formats such as DSV. Please research how to convert DSV to SAV and remove the 200 byte footer that gets appended at the end instead.
