### ISSUE TITLE
Doesn't recognize OR save

### ISSUE THREAD

**Issue by TheChromeGamer** [FlagBrew/PKSM#1329]
Whenever I load PKSM in Citra MMJ it recognizes my Ultra Moon save but not my Omega Ruby save. I have the pokedex and dexnav in the game but it still doesn't show up.

**Comment by GriffinG1** [comment]
If you were able to build PKSM with the specific flags to support Citra, you're expected to be able to debug any issues you run into there as well.

We won't provide support with it, which is why we don't offer Citra-supported builds.
