### ISSUE TITLE
Bug Report - Build fails due to compiler error

### ISSUE THREAD

**Issue by Octoham** [FlagBrew/PKSM#1330]
**Describe the bug**
Build fails on Debian WSL due to compiler error

**To Reproduce**
Get Debian on WSL
Get all _latest_ dependencies
Clone repository
Run `make` in the repository

**Expected behavior**
The build should succeed

**Screenshots**
![image](https://user-images.githubusercontent.com/46746534/177423833-1d078c39-9e94-4f72-ba47-0de4dbc5b662.png)

**Information about your environment**
 - OS version: Debian in WSL1 in Windows 11
 - PKSM version: [master](https://github.com/FlagBrew/PKSM/commit/5fc2384d0b65e5e8eb9bc932c21801b81ca597a8)
 - Entrypoint: does it matter?

**Additional context**
Does the same in the docker devkitARM container

**Comment by Octoham** [comment]
oh, and please fix this, it shouldn't be too hard
![image](https://user-images.githubusercontent.com/46746534/177424706-22c05a4c-2485-47a3-8a07-4bd986610348.png)

**Comment by Octoham** [comment]
New error now
![image](https://user-images.githubusercontent.com/46746534/177424881-523f69b3-9b11-46d7-8403-9d7c557ec023.png)
and std::pair really seems incomplete btw

**Comment by GriffinG1** [comment]
Looking at your account, it seems you have forked from @SNBeast's fork. Are these compilation issues coming while attempting to compile that fork? If so, any issues should be directed to his issue tracker.

**Comment by Octoham** [comment]
![image](https://user-images.githubusercontent.com/46746534/177425484-a0371ac3-972a-493b-ad13-973d9c179b7b.png)
![image](https://user-images.githubusercontent.com/46746534/177425562-f7ba71eb-601f-42ba-845e-d02fd80d4856.png)
![image](https://user-images.githubusercontent.com/46746534/177425634-497ced93-9a95-4dc2-8e20-566304585a07.png)
![image](https://user-images.githubusercontent.com/46746534/177425691-8a7eb778-e499-4fd1-8350-eb6a15bd9d4d.png)
and there's more

**Comment by Octoham** [comment]
> Looking at your account, it seems you have forked from @SNBeast's fork. Are these compilation issues coming while attempting to compile that fork? If so, any issues should be directed to his issue tracker.

well the first one is coming from his fork, my mistake
but all the others are from this repository

**Comment by SNBeast** [comment]
I already addressed the `-DARM11` and `-D_3DS` stuff. As for the top one, that's the compiler shifting under us in a way that we now need to explicitly include `<array>`.

**Comment by GriffinG1** [comment]
"From this repository" meaning you then git cloned the master branch of this repo, and the issues are occurring? And you are 100% sure that you have all the properly versioned dependencies? Looking at some of those errors, some are erroring in files that haven't been changed since a month after 9.2.0 released... and our private automated system is able to compile 5fc2384d0b65e5e8eb9bc932c21801b81ca597a8 fine.

**Comment by Octoham** [comment]
> "From this repository" meaning you then git cloned the master branch of this repo, and the issues are occurring? And you are 100% sure that you have all the properly versioned dependencies? Looking at some of those errors, some are erroring in files that haven't been changed since a month after 9.2.0 released... and our private automated system is able to compile [5fc2384](https://github.com/FlagBrew/PKSM/commit/5fc2384d0b65e5e8eb9bc932c21801b81ca597a8) fine.
> 
> This definitely feels like an issue with either your environment, or SN's fork.

```
git clone --recursive https://github.com/FlagBrew/PKSM.git
git submodule init
```
and i have a feeling it's with the versions of the devkitarm module

**Comment by SNBeast** [comment]
My branch built fine a month ago and now doesn't without intermediate change, it's definitely compiler changing.

**Comment by piepie62** [comment]
Griffin is incorrect here, it is the compiler upgrade. Looks to me like nlohmann will need to be updated, am currently communicating with Octoham to make a PR

**Comment by Octoham** [comment]
welp, after the recent pushes, i can now compile. this has been solved
