### ISSUE TITLE
Wont open using CIA And Wont download using remote install

### ISSUE THREAD

**Issue by B4D1NC** [FlagBrew/PKSM#1332]
I've tried to download it via QR code but it say result code 0xD8A0A046

When i try to download using Cia it wont open

**Comment by GriffinG1** [comment]
The former is due to an outdated FBI install, and out of the scope of this issue tracker.

For manual install issues, make sure you are getting the latest release from our releases page. If you are and still having this issue, please be more specific than "it won't open".

**Comment by B4D1NC** [comment]
> The former is due to an outdated FBI install, and out of the scope of this issue tracker.
> 
> 
> 
> For manual install issues, make sure you are getting the latest release from our releases page. If you are and still having this issue, please be more specific than "it won't open".

What I meant by it won't open it goes to black screen with the error 0xFFFFFFFFFF

**Comment by GriffinG1** [comment]
It tells you more than an error message. Give the full contents of the error.

**Comment by B4D1NC** [comment]
> It tells you more than an error code. Give the full contents of the error.

Additional assets download failed. 

Always make sure you're connected to the internet and on the lastest version

**Comment by GriffinG1** [comment]
Refer to [this page](https://github.com/FlagBrew/PKSM/wiki/Basics#additional-assets) on the wiki if you have a stable internet connection and still fail to download the assets.
