### ISSUE TITLE
Bug Report - PKSM doesn't detect Heart Gold in slot

### ISSUE THREAD

**Issue by BLameLance** [FlagBrew/PKSM#1334]
**Describe the bug**
When in PKSM, the "Game Card" section remains empty despite a copy of Heart Gold being there, and the 3DS itself recognizing that it is there and playable.

**To Reproduce**
1. Go to 'PKSM'
2. Click on 'Y' for absent game
3. Scroll down to "HT SS' and select the saved file on CheckPoint
4. See error 'Checkpoint/saves/IPKE POKEMON HG/Back 1/POKEMON is not valid save file'

**Expected behavior**
Heart Gold is selectable and its save editable.

**Information about your environment**
 - OS version: 11.15.0-47U
 - PKSM version: 9.2.0-656eb68a

**Additional context**
I bought this online and saw a [similar issue](https://github.com/FlagBrew/PKSM/issues/1275) and wondering if maybe my version is a fake also, but don't know how to check.

**Comment by GriffinG1** [comment]
You can check your save in HxD as pie did in that issue, and/or ask in [r/gameverifying](https://www.reddit.com/r/gameverifying/), but it likely is fake so I will be closing this. If you can prove it isn't fake, then I will reopen it.
