### ISSUE TITLE
Bug edit save pokemon cristal ESP.

### ISSUE THREAD

**Issue by raul-792** [FlagBrew/PKSM#1335]
Hello,
When I enter PKSM and select pokemon emerald version ES it doesn't let me load the sav.

PKSM>Emerald VC> sav
error :Not a valid save file
0xFFFFFFFF

The game ID is fine, checked with FBI and modified in PKSM.
I have read that pressing R and B sometimes solves it but I get another error with a black screen.

**Screenshots**
If applicable, please add screenshots to help explain your problem.

**Information about your environment**
   - OS version: 11.15.0-47E
   - PKSM version: PKSM 9.2.0
   - Entry point:

**Comment by raul-792** [comment]
![IMG_4119](https://user-images.githubusercontent.com/111419858/185073892-64c977c1-174d-44b7-adad-52940da12e92.JPG)
![IMG_4120](https://user-images.githubusercontent.com/111419858/185073915-293e926f-4f01-40e1-9633-24a2bc8e31f6.JPG)
Do I have to load a special save, if so, how or where to find it?

**Comment by GriffinG1** [comment]
As instructed in the [GBA Injection](https://github.com/FlagBrew/PKSM/wiki/GBA-Injection) part of the wiki, when you injected your own dumped copy of Emerald into a CIA did you make sure to select a 1024kbit save type? If not, then PKSM will not work with it.

**Comment by raul-792** [comment]
Could you pass me the link to verify this, I'm new to pksm.
I have the game in .cia I don't use TW. How to modify the game so that PKSM can read it correctly?
And some doubts, the events that appear in each game are the events that can be loaded in it?
Can I change the money?
I'm sorry for these newbie doubts but I did the games and the pksm over the weekend and I'm lost, I'm years behind I think.

**Comment by GriffinG1** [comment]
> Could you pass me the link to verify this, I'm new to pksm.

You can follow [these steps](https://3ds.hacks.guide/dumping-titles-and-game-cartridges#backup-gba-vc-saves) to back up your GBA save via GodMode9 and check the save size that way. There is no way to check it via PKSM.

> I have the game in .cia I don't use TW. How to modify the game so that PKSM can read it correctly?

What is "TW"? And yes, you had to inject the game to a CIA in order to be able to run it on 3ds and have PKSM read it via the VC page. If your save *is* malsized, then the only option is for you to reinject your original dumped copy, using the proper save type.

> And some doubts, the events that appear in each game are the events that can be loaded in it?
> Can I change the money?

Please read [the wiki](https://github.com/FlagBrew/PKSM/wiki) for basic use questions such as these.

**Comment by raul-792** [comment]
I did not create the .cia directly from the internet. I'll try gm9 to create the copy of sav and verify that. Thanks now I'll get to the wiki.

**Comment by GriffinG1** [comment]
> I did not create the .cia directly from the internet.

This sounds like you are saying you downloaded your injected copy from the internet. Piracy is not supported here. Buy your games and dump them yourself.
