### ISSUE TITLE
Trying to restore pksm backup

### ISSUE THREAD

**Issue by RogueEX** [FlagBrew/PKSM#1336]
I want to restore my old backup for PKSM to get my unmodded save file back for pokemon ultra sun but i can't restore it onto PKSM
[backups.zip](https://github.com/FlagBrew/PKSM/files/9397972/backups.zip)

**Comment by GriffinG1** [comment]
If it's a cartridge, enable "Show Backups" and "Enable Backup Injection" in PKSM's settings, open the oldest backup, make any tiny change, and save your changes. This will inject the old save into your cart.

If it's an installed copy, move your oldest save to `~/3ds/Checkpoint/saves/0x01B50 Pokemon Ultra Sun/ultra_sun_save/main` and restore using [Checkpoint](https://github.com/FlagBrew/Checkpoint/releases/v3.7.4).
