### ISSUE TITLE
Feature Request - OD batch renamer

### ISSUE THREAD

**Issue by Kyoshi0306** [FlagBrew/PKSM#1337]
It would be cool to have a batch renamer for the OD, because when generating a legal dex, having PokeHex as OD makes it obvious that the pokemon is from doubtful source. 

I could have renamed them one by one but it's a lot of work because I have 721 pokemon to rename by hand.

**Comment by GriffinG1** [comment]
This already exists via the Universal batch editor script. Further, you can set default info per generation to use. Refer to [this wiki page](https://github.com/FlagBrew/PKSM/wiki/Settings#tab-2-defaults) for further info.
