### ISSUE TITLE
Feature Request - Translation of names 

### ISSUE THREAD

**Issue by Kyoshi0306** [FlagBrew/PKSM#1338]
It would be cool to have a translator to translate the names of the Pokemon in the language we speak because it's kinda boring to translate their name using pokepedia one by one. Or just ask for the language we want to generate to Pokemons.

**Comment by GriffinG1** [comment]
> Or just ask for the language we want to generate to Pokemons
As I said in #1337, this is easily solved by setting default information. Please read the [entire wiki](https://github.com/FlagBrew/PKSM/wiki) and look through [all the available scripts](https://github.com/FlagBrew/PKSM-Scripts/tree/master/src) before opening up any more issues. Thanks.
