### ISSUE TITLE
Bug Report - Brief Description/Name of issue

### ISSUE THREAD

**Issue by Pomaster2** [FlagBrew/PKSM#1342]
![07236A78-D136-499B-B997-8361532859BC](https://user-images.githubusercontent.com/113395296/189772392-c3f6a1e6-845d-4afa-99ab-5bb7b8e94942.jpeg)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Information about your environment**I downloaded pksm in April 2021 when I modded my 2ds for the first time I’m very new and don’t know what this is or hot to fix it 
 - OS version:
 - PKSM version:
 - Entrypoint:

**Additional context**

**Comment by GriffinG1** [comment]
Closing as invalid. Please properly fill out the template if you would like help.
