### ISSUE TITLE
Why aren't the GPSS/Auto Legality features working?

### ISSUE THREAD

**Issue by DruidKnoT** [FlagBrew/PKSM#1349]
On my 3ds i've been using PKSM alot of time, since this morning GPSS, It is failing, sending an offline error, my wifi is working correctly, I play online with my friends and I dont have problems

I Hope some one can help me

**Comment by GriffinG1** [comment]
![image](https://user-images.githubusercontent.com/28538707/205758743-dea924f7-c0ac-42c9-bfc0-20554c744a4f.png)
From #announcements on our Discord server. Pinning this issue for others asking.

**Comment by FM1337** [comment]
GPSS and Auto Legality systems now back online.
