### ISSUE TITLE
Bug Report - Shiny Pokemon Sprite NOT shiny

### ISSUE THREAD

**Issue by echo-renza** [FlagBrew/PKSM#1350]
**Describe the bug**
Frillish in Pokemon White isn’t shiny even though toggle is on.

**To Reproduce**
1. Opened Editor for White
2. Genned shiny Frillish
3. Sprite wasn’t shiny in game, though the sparkles happen upon entering battle and red star is on summary card
I also untoggled and retoggled and same result

**Expected behavior**
Expected a shiny sprite

**Screenshots**

https://imgur.com/a/fs0HpW2

**Information about your environment**
 - OS version: I’m not sure, Lumos11.0?
 - PKSM version: Not sure where to find that but my ‘Always update to newest version’ is on
 - Entrypoint: huh?

**Additional context**
Haven’t had problems with any others so far, was just excited about that one

**Comment by GriffinG1** [comment]
Assuming female frillish, issue is that the shiny is barely different. Yell at gamefreak for bad shiny design, not a pksm bug (nor one that could be caused by pksm, if it's giving the sparkles, as changing the shiny sprite would require a rom edit)

**Comment by FM1337** [comment]
Re-opening this, as I encountered this bug as well, albeit it happens with every Pokemon on the latest build.
