### ISSUE TITLE
Put a nds save file in PKSM and it does this

### ISSUE THREAD

**Issue by PipTheOtaku** [FlagBrew/PKSM#1351]
**Describe the bug**
I cant go inside this Pokemon Diamond save file and I tried different roms but it still doesn't work

**To Reproduce**
Idk if it does that with every save but I will tell you what I did
1. Go in my NDS and choose the .sav file
2. Click on "Y" to see the menu of games
3. Choose my version
4. Choose my save 

**Expected behavior**
I wanted the save to open so I could see if it worked 

**Screenshots**
![20221208_120747](https://user-images.githubusercontent.com/117696284/206511946-8721827a-2b90-42f1-a43b-3b77887c27c3.jpg)

**Information about your environment**
 - PKSM version: Latest version

**Comment by SpiredMoth** [comment]
Sounds like the save came from an emulator like DeSmuME. which outputs a slightly modified save file. Read [this FAQ](https://github.com/FlagBrew/PKSM/wiki/FAQs#im-attempting-to-use-a-save-that-was-used-in-an-emulator-at-some-point-and-it-wont-load-what-do-i-do) from our wiki for how to fix your save file.

**Comment by PipTheOtaku** [comment]
> Sounds like the save came from an emulator like DeSmuME. which outputs a slightly modified save file. Read [this FAQ](https://github.com/FlagBrew/PKSM/wiki/FAQs#im-attempting-to-use-a-save-that-was-used-in-an-emulator-at-some-point-and-it-wont-load-what-do-i-do) from our wiki for how to fix your save file.

I dont use an emulator I use nds-bootstrap and forwarder but im gonna go see the link

**Comment by PipTheOtaku** [comment]
> Sounds like the save came from an emulator like DeSmuME. which outputs a slightly modified save file. Read [this FAQ](https://github.com/FlagBrew/PKSM/wiki/FAQs#im-attempting-to-use-a-save-that-was-used-in-an-emulator-at-some-point-and-it-wont-load-what-do-i-do) from our wiki for how to fix your save file.

Nvm I used another rom and it works now but still thanks im gonna use it if i need it!
