### ISSUE TITLE
Bug Report - Legal Living Dex Not Working

### ISSUE THREAD

**Issue by MerlinCodez** [FlagBrew/PKSM#1353]
The problem im having is that when trying to download the Legal Living Dex the app comes up saying Problem downloading dex: -128.
 
I'm trying to download the dex onto a copy of ultra sun.

**Comment by GriffinG1** [comment]
You need to grab the latest version of the legal living dex script from the [PKSM-Scripts](https://github.com/FlagBrew/PKSM-Scripts/blob/master/src/universal/legal-living-dex.c) repo and put it at `~/3ds/PKSM/scripts/universal/legal-living-dex.c`. Then run it as an external script (press X).

Alternatively, wait for the next stable release (no there is no ETA). It will be packaged with that release.

**Comment by GriffinG1** [comment]
Fixed in [v10](https://github.com/FlagBrew/PKSM/releases/latest).
