### ISSUE TITLE
Bug Report - Wondercard inject menu crashes after updating database

### ISSUE THREAD

**Issue by SuperPlushLord-Github** [FlagBrew/PKSM#1354]
**Describe the bug**
A clear and concise description of what the bug is. After the gift database updated, opening the menu produced the attached error message

**To Reproduce**
1. Insert an Ultra Sun game card and open the saved data
2. Open the Events database
3. See error

**Expected behavior**
It opens the ultra sun gift database

**Screenshots**
![image](https://user-images.githubusercontent.com/106224573/209064920-4ba1512e-c340-4a9e-9e1b-3ce508238bca.jpg)
![image](https://user-images.githubusercontent.com/106224573/209064935-458280a1-efcc-4985-8ea0-b71110314444.jpg)

**Information about your environment**
 - OS version: 11.15.0-47U
 - PKSM version: v9.2.0-656eb68a
 - Entrypoint: What does this mean?

**Additional context**

**Comment by GriffinG1** [comment]
#1352 duplicate.
