### ISSUE TITLE
Gen 3 Saves Not Showing Up, Followed GBA Injection

### ISSUE THREAD

**Issue by Volt790** [FlagBrew/PKSM#1355]
As stated in the title, I followed the GBA Injection tutorial to make sure I was putting them in correctly, making sure they had the correct ROM Save Type (I used Sanyo for all 5, with RSE having the "+MTC" option as stated) & also changed the Title IDs in PKSM to what was displayed in NSUI. I get my first Pokemon, I get the Pokedex, I save and quit to PKSM, &... nothing shows up.

I'm really unsure what steps I'm missing unless I'm supposed to use the Title ID Provided in the guide (The one ending in 6A949) for all of them & NOT the ones generated by NSUI which would be confusing since it says "Make note of the Title ID (yours will be different) of the generated CIA as you will need it later to configure your GBA title in PKSM" & the one it generates IS the one I'm putting in.

 - OS version: LumaV11.0, N3DS 11.16
 - PKSM version: 9.2.0
 - Entrypoint: GBA Virtual Console Inject.

(I have provided photos below just for additional context)
![Emerald_NoSave](https://user-images.githubusercontent.com/58134893/209898699-03e0f452-3e41-4dde-9274-be122384a734.jpg)
![Emerald_NSUI](https://user-images.githubusercontent.com/58134893/209898701-c0057fc1-cd55-48d4-8c6c-82903903eede.jpg)
![Emerald_TitleID](https://user-images.githubusercontent.com/58134893/209898702-90cea8c9-812b-4bb2-b82a-384583dfe7d4.jpg)
![FireRed_NoSave](https://user-images.githubusercontent.com/58134893/209898703-f62995a0-52a2-41c8-9d9f-4d213fff8786.jpg)
![FireRed_NSUI](https://user-images.githubusercontent.com/58134893/209898706-923d3959-57c9-441e-ad1f-600c32682223.jpg)
![FireRed_TitleID](https://user-images.githubusercontent.com/58134893/209898707-c28d3a34-aa05-4909-bad1-cf8be1e9c8d1.jpg)

**Comment by piepie62** [comment]
That is the extra saves menu. Game saves never show up there. You instead want the GBA tab of the title load menu, the first one that comes up when you load the program.

**Comment by Volt790** [comment]
... I apologize for missing that, I ended up completely glossing over that & using only the extra saves menu (which I thought was just a menu that displayed all games) bc it was how I saw to change the Gen 4/5 games that were on my 3DS via CIA-Forwarders and NDS-Bootstrap.
Again, apologies.
