### ISSUE TITLE
Bug Report - Sorry, there appears to be a networking issue! error: 0x0000006A

### ISSUE THREAD

**Issue by crocodama** [FlagBrew/PKSM#1356]
**Describe the bug**
every time i open pksm it says looking for updates, but suddenly yesterday it started saying this error right after

**To Reproduce**
1. open pksm
2. See error after "checking for update"

**Expected behavior**
the app to work like before, with no issues

**Information about your environment**
 - OS version: Sys 11.16.0-49E
 - PKSM version:9.2.0
 - Entrypoint: I have no idea what that is

**Comment by piepie62** [comment]
This is "CURLE_COULDNT_RESOLVE_HOST", which is not generally a problem with a program itself. You likely have improper DNS settings or aren't connected to a network.
