### ISSUE TITLE
Potential Idea for the future: Custom Offsets Support

### ISSUE THREAD

**Issue by FM1337** [FlagBrew/PKSM#1357]
**Is your feature request related to a problem? Please describe.**
No, not really.

**Describe the solution you'd like**
A system that allows the overriding of data structures based on an imported custom structured file, that would contain offsets of certain aspects such as save files, pokemon data, etc. 

This would allow someone with a ROM hack (such as Crystal Clear) to open their save file (note this already works), make changes and then save it (this works, but it doesn't, I believe the checksum is to blame or perhaps it miswrote some data because of a bit of save file structure differences, either way it just loads the save file without any of the changes made to it).

Not sure what the file structure would look like, could just a JSON file, where the developer (ROM hack developer or community member wanting support) would define offsets related to certain aspects such save bytes and pokemon data.

**Describe alternatives you've considered**
Creating a custom build, but that'd be a pain to do for each time you wanted to try another ROM hack.

**Additional context**
Extremely low priority, hell I'm not even sure if it's doable, but I know there has been people asking for ROM hack support in the past, and this would potentially allow it.

**Comment by SNBeast** [comment]
Detecting ROM hacks in a way that they could be resolved to a configuration would be difficult. It would require either frontend work to add a ROM hack save list, or it would require ROM hack devs to have a unique magic value or string at a standardized location in the save data.

**Comment by piepie62** [comment]
Agreed there; not only that but it also assumes that romhack data is just offset from where it normally is, which seems unlikely in the general case. Seems very complicated for something that would only be useful in a small amount of cases, and not something I think I'd ever consider given the complexities

**Comment by piepie62** [comment]
Ah, wait, I realized that you meant a JSON to completely define the structure. That's slightly more doable but still not something I think I'd want to support
