### ISSUE TITLE
Bug Report - Unknown HTTP Error

### ISSUE THREAD

**Issue by SashkDeZot** [FlagBrew/PKSM#1358]
**HTTP response Error: 0x000001F7**
Tried to legalize pokemon and got: "Got an unknown HTTP response Error: 0x000001F7

**To Reproduce**
1. Go to PKSM
2. Click on Pokemon wanted to legalize
3. See error

**Expected behavior**
That my Golem would've gotten legalized like all the others.

**Screenshots**
No screenshots.

**Information about your environment**
 - OS version: 3DS
 - PKSM version: V9.2.0

**Additional context**
Is there an update going on or something?

**Comment by FM1337** [comment]
Server was down for maintenance.
