### ISSUE TITLE
My old storage crashing the app due to the limit of bank size

### ISSUE THREAD

**Issue by DankCoffee** [FlagBrew/PKSM#1359]
Bug Description
When I open PKSM it says loading storage then it returns me to the home menu
To Reproduce
Latest version of pksm on my updated save
open pksm
its gonna crash when it says "Loading Storage"
Expected behavior
To backup my save data then update and launch normally

Information about your environment

OS version: [{CFW} 11.15.0-47 (Europe)]
PKSM version: 9.2.0

**Comment by GriffinG1** [comment]
Do you have anything in your bank?

**Comment by DankCoffee** [comment]
yes i do

**Comment by GriffinG1** [comment]
Please refer to my edit. This is a duplicate of your other issue, #1317. Wait until pie is available to help.

**Comment by DankCoffee** [comment]
how do i contact piepie62 to fix it?

**Comment by DankCoffee** [comment]
> Please refer to my edit. This is a duplicate of your other issue, #1317. Wait until pie is available to help.

ok

**Comment by DankCoffee** [comment]
one last thing, do I send the bank now for piepie62 to fix it later?

**Comment by GriffinG1** [comment]
Either go back to that issue or join the [Discord](https://discord.gg/bGKEyfY). I'm locking this.
