### ISSUE TITLE
Bug Report - pokecenter wont work

### ISSUE THREAD

**Issue by Murray097** [FlagBrew/PKSM#1361]
Ever since i used the all items script it jow freezes at the pokecenter when i go to heal my pokemon in ORAS,please get back to me when possible

**Comment by Murray097** [comment]
Now it freezes after u beat steven come on guys.

**Comment by GriffinG1** [comment]
This definitely does not sound like a bug that PKSM could be causing.

**Comment by Murray097** [comment]
It must be because it worked then all of a sudden it stopped working as
soon as i use pksm
.as soon as i put on scripts everything broke like
The pokecenters

**Comment by Murray097** [comment]
Great shut down my comment even tho you know it’s because of the pksm
