### ISSUE TITLE
Bug Report(?) - Brief Description/Name of issue

### ISSUE THREAD

**Issue by pechasketch** [FlagBrew/PKSM#1364]
**Describe the bug**
I'm not sure if this is a bug or if I'm missing a step, but I can't seem to receive any of the event Pokemon I've attempted to inject into my Pokemon Platinum save file, nor can I find any answers yet online. If someone could walk me through it (i'm very new to this, you may have to explain it like I'm stupid lol)

**To Reproduce**
1. Open PKSM
2. Navigate to + select Platinum save. (right now it says on the top screen that I have 3 Wonder Cards, as I've tried to inject 3 event pokemon)
3. Click "Events"
4. Select an English language event pokemon, one that says it's compatible with Platinum.
5. Inject to desired slot and press A to confirm.
6. Press START to inject. The program immediately backs out of the menu back to the Event Database with no indication of a confirmation, but when I check the wondercards I have through the program, the Pokemon do appear to be there.
7. Press B to return to the menu for my save file and press the save/download(?)  button in the bottom corner.
8. Exit the app and boot up Pokemon Platinum. 
9. Check Mystery Gift and Pokemon Center

**Expected behavior**
What I thought should happen, based on what I've seen from tutorials, was that if I went to a Pokemon Center, there should be a man to talk to who would give me an event Pokemon. Some other people have said you're meant to go to the mystery gift menu on the initial screen in order to accept the gift? I expected that this would be able to be completed without having to connect to Nintendo WFC.

**Screenshots**

**Information about your environment**
 - OS version: 11.16.0-49U
 - PKSM version: 9.2.0
 - Entrypoint: ?

**Additional context**
When attempting to receive a gift through any of the mystery gift connection options, nothing happens. I get "No access point in range" for the Nintendo WFC option. I've attempted to configure this separately, with the in-game wifi config menu (the whole DNS changing thing), but still I'm not able to establish a connection there in the first place (it doesn't allow for connections to any of the networks around me, despite my 3DS itself being able to connect to the internet just fine). Is this wifi connection required for the event injecting to work in the first place? If so then I guess I'm out of luck, but if someone could explain to me how to accept the event pokemon in-game it would be greatly appreciated :,)

**Comment by SpiredMoth** [comment]
In older games like Platinum the delivery person is in the Mart rather than the Center

**Comment by pechasketch** [comment]
> In older games like Platinum the delivery person is in the Mart rather than the Center

Oh my gosh, I'll have to check that when I get back to my DS later. Thank you! I'll update when I get the chance :)

**Comment by pechasketch** [comment]
Well, I feel a little bit silly, but it worked!! Thank you so much again :)
