### ISSUE TITLE
Not seeing the "scripts" folder in my sd card

### ISSUE THREAD

**Issue by MewIstheBest** [FlagBrew/PKSM#1365]
Im trying to use a legal living dex script on Omega Ruby, and i dont see a scripts folder when going into my PKSM folder inside my 3ds folder
![Screenshot 2023-03-24 23 10 42](https://user-images.githubusercontent.com/115367518/227688871-26ba8836-1b28-43c9-88e2-5aa7476a2343.png)

**Comment by piepie62** [comment]
That's because the folder isn't created by default. Just make it yourself
