### ISSUE TITLE
Bug Report - French Pokémon games not showing in VC Games tab

### ISSUE THREAD

**Issue by Scout-Yoyo** [FlagBrew/PKSM#1367]
**Describe the bug**
French Pokémon Games from Gen 1 and 2 are not showing in PKSM VC Games tab.
I have Pokémon Gold and Silver and their french version Pokémon Or et Argent. Each game have a save file but only Gold and Silver are showing.
As for gen 1, I don't have english version of the game I only have french Pokémon Bleue and it's also missing in the VC Games tab.
I'll try to install Red and Blue to see if they will appear.

**To Reproduce**
1. Open PKSM
2. Open the VC Games tab
3. French Pokémon games are missing

**Information about your environment**
 - OS version: Sys 11.16.0-49E
 - PKSM version: 10.0.0-2b194722
 - Entrypoint: cia

**Comment by FM1337** [comment]
By default, we're only checking for the English versions, however you can change the title ID of the game to other title IDs to support other languages.

See: https://github.com/FlagBrew/PKSM/wiki/Settings#title-ids

You can find title ids using the FBI app
