### ISSUE TITLE
Bug Report - Cannot press start to exit when viewing absent games

### ISSUE THREAD

**Issue by mikecbone** [FlagBrew/PKSM#1368]
**Describe the bug**
Pressing start doesn't exit the application while viewing absent games

**To Reproduce**
Steps to reproduce the behaviour:
1. Press Y to view absent games
2. Pressing start does nothing
3. Press Y again to view present games
4. Pressing start exits as expected again

**Information about your environment**
 - Console: New 2DS XL
 - OS version: 11.16.0-49E
 - Luma3DS: v12.0
 - PKSM version: 10.0.0
 - Entrypoint: CIA

**Comment by piepie62** [comment]
Whoops, that's my bad. Should be fixed in a new version.
