### ISSUE TITLE
Bug Report - Invalid met data when transferring from Gen 1/2 games

### ISSUE THREAD

**Issue by federicodc05** [FlagBrew/PKSM#1372]
When viewing in Gen 7 PKHEX a pokemon transferred from Gen 1/2, it displays its met level to be 0.

I don't know if this conflicts in any way with the legality checker in the offical games though.

**Comment by Korenji** [comment]
It does conflict with the legality checker.
Moreover, the language of every Pokémon transferred from gen 1/2 onward will be marked as English, ignoring the system language. This does not conflict with the legality checker, but it's annoying for non-English players.

**Comment by piepie62** [comment]
Just fixed both of those; the language after transfer will be the language of the save they're being transferred to, and the met level was simply forgotten in G1->7 transfers. G2->7 transfers should have been fine, though, could you please confirm that that is an actual issue?

**Comment by Korenji** [comment]
There's another error regarding gen 1→7 transfers: the OTs of in-game traded Pokémon should also change according to the target language. When I tried to make a transfer earlier, the OT remained "TRAINER" all caps and in English.

**Comment by piepie62** [comment]
Also fixed
