### ISSUE TITLE
Gen 1 and 2 box pokemon dissapearing

### ISSUE THREAD

**Issue by ToxynCorvin** [FlagBrew/PKSM#1374]
**Describe the bug**
Editing and moving gen 1 and 2 box pokemon in pksm causes them to dissapear. It happens on the VC versions.

**To Reproduce**
1. I cloned my starter into the box to modify, won't appear in box, this was on VC Crystal.
2. I was catching pokemon in Yellow, used PKSM to move pokemon to other boxes, the pokemon vanished.

formation about your environment**
 - OS version:
 - PKSM version:
 - Entrypoint:

**Comment by piepie62** [comment]
Known, and investigating

**Comment by SoaringEagle93** [comment]
I just ran into this same issue with Pokemon Crystal, however I didn't have the issue with Pokemon Red. Maybe this isn't happening on all Gen1 and 2 games?

**Comment by piepie62** [comment]
My understanding is that this issue happens when moving a G1 Pokémon to a G2 game, and not vice versa. Does this match what you observe @SoaringEagle93, @ToxynCorvin?

**Comment by SoaringEagle93** [comment]
No, what happens in my case is I put all of my pokemon from my boxes into PKSM storage and then when I try and take them out it saves my storage however it doesn't save the pokemon in my boxes in the game. Therefore my pokemon are then gone. I can replicate it with just a single pokemon or multiple.  Like I said in my first comment, this didn't happen with Red however. I was able to move everything back and forth with zero issues.

**Comment by SoaringEagle93** [comment]
In my case yes that is correct. I have not tried moving anything from G1 to G2 because I was only using PKSM has a temp storage to sort my pokemon, however after work I can try this and get back with you.

**Comment by SoaringEagle93** [comment]
Ok I tested catching a pokemon in Crystal, saved the game, loaded PKSM and cloned a G1 pokemon and replaced the G2 pokemon.  When I saved and booted up Crystal again the G1 pokemon wasn't there and the G2 was still there.

**Comment by metalgutsolid** [comment]
Bump. I just tried moving Pokemon between VC Gold and VC Crystal, when I loaded into Crystal, the pokemon had disappeared and weren't in the box as expected.

**Comment by ToxynCorvin** [comment]
I didn't move pokemon between gens but I did modify evs and ivs to max when the pokemon dissapeared from boxs in yellow and crystal.

**Comment by piepie62** [comment]
Fixed for next bugfix version

**Comment by SoaringEagle93** [comment]
> Fixed for next bugfix version

Any update on when the next bugfix should be released?

**Comment by KingGodDavid** [comment]
So any time frame of when this update will be out? Says fixed on thread discord says its been pushed when clearly it hasnt. So when its ready? Ive been told its ready so where is the update?
