### ISSUE TITLE
Is it possible to generate MissingNo. in any game with PKSM?

### ISSUE THREAD

**Issue by TwystedXYZ** [FlagBrew/PKSM#1375]
I was wondering if it would be possible to use PKSM or its built-in hex editor to generate MissingNo. in any capacity. So far, I have no progress in any of the seven generations. (3DS Version)
Thanks!

**Comment by TwystedXYZ** [comment]
There really isn't any way to catch MissingNo. in Gen II-VII.

**Comment by GriffinG1** [comment]
Won't be implemented.
