### ISSUE TITLE
Feature Request: Extra saves shouldn't be hidden in the x menu

### ISSUE THREAD

**Issue by egscodes** [FlagBrew/PKSM#1378]
Honestly not going to lie i almost made a feature request thinking the app didn't read saves files outside of those in the checkpoint folder. But then just messing around in the settings i found the extra saves which is what i was looking for. 

So i feel that feature should be more visible, if its visible in the bottom screen without having to go tru menus that would be great!

**Comment by piepie62** [comment]
Already planned; working on this right now actually

**Comment by piepie62** [comment]
Annnnd done

**Comment by GriffinG1** [comment]
Has been added with latest releases!
