### ISSUE TITLE
Feature Request: view Party in storage

### ISSUE THREAD

**Issue by egscodes** [FlagBrew/PKSM#1380]
It Seems one can only view party in editor mode? 
I'm guessing the reason its not a thing its because game might crash if no pokemon in party. But a simple solution is to only clone by default in the storage area?

**Comment by piepie62** [comment]
The reason for this is actually very simple: there's no UI space for it. Not going to be changed

**Comment by egscodes** [comment]
honestly thats fair, the only place that could fit and won't look to bad is the start menu or centered on the bottom part of the screen
