### ISSUE TITLE
Bug Report - Y button doing nothing in main menu

### ISSUE THREAD

**Issue by TwystedXYZ** [FlagBrew/PKSM#1381]
**Describe the bug**
Selecting a game, then holding the SELECT button tells you to press Y to save & launch, yet pressing Y (or SELECT+Y) does nothing.

**To Reproduce**
1. Select a game, for this I used Pokemon X, digital copy.
2. Press Y
3. Nothing happens

**Expected behavior**
Should save changes made and launch title.
**Screenshots**

**Information about your environment**
 - OS version: 11.16.0-49U
 - PKSM version: 10.0.0
 - Entrypoint: Home Menu

**Additional context**
Only tried this with 1 game, have yet to try another

**Comment by TwystedXYZ** [comment]
If Entrypoint means the bootloader, then fastboot3ds with luma3ds 12.0-3gxldr

**Comment by TwystedXYZ** [comment]
Update, issue happens for all of them

**Comment by piepie62** [comment]
Yeah that's my bad I forgot to actually include the code to have Y do that. Just use the button in the bottom-left of the touch screen until the next release
