### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ShinyHuntr** [FlagBrew/PKSM#1382]
Add MissingNo. and it's ilk in the gen 1-2 editors

**Comment by piepie62** [comment]
No, this will not happen.

**Comment by ShinyHuntr** [comment]
ok. could i know why for my own sanity?

**Comment by FM1337** [comment]
> ok. could i know why for my own sanity?

Because allowing the user to intentionally corrupt data, could lead to issues which then opens us open to having users complain about bugs as a result of allowing intentional data corruption.

Make no mistake, missingno is data corruption.

**Comment by Masamune3210** [comment]
Not all of it is benign either, I don't think generating a pokemon that causes data loss simply by being displayed is a particularly good idea
