### ISSUE TITLE
Pokemon Icons rotating

### ISSUE THREAD

**Issue by Jack220141** [FlagBrew/PKSM#1383]
**Describe the bug**
Why pokemon icons rotating in the latest version of PKSM?

**Comment by FM1337** [comment]
Can you describe the spin, is it like https://www.youtube.com/shorts/cerkDJLuT_k ?

**Comment by Jack220141** [comment]
Hahaha 
No it is real so all pokemon icon start rotating idk what this is

**Comment by Jack220141** [comment]
https://user-images.githubusercontent.com/129324420/229251232-2cdd49a4-4629-45b9-9129-7469d7eac53c.MOV

**Comment by FM1337** [comment]
Did you try turning your device off and on again?

**Comment by Jack220141** [comment]
Yes i had restart PKSM i had showing in the options and i have restart system

**Comment by TwystedXYZ** [comment]
Can someone show me how to get this to happen or is it just random?

**Comment by TwystedXYZ** [comment]
Never mind. It happened.
