### ISSUE TITLE
Bug Report - Unable to Execute Injector Script

### ISSUE THREAD

**Issue by scarletbxtch** [FlagBrew/PKSM#1384]
**Describe the bug**
Attempting to execute the injector script results in an error. Unable to remedy via re-installing CIA file.

Error reads: 

there");
^
romfs:/scripts/universal/injector.c: 16:0 value not expected here
Exit code: 1

**To Reproduce**
1. Load save file for either 3DS or Virtual Console (this was first attempted for Crystal, then reproduced for Y)
2. Go to universal scripts
3. Execute injector 
4. (Presumably) receive error screen as described above

**Expected behavior**
I expected the script to run, specifically to inject .pk2 files into my Pokemon Crystal save.

**Screenshots**
![2023-04-01_22-37-38 059_top](https://user-images.githubusercontent.com/103149809/229328296-73e34d3e-4828-4853-8e70-8f3980391245.jpg)
![2023-04-01_22-39-22 436_bot](https://user-images.githubusercontent.com/103149809/229328297-766d2095-a8a5-41eb-a63e-c612b3f2ee7d.jpg)

**Information about your environment**
 - OS version: Sys 11.16.0-49U, Luma 3DS v12
 - PKSM version: 10.0.0
 - Entrypoint: via PKSM icon on home screen

**Additional context**
Running PKSM for the first time on a new-to-me 2DS XL. I did not encounter this error on my previous system (also a 2DS XL). Both games are installed on the system.

**Comment by piepie62** [comment]
Known and fixed for the next bugfix

**Comment by TwystedXYZ** [comment]
ETA for next bugfix release? Been having the same VERY annoying issue.

**Comment by GriffinG1** [comment]
When it's ready. You can get the fixed script yourself from the [PKSM-Scripts](https://github.com/FlagBrew/PKSM-Scripts) repo if you're desperate.
