### ISSUE TITLE
Saves from forwarded nds games aren't appearing

### ISSUE THREAD

**Issue by jamzam-nds** [FlagBrew/PKSM#1385]
After hacking my 3DS I used an NDS forwarder to add Pokemon platinum and white to my homescreen, I noticed that PKSM doesn't detect those games at all. is there a way I can manually tell PKSM to look in a specific folder for saves? Or can I manually import save files? This is a separate thought, but I also have crystal on an emulator on my phone and i would love to export that team into my bank.

**Comment by GriffinG1** [comment]
Please [read the wiki](https://github.com/FlagBrew/PKSM/wiki/Settings#extra-saves).
