### ISSUE TITLE
Bug Report - Load-screen hanging with two music files in /3ds/PKSM/songs

### ISSUE THREAD

**Issue by TwystedXYZ** [FlagBrew/PKSM#1386]
**Describe the bug**
After placing two MP3 files, which worked before when using PKSM, in /3ds/PKSM/songs, i noticed that the loadscreen wouldn't disappear, just the PKSM logo bouncing around until I force-shut off the system.

**To Reproduce**
1. Download the two attached 128kbps MP3 files
2. Place them in /3ds/PKSM/songs
3. Open PKSM

**Expected behavior**
I expected it to load one of them.

**Screenshots**
Audio issue. Yes, DSP firmware is dumped.

**Information about your environment**
 - OS version: 11.16.0-49U, Luma3DS 12.0-3gxldr
 - PKSM version: 10.0
 - Entrypoint: Home Menu

**Additional context**
Files attached here.
[E.zip](https://github.com/FlagBrew/PKSM/files/11201630/E.zip)

**Comment by TwystedXYZ** [comment]
Github won't support uploading mp3 files directly, so I zipped them up.

**Comment by piepie62** [comment]
This is a problem with the underlying library that we use for MP3 reading. My local media player doesn't like those files, either. With those in mind, I'm just going to say that this is just out of scope; see [our FAQ entry on music](https://github.com/FlagBrew/PKSM/wiki/FAQs#how-do-i-add-custom-music) for the format you should be using.
