### ISSUE TITLE
Broken link in FAQS

### ISSUE THREAD

**Issue by Lictor000** [FlagBrew/PKSM#1388]
Here:
https://github.com/FlagBrew/PKSM/wiki/FAQs#why-doesnt-my-gamesave-show-up-in-pksm
The link pointing to the "Settings" page is wrong, as it is incomplete.

Current Link:
https://github.com/FlagBrew/wiki/Settings#title-ids

Should be:
https://github.com/FlagBrew/PKSM/wiki/Settings#title-ids

PS: Not sure if this was the best way to report the issue, I'm not very familiar with github.

PPS: thanks for the amazing work!

**Comment by GriffinG1** [comment]
Just fixed. Further wiki issues like this would be best reported on [our Discord](https://discord.gg/bGKEyfY) in the #pksm-general channel.
