### ISSUE TITLE
An Exeption Occured Bug

### ISSUE THREAD

**Issue by Black3356** [FlagBrew/PKSM#1390]
Describe the bug
PKSM keeps crashing any time i open it on my nintendo 3ds, showing me a screen of codes and errors attached.

**To Reproduce**
1. i open PKSM on my nintendo 3ds  
2. once loaded, appears a black screen with bunch of errors
3. crushes all the times

**Expected behavior**
it should open 

**Screenshots**

![IMG-20230412-WA0002](https://user-images.githubusercontent.com/130596390/235255370-4317f403-c092-480d-ad1e-b3d4a94c3217.jpg)

**Information about your environment**
 - OS version:Sys 11.16.0-49E luma v12.0.1
 - PKSM version:10.0.0
 - Entrypoint: via PKSM icon on home screen

**Comment by Black3356** [comment]
Can you please help me?

**Comment by FM1337** [comment]
Can you please try the following steps?

1. Try launching PKSM via the homebrew launcher (download the 3dsx version of PKSM) and see if that works
   - If that does work, then try reinstalling PKSM to see if that fixes it (make sure to take a backup of the ext data using checkpoint just in case)
2. Check your SD card for errors. Chances are if the first step doesn't work, then it could be a dying SD card

If none of those work, please submit the crash dump on discord if you haven't already and we'll look into the problem (no ETA) and let us know when you have done so.

Thank you.

**Comment by GriffinG1** [comment]
Closing due to lack of response. Please follow up on our [discord server](https://discord.gg/bGKEyfY) for further help with this, and provide the crash dump.
