### ISSUE TITLE
Bug Report - Legality checker "Invalid Type A"

### ISSUE THREAD

**Issue by AthMak** [FlagBrew/PKSM#1392]
Trying to generate a Gastly in a Pokémon Red (VC) save file results in PKSM legality checker complaining about this:

`Invalid: Invalid Type A, does not match species type.`

This appears to be true because using this Gastly in-game, results in it being hit normally by moves like Tackle, which it shouldn't. The Gastly's data in PKSM however shows that it is, in fact, Ghost/Poison type. The Gastly is generated at level 5, is male, has the three moves it should know at that level (Lick, Confuse Ray, Night Shade), and also 15 IVs and 0 EVs in every stat. It also has the correct TID/OT for that save file.

Game: Pokémon Red (Virtual Console)
PKSM version: v10.0.0-2b194722

**Comment by piepie62** [comment]
Small oversight, fixed for next version

**Comment by MageLeader** [comment]
Still an issue for the entire Gastly line. Is PKSM even being updated for 3DS anymore?

**Comment by GriffinG1** [comment]
Pie has been busy with life stuff. A bug fix release will be out when he has time and it is ready.

**Comment by MageLeader** [comment]
> Pie has been busy with life stuff. A bug fix release will be out when he has time and it is ready. You are welcome to compile the application yourself as per the README instructions if you cannot wait.

That's understandable. I only asked because the latest update for 3DS says it won't be updated anymore because they are moving on to the switch.

**Comment by GriffinG1** [comment]
> This is the final major release for the 3DS. We are shifting our focus to porting PKSM to the Switch, **this means that any future releases of PKSM for the 3DS will only contain bug fixes or minor changes.**
