### ISSUE TITLE
Bug Report - Non valid save (Emerald)

### ISSUE THREAD

**Issue by DavidAD37** [FlagBrew/PKSM#1394]
**Describe the bug**
Vainilla Emerald save file not working on PKSM after playing.

-Transfered my vainilla save from my Emerald cartridge to use on my N2DS
-Tested the save (before using it on an emulator) on PKSM. Works OK.
-Used it with a fresh-non modified-game (the Tr*shman one) on mGBA on the NDS. Game and Save with same name.
-Played a while, then saved.
-Opened PKSM to edit some things. 
"PokemonEmerald.sav is not a valid save file" appeared.

**Information about your environment**
 - PKSM version:  10.0.0

**Additional context**
I know i can ftp the save and use other programs to edit it (Yes. tested with PK**x after this), but supposedly it should work. Right?

Thanks for an answer.

**Comment by GriffinG1** [comment]
mGBA appends a footer that PKSM does not account for in the latest release. Either wait for the next release to be ready (no ETA), build the latest commits yourself (see the README file for instructions how) or figure out the length of the footer and remove it.

**Comment by DavidAD37** [comment]
> mGBA appends a footer that PKSM does not account for in the latest release. Either wait for the next release to be ready (no ETA), build the latest commits yourself (see the README file for instructions how) or figure out the length of the footer and remove it.

Thanks. Gonna try the delete-footer-on-a-hex-editor thing.

**Comment by GriffinG1** [comment]
Issue will be left open until the next release, for others to easily reference.

**Comment by LordValgor** [comment]
@GriffinG1 Is there any update to this? I'm experiencing the issue on the latest version of PKSM still.

**Comment by GriffinG1** [comment]
There hasn't been a new release yet. If you don't have a footer, then it's a different issue and not applicable here.
