### ISSUE TITLE
Bug Report - Error during startup de PKSM.

### ISSUE THREAD

**Issue by EstebanSour** [FlagBrew/PKSM#1396]
Error during startup
error code: 0xDSE06486 and description: nsInit failed.

1. Install cia and open the PKSM
2. the program charge (the icon PKSM move)
3. but the message that appears in the photo that I uploaded appears

I want to occupy it :(

 - OS version: 11.6.0-39U
 - PKSM version: 10.0.0
 - Entrypoint: PKSM icon on home screen
 
Please I need help, Before, I could use the app without problems, but from one day to the next it stopped working and I don't understand why.
![IMG_3025](https://github.com/FlagBrew/PKSM/assets/135167136/72367449-01b7-4994-93c7-eb1a48d5a9d1)

**Comment by GriffinG1** [comment]
Update to the latest version of luma.
