### ISSUE TITLE
Bug Report - I can't find gen 1/2 Pokemon in the bank

### ISSUE THREAD

**Issue by Darthkakart97** [FlagBrew/PKSM#1397]
**Describe the bug**
A clear and concise description of what the bug is. I can't see any gen 1/2 Pokemon in the storage function all I see is blank spots

**To Reproduce**
1. Go to '...' storage 
2. Click on '....' wifi
3. Scroll down to '....' any pagr

**Expected behavior** we're gen 1/2 Pokemon are there are blanks

**Screenshots**

**Information about your environment**
 - OS version:
 - PKSM version:
 - Entrypoint:

**Additional context**
Add any other context about the problem here also you guys are awesome keep up the good work

**Comment by FM1337** [comment]
I suspect this was due to prior GPSS issues (which should have now been resolved). Can you please confirm if this issue is still occurring?

If I do not receive a response within 1 week from this comment, I will assume that this issue is no longer occurring and will close the issue as such.

**Comment by Darthkakart97** [comment]
Sorry for late response I still see blank spaces in cloud storage 
![IMG_20230620_183428](https://github.com/FlagBrew/PKSM/assets/135410212/9253f630-2510-440d-bf6a-5a3979a1aef1)

**Comment by Darthkakart97** [comment]
Hi it's still not there was there a update I can downloaded

**Comment by Darthkakart97** [comment]
Hi it is still not working

**Comment by FM1337** [comment]
> Sorry for late response I still see blank spaces in cloud storage ![IMG_20230620_183428](https://user-images.githubusercontent.com/135410212/247301478-9253f630-2510-440d-bf6a-5a3979a1aef1.jpg)

You will still see blank spaces for Pokémon that are in generations that aren't supported by PKSM (such as Generation 9 or BDSP/LA) but you should be able to see generation 1/2 pokemon.

**Comment by Darthkakart97** [comment]
Let   me see if I can find one

**Comment by Darthkakart97** [comment]
Could you add generation filter to the search filters

**Comment by Darthkakart97** [comment]
Found a game boy Bulbasaur thanks for the help

**Comment by FM1337** [comment]
> Could you add generation filter to the search filters

You can open a feature request ticket, but this likely will not be added anytime soon as PKSM for 3DS is no longer receiving feature updates as we shift our focus to developing for the switch.


> Found a game boy Bulbasaur thanks for the help
Good to hear it, I'm going to close this issue now as it is resolved.

**Comment by Darthkakart97** [comment]
We're can I make segestions for the app

**Comment by GriffinG1** [comment]
You can make suggestions in the appropriate channel on our discord. This issue is now locked.
