### ISSUE TITLE
PKSM 10.0 doesnt work on citra for android

### ISSUE THREAD

**Issue by bhetong28** [FlagBrew/PKSM#1398]
**Describe the bug**
PKSM 10.0.0 doesnt work on citra. It says rosalina sysmodule wasnt found

**Screenshots**
![Screenshot_2023-06-05-14-28-31-677_org gamerytb citra_emu](https://github.com/FlagBrew/PKSM/assets/36464328/baf91a24-0cae-4a25-8ebe-120e94b51d08)

**Information about your environment**
 - OS version: 
 - PKSM version: 10.0.0
 - Entrypoint:

**Additional context**

**Comment by FM1337** [comment]
PKSM is not designed to run on emulators
