### ISSUE TITLE
Bug Report - Brief Description/Name of issue

### ISSUE THREAD

**Issue by DemonicMask** [FlagBrew/PKSM#1400]
I just installed pksm 10.0.0 and loaded it up and when loaded it says the following ,

Error during startup: 0xFFFFFFFF
Description: additional assets download failed.

then it tells me to make sure I am connected to the internet and that I am on the latest version.

my 3DS is connected to the internet 

**Expected behavior**
Should have created some files and loaded up

**Screenshots**
![image](https://github.com/FlagBrew/PKSM/assets/136274109/a497ec39-bc72-4c5b-a628-5cada1966800)

**Information about your environment**
 - OS version:   Windows
 - PKSM version:  10.0.0
 - Entrypoint:

**Additional context**
any reply would be great, I have uninstalled and reinstalled multiple times.

**Comment by FM1337** [comment]
https://github.com/FlagBrew/PKSM/issues/1188#issuecomment-644519450
