### ISSUE TITLE
GPSS and Auto-Legality Offline

### ISSUE THREAD

**Issue by Zwaby** [FlagBrew/PKSM#1401]
**Describe the bug**
I can't connect to GPSS to access cloud boxes. I am getting this error:
Error communicating with GPSS:
503

**To Reproduce**
1. Go to 'storage'
2. Click on 'Wi-Fi symbol on bottom left
3. See error

**Expected behavior**
I want to be able to access cloud boxes when I click the symbol.

**Screenshots**
![gpss error](https://github.com/FlagBrew/PKSM/assets/136278061/826494e0-e1e0-4ff8-9518-1d8584d51213)

**Information about your environment**
 - OS version: 11.17.0-50U, Luma v12
 - PKSM version: Latest
 - Entrypoint: cia

I'd appreciate any help. Thanks in advance!

**Comment by GriffinG1** [comment]
The GPSS is currently offline as part of a data migration. No ETA when it will be back up. I will close this when it is.

**Comment by Zwaby** [comment]
Great, thank you for clarifying!

**Comment by GriffinG1** [comment]
GPSS and Auto-Legality are now back up.
