### ISSUE TITLE
Bug Report - pikachu with cap/ can't see

### ISSUE THREAD

**Issue by belkrus45** [FlagBrew/PKSM#1408]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Information about your environment**
 - OS version: 
 - 11.17
 - PKSM version:
 -  double digit
 - Entrypoint: 
cap pikachus are not appearing in the double digit version pksm
![IMG_20230713_191520583](https://github.com/FlagBrew/PKSM/assets/65639681/66c52c7b-07e1-4f5d-95e0-d4990092826c)
![IMG_20230713_191651188](https://github.com/FlagBrew/PKSM/assets/65639681/9b1347a1-55bd-4813-9324-57d5134b3012)
![IMG_20230713_193650062](https://github.com/FlagBrew/PKSM/assets/65639681/6c3cebc1-071c-40b2-8a2d-9abd3dea5e49)
![IMG_20230713_193752197](https://github.com/FlagBrew/PKSM/assets/65639681/4d9dd79d-5165-4e3c-b677-da1c040963ec)

**Additional context**

**Comment by FM1337** [comment]
Known bug #1373 will be fixed in next bug fix release (no ETA)
