### ISSUE TITLE
Bug Report - Got an unknown HTTP response Error: 0x00000193

### ISSUE THREAD

**Issue by AdemJensen** [FlagBrew/PKSM#1412]
**Describe the bug**
The bug happens when trying to auto-legalize a Pokémon. I am not sure if this is an error.

**To Reproduce**

1. Go to editor
2. Click on a pokemon
3. Check to see if legal, if illegal, auto-legalize

**Expected behavior**
The pokemon should be legal with no problems

**Screenshots**
N/A

**Information about your environment**
 - OS version: New3DS-JP 11.17.0-50J
 - PKSM version: 10.0.0
 - Checkpoint version: v3.7.4 

**Additional context**
Tried to use proxy, change Wi-Fi settings, none of them works.

Got wireshark sniffing records here: [capture-pksm.zip](https://github.com/FlagBrew/PKSM/files/12448299/capture-pksm.zip), something is wrong with the TCP connections...

![image](https://github.com/FlagBrew/PKSM/assets/23029457/a9a1ed9a-7296-4d84-8585-073ee92b9712)

**Comment by FM1337** [comment]
Give it another try and let me know if it works now?

**Comment by FM1337** [comment]
As it has been 2 weeks since my comment and there has been no follow up, I will be closing this issue. Please re-open if you are still having this issue.
