### ISSUE TITLE
Bug Report - Brief Description/Name of issue

### ISSUE THREAD

**Issue by Focas2003** [FlagBrew/PKSM#1418]
**Describe the bug**
Well after a year i want to update the app but I found this error:
Error during startup: 0xD8E064
Description: nsInit failed
**To Reproduce**
1. Go to pksm
2. Blackscreen with homebrew 
3. the error and descrption
4. press start to exit
**Expected behavior**
I want to edit pokemon :c

**Screenshots**
![image](https://github.com/FlagBrew/PKSM/assets/72712950/70a7fa22-7533-406d-b5f6-c5935f4fd7d0)

**Information about your environment**
 - OS version: Idk :C
 - PKSM version: 10.0.0
 - Entrypoint: Cautions (FBI)

**Comment by FM1337** [comment]
Closing this as it was solved back on Discord on 06/01/2024. Issue was outdated Luma3ds version.
