### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by SmoothLA420** [FlagBrew/PKSM#1420]
**Is your feature request related to a problem? Please describe.**
Switch porting
**Describe the solution you'd like**
This website may help with switch development too: https://switch.homebrew.guide/homebrew_dev/app_dev.html
**Describe alternatives you've considered**
I've seen here in the projects you're trying to make the Switch port possible.
**Additional context**
I can try to help as I've a modded Switch and access to multiple computer OSes.

**Comment by GriffinG1** [comment]
Duplicate of #1175.
