### ISSUE TITLE
Bug Report - Pokemon black not showing in the game selection menu

### ISSUE THREAD

**Issue by Amittere1** [FlagBrew/PKSM#1423]
**Describe the bug**
When on the game selection screen it only shows 3ds games but not black. Also its digital version of black, pirated

**Information about your environment**
 - OS version: O3DSXL on latest version
 - PKSM version: latest version

**Comment by SpiredMoth** [comment]
1. PKSM only auto-detects cart versions of DS games.
2. We at FlagBrew do not support piracy.
