### ISSUE TITLE
Feature Request - Pokemon Home + Gen 8 and 9 support

### ISSUE THREAD

**Issue by SnomBaby** [FlagBrew/PKSM#1426]
Is it possible to transfer Pokemon from PKSM to Home in a future update? Pokemon Bank and Transporter are shutting down eventually, and there is basically everything with those 2 apps in PKSM, the only thing missing is Home support

**Comment by GriffinG1** [comment]
Transfers to home would require interacting with Nintendo's server which would end in this project getting taken down. Refer to #1175 for gen 8/9 support.
