### ISSUE TITLE
Bug Report - in-game menu gone (Pokemon X)

### ISSUE THREAD

**Issue by Natriss** [FlagBrew/PKSM#1433]
**Describe the bug**
So I tried to test this and after getting the EON gift and played the game. I hit X to open up the menu and all options are gone.

**To Reproduce**
1. Click on X

**Expected behavior**
The menu options should still be visible. 

**Information about your environment**
 - OS version: 11.16.0-49E
 - PKSM version: 10.0.0

**Comment by Volcan4436** [comment]
The Eon ticket is for ORAS not X Y and as such will cause that issue

**Comment by Natriss** [comment]
Ah okay, thx for the heads up.
