### ISSUE TITLE
Shiny Arceus Event - Missing Shiny Arceus Event in Injector

### ISSUE THREAD

**Issue by alanleon26** [FlagBrew/PKSM#1434]
**Describe the bug**
In the Event injector for Alpha Sapphire unable to find the shiny Arceus event that was distributed in Japan in 2015, all that seems to appear are non-shiny variant. Which can be found here: https://www.serebii.net/events/dex/493.shtml. I have not checked to see if the issue is present for all gen 6 games. 

**To Reproduce**
1. Go to PKSM
2. Click on Events
3. Click On 0081 Japanese Arceus with Silk Scarf or 0123 Japanese Arceus with Silk Scarf (I believe one of these are meant to be shiny as they both have silk scarf which matches the serebii event description but neither are)
4. See Error: When opening the game and recieving the mystery gift neither of the arceus are shiny

**Expected behavior**
One of these injected wondercards should yield a shiny arceus. But when recieving gift from Pokemart neither of them are.

**Screenshots**

![Screenshot 2024-01-05 195420](https://github.com/FlagBrew/PKSM/assets/99235072/249e7ffb-9368-49fa-84d6-2daa3cf184c5)
![IMG_7850](https://github.com/FlagBrew/PKSM/assets/99235072/6ccf48d4-a24b-425a-9cce-8ed94bfaa11a)
![IMG_7849](https://github.com/FlagBrew/PKSM/assets/99235072/6d226290-5762-4a4a-a40d-4b2aeaf0aad6)
![IMG_7854](https://github.com/FlagBrew/PKSM/assets/99235072/8f1608a7-96ce-4bf7-9bc7-c0854ac9234b)
![IMG_7852](https://github.com/FlagBrew/PKSM/assets/99235072/14159d04-cb90-4642-8ad2-e29c2c3294a9)
![IMG_7851](https://github.com/FlagBrew/PKSM/assets/99235072/c7c76352-58a7-4e8d-aa50-cdd6207931fb)
![IMG_7853](https://github.com/FlagBrew/PKSM/assets/99235072/c1bdf2f5-0b2d-4c55-8075-fb37b00b8899)

**Information about your environment**
 - OS version:
 - PKSM version:10
 - Entrypoint:

**Additional context**

**Comment by AChair0** [comment]
did you manage to get it?

**Comment by NinjaArmy36** [comment]
Can confirm this is an issue

**Comment by AChair0** [comment]
The one with SID 81 is supposed to be shiny

**Comment by Zomgnomes** [comment]
Not sure why this was closed, this is clearly still broken.

From the [wiki](https://github.com/FlagBrew/PKSM/wiki/Event-Injector) it says if it's missing anything from [EventsGallery](https://github.com/projectpokemon/EventsGallery) to report it, and clearly [Shiny Arceus](https://github.com/projectpokemon/EventsGallery/blob/master/Released/Gen%206/Wondercards/JPN/0081%20XYORAS%20-%20%E3%83%87%E3%82%BB%E3%83%AB%E3%82%B7%E3%83%86%E3%82%A3%20Arceus%20Shiny%20(JPN).wc6) is missing from the build.

You can still get it by downloading the .wc6 from EventsGallery throwing it in `3ds/PKSM/inject/` on your SD card, then using injector.c under the universal scripts in PKSM to get it, but it's frustrating that it requires those extra steps.
