### ISSUE TITLE
Port to Wii & Switch 

### ISSUE THREAD

**Issue by Volcan4436** [FlagBrew/PKSM#1440]
I have been wanting this to be ported to more consoles and as Such I am Putting a Money Bounty on The porting of PKSM to more platforms those payouts being:

Switch: 25 USD
Wii: 20USD

hopefully this will encourage someone to create these ports.

if you want to claim the payout contact me on Discord: _Volcan

**Comment by FM1337** [comment]
First off, we're not porting this to the Wii, that would be stupid.

Secondly, this is neither a feature request, or a bug report, so this is spam.

Thirdly, we're not doing bounties, that's a good way to end up on Nintendo's radar which is the last thing we need.

Fourthly, there are bounty websites that are more trustworthy than a random guy saying "Oh yeah I'll give you $20 if you port it to the Wii and $25 if you port it to the switch" and claiming to get the "reward" to message you on discord.

Do not open an issue like this again.
