### ISSUE TITLE
pokemon spin

### ISSUE THREAD

**Issue by rncg77** [FlagBrew/PKSM#1447]
hi my pksm suddenly starting to spin my pokemon in all my games gen 5,gen 6 gen 7 all in editor in bank  spins 
![Uploading 20240401_212335[1].jpg…]()
![20240401_212331 1](https://github.com/FlagBrew/PKSM/assets/165735257/3d761b54-6eae-4e9b-88f7-532612d42cb9)

**Comment by FM1337** [comment]
Look at the date.
