### ISSUE TITLE
Bug Report - Bag Editor busted.

### ISSUE THREAD

**Issue by modular511** [FlagBrew/PKSM#1449]
When you go to add items, it defaults to regular items - not medicine, z crystals etc like it used to

**To Reproduce**
1.  Open Pksm and click any gen 7 game
2. click bag
3. go to add an item  in any section but items
4. you'll notice you cant add berries, z crystals, tm/hm etc - it just lets you add regular items

**Expected behavior**
I expected it to work how it always did, but seems that last update broke something lol

**Information about your environment**
 - OS version: 11.17.0-50
 - PKSM version: PKSM 10.1.0
 - Entrypoint: Luma CFW

**Additional context**
It just seems that the most recent update needs a fix to sort out the item categories so that all works well! I love the app! thank you :)

**Comment by FM1337** [comment]
Looking into this now, no idea what would've caused it so this is gonna take some time to debug.

**Comment by Drunkpikachu420** [comment]
I'm having a similar problem with pokemon gold. I can only inject tms and hms no other items even in the pokeballs pocket

**Comment by Drunkpikachu420** [comment]
Awesome thank you so much I love this app it has been a lifesaver

**Comment by FM1337** [comment]
Fixed in 10.1.1
