### ISSUE TITLE
Gen 1 pokémons holding random itens

### ISSUE THREAD

**Issue by AquamarineDreams** [FlagBrew/PKSM#1457]
**Bug description**

So, I was trying this application to test transferring pokemon between games. Quickly I realized that my gen 1 pokémons were holding itens, that I didn't even had yet, like TMs for example. Wich shouldn't be possible since gen1 can't hold itens.

I know that I can just delete them via the editor, but I thought that I should report it anyway

**To Reproduce**

1. Open a gen1 gamefile in pksm
2. Notice that your pokemon is holding a random item

**Screenshots**

![2024-05-19_16-22-07 300_top bmp](https://github.com/FlagBrew/PKSM/assets/140275860/a076ac01-8d6c-4133-bc58-5b9fca252a8a)
![2024-05-19_16-22-14 966_top bmp](https://github.com/FlagBrew/PKSM/assets/140275860/daa346f8-e965-42ef-93fc-6105ba45b7a7)

**Information about your environment**
 - OS: New 3ds xl [11.17.0-50U] CFW [Luma 13.1.1]
 - PKSM version: 10.1.1 - latest

**Additional information**
Game: Pokemon yellow [VC]

**Comment by GriffinG1** [comment]
Working as intended. Please refer [here](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_wild_held_item_(Generation_II)) for more information.

**Comment by AquamarineDreams** [comment]
> Working as intended. Please refer [here](https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_wild_held_item_(Generation_II)) for more information.

Oh, sorry. I really didn't knew that. That's a really interesting characteristic of gen1.
