### ISSUE TITLE
Feature Request - Ability to read save files from VC Injected GBA Games like FR/LG

### ISSUE THREAD

**Issue by JediCruz1** [FlagBrew/PKSM#1466]
Rather than playing these GBA games via an emulator in Twilight Menu, using the virtual console to play them is more intriguing but creates the inability to read the save files via PKSM. Yes you can extract the save file via GM9 and have PKSM read it that way and then reinject the save file back but that means you have to extract the save file every time you want to edit and then reinject. If there a way for PKSM to read the VC game file natively then I think this would a lot of time.

**Comment by SpiredMoth** [comment]
PKSM can already read saves from GBA VC injects, but it can't find those injects automatically. You need to configure them in the [Title IDs section](https://github.com/FlagBrew/PKSM/wiki/Settings#title-ids) of PKSM's Settings.

**Comment by JediCruz1** [comment]
Actually, I found out how to do this natively using the Title IDs under Misc. As long as the tool used to create the Injected VC gives the Title ID in the CIA header, you can use it here. Now to see we can determine the Title ID’s for NDS games on that are on the main screen that was done by NDS Forwarder.

**Comment by SpiredMoth** [comment]
NDS Forwarders are essentially shortcuts for running a NDS game through TWiLight Menu, and PKSM [already supports](https://github.com/FlagBrew/PKSM/wiki/FAQs#why-doesnt-my-gamesave-show-up-in-pksm) editing those saves too.
