### ISSUE TITLE
Bug Report - Ultra Sun 3DS crashing when searching the bag for an item to swap/add

### ISSUE THREAD

**Issue by sebcat45** [FlagBrew/PKSM#1467]
The 3DS crashes

**To Reproduce**
1. Go to bag
2. Click "none"
3. Search. i.e. "elec"

**Expected behavior**
A Crash

**Information about your environment**
 - OS version: sorry idk
 - PKSM version: the most recent as of this post
 - Entrypoint: idk for this srry

**Additional context**
trying to get a electric stone when it happened. it happened multiple times
I may take a small while to respond.
I will add a small video of it happening soon

**Comment by FM1337** [comment]
Known issue #1455
