### ISSUE TITLE
Feature request: filters in extra storage

### ISSUE THREAD

**Issue by d4mation** [FlagBrew/PKSM#209]
Currently when in the Extra Storage menu, you have to open up the Summary of a Pokemon to determine just about anything about them.

If it were possible to search for things like Pokeball, Ability, Markings, Egg Group, etc. to help track down specific Pokemon it would be absolutely fantastic.

**Comment by piepie62** [comment]
I really want to do this, but I'm not entirely certain what the UI for it should be, especially considering that what I would normally use for a default value (in code, zero) is a valid value in multiple cases. Does anybody have any ideas for this?

**Comment by Epicpkmn11** [comment]
> Does anybody have any ideas for this?

Ideas for the menu for selecting what filters to apply?

Here's a screenshot of what I did in pkmn-chest if its helpful
![filter](https://user-images.githubusercontent.com/41608708/69523569-d2077000-0f29-11ea-8c11-f1a9a90dba5b.png)
the `x`/`√` on the left is whether that filter is enabled, the `=`/`≠` is whether to match or match to not for that item, and the right most column mostly take you to list selections or keyboard entries

**Comment by piepie62** [comment]
This is essentially done. I'll very likely be refining and adding options to the UI in the future, but I'm happy enough with it to close this.
