### ISSUE TITLE
Feature Request: Box Sorting

### ISSUE THREAD

**Issue by AlanBTG** [FlagBrew/PKSM#386]
Okay, so 1 of the many features that the official Pokemon Bank app is missing is sorting. Having over 3k pokemon and no way to sort them by species, level, nature, etc. is really annoying. Do you think It could be done on PKSM?

**Comment by GM-Script-Writer-62850** [comment]
Or a search feature like what is present in sun/moon, but searching by ivs would be a nice touch (i have about 1.5k pkm i bread in there; never know when something will be useful)
even a quick find to find the next match would be nice

**Comment by BernardoGiordano** [comment]
Implemented in 6.1.0
