### ISSUE TITLE
[Feature Idea] Editing Stat Markings

### ISSUE THREAD

**Issue by ewormPL** [FlagBrew/PKSM#509]
It'd be nice if PKSM gave us the option to edit what the game calls markings, the six little icons that are typically used to mark the stat IVs of the Pokémon.

Better yet, an additional option could be made to automatically fill the markings representing the stats when the stat's IV is 31. In Sun&Moon the markings have two color options, so one could go for the 0 or 31. Maybe this option could be customized? I know some people use the blue markings for the 31 stats and others (like myself) use the red ones (if in case of natures red is high and blue is low, then it's natural to do the same with the markings).

Anyway, that's my little input. Keep up the good work, PKSM is fantastic!

**Comment by vaz** [comment]
A marking editor would be cool. I see your idea as two ideas really, 1) being able to edit them at all (besides via hex editing) and 2) providing an option for auto-marking with a few values to represent the few popular marking schemes (I often use red for 31, blue for 30 to see hidden power patterns - but I see blue for hyper trained, or for desirable 0s (which I do during breeding), and so on).

It could probably be boiled down to a few checkboxes for auto-marking to happen after saving in the stat editor:

- [ ] mark 31s (red if gen7+)
- [ ] mark 30 as blue (if gen7+)
- [ ] mark 0 as blue (if gen7+)
- [ ] mark hyper-trained as blue (if gen7+)

Everyone has their own scheme but it would get complicated fast to try to make it *that* customizable (IMO), this would keep the logic and UI pretty straightforward. Of course someone might have a better idea :)

**Comment by BernardoGiordano** [comment]
Implemented in 6.1.0
