### ISSUE TITLE
Gen 4 Bank

### ISSUE THREAD

**Issue by paco121** [FlagBrew/PKSM#604]
Hi, love your app, but I have a doubt, is it possible to move pokes from Diamond to the bank and then to Ultra Sun? I have launched PKSM but when I try to open "Storage" or "Editor" options it says "this function is not enabled (yet)". I don't know if I have installed it uncorrectly or something or if it is not possible yet. Hope in a future we can use bank in gen 4-5. Congrats and thank you sooo much for your awesome job!

**Comment by nabithahmed** [comment]
It is not possible yet, and won't be for the forseeable future, if no one is willing to make a contribution towards it.

**Comment by chpoit** [comment]
If I were to want to look into this, at least to jerry rig something to avoid me the task of using the horrible in-game migration,, what should I look at?
