### ISSUE TITLE
PKSM Storage doesn't update the "Held Trainer" label

### ISSUE THREAD

**Issue by halosamuel44** [FlagBrew/PKSM#640]
When you use the bank storage and send pokemon to a different Trainer, the Held Trainer Label doesn't get updated, thus generating an illegality issue (which, luckily, doesn't affect trades or battles) on any illegality checker.
In other words: If I have a savefile A, put some pokemon from it on storage, and then put those pokemon on a savefile B, the Held Trainer label will show the value it had on savefile A, instead of changing to the Trainer name of savefile B. Weird

**Comment by Qiyao7** [comment]
#594 
Waiting for next release.
