### ISSUE TITLE
[Feature Request] Scripts subfolders

### ISSUE THREAD

**Issue by SpiredMoth** [FlagBrew/PKSM#649]
Based on a suggestion from the PKSM Discord server, subfolders would be a great addition to the script portion. It would allow the collapsing large groups of similar scripts (Vivillon, legend resets, etc.) and would also be a solution to the dilemma of [scripts with illegal effects](BernardoGiordano/PKSM-Tools#16) (hide them in a subfolder named "Illegal effects" or something similar).

**Comment by PKMWM1** [comment]
I think this would be a great idea. As I have made a lot of scripts for my own games, and would like to subdivide them rather then just be given a +200 Item list
