### ISSUE TITLE
Pokedex flags not implemented pre-gen7

### ISSUE THREAD

**Issue by Bennemans360** [FlagBrew/PKSM#656]
When transferring a or many pokemons from the bank to the boxes of Omega Ruby from Y and then check the in-game pokedex the transferred pokemons are not flagged as captured. I saw that this was fixed in v5.1.0, which is the version I have, but it doesn't seem to work.. I am early into the game and doesn't have national dex yet but Wingull was a pokemon I already catched in Y and is part of the Hoenn region so transferring this transfer would work?

I have seen a lot of closed issues about this bug so maybe it is just me? Or is the changelog entry about pokedex flag setting only applicable for transferring to Sun, Moon or the newer USUM? 

Greetings from Belgium and thanks for the great work!!!

**Comment by Bennemans360** [comment]
Ooooh ok that's why. How are pokemon 'flagged' then as captured or seen in the system.

**Comment by Seta19** [comment]
Been having this issue as well..sorry new here, so fixed in the rewrite means next update or?
