### ISSUE TITLE
Move wondercard dumping into its own menu

### ISSUE THREAD

**Issue by zweilous** [FlagBrew/PKSM#689]
I was wondering if it's feasible to move mystery gift/wondercard dumping into its own menu away from the event database.

If my intention is to just dump my own existing wondercards and not inject any that are built into PKSM's database, I find that it's not intuitive to have to select a wondercard from the event database to be able to access the existing wondercard slots.

**Comment by ccfman2004** [comment]
I second this.  It took me a while to figure out how to do it in the first place as it wasn't obvious.
