### ISSUE TITLE
Any plans to support the Gen 1/2 VC titles?

### ISSUE THREAD

**Issue by m2pt5** [FlagBrew/PKSM#698]
I ask mostly for the storage function, as it would be good for people who don't use Pokemon Bank.

**Comment by c-schuhmann** [comment]
There are no plans at the moment AFAIK.

**Comment by Multimegamander** [comment]
@m2pt5 I made a fork, look at my fork, I plan on having that.
and, Bernardo said he never has plans for that :/

**Comment by skyforce77** [comment]
Maybe @gocario could help on that ?

**Comment by FM1337** [comment]
> Maybe @gocario could help on that ?

I don't think he's active in the homebrew community anymore.

**Comment by lagseeing** [comment]
This would be sweet.

**Comment by Midnoclose** [comment]
I would like to work on this, but I don't know when the afformentioned rebuild will happen.

**Comment by piepie62** [comment]
It's already been done

**Comment by Midnoclose** [comment]
sweet! I will get right to work then.

**Comment by piepie62** [comment]
Just a note for working on it: make sure to run `make format` every once in a while to have your code match our style. Other than that, have fun!

**Comment by Midnoclose** [comment]
This si more daunting than I thought, mainly because I have to resize the title screen gui.

**Comment by Lost-Systems** [comment]
Any updates on this currently?

**Comment by LonerPupper** [comment]
> Any updates on this currently?

none that is known to the community they just got finished with GPSS (Global PKSM Sharing Storage) and still have bugs to finish so id give them til 8.0.0 or 9.0.0

**Comment by GriffinG1** [comment]
Bahahahahahahah. Again, nobody on FlagBrew _wants_ to handle it, but anyone who wants to do it themselves and PR it are free to. Afaik from the discord server, @Midnoclose chose to stop working on it due to it being a pain in the ass.

**Comment by Midnoclose** [comment]
i was having trouble with GUI stuff, maybe I’ll start working on it again

**Comment by piepie62** [comment]
Like we said on the Discord, don't pay attention to GUI stuff until you've done the core work. That's the main pain, and, no offense meant, but because I designed literally the entire GUI system, that's the part that I can definitely do the easiest

**Comment by Midnoclose** [comment]
I know you said that, that’s why I said that I might start workin on it again

**Comment by FM1337** [comment]
With the publishing of [PKSM-Core](https://github.com/FlagBrew/PKSM-Core), it might be easier for anyone interested in attempting to add virtual console support. 

Our original stance still stands though, not of the main Flagbrew team has any interest (or time) to add VC support to PKSM. If you'd like to help out and add it, more power to you and you're more than welcome to open a pull-request if you should ever get it successfully added.

**Comment by lagseeing** [comment]
Is this being considered?

**Comment by SpiredMoth** [comment]
Our stance remains the same: nobody on the team currently has any interest in working on it, but we'll gladly accept someone else's work

**Comment by FM1337** [comment]
At this point the discussion has gone on long enough and it always loops back to the beginning.

Our final stance on the matter is this: **No one on the FlagBrew team has any desire to add generation 1 and 2 support to PKSM. We do not and will NEVER have any plans to add it ourselves. If you would like to see it added, then by all means please, develop it yourself and open a pull request. If it meets our standards we will merge it in and credit you appropriately. But if you have no plans on doing so, then DO NOT ASK FOR GEN 1/2 support**.

I am closing this issue once and for all.
