### ISSUE TITLE
Add Shiny Zygarde along with the resent legendary events wonder card

### ISSUE THREAD

**Issue by MasterSara85** [FlagBrew/PKSM#728]
it would be nice if some how you could add the rent legends everyone missed keep up the good

**Comment by Ronanklan** [comment]
So, hey buddy!

Did you get your shiny Zygarde?

If NOT, email me...(dronan24@yahoo.com)
I will trade you 1 for FREE..

So hit me up if you still want a Shiny Zygarde!
I have cloned 100s of them...

**Comment by Ronanklan** [comment]
@KofiMatson123

Im sorry, i dont think i understand that process exactly...

But are you sayin it is possible to inject event pokemon that are NOT already available in the events tab?

Like i missed February's Legendary this year...
Can i inject that one with this method you speak of?

**Comment by freddyrv** [comment]
@KofiMatson123 I am trying to follow this procedure without success, I don't get the Y (Wireless option) while in the events tab, only when I am in edit or storage, appreciate your help.

**Comment by Mike007899** [comment]
Select any event, like Mewnium-Z, and it will show you the wireless option.

**Comment by freddyrv** [comment]
thank you @Mike007899 after some troubleshooting, mostly network, I have been able to use the wireless wondercard feature successfully, appreciate your help.

**Comment by iiiddd2** [comment]
How do i wirelessly inject events?It tells me that the pkx/wcx or smth is wrong
