### ISSUE TITLE
PKSM soft-locks 3DS if storage server isn't shutdown before exiting the storage screen

### ISSUE THREAD

**Issue by FM1337** [FlagBrew/PKSM#743]
If you press Y after loading up the bank and then back out by pressing B and then pressing B to cancel the changes to the bank followed by loading up the editor and pressing Y you'll get the "socInit failed!" error.

If you try to go and kill the server in attempt to fix this error by going back to the storage option, you'll get the "Error during processing phase!" error, this error will keep occurring no matter times you try and press A.

Once this has happened if you try to close it by returning to the home menu on the 3DS and closing the app, the 3DS will get soft-locked on "closing software" and you'll have to force reboot the 3DS.

**Comment by BernardoGiordano** [comment]
Doesn't happen in the rewrite
