### ISSUE TITLE
[Feature Request] Only Generate Legal Pokemon & Bring Back Complete Pokedex

### ISSUE THREAD

**Issue by sethreign8103** [FlagBrew/PKSM#751]
PKSM needs an option in the settings or should just default to be unable to generate illegal pokemon. Everyone doesn't always have a pc/laptop handy to cross check legality. I would also like to see an option somewhere to generate a full pokedex again like you could with older versions. Wonderful program otherwise.

**Comment by SpiredMoth** [comment]
Legality is complex, with *lots* of pitfalls. And that's without getting into "can be used online" legal vs. truly legal. It's better to stick with the current behavior of a set of defaults that work for genning versions of most things that approximate legality.

As far as "generating a full pokedex" goes, Bernardo will probably continue to leave that to [scripts](https://github.com/BernardoGiordano/PKSM-Tools/tree/master/PKSMScript). Currently there is an "Inject living dex" script for most games, though none currently update your dex (filling out seen and owned).

**Comment by sethreign8103** [comment]
Isn't legality checks what is done on the pc version though? I don't understand why that can't be done on here. I would think a legality check would make this much more useful.

He took out/moved/renamed the living dex option sometime after version 4.2.2 for some reason & isn't available or is just really difficult to find now. It use to be under "Mass Injector" and I would like to see it return. It use to generate a full living pokedex and update the pokemon that you've seen/caught. Now that option doesn't seem to exist anymore.

**Comment by Mike007899** [comment]
1, the PC program is the legality checker since its a seperate thing, just like servepkx.

2, you can still accomplish this with complete dex scripts under "Scripts" that you can find under the PKSM Tools repo.

**Comment by sethreign8103** [comment]
Back to my reason for starting this regarding the legality checker, not everyone has access to a pc to cross check. Also it kind of defeats the purpose of calling it an AIO editor when you need extra stuff to check. That's good that you can still inject a living dex but I still don't understand why it had to be taken away from being a part of the app itself in the first place.

**Comment by Mike007899** [comment]
1, I understand this completely, but if you cant use a PC and are stuck using a phone, research your legality and go from there.

2, too many bugs and kept throwing errors on stuff that wasnt needed.

**Comment by sethreign8103** [comment]
I'd need to double check with the latest version but I remember me & my gf spent a few hours one day with a slightly older version doing tons of research on what moves were legal for which pokemon etc. and we made them with this but we still had to use the pc version to make them useable even though everything was as legal as it could possibly be. So for those of us that don't always have access to pc's there needs to be an option to check legality from within this app.

**Comment by Mike007899** [comment]
I understand this and once I can get my hands on more free time and the rewrite, I shall publish my guide.

**Comment by architdate** [comment]
It is impossible to "not allow" generation of illegal pokemon while they are being generated. The legality checks are always post processed and cannot be done while the generation is ongoing. The generation of living dex can be done via PKSM Scripts. Please check the repo under FlagBrew organization for the same.
