### ISSUE TITLE
Crash in PKSM Hex Editor

### ISSUE THREAD

**Issue by gamerboi938** [FlagBrew/PKSM#753]
Changing the hex value on the species byte causes PKSM to crash

PKSM Version 5.1.4

**Comment by Gudf** [comment]
Seems to occur when trying to enter invalid values using the keyboard on the touchscreen. (Resulting in values >721 or 0x02D1 on 6th gen,  values >802 or 0x0322 in SuMo, and values >807 or 0x0327 in USUM)

**Comment by piepie62** [comment]
Should be fixed in the rewrite. If not, just comment and I will reopen the issue.
