### ISSUE TITLE
Crash when opening PKSM 

### ISSUE THREAD

**Issue by JojOo517** [FlagBrew/PKSM#754]
When I'm trying to opening the app, it crash and just don't open. Here is a photo. PKSM was working perfectly and I didn't do anything in particular, just transferring Pokemons.

![img_20180723_213242 1](https://user-images.githubusercontent.com/41593541/43098921-d71336aa-8ec0-11e8-825a-7e1dc388fe6a.jpg)

![img_20180723_213248 1](https://user-images.githubusercontent.com/41593541/43098800-7ab9d832-8ec0-11e8-94f5-cda29b3e85b8.jpg)

**Comment by FM1337** [comment]
Not enough information and it's been a month, I'm closing this issue.
