### ISSUE TITLE
Editor for Gen 4 and 5 if possible 

### ISSUE THREAD

**Issue by Lucas2202** [FlagBrew/PKSM#756]
Hi like your software a lot but is possible to use editor for gen 4 and 5 in the future thank you :)

**Comment by Ninjistix** [comment]
i think that requires the physical cartridge not a rom, afaik there's no support besides gen 6+ (cia installed) or physical cartridge, not even VC titles are supported (gen 1&2)

**Comment by jride1995** [comment]
having the physical cartridge of gen 4 & 5 does not work with PKSM on the latest firmware. Hope there is an way to edit gen 4 & 5 in future.
