### ISSUE TITLE
[Feature Request] Forwarder Compatibility?

### ISSUE THREAD

**Issue by ewormPL** [FlagBrew/PKSM#771]
Would it be possible to make PKSM read and modify saves created with games launched via [a forwarder](https://gbatemp.net/threads/nds-forwarder-cias-for-your-home-menu.426174/)? These saves are simple .sav files created next to the .nds file - by dafault, it's "root\roms\nds\"

**Comment by Multimegamander** [comment]
The saves would have to have a set name too (ie. diamond.sav black2.sav hg.sav etc)

**Comment by piepie62** [comment]
This will be indirectly supported in the exact same way TWiLightMenu++ saves will be
