### ISSUE TITLE
Omega Ruby Cartridge Brick?

### ISSUE THREAD

**Issue by Naphan0** [FlagBrew/PKSM#777]
I added a shiny jirachi event and a Pokémon into my box and now I get an error when I open the game or about a minute in to playing. This is what it says on my screen:

An error occurred (ErrDisplay)

Error Type: generic
Process ID. 39
Process name sango-1
Process title id 0x000400000011c400
Address 0x0012884c
Error code 0xd900458b

What should I do?

**Comment by fennectech** [comment]
Use PKSM to backup your Pokémon and use checkpoint to delete your game save data.

**Comment by BernardoGiordano** [comment]
This should have nothing to do with PKSM
