### ISSUE TITLE
[Feature Request] Compatibility With DSi Menu++

### ISSUE THREAD

**Issue by ReaperJack** [FlagBrew/PKSM#779]
Is it possible to add an an interface that can take the save files from the ds roms folder that go into the save files so that they can be used with DS Roms

**Comment by Mike007899** [comment]
No. Flashcard/DSiMenu++ support will never be added and stop asking for it since its basically supporting piracy by asking for this to happen.

**Comment by FLCN17** [comment]
If that were strictly true PKSM wouldn't offer support for carts OR backups. Its simply a matter of getting everything pointed to the DSI menu save directory and making sure the save files are formatted that same. Flashcarts should work as its just emulating a DS cart right? Are saves in the same spot as a legit cart?

**Comment by deadair3210** [comment]
Every ds flashcard works differently, but most if not all of them use their own way of pointing the game to it's save. It's very rarely in the normal spot.

**Comment by piepie62** [comment]
Flashcarts are VERY unlikely to be possible, whereas DSiMenu++ support will come in the rewrite with support for editing arbitrary saves on the SD card

**Comment by Multimegamander** [comment]
YeEt, it's here ma boiz
