### ISSUE TITLE
Redirection failed when attempting to download assets on first boot

### ISSUE THREAD

**Issue by XrissXross** [FlagBrew/PKSM#781]
I am attempting to use PKSM for the first time. When the application loads, it loads graphics then attempts to download assets but each one gives an error "Redirection failed! Press A to continue". After pressing A through each asset, it says "Backing up bank..." then says "Restart the application! Press A to continue" then takes me back to the homescreen. I have the "additionalassets" on the SD card in the PKSM folder as well. I also attempted it without the additional assets folder, but same error. I tried it with Pokemon X, Sun and Ultra Sun, all with the same error. Please help. 

-Noob

**Comment by BernardoGiordano** [comment]
Please have a look to the readme.
