### ISSUE TITLE
"Failed to Download Status Code"

### ISSUE THREAD

**Issue by YourUncleGreen** [FlagBrew/PKSM#783]
Hello,

I have read all the release notes and looked online but have not found an answer.
I am connected to the internet and everytime I open the app, it has to "download graphics" but it always comes back with an error saying "Failed to download status code"
After a few taps of A, I have to restart the app?

Also I know that my additional assets folder is empty but I can't find any readme file.

Am I doing something wrong?
P.s. I downloaded the PKSM.zip (PKSM 5.1.4). The PKSM.cia was downloaded via FBI

**Comment by TylerFurrison** [comment]
You have to manually place the additionalassets folder into the pksm folder, GitHub TLS doesnt let it automatically do it anymore, unless you're on CFW and install the cia, which installs the additional assets with the app.

**Comment by SpiredMoth** [comment]
[Here is PKSM's README](https://github.com/FlagBrew/PKSM)

For trouble with downloading the additional assets, check the [installation section](https://github.com/FlagBrew/PKSM#installation)

**Comment by YourUncleGreen** [comment]
Thanks guys, I'll try right now!

**Comment by TylerFurrison** [comment]
if Im correct, there should be more than that

**Comment by YourUncleGreen** [comment]
Sorry I was playing with the buttons...

Anyway there is a bunch of other files inside the i18n folder.

Should I delete them or something

**Comment by YourUncleGreen** [comment]
So I opened the readme.md and I found 3 entrypoints. I am using Homebrew so which one should I download?

**Comment by SpiredMoth** [comment]
The only thing to download is what you get from the `additionalassets` link below the table

**Comment by YourUncleGreen** [comment]
Which one exactly

> The only thing to download is what you get from the `additionalassets` link below the table

Sorry but where? I really suck at this.

**Comment by SpiredMoth** [comment]
In the README, under "Installation" there's a table listing the different entrypoints. Below that is a couple of paragraphs and there is a link labeled "additionalassets" in the second one

**Comment by BernardoGiordano** [comment]
This isn't the proper place to troubleshoot. Please ask for help in the Discord server instead. https://discord.gg/bGKEyfY
