### ISSUE TITLE
[Feature Request] Default Egg Date

### ISSUE THREAD

**Issue by ralphwicked** [FlagBrew/PKSM#786]
Please add the default egg date in the settings please,

The dates aren't matched when genning a pokemon when its a breedable one the default egg date is set to january 1, 2000 and we need to go to the hex editor to fix it and its too much when we do bulk genning with different species of pokemon, it'll help us a lot,

(BTW the app improved so much and i love the things you guys added I appreciate your effort thanks :100: :1st_place_medal:)

**Comment by Subject21J** [comment]
You can change the default date in the PKSM settings not the hex editor. It applies to all Pokemon created by PKSM.

**Comment by ralphwicked** [comment]
I know but thats only for the default date or met date, its different with the egg date or egg received date.

**Comment by piepie62** [comment]
This is not going to be done. Having a default egg date on non-"hatched" Pokémon is not a good idea, and there's no good way to indicate whether a genned Pokémon is supposed to be "hatched"
