### ISSUE TITLE
Transfered pokémons aren't being recognized by the pokédex (version 5.1.4)

### ISSUE THREAD

**Issue by Valdrigr** [FlagBrew/PKSM#795]
Hello, I just finished playing pokémon X and then transfered everything I caught to the PKSM Storage. I'm playing ORAS right now and the pokédex isn't showing pokémons I brought through the storage as caught (also, they only start to count as "seen" when I battle with them). Sorry if there's a solution, but I do have the latest version and I couldn't find a way to fix it (other than inserting it on daycare and removing).
Also, thanks for the great work, the application is amazing!

**Comment by piepie62** [comment]
Fixed in the rewrite
