### ISSUE TITLE
Issue with Bank

### ISSUE THREAD

**Issue by SoulZoul** [FlagBrew/PKSM#796]
Hey all, First of all, thanks for this amazing app.

Anyway, my issue with PKSM's bank is that i can't put any pokemon in some spaces on the bank. the spaces are pretty random. there are boxes that are fully working while there are some boxes with random spaces where i can't put any pokemon in. The pokes I wanna put in them are legit checked and/or proofed event pokemons so the spaces issue aren't caused by illegal pokes.

Would like to know how to solve this issue

Also, I think it would be great if you guys could be add a feature where you can clone pokemons directly on the storage option instead of having to put them in your game and go to editor to clone them.
While it is a rather minor thing, but it'll make bulk trades easier for me

Thank you for your help

**Comment by piepie62** [comment]
The issue you're experiencing is called "bad sectors", and I don't know much about why they happen or how to fix it. Cloning Pokémon directly from storage will be in the rewrite, though

**Comment by piepie62** [comment]
I'm going to close this because I haven't had any experiences with bad sectors in the rewrite. If it starts happening, then just reply to the issue and I'll reopen it
