### ISSUE TITLE
Issue with installing

### ISSUE THREAD

**Issue by Aneppre** [FlagBrew/PKSM#797]
it keep saying "failed download assets, press A to continue."
I also restarted the program, but nothing to do

**Comment by TylerFurrison** [comment]
Try downloading them manually, this isn't an actual issue with the program, just ask for help in Discord next time

**Comment by BernardoGiordano** [comment]
This isn't the proper place to troubleshoot. Please ask for help in the Discord server instead. https://discord.gg/bGKEyfY
