### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by Rand0mP3rs0n** [FlagBrew/PKSM#799]
I just installed Homebrew and PKSM today. It keeps saying "redirection failed" for all of the assets, even though I have them manually put into the SD card. Once it gets through 9 of those, it makes me restart, which is an instant crash. This is happening on the latest version of PKSM, I double-checked. I've tested it with Alpha Sapphire and Sun, both with the exact same results.

I've done everything recommended. I've followed every step. I've read the readme. Regardless of this, I still get this error. I've spent hours trying to fix it to no avail. None of the previous issue reports help me in the slightest, so I decided to make on of my own.

**Comment by BernardoGiordano** [comment]
You should be connected to download the assetss. Also, this is not a bug with the software; you should ask in our troubleshooting channels on Discord to get issues like thiss sorted out next time

**Comment by Gamer2020** [comment]
Isn't the point of manually copying the assets to not have to download them? Issue originator clearly specifies that he copied them over already.

Get Outlook for Android

________________________________

**Comment by BernardoGiordano** [comment]
Manually copying assets != manually copying assets in the correct place. The readme also explains that

**Comment by Gamer2020** [comment]
Ah OK. Thank you.

Probably would be more productive to explain that off rip.

Get Outlook for Android

________________________________

**Comment by Rand0mP3rs0n** [comment]
The reason why I downloaded the assets manually is because they weren’t downloading even when I was connected to WiFi. I know for a fact that it’s connected. Still haven’t found a solution.

**Comment by Rand0mP3rs0n** [comment]
I am using version 5.1.4. I don’t know if it matters at all, but if it helps I’m using steelhax homebrew.
