### ISSUE TITLE
PKSM v.5.1.4 - Pokemon White / Black 2 Bank Storage and editing does not work

### ISSUE THREAD

**Issue by LAX18** [FlagBrew/PKSM#802]
Unsure if you were aware, or if you are and I have a bad version but I am unable to edit my Pokemon White 2 and White saves as well as transfer those Pokemon to the offline bank. I wish to transfer them to OR without having to pay. Thanks!

**Comment by piepie62** [comment]
That's going to be in the rewrite.

**Comment by LAX18** [comment]
Ah okay. Is the rewrite in the PKSV.cpp branch of this repo or located elsewherr?

**Comment by piepie62** [comment]
It is the PKSM.cpp branch, yes
