### ISSUE TITLE
Always get Red Screen on Startup (5.1.4)

### ISSUE THREAD

**Issue by LavaringX** [FlagBrew/PKSM#808]
I can see that a lot of people have had this problem before, but I am on the newest version and am not sure the previous questions will help me here. I can barely seem to access PKSM at all, I almost always get a red screen on startup when trying to access it via Homebrew > PKSM > Poké Transporter. The only way I can get it to work is by selecting PKSM > Pokémon X, but when I do that I can't load Pokémon Moon without getting an error message about a sizing issue. Homebrew > PKSM > Pokémon Moon was no help. Switching to an earlier version seemed to fix the problem, but when I did that I got the "Failed to Download Assets!" error message for everything. Can somebody help?

**Comment by SpiredMoth** [comment]
When using the hax build of PKSM on 3DS games, you need to select the same game both times (Homebrew > PKSM > Pokémon X > Pokémon X) for it to work

When using the hax build on DS games, you select Transporter the first time, then your DS game (Homebrew > PKSM > Transporter > Diamond)

**Comment by LavaringX** [comment]
That won't help me here. I attempted to start it up with Homebrew > PKSM > Pokémon Moon and it crashed.

**Comment by LavaringX** [comment]
Thank you for the advice, though, that will definitely help me in the future.

**Comment by LavaringX** [comment]
I got the problem fixed, I had to copy the hax folder into 3ds and then run only PKSM.xml. Thanks!
