### ISSUE TITLE
DS games - Pksm

### ISSUE THREAD

**Issue by B2bewild** [FlagBrew/PKSM#813]
So does this mean Pksm can now let me play black1/2 white 1/2 diamond,  Pearl,  soul silver and heart gold??? If so how do I make it work on  pksm please an thank you? 😊

**Comment by piepie62** [comment]
PKSM can't help you play any games. When the rewrite comes out, it'll be possible to edit Gen 4-7 games.

**Comment by B2bewild** [comment]
Whoops sorry  piepie  I mean to help me edit soul silver and heart gold?

**Comment by piepie62** [comment]
Those are Gen 4 games, so yes, once the rewrite is out

**Comment by B2bewild** [comment]
Woohoo.  Just need to reput pksm onto my console so I can do this for soul silver

**Comment by BernardoGiordano** [comment]
Nope

**Comment by B2bewild** [comment]
Awesome thank you Bernardo :)
