### ISSUE TITLE
Feature Request - Set Pokemon as caught and seen in PokeDex when added to game

### ISSUE THREAD

**Issue by deadair3210** [FlagBrew/PKSM#827]
**Is your feature request related to a problem? Please describe.**
It's annoying to add Pokemon from the bank or from being generated, only for them to not be added correctly to the PokeDex.

**Describe the solution you'd like**
Perhaps handle it like pkhex does on PC, when a Pokemon is added, the seen/caught flags as well as gender/specific version if applicable is updated to reflect it. 

**Describe alternatives you've considered**
At least could we get the seen caught flags updated?

**Additional context**

**Comment by FM1337** [comment]
Uh... this feature is already added in 6.0.0

**Comment by deadair3210** [comment]
If it is, then I don't know how to trigger it. Just backed up my Pokemon to
start over, and when I added them to the new save they were not in the Dex,
like I hadn't ever seen them

**Comment by FM1337** [comment]
what game?

**Comment by deadair3210** [comment]
Omega ruby

**Comment by FM1337** [comment]
I'll go test this and post the results.

**Comment by FM1337** [comment]
I generated a bulbasaur, and it got added to the national dex in omega ruby.
I brought over a Poochyena from storage and it added it to both the national desk and the hoenn dex

Not sure what's going on with yours but it's working fine on my end.

**Comment by deadair3210** [comment]
Weird, could it be because I moved them to a save that didn't have the Dex
yet? Or because they weren't native to that save?

**Comment by FM1337** [comment]
I have a very strong feeling it's because you don't have the pokedex yet.

**Comment by deadair3210** [comment]
Even then, there is still something wrong, as doing the exact same thing in
pkhex added them correctly even though I didn't have the Dex yet

**Comment by FM1337** [comment]
...Try getting the pokedex (I assume when you said you didn't have the dex, you mean the actual pokedex and not the national dex) and try again.

**Comment by deadair3210** [comment]
I will later today, but considering other programs can alter the Dex from the first save, I don't think it's a issue with the save

**Comment by deadair3210** [comment]
Just checked a save farther in the game and it indeed adds the Dex entries correctly. Maybe the program isn't setting something correctly in the save if you don't have the dex yet?

**Comment by FM1337** [comment]
It's likely it doesn't set this flag to avoid causing any issues with the game.

**Comment by deadair3210** [comment]
If adding Pokemon without the dex does anything bad, I haven't noticed it. Currently playing all of the games in order, and moving all the caught Pokemon to the next game as I go. Haven't noticed any problems with any of the games

**Comment by FM1337** [comment]
Regardless, the feature already exists and you simply just need to obtain the pokedex before the pokedex flags are registered.

**Comment by deadair3210** [comment]
So I figured out why we couldn't trigger the bug, the first time I added the Pokemon I used the whole box button, not individually.
