### ISSUE TITLE
Bug Report: Loading in French

### ISSUE THREAD

**Issue by SageHax** [FlagBrew/PKSM#828]
PKSM was installed and it loaded up in French.

**Comment by deadair3210** [comment]
Mine loaded up in Japanese, maybe unintialized variable?

**Comment by FM1337** [comment]
Pressing select on the save loading screen (or pressing the settings button after loading the save) will bring up the settings menu, the first page of the menu is the language page, You can set your language there.

**Comment by deadair3210** [comment]
Could it possibly default to the language of the loaded save?

**Comment by FM1337** [comment]
Most likely that, or it was a previous setting from the previous version of PKSM that might've caused it, either way it's an easy fix.

**Comment by BernardoGiordano** [comment]
It's more likely that your console is French and you didn't know

**Comment by SageHax** [comment]
I'll pass it along to them to see if that suggestion about the loading screen is the fix.

**Comment by deadair3210** [comment]
That would be impressive, not noticing an entiely different language lol

**Comment by SageHax** [comment]
The Language fix did help for them. Thanks for the fast replies!
