### ISSUE TITLE
Bug Report: Pokemon Gender being incorrectly set during transfer

### ISSUE THREAD

**Issue by Yushiroh** [FlagBrew/PKSM#833]
So I was amused when I updated my PKSM and I started to transfer my Pokemon 6th gen game AS (Gardevoir female) it worked perfectly in my Pokemon Moon, but when I started to transfer it on my pokemon black cartridge, it started to gender bend my pokemon to a male, I tried the pokemon editor but as I save it as a female the game recognizes the pokemon as a male, I hope this could be fixed in future updates

**Comment by piepie62** [comment]
So, what is the issue you are reporting?

**Comment by Admiral-Fish** [comment]
Please upload a before and after of the pkm file. If you don't want to upload them publicly then join the FlagBrew Discord and you can send them to use privately.

**Comment by piepie62** [comment]
As there has been no response, I'm closing this issue. It should be fixed with latest commits, anyway, if I understand the issue correctly.
