### ISSUE TITLE
Bug Report - Storage crash

### ISSUE THREAD

**Issue by Geistica** [FlagBrew/PKSM#835]
The software crashes after I go to the storage

1. Go the saved file of the pk game
2. Click on 'storage'
3. Game crashes

Idk maybe the storage?

 - OS version: 11.9.0
 - PKSM version: 6.0.0
 - Entrypoint: 1.01.2019

**Additional context**
When I go to the pokemon center of ultra moon and I heal the cheated pokemons the game decides to show a bulbasur instead of the right pokemon idk if the editor is the same as the storage anyways. The stats of the cheated pokemon are also not equal to the lvl so it would be nice to add that too.
Other than that sry for not making multiple bug reports.

**Comment by BernardoGiordano** [comment]
can you send your storage file?

**Comment by Geistica** [comment]
Excuse me to ask but where is that saved?

**Comment by piepie62** [comment]
Question: did you rename a storage box?

**Comment by BernardoGiordano** [comment]
Please export your PKSM save file with Checkpoint @Geistica 

you only sent the backup

**Comment by Geistica** [comment]
> Question: did you rename a storage box?

nope

**Comment by Geistica** [comment]
[0xEC100 PKSM.zip](https://github.com/FlagBrew/PKSM/files/2724669/0xEC100.PKSM.zip)

**Comment by RealmOfIce** [comment]
Making a new game file and opening it on there first worked but,  Depends on if you want to start over

**Comment by BernardoGiordano** [comment]
@Geistica found your issue. You renamed your language boxes/changed your language probably, because the json containing the boxes name is fucked up. This issue has been sorted out in a recent commit already, so I'll close this issue leaving you a new json file with which you'll be able to open your storage in the meanwhile

**Comment by BernardoGiordano** [comment]
Replace your `pksm_1.json` file in the backup you sent to me with this one: https://www.dropbox.com/s/tbw4j239immzm8m/pksm_1.json?dl=0

then restore said backup and PKSM will magically restart working again in the storage

**Comment by Geistica** [comment]
I'm sorry to tell you but it still crashes

**Comment by BernardoGiordano** [comment]
Can you backup your extdata again and send them back?
