### ISSUE TITLE
Bug Report: Pokedex Flags for bulk storage is not working... ¿Again?

### ISSUE THREAD

**Issue by Pokefanmati** [FlagBrew/PKSM#837]
Same as describes here: https://github.com/FlagBrew/PKSM/issues/569. I left a message there, but the theread is closed and i'm not sure how that works.
When transfering pokemon ussing the buttom to transferer a whole box, these don't flag in the Pokedex; I tried twice.

 - OS version: 11.9.0; Luma 9.1
 - PKSM version: 6.0.0

**Comment by piepie62** [comment]
Fixed in the latest commit

**Comment by deadair3210** [comment]
Knew I wasn't crazy lol
