### ISSUE TITLE
Bug Report: Wondercard injection for Generation 4 not working correctly

### ISSUE THREAD

**Issue by FM1337** [FlagBrew/PKSM#838]
**Describe the bug**
Attempting to inject a wondercard into my Pokemon Diamond save file appears to work, but the wondercard doesn't get stored and on some occasions gives me a bad egg.

**To Reproduce**
1. Load Pokemon Diamond save in PKSM
2. Go to events screen
3. Select event to inject
4. Inject event
5. Save changes
6. Load up game and check mystery gift screen

**Expected behavior**
The wondercard of the newly injected item should be in the list

**Screenshots**
N/A

**Information about your environment**
 - OS version: Latest version (11.9 I believe)
 - PKSM version: 6.0.1
 - Entrypoint: Launching via CIA

**Additional context**
N/A

**Comment by Pokefanmati** [comment]
In the last version, the injector used to fail if the save did'nt have at least one wondercart. Try to put one the ussing PokeHex and then try it ussing PKSM. I worked for me in Ultra Moon

**Comment by FM1337** [comment]
> In the last version, the injector used to fail if the save did'nt have at least one wondercart. Try to put one the ussing PokeHex and then try it ussing PKSM. I worked for me in Ultra Moon

There's already wondercards in my save. It doesn't make a difference

**Comment by piepie62** [comment]
Fixed by 90b3e39
