### ISSUE TITLE
[Just want to confirm] Does the editing function for DS Pokemon games perfectly work in 6.0.0?

### ISSUE THREAD

**Issue by felixlee0530** [FlagBrew/PKSM#839]
Hello, PKSM developer,

I just found that PKSM has been updated to v6.0.0 which you explained that it supports DS games.

1. Does the **box / party editors** work perfectly in v6.0.0 for any Gen 4 / 5 pokemon games?

2. Does PKSM only work in authentic DS carts, not pokemon games in R4 flashcarts?

3. Does the DS editing function work in previous versions?

Reply will be appreciated. Thank you so much for your hard effort!

**Comment by piepie62** [comment]
Yes
Yes
That doesn't make sense, of course 5.1.4 won't work

**Comment by piepie62** [comment]
Furthermore, if you want to ask general questions, join the discord
