### ISSUE TITLE
When I used 6.0.0 on my hombrewed 3ds it just stays on a yellow screen and when I use the one before it works but dosent show the pokemon sprites its good just hard to find the pokemon I want. Hope you fix it. Thanks. Bug Report

### ISSUE THREAD

**Issue by cattothatsnotfatto** [FlagBrew/PKSM#840]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Information about your environment**
 - OS version:
 - PKSM version:
 - Entrypoint:

**Additional context**

**Comment by Pokefanmati** [comment]
You should... give more information. Also I think it only works on CFW 3ds

**Comment by FM1337** [comment]
From the change log

`Support for *hax (also known as just homebrew) has been dropped. PKSM
only works under a Luma3DS environment.
Specifically, PKSM will check for the hb:ldr port, which is available, for
example, through the Rosalina system module.
If you try booting PKSM under *hax, it will return to the homebrew launcher.
This also means PKSM will not work in Citra.`

*hax support is no longer a thing starting with 6.0.0, get CFW on your device.
