### ISSUE TITLE
Feature Request: Group Movement

### ISSUE THREAD

**Issue by Pokefanmati** [FlagBrew/PKSM#844]
It's a request. 
In the main Pokémon series since Pokémon B2W2, we have the option to move a whole Pokémon group from any size. I would like that to be added, it'll make easier to sort Pokémon.

Here, it's the yellow option.
![image](https://user-images.githubusercontent.com/44351218/50614836-e4fff480-0ec0-11e9-8ac1-525c459e0a5e.png)

Thank you for reading.

**Comment by gaiaweylyn** [comment]
I absolutely second this. I use this feature a lot in the main games and also did in Bank.

**Comment by piepie62** [comment]
Added for the next release
