### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by unskilledmagician** [FlagBrew/PKSM#846]
PKSM crashes after opening application. Just updated to 6.0.0, when i launch it it loads up, doesn't show any games, then crashes a few seconds later.

**Comment by Pokefanmati** [comment]
Are you ussing hombrew launcher?

**Comment by unskilledmagician** [comment]
I'm using cfw, but i just read a previous similar bug post and realized that the problem is probably the flashcard i always have in my 3ds.

**Comment by unskilledmagician** [comment]
that was it
