### ISSUE TITLE
No pokemon pics (Sa) and no reading cartridge (Ss)

### ISSUE THREAD

**Issue by Totinos94** [FlagBrew/PKSM#847]
Hello dear !

I followed the instructions to install pksm 5.1.4 reading the Readme.
I run the app with homebrew launcher (steelhax i guess)
I run the app, the storage box manage shows me no pokemon pics, but they are there (sapphire alpha)
I run Silver Soul and it can't find the cartridge or "invalid size" error.
Tried already to restore pksm or re-install; already read Readme. 

I can't understand what is the problem. I attach photos.

Other info: original fw - ver. 11.9.0-42E (nintendo 3ds)

![1](https://user-images.githubusercontent.com/46332598/50618503-7e47fe80-0ef3-11e9-861e-e07a2aa898aa.PNG)

![2](https://user-images.githubusercontent.com/46332598/50618764-40e47080-0ef5-11e9-81d7-2bd5a9fef583.jpg)

![3](https://user-images.githubusercontent.com/46332598/50618800-65404d00-0ef5-11e9-954a-8a3bd4e90c22.jpg)

The last one show you the Sapphire Alpha problem

![4](https://user-images.githubusercontent.com/46332598/50618842-a0db1700-0ef5-11e9-8a96-00b50b3ca1e4.jpg)

![5](https://user-images.githubusercontent.com/46332598/50618862-bb14f500-0ef5-11e9-80a9-cfd70fe29f1d.jpg)

These last two show you the problem with Silver Soul.

Italian version of the game - pksm.
So what wrong ? I'm so dumb ?

**Comment by piepie62** [comment]
Easy fix: don't use 5.1.4

**Comment by Totinos94** [comment]
The point is that i don't want to install cfw.
So i used the 5.1.4 - problem
So i used the 5.1.2 - same identical problem

I know 6.0.0 could be better but  could It be also an homebrew problem ?

Any trusted source for cfw on a old 3ds?

Thanks on advance!

**Comment by piepie62** [comment]
https://3ds.hacks.guide
Have fun
