### ISSUE TITLE
Pokemon X, Y and Sun storage crash

### ISSUE THREAD

**Issue by AshenDragon** [FlagBrew/PKSM#848]
After using PKSM to store three pokemon i was trying to swap to a different game of the same version (Pokemon Y to Pokemon X) after cloning them the clones were put in the bank for an attempted transfer. PKSM loaded fine, Editor amd everything else was avaliable, except for storage, whih immediately brings me to the home screen not long after i try to open storage. Additional notes: Said bank box they were placed in had indeed been renamed, said name included a / not sure if that is crucial. As well, trying to open storage in pokemon Sun also evented in a crash. Same symptoms as above.

**Comment by piepie62** [comment]
Fixed by commit a5c3d03
