### ISSUE TITLE
Bug Report - GenderLess Pokemon Have Gender! PKSM 6.0.0 Specially Mythical And Legendaries Pokemon. And Also Met place and Egg hatch Place in the defaults setting did not work on generated pokemons

### ISSUE THREAD

**Issue by weapons23** [FlagBrew/PKSM#849]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Information about your environment**
 - OS version:
 - PKSM version:
 - Entrypoint:

**Additional context**

**Comment by piepie62** [comment]
First off, you completely ignored the template.
Second, legendary genders set to genderless on generation will not be fixed; it's just too much to keep track of for a very little thing.
Third, and most puzzling to me, the options you mentioned as "not working" _don't exist_

**Comment by weapons23** [comment]
Im editing the bug format cuz theres lack of evidence.
