### ISSUE TITLE
Bug Report - Alt forms

### ISSUE THREAD

**Issue by vampymaria** [FlagBrew/PKSM#851]
**Describe the bug**
Arceus, Genesect, and Xerenas

**To Reproduce**
1. Go to 'Xerenas"
2. Click on 'alt form.'
3. Scroll down to 'see venasaur.'
The other two don't show at all. They should show alts

**Expected behavior**

**Screenshots**

**Information about your environment**
 - OS version: 11.Idek I lost track. 
 - PKSM version: 6.0.0
 - Entrypoint:

**Additional context**
This is for ultra sun btw
![Uploading JPEG_20190103_112342.jpg…]()
.

**Comment by vampymaria** [comment]
![jpeg_20190103_112342](https://user-images.githubusercontent.com/38189579/50651110-62267a80-0f50-11e9-96ef-597f32a06a1d.jpg)

**Comment by BernardoGiordano** [comment]
Fixed via https://github.com/FlagBrew/PKSM/commit/c206b0e42c6be0933214be54c8104ddbadbf86f4
