### ISSUE TITLE
Bug Report - Bank crash with QR Scanner

### ISSUE THREAD

**Issue by ReshibanGaming** [FlagBrew/PKSM#855]
**Describe the bug**
In the Bank with Pokémon W2, using twice L+R make crash of the console (ARM11 error)

!!!Finaly, cannot reproduce the crash, but I publish this issue for help to find this bug!!!

**To Reproduce**
1. Open PKSM 6.0.0 with .cia file
2. Open Pkmn W2 save in the cartridge
3. Open the **__Editor__**, and click on your team (maybe not important)
4. Open QR Scanner "L+R" and press "B" to quit QR Scanner
5. Reopen QR Scanner "L+R" and press "B" to quit
6. Crash :)

**Information about your environment**
 - OS version: 11.9.0-42E
 - PKSM version: 6.0.0
 - Luma3DS 9.1
 - New 2DS XL

**Additional context**
Finally, open QR Scanner with "L+R", push "B" and during that closed QR Scanner, always let pushed "L" and spam "R".

It is not that I did for the first crash, but that make crash the console.

**Comment by BernardoGiordano** [comment]
Can't reproduce
