### ISSUE TITLE
Bug Report - Bug with action in the bank

### ISSUE THREAD

**Issue by ReshibanGaming** [FlagBrew/PKSM#856]
Very simple:

**__Steps__**:
 - Open PKSM on Home menu (.cia application)
 - Go to Pkmn W2 save in the cartridge
 - Open the bank
 - Click on the Orange button in the top right (**^ >**) of the down screen
 - Press "B" to cancel the action
 - **The action is executed**

**__Material__**:
 - PKSM 6.0.0
 - Luma3DS 9.1
 - New 2DS XL 11.9.0-42E

**Comment by BernardoGiordano** [comment]
Of course it is. The B button is needed to return to the previous screen, not to cancel the actions
