### ISSUE TITLE
Editing save files in a flashcart (without a computer)

### ISSUE THREAD

**Issue by felixlee0530** [FlagBrew/PKSM#857]
**Is your feature request related to a problem? Please describe.**

Sometimes, when I played Pokemon games in a flashcart, I struggled to move those pokemon in the save files to a legit cartridge. For example, since Gen 4 games prevented trading between a Korean game and a game with another language, whenever I got a legendary or event pokemon in a korean rom in my flashcart, I had to extract them using PkHEX and then insert them in another save, and then overwrite that save in the official cart.

**Describe the solution you'd like**

Therefore, I'm not sure if it is possible, but it will be better to let PKSM open those save files in my flashcart. It will be really appreciated. Since I need my laptop to transfer those pokemon (using pkhex) it is quite bothering. Also, it is hard for me to get a korean cart for gen 4 since I'm living somewhere else.

**Describe alternatives you've considered**

**Additional context**

**Comment by piepie62** [comment]
It isn't possible.

**Comment by deadair3210** [comment]
Would take paragraphs of code for each specific card even if it was, making it not worth it to impliment
