### ISSUE TITLE
Bug Report - Gen 5 generation bug

### ISSUE THREAD

**Issue by krayziezay** [FlagBrew/PKSM#859]
When using PKSM and Pokemon Black 2 cartridge 
And try to gen scizor lvl 5 I set the moves I wanted I  saved my settings. When I opened B2 and I open my pokemon team the scizor I gen has PKRS which I have set to no and then the game freezes

**Comment by Admiral-Fish** [comment]
Upload your save please

**Comment by piepie62** [comment]
I'm about 96% certain this will be fixed with the next release, if it hasn't already been with 6.0.1. If not, reply and I'll reopen the issue
