### ISSUE TITLE
Feature Request: Hex editor button use 

### ISSUE THREAD

**Issue by CaptainBarnaklez** [FlagBrew/PKSM#860]
I have a suggestion for PKSM.
In the byte editor, you were able to increase or decrease values with the A button and the X button.
Seems it isn't in the current build anymore.
It is convenient to keep it in order to edit bytes without the need of the touch screen (in case this one doesn't work) or just if you slipped one byte while using the touch screen, pressing the A button or the X button is sometimes more comfortable than pulling the stylus again or using your fingers while holding the console.

**Comment by BernardoGiordano** [comment]
Fixed via 59acda4cc3db47e9bc17c63883d68701e938be27
