### ISSUE TITLE
[Feature Request] Save Info menu option

### ISSUE THREAD

**Issue by SpiredMoth** [FlagBrew/PKSM#862]
Basically just a screen that can display various info about the loaded save. In terms of appearance, I was thinking something like the Options menu

**Reason(s)**
- User may want to confirm that they loaded the correct save (like a generically named automatic backup)
- User wants to view info that the game won't show, like Munchlax trees in DPPt
- User wants to view info about the save without having to restore it and load up the game
- Could also be a good spot in the GUI to setup controls for editing some things that don't really have a place already (I'm aware that most/all of these could be left to scripts to edit)

**What to show:**
Some of these are unlikely to be included due to the necessary work. There's probably more that could be shoved in here too
- Trainer info (Name, TID, SID, TSV, Gen 7 ID, etc.)
- RNG seed
- Pokedex status (seen, owned, possibly Regional dex versions of info too?)
- filled WC slot count
- Badges/Stamps?
- Last save location? (route/cave/etc.)
- Game/generation specific info
    - D/P/Pt: Munchlax trees
    - B/W/B2/W2: Entree level(s)
    - OR/AS: Super Secret Base location?

<br>

Been holding this back because I didn't come up with it soon enough before release and wasn't sure I had enough support to justify the work

**Comment by piepie62** [comment]
I've added the trainer info, stamps/badges, wonder cards, national dex stuff, and generation, but is there anything else that anyone watching this wants?
