### ISSUE TITLE
Feature Request: Hex editor lacks the Hyper training byte.

### ISSUE THREAD

**Issue by CaptainBarnaklez** [FlagBrew/PKSM#863]
In the previous PKSM version, hyper training a Pokémon was possible from the Hex Editor.
However it seems it can't be done anymore in the new PKSM.
Edit: Forgot to add that a feature like this is vital to edit any Generation 7 Pokémon.

**Comment by BernardoGiordano** [comment]
Fixed via https://github.com/FlagBrew/PKSM/commit/f4f271a33c502e1cf4e8f469ac7f368debc8ed77
