### ISSUE TITLE
Feature Request: Better Bank Box Handling

### ISSUE THREAD

**Issue by GriffinG1** [FlagBrew/PKSM#864]
Just going through the ideas we had:

- Folders akin to official Bank's handling
- Box selection grid
- Folders in box selection grid

cc @piepie62

**Comment by piepie62** [comment]
Oh, uh, I don't actually know what you mean by official bank's handling. Could I get a screenshot?

**Comment by GriffinG1** [comment]
![image](https://user-images.githubusercontent.com/28538707/50721268-ede7f600-1079-11e9-8fd2-877a7396c122.png)
They call em groups. Number underneath is how many boxes are in it. Can be renamed looks like this in-box:
![image](https://user-images.githubusercontent.com/28538707/50721275-0e17b500-107a-11e9-8dee-0cfa0e592a00.png)

**Comment by pokelector** [comment]
I second this.
It's hard to organize with PKSM's current bank.
This will make it easy to sort my stuff.

How hard would it be to implement?

**Comment by Volti-p** [comment]
That would be a good Feature for the bank. :) Then we can better sorting out our Pokémon! :)

**Comment by piepie62** [comment]
Groups are done, as is a box selection grid
