### ISSUE TITLE
Bug Report - crash when booting PKSM 6.0.0

### ISSUE THREAD

**Issue by crk2005222** [FlagBrew/PKSM#867]
**Describe the bug**
crash when booting PKSM 6.0.0

**Screenshots**
![img_0236](https://user-images.githubusercontent.com/46404896/50728604-845bfc00-10fa-11e9-8594-fcd64b8f8f94.JPG)
![img_0237](https://user-images.githubusercontent.com/46404896/50728605-845bfc00-10fa-11e9-9183-e30c9fb5526d.JPG)

**Information about your environment**
 - OS version: 11.9.0-42J
 - PKSM version: 6.0.0
 - luma version: 9.1

**Comment by BernardoGiordano** [comment]
if you have a flashcart inserted, remove it. this issue has already been addressed and fixed

**Comment by crk2005222** [comment]
removed flashcart, boot PKSM, it just returns to home menu without showing the crash screen.
