### ISSUE TITLE
PKSM 5.1.4 

### ISSUE THREAD

**Issue by magnuzt** [FlagBrew/PKSM#868]
Dear all,

I'm pretty new to home brew. I was installing SteelMiner just now and installing PKSM with 3dsx extension along with the xml file. But when I go to PKSM, it stucked on loading graphics.
I'm using PKSM 5.1.4 since I read somewhere 6.0 doesn't work on homebrew.

Your help and guidance will be appreciated. Thank you.

**Comment by FM1337** [comment]
5.1.4 is dropped and no longer works.
