### ISSUE TITLE
Bug Report - Cannot boot PKSM 6.0.0 (NO FLASHCART)

### ISSUE THREAD

**Issue by crk2005222** [FlagBrew/PKSM#869]
**Describe the bug**
when trying to boot PKSM, it just return to home menu without even showing a crash screen. 

**Information about your environment**
 - OS version: 11.9.0-42J
 - PKSM version: 6.0.0
 - luma version: 9.1
 - NO FLASHCART is inserted

**Additional context**
then, I reinstalled 5.1.4. All Pokemon icons disappeared.
![img_0238](https://user-images.githubusercontent.com/46404896/50729745-0bb26b00-110d-11e9-86c7-a28f1f6fea30.JPG)
![img_0239](https://user-images.githubusercontent.com/46404896/50729746-0bb26b00-110d-11e9-9f7e-928b86954342.JPG)

**Comment by FM1337** [comment]
Try the latest release (6.0.1) and see if this issue still happens.

Also 5.1.4 is no longer supported.

**Comment by crk2005222** [comment]
problem solved in 6.0.1.
