### ISSUE TITLE
Save file issues from SD card

### ISSUE THREAD

**Issue by SuperCodingBear** [FlagBrew/PKSM#871]
OS Version - 11.9.0-42E
PKSM Version - Latest
Entrypoint - Rosalina HBL VIA CFW

I installed the latest update of PKSM a few days ago, and used the save file tool to set up my JSON to point to each of my saves. It worked, my games would show up with the names of the save files when pressing Y for absent games.

However, when I tried to open any of them, I would get error 0xE0E046BE.

Today, I noticed there was an update, so I installed it. I figured I would revisit the absent save function, and to my surprise, PKSM loaded up every save in my folder, and named them savefile.

I could open any savefile. Clubhouse games threw an error (of course), but all of my pokemon saves opened. However, I could open any save under any game, and I knew this would cause problems. 

My attempted solution to this was going and making a new JSON file, to the effect of:

Pokemon Diamond
EUR
/Roms/Saves/D
Pokemon Diamond.sav
And so on for each game. 

The saves now show up under the proper games, but once again, attempting to open them gives me the error 0xE0E046BE.

It's strange, because they were opening before.

My generated Config.JSON is as follows 

{
  "autoBackup": true,
  "defaults": {
    "date": {
      "day": 1,
      "month": 1,
      "year": 2000
    },
    "nationality": 2,
    "ot": "PKSM",
    "pid": 12345,
    "sid": 54321
  },
  "extraSaves": {
    "ADAO": {
      "files": [
        "Pokemon Diamond.sav"
      ],
      "folders": [
        "/Roms/NDS/D"
      ]
    },
    "APAO": {
      "files": [
        "Pokemon Pearl.sav"
      ],
      "folders": [
        "Roms/NDS/P"
      ]
    },
    "CPUO": {
      "files": [
        "Pokemon Platinum.sav"
      ],
      "folders": [
        "/Roms/NDS/PL"
      ]
    },
    "IPKO": {
      "files": [
        "Pokemon Heartgold.sav"
      ],
      "folders": [
        "/Roms/NDS/HG"
      ]
    },
    "IPGO": {
      "files": [
        "Pokemon Soulsilver.sav"
      ],
      "folders": [
        "/Roms/NDS/SS"
      ]
    },
    "IRBO": {
      "files": [
        "Pokemon Black.sav"
      ],
      "folders": [
        "/Roms/NDS/B"
      ]
    },
    "IRAO": {
      "files": [
        "Pokemon White.sav"
      ],
      "folders": [
        "/Roms/NDS/W"
      ]
    },
    "IREO": {
      "files": [
        "Pokemon Black 2.sav"
      ],
      "folders": [
        "/Roms/NDS/B2"
      ]
    },
    "IRDO": {
      "files": [
        "Pokemon White 2.sav"
      ],
      "folders": [
        "/Roms/NDS/W2"
      ]
    }
  },
  "fixBadSectors": true,
  "language": 1,
  "randomMusic": false,
  "storageSize": 2000,
  "transferEdit": true,
  "useExtData": true,
  "useSaveInfo": true,
  "version": 3,
  "writeFileSave": true
}

**Comment by piepie62** [comment]
Your file paths are all wrong. If you want more help than that, join the Discord server https://discord.gg/bGKEyfY
