### ISSUE TITLE
Bug Report - PKSM Returns to home menu on boot

### ISSUE THREAD

**Issue by NeoUmbreon** [FlagBrew/PKSM#873]
**Describe the bug**
Opening the app shows the homebrew logo for a few seconds, then returns to home screen. 

**To Reproduce**
1. Open PKSM
2. Returns to home menu

**Expected behavior**
PKSM opens

**Information about your environment**
 - OS version: 11.9.0-42U
 - PKSM version: 6.0.1
 - Entrypoint: Luma3ds CFW

**Additional context**
I am connected to the internet.
This has only become an issue upon updating from 6.0.0 to 6.0.1.
I thought this was due to a flashcart being inserted, although this was said to have been fixed in 6.0.1, but the same results occur without it inserted.

**Comment by BernardoGiordano** [comment]
Backup the PKSM extdata archive with Checkpoint, then remove the config.json file and restore it

**Comment by NeoUmbreon** [comment]
I have done what you suggested, but nothing has changed.

**Comment by BernardoGiordano** [comment]
Can you tell me your Checkpoint version?

**Comment by NeoUmbreon** [comment]
The latest, 3.6.0

**Comment by BernardoGiordano** [comment]
can you backup your PKSM extdata with checkpoint another time and send them here?

**Comment by NeoUmbreon** [comment]
I closed the issue because what you told me to do on discord solved it
