### ISSUE TITLE
Bug Report - Bag Item Search does not respect search results

### ISSUE THREAD

**Issue by deadair3210** [FlagBrew/PKSM#875]
**Describe the bug**
When adding something to the bag, at least in Omega Ruby, while search does work, instead of inserting the selected item, it selects what would be in that spot had the user not searched for anything

**To Reproduce**
1. Go to Bag
2. Search for something
3. Scroll to 3rd item
4. Select it, only to have the 3rd item in the global list added instead of the searched item

**Expected behavior**
The item listed to be added correctly

**Screenshots**

**Information about your environment**
 - OS version:11.9
 - PKSM version:6.0.1
 - Entrypoint:CIA

**Additional context**

**Comment by piepie62** [comment]
Fixed in latest commit
