### ISSUE TITLE
Bug Report - When i generate a pokemon it crashes for white 2 and Black 2 

### ISSUE THREAD

**Issue by Andrew755** [FlagBrew/PKSM#876]
![img_0229](https://user-images.githubusercontent.com/34986149/50742868-23095b00-11d6-11e9-8bda-f96db855a1b1.jpg) this is on version 6.0.1

**Comment by Andrew755** [comment]
[Crash_Dump.zip](https://github.com/FlagBrew/PKSM/files/2738315/Crash_Dump.zip)

**Comment by FM1337** [comment]
please post your save file

**Comment by Andrew755** [comment]
[crash_dump_00000153 (2).zip](https://github.com/FlagBrew/PKSM/files/2754631/crash_dump_00000153.2.zip)

**Comment by Andrew755** [comment]
[Black 2 & White 2.zip](https://github.com/FlagBrew/PKSM/files/2754703/Black.2.White.2.zip)

**Comment by FM1337** [comment]
Saves appear to be valid when testing with PKHex, I'll verify what happens when loading them in PKSM on my end when I get home.

**Comment by Andrew755** [comment]
sounds good

**Comment by Andrew755** [comment]
It's only when I create a pokemon it crashes

**Comment by piepie62** [comment]
Has been fixed in recent commits
