### ISSUE TITLE
Thank you 

### ISSUE THREAD

**Issue by B2bewild** [FlagBrew/PKSM#877]
Thank you to all the amazing creators for enabling us to use pksm for gen 4 games.  I really appreciate it a lot,  it's helped me with my soul silver as I got stuck a lot without a lot of money or potions as I kept running out lol.  You guys are absolutely amazing.  Thank you thank you thank you a million times over. also thank you for also answering problems and help fix it  when you guys can.  

I know this isn't an issue.  I just thought it would be awesome to give the creator and helpers an appreciation post for being amazing.

**Comment by FM1337** [comment]
While we appreciate the thank you, please make sure to only post bugs/feature requests on the issues page on the repo.

If you'd like to say thank you in the future, please do so on the discord server found [here](https://discord.gg/bGKEyfY)

We do have a patreon available if you'd like to donate you can find it [here](https://patreon.com/FlagBrew)
