### ISSUE TITLE
Bug Report - L/R doesn't work to switch between wondercards with the same ID

### ISSUE THREAD

**Issue by BernardoGiordano** [FlagBrew/PKSM#878]

**Comment by piepie62** [comment]
As in different languages? Or the ones that have the same ID but different data?

**Comment by BernardoGiordano** [comment]
Same ID, check it with the thousands hat pikachu for SM

**Comment by piepie62** [comment]
I'm guessing this also has to do with your changes to the Wonder Card packing system? I had designed it to keep even the ones with the same ID

**Comment by BernardoGiordano** [comment]
nope, I made sure to test that out in the stable too, that's why I'm submitting the issue ~~totally not for remembering about it~~

**Comment by piepie62** [comment]
Um, the Pikachus I believe you re looking at seem to have different IDs to me

**Comment by piepie62** [comment]
It seems that I forgot to put a form check in the Wonder Card packing for Gen 6/7. Instead of switching between cards on L/R, I designed it to have every available type of Wonder Card there, with the ones that inject the same thing grouped.

**Comment by piepie62** [comment]
Fixed with changing the Wonder Card packing system
