### ISSUE TITLE
Feature Request - Event Filters

### ISSUE THREAD

**Issue by GriffinG1** [FlagBrew/PKSM#881]
Currently the event list is extremely long. It's a pain to find what you want to inject unless you know the wondercard number. If possible, being able to split the events up by language would be nice. It'd certainly make finding what you need quicker. Possibly done via a set of tabs on the bottom screen?

**Comment by piepie62** [comment]
Hmm... the main problem with that is that they kind of are already. The events that show in a different language are events that are available but do not have the currently selected PKSM language available. This actually sounds like it would be more of a "filter" than a "sort", which I suppose could be considered

**Comment by GriffinG1** [comment]
Fair point, filter would probably be more accurate. I'll update the title

**Comment by piepie62** [comment]
Filter by language has been added
