### ISSUE TITLE
Bug Report - (HGSS) PKSM Editor Does Not Reflect Gender Editing

### ISSUE THREAD

**Issue by itsmikerofl** [FlagBrew/PKSM#886]
**Describe the bug**
When editing Pokemon Gender, PKSM will reflect the change across reboot, but the change is not reflected in-game.

**To Reproduce**
1. Go to 'Editor'
2. Click on any Pokemon
3. Adjust Pokemon Gender
4. Click 'Save'
5. Return to PKSM Main Menu
6. Save changes
7. Boot into game
8. Check edited Pokemon
9. Edited Gender does not reflect
10. To confirm, enter PKSM
11. Go to 'Editor'
12. Check edited Pokemon in PKSM Editor
13. Edited Pokemon has the Gender set by PKSM
14. Experience discrepancy

**Expected behavior**
Editing Pokemon Gender in PKSM will reflect upon booting game.

**Screenshots**
N/A

**Information about your environment**
 - OS version: 11.9.0-42U
 - PKSM version: 6.0.1
 - Entrypoint: Unsure

**Additional context**
Rebooting the console in between using PKSM and booting the game has no effect.

**Comment by piepie62** [comment]
Fixed in latest commit
