### ISSUE TITLE
Bug Report - Can't use any Z-moves

### ISSUE THREAD

**Issue by ad33zy** [FlagBrew/PKSM#887]
**Describe the bug**
I am not able to use any z power moves.  It says: There is no usable move: when I click Z-power on the left.  Even when having the right moves and item, I can not select any moves

**To Reproduce**
I created pokemon using PKSM, and then gave them a moveset, and then gave them the Z crystal on teh bag screen

**Expected behavior**
I should be able to use the corresponding Z move

**Information about your environment**
 - OS version:11.8
 - PKSM version: 6.01
 - Entrypoint: in battle

**Additional context**
I was about 1/8th through the game and was adding pokemon

**Comment by piepie62** [comment]
There are two Z-Crystal items. One is meant for bag use, and the other is meant for giving to Pokémon. Are you absolutely certain you used the right one?

**Comment by ad33zy** [comment]
> There are two Z-Crystal items. One is meant for bag use, and the other is meant for giving to Pokémon. Are you absolutely certain you used the right one?

I did, I am able to see it when I choose moves, its on the left for Z-Moves, but the moment I use it, it says : There is no usable move.

**Comment by gommoso88** [comment]
BEFORE try this, make a backup of your save with checkpoint in your console
try to restore backup.
Connect your sd to pc, open folder 3DS, open folder PKSM, open folder BACKUPS and open the folder
0x01b51 (this is in my case, i've pokemon ultra moon europe). In this folder there are all backups of your game, order the folders in "last modification" for see the date when you not have this issue , before you mod your save, pksm make a backup.
Try to remember when the issue appeared and open the folder with the date you have chosen.
ES: 0x01b51 -> 2019011809185 -> main
Ok, you need the file "main". Copy this file and go in folder 3DS, open folder CHECKPONT, open the folder SAVES. Search the game (es. 0x01B51 Pokémon Ultra Moon), open the folder, create a new folder and in this new folder paste the file "main"
( In CHECKPOINT there is a folder named "extdata" in this folder there are other saves, but i no know if you have save of pokemon in this folder or not, in my case, i have the save of pokemon ultra moon in folder SAVES. )
OK, start your console, open CHECKPOINT and choose your version of pokemon, now you see two "save", the first done before starting this guide, and the second done "now". The second is called as the folder you created in PC. Restore this, open your game and try to see if the issue has been solved.

p.s. For see the id of your game, in your PC, go in SD -> 3DS -> CHECKPOINT -> SAVES. In this folder there are all your game (id <name of game>).
If you have done progress after the issue, you lose your progress, but you solve the issue.

I hope it helps you, in my case it helped.
p.s.s. i'm italian and sorry if a no write right.

**Comment by KOS-MOSv3** [comment]
Hi so I had this exact issue, it seems to be connected to the mega unlock script. Once I went back to before running that it was resolved.

**Comment by Gudf** [comment]
Whoops, I may have done something wrong if that's the case. I'll check again.

**Comment by KOS-MOSv3** [comment]
Could it be that theres a script glitching use of it before its legally obtained? Weirdly, I was able to select to use a z move but it just lost connection to any moves on all pokemon, using the z crystals from the bag not from pksm.

**Comment by Gudf** [comment]
Maybe. Can't say for sure though.

**Comment by KOS-MOSv3** [comment]
Well no worries, I restored my save and got the one right before I unlocked it. Hopefully its an easy fix, thanks for the work yall do I love this app

**Comment by Gudf** [comment]
Yeah it should be pretty easy, although I'll need to use a C script, which I've never done before, so it will take a bit longer than just changing a value.

**Comment by Gudf** [comment]
Alright, try with the script in this .zip. It should go in the correct location by simply unzipping it at the root of your SD card.
[Mega_evolution_toggle_script.zip](https://github.com/FlagBrew/PKSM/files/2849281/Mega_evolution_toggle_script.zip)

**Comment by KOS-MOSv3** [comment]
That didnt work, it brought the issue back. I ran the script, gave Lopunny a mega stone, went into battle and she could evolve but when I went to Incineroar the Incinium Z opens but doesnt work with Darkest Lariat and says no moves available.

**Comment by KOS-MOSv3** [comment]
Do you want my save to work with?

**Comment by SpiredMoth** [comment]
I can think of three reasons why Z-moves aren't working for you:
1. you're (unintentionally) giving your Pokémon the bag versions of the Z-Crystals -- try giving the Z-Crystal to the Pokémon in-game
2. our documentation mixed up the Z-move and Mega Evolution flags
3. there's an undocumented flag somewhere else in the save that the game uses to determine if the Z-move(s) can be used

**Comment by KOS-MOSv3** [comment]
I think its #3. I didnt edit z crystals in, only loppunite. I'm near po town so the only item i modded in was a mega stone and I think theres only 1 for those. I tried giving the z crystals again yesterday when it first occured and that didnt help. It could be 2 but @Gudf gave me another script and that didnt help either. Because of that, I really think its #3 but I don't know a lot about coding and such so I appreciate the help.

**Comment by KOS-MOSv3** [comment]
Feel free to test with my save all you guys want, it seems to be the mega script bc i had no issues until i used that around the 8th or 9th

**Comment by KOS-MOSv3** [comment]
Also that save is the one right before I ran the script.

**Comment by Gudf** [comment]
Are you sure you tried the right script? You should access it by pressing x then y in the scripts menu.

**Comment by KOS-MOSv3** [comment]
So I added the script you commented with before and just opened pksm, when I press x in the script menu it says /3ds/pksm/scripts/usum not found. but on the scripts page with the path romfs:/scripts/usum has a bunch. When I press y for universal, it only has 4. dppt trophy, pkx injector, save language, and vivillon. And when I tried before I just used the scripts page's mega evolution script at the bottom.

**Comment by piepie62** [comment]
Try Y then X

**Comment by KOS-MOSv3** [comment]
That worked! Sorry for the hassle, thank you

**Comment by ad33zy** [comment]
@KOS-MOSv3 I did the mega unlock thing as well, what should I do?

**Comment by gommoso88** [comment]
BEFORE try this, make a backup of your save with checkpoint in your console
try to restore backup.
Connect your sd to pc, open folder 3DS, open folder PKSM, open folder BACKUPS and open the folder
0x01b51 (this is in my case, i've pokemon ultra moon europe). In this folder there are all backups of your game, order the folders in "last modification" for see the date when you not have this issue , before you mod your save, pksm make a backup.
Try to remember when the issue appeared and open the folder with the date you have chosen.
ES: 0x01b51 -> 2019011809185 -> main
Ok, you need the file "main". Copy this file and go in folder 3DS, open folder CHECKPONT, open the folder SAVES. Search the game (es. 0x01B51 Pokémon Ultra Moon), open the folder, create a new folder and in this new folder paste the file "main"
( In CHECKPOINT there is a folder named "extdata" in this folder there are other saves, but i no know if you have save of pokemon in this folder or not, in my case, i have the save of pokemon ultra moon in folder SAVES. )
OK, start your console, open CHECKPOINT and choose your version of pokemon, now you see two "save", the first done before starting this guide, and the second done "now". The second is called as the folder you created in PC. Restore this, open your game and try to see if the issue has been solved.

p.s. For see the id of your game, in your PC, go in SD -> 3DS -> CHECKPOINT -> SAVES. In this folder there are all your game (id -name of game-).
If you have done progress after the issue, you lose your progress, but you solve the issue.

I hope it helps you, in my case it helped.
p.s.s. i'm italian and sorry if a no write right.

**Comment by ad33zy** [comment]
Thanks @gommoso88 but I think @KOS-MOSv3 found a way to solve it without losing progress

**Comment by Gudf** [comment]
No, KOS-MOSv3 solved it by retoring a backup from before using the script, which is exactly what gommoso88 described.
The only way I see to fix this without losing progress would be to open both saves (the one before and the one you have now) in a hex editor and copy the value at adress 0x1478 from the save before using the script to the save after using the script. Then you'd need to open the modified save either in PKSM or PKHeX (For example to use the fixed script) before injecting it back, or the game will say it's corrupted.Finally, inject it back into your game, and it should be fixed.
