### ISSUE TITLE
Bug Report - PKSM does not run after injecting extrasaves into JSON

### ISSUE THREAD

**Issue by chrayfish** [FlagBrew/PKSM#889]
When using Checkpoint to inject an edited JSON into PKSM to use extrasaves, I am no longer able to launch PKSM. The black screen with 'Homebrew' white text appears and then it reverts back to the 3ds home screen.

I have edited the JSON file in Visual Studio to ensure line breaks are preserved. The extra saves segment is as below:
```
  "extraSaves": {
    "IREO": {
      "files": [
        "/roms/nds/Pokemon Black 2.sav"
      ],
      "folders": [
      ] 
    }  
},
```
The sav file does exist at that directory on my micro SD card and the ROM header has been checked and is definitely IREO.

PKSM version: 6.0.1

I can revert to my original JSON via check point and PKSM will load again but I just cannot seem to get the extrasaves function to work.

**Comment by FM1337** [comment]
When you injected the config.json, what version of checkpoint did you use?

**Comment by chrayfish** [comment]
> When you injected the config.json, what version of checkpoint did you use?

Checkpoint 3.0.0

**Comment by FM1337** [comment]
You need to inject using 3.6.0
