### ISSUE TITLE
Gen 4 and 5

### ISSUE THREAD

**Issue by zener88** [FlagBrew/PKSM#892]
Hi, I am using PKSM, I have Sapphire Alpha anda X installed and everything works fine, but when I try to load any gen 4 or 5 game it doesn't show up in the app. I have the games on my sd and I play them with Twilight Menu, I also have Pokémon Radar installed but I don't know how to use it for PKSM to recognize the saves.

**Comment by piepie62** [comment]
Look at the wiki
