### ISSUE TITLE
bug happiness

### ISSUE THREAD

**Issue by paf2014** [FlagBrew/PKSM#893]
In last update I found the following bugs:
when you catch a pokemon that evolve for max happinees in x/ y for instance,edit it with pksm to have max happiness,store it in pksm bank and transfer it to another game(or/as) and level up it so as that it should evolve,the pokemon does not evolve.(I verified this with woobat and chingling but this happens with all pokemons that evolve for max happiness).If after you store it in pksm bank you put the pokemon back in the same game you caught the pokemon the evolution works fine.
the same happened with buneary from or/as.if you edit it to have max happiness,store it in pksm bank and after that transfer it to or it evolves after leveled up,if it is put in pokemn x/y no.
the other bug is about eevee: if you take one in x/y,store it,transfer it to us/um and make all things that are needed to evolve it into sylveon,the evolution fails after eevee is leveled up.if before leveling it up you save your game,store eevee in pksm bank and bring it back to the game you caught it,the evolution works fine.
sorry with has already been reported.

**Comment by SpiredMoth** [comment]
The happiness thing is actually how the games work: when a Pokémon is traded to another game, it's happiness is reset to the base value for its species. Transferring through storage affects Pokémon the same as trading -- the friendship value is reset to the base value for the species.

As for evolving Eevee to Sylveon, I'm not as familiar with Gen 7 mechanics so I'm not sure if Amie affection is kept during migration. If it's not kept, then it's the same situation as friendship which I explained above. If it is kept, that sounds it might be like a bug in the transfer logic relating to Amie/Refresh affection.

**Comment by piepie62** [comment]
Affection is OT/HT specific, as well, yes

**Comment by paf2014** [comment]
there are bugs in happiness and about eevee. As I said above if you take a pokemon that evolve through max happiness in a game put in a bank of pksm and transfer to different game and after that edit the happiness of it to 255,the pokemon does not evolve while leveled up.
the same to eevee:if you take it,in a gen 6 game, put in a bank of pksm transfer to us/um,use a rainbow bean on it(is enough to give it two heart of affection) and it knows a fairy move.it will not evolve while leveled up.
the pokemon just evolve if you put it back from bank in the same game you caught it.

**Comment by piepie62** [comment]
Do you have "Edit During Transfers" set to "Yes"?

**Comment by paf2014** [comment]
was set to no.when I set it to yes both problems were solved.thanks for informations

**Comment by piepie62** [comment]
Yeah, without Edit During Transfers on, it doesn't update the Pokémon to think that you are the current trainer.
