### ISSUE TITLE
restoring nds sav

### ISSUE THREAD

**Issue by paf2014** [FlagBrew/PKSM#895]
how could I restore a nds sav back file that is created when I open this type of game in pksm?or even read them?in tittle screen i only have access to sav game files.even how could I restore my bank file?

**Comment by deadair3210** [comment]
Use checkpoint to restore the saves, don't think there is a way to restore them from pksm, it just takes a backup to make sure you have one. Pretty sure the bank is held in the exdata of pksm, so you would need a backup of that, and to restore it with checkpoint as well

**Comment by piepie62** [comment]
Deadair3210 is correct, you have to use Checkpoint to restore the saves. Bank is stored in extdata, though the backup is in `/3ds/PKSM/banks/pksm_1.bnk.bak` and the name backup is `/3ds/PKSM/banks/pksm_1.json.bak`, and you would restore those by copying them over a PKSM ExtData backup's `banks/pksm_1.bnk` and `banks/pksm_1.json`, respectively
