### ISSUE TITLE
Bug Report -  Error 5.1.4 (resources)

### ISSUE THREAD

**Issue by daniel95000** [FlagBrew/PKSM#898]
I have a problem that I can not properly download the image resources in version 5.1.4 (I use this version because of the impossibility of being able to install 6.0.0 and 6.0.1), the pokemon in the bank appear transparent and are not displayed (I do not know what else is affected by this).

I would like to be able to use this app because I need to transfer my Pokémon from Version X to Ultra Moon.... since I really hate to lose all my pokemon (I have everyone trapped and I have no money due to the situation of my country so I can not buy the pokemon bank of Nintendo)

I'm sorry for my bad English I speak Spanish and I come from Venezuela

Note: If there is nothing to do I would like to please give me an alternative to transfer it. This tool already worked perfectly in the past in the old versions and it did not occur to me to update it until now if I bought USUM ... if it were not because I thought I could update to version 6.0.1 (later I realized that I needed CWF thing that will not install: s) I would not be asking you to please help me :(

Note 2:I own a 3ds old version 11.4.0-35U and use oothax or soundhax to access the Homebrew Channel

**Comment by piepie62** [comment]
5.1.4 is no longer supported. You can upgrade to CFW using any method listed on https://3ds.hacks.guide/

**Comment by daniel95000** [comment]
> 5.1.4 ya no es compatible Puede actualizar a CFW utilizando cualquiera de los métodos enumerados en https://3ds.hacks.guide/

Excuse me but ... I do not have the ability to install CWF ... could not they make the resources available to people who need it from that version please? :c

**Comment by piepie62** [comment]
You do have the ability, there is a free method there

**Comment by piepie62** [comment]
The resources were made unavailable because there is no reason to not upgrade to CFW now

**Comment by daniel95000** [comment]
> You do have the ability, there is a free method there

Which method? I do not have any R4 and I do not have the ability to disarm my 3ds ...


> The resources were made unavailable because there is no reason to not upgrade to CFW now

I do not try to bother anyone but what is the main reason for not keeping the old versions of PKSM? :s

Oh why is it no longer about helping these people who simply do not have the capability for the CWF installation methods? :C

**Comment by piepie62** [comment]
Because you can. FrogMiner is the method to use

**Comment by daniel95000** [comment]
> Because you can. FrogMiner is the method to use

you want to say that I should update my 3ds? The last update is 11.9.0-42 ..... it will work?
