### ISSUE TITLE
Bug Report - Brief Description/Name of issue

### ISSUE THREAD

**Issue by RubberDuck55** [FlagBrew/PKSM#899]
Qr code is not working

Go to Editor
Click L + R
Wait for it to find my QR code
Nothing Happens
Expected behavior
Scan the QR code and load the pokemon

Entrypoint: Cia
System version: latest

**Comment by piepie62** [comment]
Trust me, I know that the QR scanner is finnicky, but it _does_ work. I tested it myself.

**Comment by BernardoGiordano** [comment]
Make sure you're trying to scan QR codes generated via latest PKHeX, as well.
