### ISSUE TITLE
Stat/Shape Markings on Transfer Gen 6-7

### ISSUE THREAD

**Issue by UnderdarkFox** [FlagBrew/PKSM#901]
Tested from Gen 6 AS to Gen 7 UM. Transferring a Pokemon with no stat/shape markings results in no issues, but transferring with stat markings filled cause them to become unchangeable. First three, Circle Triangle Square, become pink in summary, and cannot be changed in game. Hex editor also does nothing for the markings.

It's quite strange.

Transferring effected Pokemon back allows markings to be edited and corrected with no noticeable changes. Hex editor also shows properly for Gen 6, but Gen 7 has no effect (I assume due to the black/pink/blank options)

**Comment by piepie62** [comment]
Turns out the Gen 7 markings are in a different spot. Should be fixed with the latest commit
