### ISSUE TITLE
Music

### ISSUE THREAD

**Issue by bleeding4** [FlagBrew/PKSM#903]
How do you add music to the PKSM application?

**Comment by SpiredMoth** [comment]
From [PKSM's changelog](https://github.com/FlagBrew/PKSM/wiki/Changelog):

+ **PKSM now supports audio playback**. Audio will start once boot is completed.
  + There actually is no way to stop the audio playback, so turn down the volume
    in case it starts getting annoying.
  + It's possible to provide your own audio soundtracks by placing `.mp3`
    files in the `sdmc:/3ds/PKSM/songs` folder.
  + It's suggested to provide relatively small sized files. We generally suggest tracks
    with a length of no more than 4 minutes, single channel, with a sampling
    frequency of 44100Hz and a bitrate of 96kbps.
    + These characteristics are not actual constraints: you can throw whatever
      you want into the SD card and PKSM will mostly be able to work with it fine.
    + You can convert a track to get these characteristics through
      [ffmpeg](https://stackoverflow.com/questions/3255674/convert-audio-files-to-mp3-using-ffmpeg).
