### ISSUE TITLE
Korean fonts crash in every kind of menu inside PKSM

### ISSUE THREAD

**Issue by felixlee0530** [FlagBrew/PKSM#906]
Whenever I go into a menu in PKSM (such as settings, event page, etc..) Korean fonts crash and they show question marks on the letters. Other languages such as English and Japanese work fine, of course.

Do I have to install an extra language pack or something to display the Korean font properly?

**Comment by piepie62** [comment]
That's just a limitation of the way text display works right now. It's being discussed with the writer of Citro2D, the graphics library that PKSM uses

**Comment by felixlee0530** [comment]
I'm just having some trouble picking some wonder cards in Korean letters since they're all in question marks, which is quite confusing. Do you expect a solution for this in the future?

**Comment by piepie62** [comment]
No promises, but I think that it's getting somewhere
