### ISSUE TITLE
Issues on Homebrew

### ISSUE THREAD

**Issue by CyrilEpic** [FlagBrew/PKSM#908]
Hi! First of all I want to thank you for making this  app to enhance the pokémon experience!!!! Great work to you all and keep it up :D

Though I have one slight problem; I don’t seem to be able to get PKSM to work on my homebrewed 2ds. When trying to put PKSM in homebrew: I download the .3dsx for PKSM 6.00 (the latest I think) then put it in the 3ds folder (the usual stuff) but then a few things occur.

1- Downloding assets 1-8 doesn’t work.
2- When it asks me to restart the application, so I press the « a »button but then it shows a frozen red sceen and I have to hard reset my 2ds.

I tried everything I could possibly think of and can’t make it seem to work :/ would you be able to assist me?

Thank you in advance for your solutions!

**Comment by BernardoGiordano** [comment]
Hi,

as stated in the very first page of the [documentation](https://github.com/FlagBrew/PKSM/wiki/Getting-Started), PKSM can't run without CFW.

Also, the issue you're describing makes me think you're not even trying to boot PKSM 6.0.1 (which is  the latest as we speak), but something like a couple years old release.
