### ISSUE TITLE
Feature Request: Cache data

### ISSUE THREAD

**Issue by FM1337** [FlagBrew/PKSM#911]
**Is your feature request related to a problem? Please describe.**
Loading times are long

**Describe the solution you'd like**
Cache some data like saves to increase loading time and then have a button to refresh the cache if the user needs to refresh it.
**Describe alternatives you've considered**
Deleting all games and just having one to make loading fast, but I like having my games.

**Additional context**
@piepie62 also hates the slow loading times.

**Comment by piepie62** [comment]
Thinking about this, the loading times actually aren't related to the game loading; the game loading happens as quickly as you see it happen on the screen. All of the loading time has to be spent loading, for example, the spritesheets
