### ISSUE TITLE
Delete Pokémon From Party

### ISSUE THREAD

**Issue by 197ShinyUmbreon** [FlagBrew/PKSM#912]
I understand that injecting party Pokemon directly has unintended consequences, but not being able to delete a bugged Pokemon at all from your party (tested in Pokemon White) is quite frustrating and requires backup from saves. 
It's odd you're allowed to add to party but not delete.
The only way to release a Pokemon is through the Storage option, which doesn't show you the party.

**Comment by piepie62** [comment]
A fix is already in place. It'll be done with 6.0.2
