### ISSUE TITLE
Bug Report - Additional Assets needs

### ISSUE THREAD

**Issue by RolmanIronman** [FlagBrew/PKSM#914]
**Describe the bug**
I Install the version 6.0.1 And the execute the PKSM only apper a bug and Exit "Additional assets..."

**Expected behavior**
In the forum says to copy the files by hand, but What files? I can not find a RAR or ZIP with the files, I look for copy and test and it still does not work, many broken and old links.

**Comment by Mike007899** [comment]
Is your wifi turned on? If not, turn it on and try again. If yes, are you using CFW or steelhax aka *hax? If the latter, aka *hax, please slide over to the Discord server and I shall help you.

**Comment by RolmanIronman** [comment]
Its totaly my fault, the wifi is malfunction. I rest the modem and now download the arhives, so sorry.
