### ISSUE TITLE
Gender issue when generating from the editor

### ISSUE THREAD

**Issue by CloudOfMist** [FlagBrew/PKSM#916]
When i generate a legendary pokemon on PKSM 6.1.0 (for example Mew) it has gender!!

**Comment by TLATER** [comment]
This is a duplicate of #849, see why this happens there.

Please search through the closed issues before creating an issue.

**Comment by CloudOfMist** [comment]
I will. Thank you kind sir!


Στις Κυρ, 10 Φεβ 2019 - 15:53 ο χρήστης Tristan Maat <
notifications@github.com> έγραψε:
