### ISSUE TITLE
Question about PKSM 6.1.0

### ISSUE THREAD

**Issue by kuai18** [FlagBrew/PKSM#917]
Hello,

I have only one question, does PKSM 6.1.0 support old version Luma3DS (for A9/B9 v1.0, which don't support Rosalina) if compiled with Citra compatibility option?
If yes, where to download Citra compatibility version, or I need to compile it by myself?

Thanks a ton!!

**Comment by TLATER** [comment]
If you're looking for support, the discord server is usually more appropriate:

https://discord.gg/bGKEyfY

**Comment by BernardoGiordano** [comment]
Probably, yes. It hasn't been tested.

And, yeah, you need to compile it by yourself.
