### ISSUE TITLE
[Feature Request] BRSTM/BCSTM Support

### ISSUE THREAD

**Issue by trainboy2019** [FlagBrew/PKSM#924]
**Is your feature request related to a problem? Please describe.**
PKSM currently supports MP3 for music, but not common looping audio files, like BRSTM or BCSTM.

**Describe the solution you'd like**
Support to play BRSTM/BCSTM files

**Describe alternatives you've considered**
None, really

**Additional context**
I know there has been an app in the past that could play BCSTM files, however, that app was written in cpp3ds, and it was broken in a later update.

**Comment by piepie62** [comment]
I thought that those were 3DS-specific formats? And PKSM automatically loops the song, so I don't see why this would be an issue. Could you clarify why that would be an improvement over having a single song looped?

**Comment by trainboy2019** [comment]
BCSTM is commonly used for the 3DS, and BRSTM is common for certain wii games. By looping I mean support for loop points to loop songs seamlessly.

**Comment by BernardoGiordano** [comment]
I think this is out of scope, mp3 is more diffused and is enough for PKSM to take care of
