### ISSUE TITLE
Wonder cards not appearing in Ultra Sun

### ISSUE THREAD

**Issue by joshbgosh10592** [FlagBrew/PKSM#928]
**Describe the bug**
Injecting Wonder card not actually appearing in Ultra Sun.

**To Reproduce**
Attempt to inject a Wondercard event, no errors in PKSM.
Launch the game but notice no prompt for Mystery gift, and no Delivery man at the Pokemon center.
Relaunching PKSM shows the same Wondercard listings as attempted in step 1.

Ran "Clear Myster Gift data.pksm", launched game, moved a few feet, and saved. Loaded PKSM again and injected a known acceptable wonder card (Marshadow), still nothing in game.

**Expected behavior**
Wondercard be correctly injected and acceptable in game from the Delivery Man.

**Information about your environment**
 - OS version: 11.8 (USA) New3DS XL
 - PKSM version: 6.1.0-c903055
 - Entrypoint: Luma (.CIA)

**Additional context**
Also to note, I am unable to dump Wonder Cards in PKSM by pressing X.
Injecting items into the bag succeeds. I'm also unable to view any Pokemon from inside PKSM.
Date is currently set to today's date, Feb, 21st, 2019 in PKSM

**Comment by BernardoGiordano** [comment]
are you sure you saved your changes? Test with v6.1.1.

**Comment by piepie62** [comment]
@joshbgosh10592 Any update on this issue?

**Comment by joshbgosh10592** [comment]
Sorry, I've been away on travel and left my CFW'd 3DS at home...
I have a theory. I've modified the crap out of this game save and I'm wondering if I just need to reset it. I'll try to do that tonight and return back.

**Comment by joshbgosh10592** [comment]
That did it. I guess I just messed up my save so much that weird things were going on. Fun thing, I even tried to open the game again and it said that my save was corrupt, so that backs up my thought.
Sorry, good to mark this as closed - game save was FUBAR'd.

**Comment by piepie62** [comment]
Alright, then. If it pops up again under less strange conditions, feel free to open another issue.
