### ISSUE TITLE
Nicknames aren't fully working

### ISSUE THREAD

**Issue by uhhhidknicole** [FlagBrew/PKSM#930]
On newest release, 6.1.0. Nickname setting seems to be bugged. PKHex shows they're illegal because the nickname checkbox isn't marked. Tested with 3 Pokémon, one that was traded to me and two that were mine (under my OT), all illegal and needed the nickname box checked. Is this a PKSM issue or a PKHex issue?

**Comment by uhhhidknicole** [comment]
Sorry, *6.1.0

**Comment by piepie62** [comment]
Mmm, I'll look into that

**Comment by BernardoGiordano** [comment]
Please test with v6.1.1.

**Comment by uhhhidknicole** [comment]
Seems to be working fine on 6.1.1! Thanks for fixing it :D
