### ISSUE TITLE
Red screen on startup, before selecting a game (6.11)

### ISSUE THREAD

**Issue by Xingbairon** [FlagBrew/PKSM#937]
during pksm startup from homebrew using steelhax, the bottom screen is stuck on red before any inputs are allowed to be entered.  

**To Reproduce**
launch homebrew via steehax,
select pksm from the homebrew menu 

I have never reached the restart pksm screen since i've never been able to launch pksm properly, and always crash at the red screen stage, freezing it, and have to power off my 3ds to restore function.

**Comment by BernardoGiordano** [comment]
From the wiki:

> Attention: launching via *hax entrypoints is not supported due to technical limitations.
