### ISSUE TITLE
Bug Report - 2 small bug

### ISSUE THREAD

**Issue by kuai18** [FlagBrew/PKSM#939]
**Describe the bug**
1. Press L\R button can't  switch multiple WonderCard in WC inject screen.
2. Chinese Nickname of Pokemon can't be displayed in PKSM, it all shows '???'. (But Chinese Species of Pokemon can be showed in PKSM correctly)

**Information about your environment**
 - OS version: 11.9.0
 - PKSM version: 6.1.1

**Comment by piepie62** [comment]
The L/R button works to switch between multiple items in a single Wonder Card. There should be no need for the multiple Wonder Card switching that there was before. As for the Chinese characters, that's a problem with the 3DS system font not being able to display them, though it's being worked on.
