### ISSUE TITLE
PKSM transfer issue pt.2 

### ISSUE THREAD

**Issue by pokelector** [FlagBrew/PKSM#941]
What happened:

Had a Zorua on File A **who I was the OT of.** it had friendship 120. Transferred to File B, friendship was reset to CT/OT 0/120 as expected.
Transferred back to File A, and the Zorua was still friendship 0 as if I wasnt the OT. It shouldve gone back to 120/120 since it was back to the OT. As a result, I was not recognized as Zorua's OT even though I was.

All I have to do is tap 'take ownership'. 

This happened with an Igglybuff that I was not the OT of. The bug happened, causing me to not be the Handling current Trainer, so it wouldnt evolve. The current handling trainer was still the previous trainer.

Please fix it so transferring the way I described updates HT as opposed to leaving it behind. This is frustrating because ny Pokemon arent transferring right, so they could be illegal...

**Comment by Admiral-Fish** [comment]
Is this related to #940 or no?

**Comment by piepie62** [comment]
To which game did you transfer?
Also, friendship being lower than normal is not a legality issue; I'm 99% certain it's perfectly possible to lower friendship
