### ISSUE TITLE
Bug Report - Multi-selector

### ISSUE THREAD

**Issue by pokelector** [FlagBrew/PKSM#944]
When "Edit during transfers" is active, normally a Pokemon when transferred is edited to act as though it was traded.

When you use multi-select to move a batch of Pokémon from bank to your game, only the first Pokemon will be edited to act as though it was traded. 

Here's an example!

I had a Sandshrew, Togepi, Pikachu, Rattata, Raichu, and Vulpix in my Bank. All of these were transferred from File A, where they were bred from. When I use multi-select to move them from PKSM Bank to my File B, only the Sandshrew is edited to reflect that File B is now the new Handling Trainer (the thing I noticed was friendship being reset to 0 as expected) The Togepi, Pikachu, Rattata, Raichu, and Vulpix still had friendship 120 as if they were still in File A and never transferred.

It appears that the new multi-select feature makes it so only the first Pokémon in the batch gets edited on transfer. 

This caused undesirable glitch, friendship evolution not working. Using the box swap (Bank->PC mass swap) fixes the issue.

**Comment by piepie62** [comment]
Fixed
