### ISSUE TITLE
Implementation Request for PKSM - Friendship

### ISSUE THREAD

**Issue by pokelector** [FlagBrew/PKSM#946]
~~more friendship hooray~~

I'd like to see this in PKSM's edit during transfers feature.

If transferred to ot OT: Revert CT Friendship to whatever the OT Friendship is currently set as.

If transferred to non-OT (aka any save file that ISN'T OT) : Reset the CT Friendship to base value (such as 35 for Shuppet, 70 for Mimikyu, 0 for Buneary, 100 for Croagunk, etc.) and leave the OT Friendship alone.

For example:
Pidgey (On OT file) : CT/OT 120/120
Pidgey (On any Non-OT file) : CT/OT 70/120
Buneary (Transferred back to OT file) : CT/OT 120/120

I tested it like this:
I had a Decidueye on a **non**-OT file. It had CT/OT 123/120
I Link Traded it to a different **non**-OT file. It had CT/OT 70/120.
I Link Traded back to the first **non**-OT file. It had CT/OT 70/20.
I Link Traded it back to the **OT** file. It had CT/OT 120/120.

This shows that Link Trade resets to base always, unless it goes to the OT. Since PKSM transfer is meant to emulate Link Trading, I would like to see this implemented. This would lend itself to a more realistic transfer experience

*This is for all Generations of games. The friendship resets in PokeBank too when transferring between gens.*

Summary:
Friendship resets to base when Link Trading between games, unless you're trading it back to the OT in which case it goes back to whatever the OT friendship was. See above examples!
It ALWAYS resets to base when transferring between Gens in PokeBank.

**Comment by Admiral-Fish** [comment]
This should be handled by #957. Feel free to test and tell me if I forgot anything
