### ISSUE TITLE
My ditto was replaced by a bad egg in the daycare after cloning pokemons in platinum

### ISSUE THREAD

**Issue by pikachuk** [FlagBrew/PKSM#949]
**Describe the bug**
My ditto was replaced by a bad egg in the pokemon daycare after cloning pokemons from my platinum version to the 3ds storage to transfert them to future gens (I wanted to breed a pokemon so I went to the daycare and I saw that instead of my ditto, the woman gave me a bad egg even though I didn't even modify anything about my ditto and I didn't hack anything in the game)

**To Reproduce**
I haven't been able to reproduce the issue a second time as I didn't figure out what caused it exactly

**Expected behavior**
The pokemon in the daycare should stay the same

**Screenshots**
![IMG_0006](https://user-images.githubusercontent.com/16335601/54554350-82dd6880-49b4-11e9-9fae-32904b6c5672.JPG)

**Information about your environment**
 - OS version:  11.9.0-42E
 - PKSM version: 6.1.1
 - Entrypoint: CIA ? if that's what you mean

**Additional context**
My ditto was a traded ditto with someone from an other country, so I was using this ditto to do the masuda trick in order to increase my chances to get a shiny
moreover, since I downloaded PKSM, I only cloned a zubat and my legit shiny giratina (obtained through soft resetting) to the local storage to then transfer them to my black version first, then omega ruby then moon (I wanted to be sure it went through the whole process2 gen by gen)

My platinum version is French if it changes anything

**Comment by pikachuk** [comment]
![2019-03-18_19-38-36 065_top](https://user-images.githubusercontent.com/16335601/54554867-cdabb000-49b5-11e9-8576-244a0641a632.jpg)
PKSM seems to still recognize my ditto though

**Comment by piepie62** [comment]
Hmmm... I'll look into that. Could you send your save and the automatic backup that should have been made?

**Comment by pikachuk** [comment]
[CPUF.zip](https://github.com/FlagBrew/PKSM/files/2979861/CPUF.zip)
that's the automatic backup directory, I'm not sending the save mostly because I tried after that to change the OT to my OT only to see if it at least fixed the pokemon but it didn't work

**Comment by pikachuk** [comment]
after restoring my first saved backup, I can see that my ditto was still intact on the first save, I'll test all of them to see exactly which was the save where it became a bad egg to help you see what exactly changed

**Comment by pikachuk** [comment]
[BAD SAVE.zip](https://github.com/FlagBrew/PKSM/files/2979965/BAD.SAVE.zip)
this zip contains the last good save and the first bad save, it will allow you to compare both to see what changed

**Comment by piepie62** [comment]
I'm 99 percent sure that I know what the problem is, and a fix should be coming soon. Thanks for your cooperation

**Comment by pikachuk** [comment]
I'm glad my problem will at least allow to prevent other people from losing important pokemons

**Comment by piepie62** [comment]
For now, if you want to avoid this, I'd recommend not having Pokémon in the day care while using PKSM. The next release will have fixed it.

**Comment by pikachuk** [comment]
Ok, thanks
