### ISSUE TITLE
OT legality issue

### ISSUE THREAD

**Issue by uhhhidknicole** [FlagBrew/PKSM#951]
Checked in PKhex, Pokémon that I have transferred using PKSM from gen 6 to gen 7 leave the "Latest (not OT) Handler" field blank, and marks the Pokémon as illegal.

PKHex alert message: "Invalid: Current handler cannot be past gen OT for transferred specimen".

Putting my trainer's name in the OT field, moving the Pokémon into the PC, and then checking legality again makes it legal.

Tested by transferring
Pokémon X > Pokémon Ultra Moon
Pokémon Y > Pokémon Ultra Moon
Pokémon Omega Ruby > Pokémon Ultra Moon

Not sure if this is an issue with PKSM or with PKhex, though I did try this with the same results on the two newest versions of PKHex

**Comment by piepie62** [comment]
Should be fixed in the next version
