### ISSUE TITLE
Bug Report - Yellow Screen when load PKSM

### ISSUE THREAD

**Issue by chaosfreak93** [FlagBrew/PKSM#952]
**Describe the bug**
When i try to load PKSM with HomeBrew it crash with a Yellow Screen.
(It hangs on)

**To Reproduce**
1. Start HomeBrew
2. Try to start PKSM
3. You will see a Yellow Screen

**Information about your environment**
 - OS version: OLD 11.9.0-42E
 - PKSM version: 6.1.1
 - Entrypoint: HomeBrew

**Comment by Volti-p** [comment]
You Need a CFW, to use PKSM.

**Comment by chaosfreak93** [comment]
Readme.md:
This software works on CFW and Rosalina-based Homebrew Launchers.

**Comment by Volti-p** [comment]
Rosalina is the CFW based HB Launcher.

**Comment by chaosfreak93** [comment]
I use a Rosalina-based Homebrew Launchers 

[HomeBrew](https://github.com/fincs/new-hbmenu)

**Comment by Volti-p** [comment]
If you have an Rosalina-based Homebrew Launcher, you wouldn't get an Yellow Screen. You have an *hax based Homebrew Launcher and that is not supported anymore. Upgrade to an CFW to use PKSM.

**Comment by piepie62** [comment]
Volti-p is correct. You must have CFW for PKSM to work. https://3ds.hacks.guide will get you started.
