### ISSUE TITLE
Make game and storage save together

### ISSUE THREAD

**Issue by UserWest** [FlagBrew/PKSM#958]
It would be cool to see an option to have your game data save whenever storage data saves, too often do I accidentally not save game data after having saved storage data and accidentally delete or duplicate pokemon as a result.

**Comment by piepie62** [comment]
PKSM is specifically designed to save the storage separately from the save, to allow both easy multiple duplication (which, I admit, with one of the latest commits is an obsolete reason) and to mirror being able to save or discard changes to the main save. With the storage group feature that's coming soon, you will be able to sort of emulate this, but the main way it's done will stay the same.
