### ISSUE TITLE
Ampharos everywhere

### ISSUE THREAD

**Issue by valkyire** [FlagBrew/PKSM#959]
**Describe the bug**
Suddenly every single sprite is an ampharos. So my boxes and storages are now all ampharos. Im unsure when exactly it happened but sometime today

**To Reproduce**
1. Press Y on the home page to see absent games. All the sprite icons there are ampharos. 
2. Load any game in PKSM and go into storage, everything is an ampharos. Clicking on one would show the correct data but the sprite is still ampharos. If I run the actual game there isnt an issue with the sprites at all. 

**Expected behavior**
I havent even seen or caught an ampharos yet, it shouldnt appear everywhere lol

**Screenshots**
added

![1554047887518](https://user-images.githubusercontent.com/26110140/55291413-e2cd0980-53cd-11e9-8468-5d3c5e5b95a7.jpg)
![1554047995129](https://user-images.githubusercontent.com/26110140/55291442-20319700-53ce-11e9-9401-15c8e333e88a.jpg)
![1554048051357](https://user-images.githubusercontent.com/26110140/55291456-3dfefc00-53ce-11e9-897f-6e9c996c03fd.jpg)

**Information about your environment**
 - OS version: 11.9.0 42E
 - PKSM version: 6.2.1
 - Entrypoint:?? 

**Additional context**

**Comment by BernardoGiordano** [comment]
PKSM automatically checks for non-optimal Pokémon and automatically converts them to a superior one. You've been lucky and yours is Ampharos

**Comment by valkyire** [comment]
I wish they were all missingnos though. But say i want to be inferior, how do i go about reverting to my non-optimal pokemans?

**Comment by BernardoGiordano** [comment]
They may recover at some point. It only needs a high power of will...

**Comment by ericjwg** [comment]
april fools haha. i just realize it.

**Comment by fennectech** [comment]
i dont know what your talking about.  Its  clearly an absol

**Comment by scaler85** [comment]
I have same problem, but all spirits are eevees

**Comment by scaler85** [comment]
Pls help fix
