### ISSUE TITLE
Gen V wondercards having problem with dates?

### ISSUE THREAD

**Issue by arisniko1** [FlagBrew/PKSM#961]
So aside from the Ampharos sprite EVERYWHERE thing that I noticed you already know I am trying to inject wondercards in my W2 and while I change the PKSM settings to show the actual event date eg 3/15/2013 when I go to the actual game wondercard album in the game it shows as 3/15/  13 with two spaces in front of 13 instead of 20 and then when I get the Pokemon from the deliveryman the date in the pokemon's summary says 3/15/2061?!?!?!
The thing is i want to transfer these through transporter and into Pokemon Bank as I dif the gen VI pokemon and i doubt 2061 in the date will be taken as legit. Not to mention that I dont want having to watch it. 
Please guys do something! Thanksss!
 
**To Reproduce**
As stated above.

**Expected behavior**
My shiny Dialga with correct received date and wonder card exaclty as if I would receive it back in 2013. And like I did with many Pokemon in AS already which are perfect eg Volcanion in AS.
Maybe there is only something to be fixed in BWB2W2?? 

Also: the Ampharos is everywhere. Whichever game I play. 

**Screenshots**

**Information about your environment**
 - OS version:
 - PKSM version: 6.2.1
 - Entrypoint:

**Additional context**

**Comment by kwsch** [comment]
`13 - 2000 = F83D`, clamped to 8bit = `3D`. 0x3D = 61, which +2000 is 2061.
Looks like there's a +/- 2000 issue :)

**Comment by GriffinG1** [comment]
Hey just for future notice, you don't need to close your issue (#960) and a new issue if you improperly named yours. Just click "Edit" right next to "New Issue" at the top right. when you have the issue open.

**Comment by arisniko1** [comment]
Oh ok. I tried the edit thing and it wouldnt let me edit the title lol.
Anyway how does it help, what you wrote? I didnt get it hahaha.
Pokemon hacking for dummies please.

Φιλικά
Νικολόπουλος Α.

Στις Δευ, 1 Απρ 2019, 08:45 ο χρήστης Griffin <notifications@github.com>
έγραψε:

**Comment by RPGFAN128** [comment]
In real life 13 - 2000 = -1987.  But in hexadecimal -1987 ends in F83D.  If you have an eight-bit number it can store a possible 256 values.  Hence "clamping to 8 bit" is meaning we only get a value between 0 and 255 even if the number is larger.  (or smaller...)  In hex it is easy since you just chop off the last two hex values which are 3D.  In math speak you would take the value F83D mod 100 in hex ( or more recognizable for non-programmers, 63549 mod 256 ) which would give you the values 3D (or 61 in decimal).  

This idea may require more math classes and/or more programming classes.

**Comment by arisniko1** [comment]
Ok I think I get it. And now for the important part. Can any of you awesome
people fix it? :D

Φιλικά
Νικολόπουλος Α.

Στις Δευ, 1 Απρ 2019, 17:28 ο χρήστης RPGFAN128 <notifications@github.com>
έγραψε:

**Comment by piepie62** [comment]
Hello! Can I ask what your default date settings are?

**Comment by arisniko1** [comment]
I change the default date in pksm so that it shows like i took the event in the time it was released (2013)

**Comment by piepie62** [comment]
Alrighty, I'll look into it

**Comment by piepie62** [comment]
If this is broken in the next release, feel free to reopen
