### ISSUE TITLE
Yellow Screen Upon Booting PKSM

### ISSUE THREAD

**Issue by GamingFox72** [FlagBrew/PKSM#962]
When I attempt to load PKSM from the Homebrew Launcher, It gives me a yellow screen while trying to load PKSM. I think it is a bug because I've tried loading it for the 
past 3 days but I still get the same result.

What I thought was going to happen was it would boot into PKSM and save assets then tell me to choose a game etc.

**Information about your environment**
 - OS version: 11.9.0-42U
 - PKSM version: 6.2.1 (Latest)
 - Entrypoint: Homebrew Launcher

Please Help Me A.S.A.P. as I'm currently planning to do a giveaway with my GF.

**Comment by Volti-p** [comment]
You can't use PKSM without CFW. Homebrew alone is not enough.
