### ISSUE TITLE
[Feature Request] Sort storage boxes by Pokemon ID Number or Name

### ISSUE THREAD

**Issue by nsuchy** [FlagBrew/PKSM#963]
**Is your feature request related to a problem? Please describe.**
My storage boxes are kind of a mess and sorting by hand would take hours. I'd like an easy toggle to sort the box by Pokemon Name or ID Number (ideally the change would persist on disk)

**Describe the solution you'd like**
An easy button to click to sort the boxes. To be clear this would be sorting all Pokemon across all boxes, not limited to sorting a single box.

**Describe alternatives you've considered**
Taking the time to sort by hand.

**Additional context**
N/A

**Comment by piepie62** [comment]
Already possible. Hit start
