### ISSUE TITLE
Feature Request: Ampharos Theme

### ISSUE THREAD

**Issue by FM1337** [FlagBrew/PKSM#964]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
An Ampharos theme for PKSM, something that uses the Ampharos's colors and also maybe have it featured on some screens

**Describe alternatives you've considered**
a Giratina theme

**Additional context**
Ampharos isn't appreciated enough and honestly needs to be more appreciated, and I think if we add an Ampharos theme to PKSM, it will bring the fact more attention that Ampharos is one of the best Pokemon in general.

**Comment by deadmanbomber** [comment]
I honestly would see this as an option, but instead, we can make our own themes and import them VIA at code or something.

**Comment by FM1337** [comment]
On second thought, this is a stupid idea and I'm fairly certain I was either drunk or half-asleep when I suggested it.
