### ISSUE TITLE
Please Help me create Zeraora

### ISSUE THREAD

**Issue by daniel95000** [FlagBrew/PKSM#966]
Hello you will see that they no longer support 5.1.4 but I just want to ask for help to create this Zeraora
 
https://projectpokemon.org/home/files/file/2938-fula-city-zeraora/

is the last pokemon that I need to complete for my dex and it is impossible for me to get it.

I just want the steps that I should follow to create it as it comes out there ...

What I do not understand is how to change the SID and the TID to the ones that are in that Zeraora ... where they are changed (in the symbol that appears in the upper right corner) but I do not understand that part very well...

What exact values should I put so that the Zeora that is created automatically is equal to the Zeraora that comes out on that page that I place?

**Comment by BernardoGiordano** [comment]
Check the Discord server for troubleshooting.

**Comment by piepie62** [comment]
As you said, 5.1.4 is unsupported
