### ISSUE TITLE
Red Screen Freeze 6.2.1

### ISSUE THREAD

**Issue by P1Phoenix** [FlagBrew/PKSM#967]
Hello, just writing to aks for help about the 6.2.1 pksm update. I have been trying to update from an older version to the latest but every time i try to start it up it gets stuck on a red screen. Thank you for all you PKSM tools and Thank you for the help.

**Comment by piepie62** [comment]
*SIGH* https://github.com/FlagBrew/PKSM/wiki/Getting-Started Read this

**Comment by P1Phoenix** [comment]
Sorry for the annoyance I’m just confused because I don’t have CFW and I’m using an older version of PKSM so could help just get one that works with ultra moon

**Comment by piepie62** [comment]
Sure. Get CFW.

**Comment by P1Phoenix** [comment]
So I need cfw ?

**Comment by piepie62** [comment]
Yes

**Comment by P1Phoenix** [comment]
Ok thank you for the clarification
