### ISSUE TITLE
Feature Request - Show Typing in Editor

### ISSUE THREAD

**Issue by DJayCubbz** [FlagBrew/PKSM#968]
So I’m not sure if I’m blind, but I haven’t ever been able to find the typing of Pokémon in the editors in all the time I’ve used this. 

If it hasn’t been suggested already I would love to see this is the summary. I know the typings of most Pokémon but not all of them, so it’s be helpful, especially to those who aren’t well versed in the typings of each mon. 

I am aware that you can see the typings outside of the editor, but it would be significantly more helpful if we could see them while genning. 

Thanks for everything you do, this is a really dope application.

**Comment by piepie62** [comment]
That should be possible, though I'm not sure exactly where to put it graphics-wise. Any suggestions?

**Comment by DJayCubbz** [comment]
Hey thanks for replying!!

A few options I think could work are:

- Perhaps in place of hidden power typing on top screen?

- Or even putting it next to the Pokemon's name on either the top or bottom
summary screens. This would of course be the menu where the initial editing
options are pulled up (level, nature, etc).

- You could even put it in place of pokerus on the top summary screen and
just put an icon for pokerus next to the shiny indicator.

Any of these I think could be viable, I like the latter two more than the
first one, since they seem more aesthetically pleasing.

**Comment by piepie62** [comment]
I've been examining the spacing, and I think the Pokérus icon is the best idea. However, I don't know what it should look like, and I can't design worth shit. If you are able to join the Discord server, we could discuss that, if you're any good at graphics. If not, I can see what I can get

**Comment by piepie62** [comment]
The main issue is that the icon needs to be clearly for Pokérus in all the languages PKSM supports

**Comment by DJayCubbz** [comment]
I will join the discord. Its been a while since I've done graphic design,
but I can try whipping up a few icons in illustrator and showing them to
you.

**Comment by DJayCubbz** [comment]
I’ve joined the discord under the same name.

**Comment by DJayCubbz** [comment]
Whenever you see this, if you could message me on discord (I’m not sure which user is yours on there.)

**Comment by piepie62** [comment]
Done in commits :) Will be merged with the next version
