### ISSUE TITLE
Feature Request: Edit saves from DSIMenu++/TwilightMenu/TWLoader/SRloader

### ISSUE THREAD

**Issue by nsuchy** [FlagBrew/PKSM#970]
**Is your feature request related to a problem? Please describe.**
I want an easy way to edit saves from DSIMenu++/TwilightMenu/TWLoader/SRloader.

**Describe the solution you'd like**
PKSM to automatically detect the saves and allow me to edit them.

**Describe alternatives you've considered**
Exporting saves and copying over with the file renames.

**Additional context**
N/A

**Comment by SpiredMoth** [comment]
This already exists and is documented in the wiki: https://github.com/FlagBrew/PKSM/wiki/Configuration#extra-saves
