### ISSUE TITLE
Crash each time i launch pokemon X after editing the save

### ISSUE THREAD

**Issue by Mimi4Craft** [FlagBrew/PKSM#971]
Each time i try to launch my game i have a "An exeption occurred"

The only thing i've done is sending gen IV (pokémon diamond french version) pokémons to gen VI (pokémon X europe) then the game won't boot anymore (was working fine before, and i also try to remove the imported pokémons without succes)

I've made a dump of the crash and of my savefile 

I'm using PKSM 6.2.1 cia version

Edit : After reinstalling the game it seems to be working again but didn't test PKSM yet might have been my mistake because i haven't got the national dex and try to mess with different gens pokemons

[main.zip](https://github.com/FlagBrew/PKSM/files/3077511/main.zip)
[crash_dump_00000000.zip](https://github.com/FlagBrew/PKSM/files/3077515/crash_dump_00000000.zip)

**Comment by piepie62** [comment]
If you experience it again, make another issue. Closing
