### ISSUE TITLE
Cannot mass clone Pokémon into extra storage

### ISSUE THREAD

**Issue by deadmanbomber** [FlagBrew/PKSM#974]
Steps to see issue:
1) go to storage option
2) enable multi selector (the green arrow)
3) if you press clone, it clones the Pokémon that the cursor is hovering over ONLY

I just wanted to put these in storage quickly, just so I can randomize every Pokémon I have in my PC box, but I can't do it as fast as I hoped and would have to clone a single Pokémon one by one.

I expected the game to duplicate the entire selection.

**Comment by piepie62** [comment]
A) PKSM is not the game. B) This has been fixed in commits and will be included in the next release

**Comment by victorf8** [comment]
This is still the issue

**Comment by piepie62** [comment]
Reopening to match new method of dealing with issues
