### ISSUE TITLE
Cannot inject other gifts on Pokémon Ultra Moon

### ISSUE THREAD

**Issue by axcolleen** [FlagBrew/PKSM#975]
I can inject other gifts like the three main starters, Pikachus, berries, and some legendaries and ultra beasts, but I can’t inject the rest of the z stones and the rest of the legendaries. I’ve edited the date defaults but it didn’t work. 

Thank you for checking my issue.

**Comment by piepie62** [comment]
A) Are you saving your changes?
B) "It didn't work" is far too unspecific to be in any way helpful

**Comment by axcolleen** [comment]
I am saving my changes. There’s an update. I can only claim one gift at a time. But for other gifts I can claim 36 for the first time.

**Comment by piepie62** [comment]
Are you injecting into the correct slot with overwrite wondercards set to true?

**Comment by axcolleen** [comment]
You are right, I didn’t thought of setting the override card to true. It is working now. Thank you so much!
