### ISSUE TITLE
Bug Report - Storage - Transfer causing game to crash while scrolling Pokedex

### ISSUE THREAD

**Issue by teelolws** [FlagBrew/PKSM#977]
**Describe the bug**
Pokemon Pearl - While scrolling the Pokedex, the game will freeze after a few page scrolls. Its always when hitting Sandslash while scrolling down, or Chansey if its on Regional mode. This is after using PKSM to transfer a bunch of Pokemon from HeartGold.

Setups I have tried:
I tried it on two different consoles, ruling out it being a console issue. 3DS and a DL Lite.
I tried transferring the save to a completely different cartridge of the game, but its still happening. So the problem is with the save file.
I tried ripping the .nds and save and running them on an emulator, and interestingly, the bug doesn't happen when running on an emulator. So something screwy is happening that the emulator corrects?
I tried restoring the save backup and the bug went away.

**To Reproduce**
1. Go to Pokedex
3. Scroll down a few times
4. Game freezes

**Information about your environment**
 - OS version: 3DS with CFW, and an unmodded DS Lite
 - PKSM version: 6.2.1
 - Entrypoint: 

**Additional context**
Attaching the original save and the save after injection

[pksm backup.zip](https://github.com/FlagBrew/PKSM/files/3098897/pksm.backup.zip)

**Comment by piepie62** [comment]
The emulator fixing the problem seems like a problem in the emulator's accuracy. I'm guessing this is something to do with seen flags not being set with caught flags set, or improper caught flags set. I'll look into it

**Comment by teelolws** [comment]
Built your latest nightly, seems to be fixed now. I wasn't able to test the original setup (HG to Pearl) though, only Pearl to Platinum.
