### ISSUE TITLE
Bug Report - Storage Settings Set to 0 Boxes

### ISSUE THREAD

**Issue by TheeAnonymousOne** [FlagBrew/PKSM#978]
Description:
There will be loads of boxes filled with poorly generated and broken Pokémon. Browsing through these boxes will eventually resort into an entire system crash very shortly.

Steps to reproduce:
1. Go to Settings, then Misc.
2. Set Storage size to 0
3. Exit and go to Storage

Expected:
I would have expected a menu to say "Cannot generate 0 Boxes" or "No available boxes in Storage" or something along those lines.

Screenshot:
https://i.imgur.com/9LdsV2z.png

OS version: 11.9.0-42U
PKSM version: 6.1.1
Entrypoint: Installed CIA

**Comment by piepie62** [comment]
Will be fixed in the next version already
