### ISSUE TITLE
Feature Request: Support for forwarded NDS Pokémon games in the 3DS

### ISSUE THREAD

**Issue by axcolleen** [FlagBrew/PKSM#979]
There’s NDS Pokémon games installed in the 3DS via CIA, and PKSM doesn’t detect them. I was wondering if there will be a support for them? Thank you so much for reading.

**Comment by piepie62** [comment]
If they're on a flashcart, that's impossible without a monumental amount of work and years of troubleshooting. If they're run through TWiLightMenu++, then read the [wiki](https://github.com/FlagBrew/PKSM/wiki)

**Comment by axcolleen** [comment]
They’re not on a flashcart, they’re installed in the 3DS.

**Comment by piepie62** [comment]
The actual ROMs are not installed as a CIA, you installed a forwarder which either runs the ROMs that are on a flashcart or uses TWiLightMenu++

**Comment by axcolleen** [comment]
Okay, just to understand properly, a game from the home screen of the 3DS without opening TWiLightMenu++ is using TWiLightMenu++? The 3DS isn’t using the flashcart. This is what I’m using: https://gbatemp.net/threads/nds-forwarder-cias-for-your-home-menu.426174/

**Comment by Volti-p** [comment]
They should work with the extra saves Thing, because they use NDS-Bootstrap and NDS-Bootstrap is the Thing, that runs the Games, so it should work. The save Location is the same as TWiLightMenu++ uses.

**Comment by axcolleen** [comment]
Oh I see. Thanks Volti-p and piepie62!
