### ISSUE TITLE
QR CODE Don't Work

### ISSUE THREAD

**Issue by Saintsetsuna** [FlagBrew/PKSM#980]
When i try to read a qr code from Pokemon Platinum in PKHex, nothing happens, simply return to the editor screen

**Comment by piepie62** [comment]
What QR code are you trying to read? If it's a non-G4 QR code, then yeah, it won't work

**Comment by piepie62** [comment]
24 hour warning: if you do not reply, this issue will be considered dead and will be closed.

**Comment by FM1337** [comment]
8 hour warning: if you do not reply, this issue will be considered dead and will be closed.

**Comment by FM1337** [comment]
@Saintsetsuna Since you did not respond in time, this issue is now closed.
