### ISSUE TITLE
LGPE Events Gallery Support

### ISSUE THREAD

**Issue by kamronbatman** [FlagBrew/PKSM#982]
Recently I added the wondercards for LGPE (Under Gen 7). PKSM should add support for packing them.

**Comment by piepie62** [comment]
Yeah, I just haven't figured out a good way to handle them yet. Every other generation of Wonder Cards have language data, and that's how PKSM is set up to read them. It's going to take some sort of special case, but I'm not sure exactly how I want it to look

**Comment by kamronbatman** [comment]
<img width="619" alt="Screen Shot 2019-04-24 at 10 24 10 AM" src="https://user-images.githubusercontent.com/3953314/56679998-289e8a00-667b-11e9-9d80-baf37ce8636a.png">
Attached is the MewTwo wondercard for LGPE.

Offset 0xEE starts the OTNames. It is a fixed array of 9 elements (26 bytes each). All 00's indicates Trainer's Name.
Offset 0x1D8 starts the language tags. It is a fixed array of 9 elements (1 byte each). 0 indicates language tag matches the redemption game.
Offset 0x1E1 starts the game languages. It is a fixed array of 9 elements (1 byte each). This (we believe) indicates the game language.

The game seems to look up the index of the game language in array 3 and uses the same index to get OTName/Language tag.

Attached is the Chansey (Note that it is broken) with the forced-japan language tags:
<img width="617" alt="Screen Shot 2019-04-24 at 10 27 13 AM" src="https://user-images.githubusercontent.com/3953314/56680450-21c44700-667c-11e9-8154-05fd885921b0.png">

**Comment by PP-theSLAYER** [comment]
Technical documentation of the LGPE WC Full Map:
https://projectpokemon.org/docs/gen-7/lgpe-wonder-card-full-map-r119/

As of now there is no item wc out in the wild, so it's not documented yet.
I expect it to be similar to Gen 7 version, but wouldn't know for sure until we get a copy.

**Comment by BernardoGiordano** [comment]
This will be handled if and when PKSM gets ported on the Switch, I have no plans of including LGPE/Gen 8 wondercards to the 3DS version of PKSM

**Comment by piepie62** [comment]
Random note on this: the current way PKSM is set up is also not conducive to the way that LGPE wonder cards work. PKSM expects each separate Wonder Card to have a specific language, and changing that would require fairly large changes. Not saying it can't be done, just making an easily findable note about it
