### ISSUE TITLE
I can’t find my black copy in PKSM

### ISSUE THREAD

**Issue by Qu0t3** [FlagBrew/PKSM#985]
It’s a .NDS file of Pokemon Black I use TWLOADER to execute. Is there any way I could open this in PKSM?

**Comment by SuperSaiyajinVoltZ** [comment]
Yes, with the extra saves thing from PKSM. (Read the Wiki)

**Comment by Qu0t3** [comment]
I still can’t find the save, I pressed y went to the black and white section and nothing popped up. It’s a .sav food, could that be the problem?

**Comment by SuperSaiyajinVoltZ** [comment]
https://github.com/FlagBrew/PKSM/wiki/Configuration#extra-saves   Read this.

**Comment by Qu0t3** [comment]
Thank you.

**Comment by Qu0t3** [comment]
Close
