### ISSUE TITLE
Region Settings in PKSM

### ISSUE THREAD

**Issue by MatthewCharizard** [FlagBrew/PKSM#988]
Hi there. How do I edit the region of the pokemon I generate as well as the encounter date on PKSM? Cheers!

**Comment by piepie62** [comment]
By region, I assume you mean met region, which is handled by the game version byte. Encounter date would be met date. Both can be found in the hex editor

**Comment by MatthewCharizard** [comment]
Right, the met region. Say if I want to have a hitmontop with sucker punch it must have been bred in HG/SS. How do I select that?

**Comment by piepie62** [comment]
With the hex editor. It shows what the value for the game byte means. If it doesn't for you, then update. Any more trivial troubleshooting should be done on the Discord, not here

**Comment by MatthewCharizard** [comment]
Thank you very much. I'm new here...not sure what Discord is or how to use it
