### ISSUE TITLE
Diamond and Pearl events not working

### ISSUE THREAD

**Issue by zener88** [FlagBrew/PKSM#989]
Since the last release, events are not working for me in Diamond and Pearl. I set an event into an empty slot, I set overwrite true and then I save my changes, but when I go to the shop nobody appears in order to giving me the item/pk. I've tried some events before the last update and It worked fine, actually I got one Manaphy egg that way, but now nothing happens. It works properly with other games, this is only for Diamond and Pearl, not sure about Platinum.

**Comment by kylebass** [comment]
Can confirm. Having the same issue.

**Comment by piepie62** [comment]
This is known and will be fixed with the next version
