### ISSUE TITLE
Cannot Open this file on Windows 10

### ISSUE THREAD

**Issue by ImIrritated** [FlagBrew/PKSM#990]
Used to be able to download open it, but I think my "40 day" free trial of Winrar actually ran out. Whenever I try to open this file now, It just pulls up the Winrar installer no matter how many goddamn times I've installed  it, meaning it prompts me to install winrar while it's already installed and doesn't let me open the file. FBI doesn't accept QR codes anymore and I've searched the far corners of the internet for solutions to these problems and have found nothing, so I'm here.

**Comment by Subject21J** [comment]
This repo isn't for general pc issues. You clearly didn't look hard enough, use 7zip instead of winrar. https://www.7-zip.org

**Comment by Oreo639** [comment]
>Winrar

Check out 7zip or peazip
>FBI doesn't accept QR codes anymore

Update FBI. Also FBI never "stoped accepting qrs". Github updated security to use SSL1.2 with the 3ds's ssl sysmodule only supporting up to 1.1. It was updated to use cURL and mbedtls as a fallback so this shouldn't be a problem anymore.

Also excuse me if I am being stupid but what do you mean by `this file` and `it`.

**Comment by GriffinG1** [comment]
Likely the pksm source code, since pksm releases are solely cia and 3dsx

**Comment by piepie62** [comment]
Yep, not an issue with PKSM at all
