### ISSUE TITLE
Japanese pokemon names become affected when transfering backwards a gen

### ISSUE THREAD

**Issue by githubthrowaway102938** [FlagBrew/PKSM#991]
When transferring japanese pokemon back from gen 6 or 7 to 5 or 4, their names become different and the OT name too

1. take a japanese pokemon from gen 6 or 7 (can  also be from 4 or 5 and transfered forward)

2. put them into a gen 4 or 5 pc box (both gens have different effects)

3. in gen 4 the pokemon name simply changes to have different or less characters (ie kyrogre goes from カイオーガ to カイオ, and other pokemon names become changed entirely.) 

when viewing the summary of a pokemon where a japanese OT name appears the game will freeze but not damage anything.

 In gen 5 the japanese OT is fine to look at, but the pokemon name is also shortened but also is given question marks (ie kyogres name becomes カイオ??????????????????? in a battle screen)

4. when looking in PKSM the pokemon name or OT name can get a question mark block character at the end of their names too.

 - OS version: new 3ds not XL
 - PKSM version: latest 6.2.1 (also present in 6.1.0)

**Comment by Admiral-Fish** [comment]
Do you have pk file examples?
