### ISSUE TITLE
Feature Request: ZL/ZR Buttons to Navigate Boxes Quicker

### ISSUE THREAD

**Issue by FranticUmbreon** [FlagBrew/PKSM#992]
Navigating boxes by holding down L/R/ZL/ZR hasn't been terribly slow, but would leaving L and R function as they do now but allowing one press of ZL and ZR navigate 10 boxes at a time each way be a possibility? 

I know not everyone has a new 3ds/2ds, but this would be a welcome enhancement to those who do. (Unless it's only me that would like this, or I missed it when I searched for an issue similar to this)

**Comment by piepie62** [comment]
This was debated, and it was decided that the current behavior would be best. Pressing one of the menu buttons (start or select, don't remember which in the release--I'm used to testing commit builds) should allow you to jump between boxes
