### ISSUE TITLE
Feature Request: Edit Pokemon in Storage

### ISSUE THREAD

**Issue by MFGookey** [FlagBrew/PKSM#993]
**Is your feature request related to a problem? Please describe.**
There are some Pokemon whose Gen VII representation is invalid in earlier games, such as the HA Totodile family (for having unreleased hidden abilities), and Mothim and Zygarde (for having invalid forms).

**Describe the solution you'd like**
I would like to be able to open the editor for the Pokemon who are stuck in storage due to being unable to be moved to the currently open save file in order to fix the reasons that are keeping them stuck in storage.

**Describe alternatives you've considered**
I worked around this at the time by loading a Gen VII save, and then moving the pokemon into the Gen VII game to fix the problematic traits with the editor.  I then copied the edited pokemon back into storage and was able to move the new copies into the older games.

**Additional context**
The easiest way to experience this problem is to try to move a hidden ability (Sheer Force) Totodile into a gen IV game's save file.

You will be given an error saying:
> Could not transfer Pokemon:
> Impossible ability
> Press A to continue

I was able to reproduce this error reliably in save files for Diamond, Pearl, Platinum, and Heart Gold.

**Comment by piepie62** [comment]
I think that is the most sane way to handle that situation, actually. The editor currently assumes that you're editing the same generation of Pokémon that you have loaded, and I don't really care to change that assumption.
