### ISSUE TITLE
Bug Report - Please help

### ISSUE THREAD

**Issue by Francesco160** [FlagBrew/PKSM#994]
Hi! When I try to open PKSM it shows up a text that says "Error during startup: 0xE0E046BE  Description: Archive : : init failed." Here are some screenshots... Please help me! 
![received_1301569833324148](https://user-images.githubusercontent.com/50595473/57647089-63cd1280-75c2-11e9-8692-1203e5d4c8ef.jpeg)
![received_2409113382472104](https://user-images.githubusercontent.com/50595473/57647090-6465a900-75c2-11e9-9d18-4c1078ff1819.jpeg)

**Comment by piepie62** [comment]
I believe this was a known issue with 6.2.0. Could you try updating to 6.2.1 and reporting back?

**Comment by Francesco160** [comment]
You mean the Hotfix edition for 6.2.1?

**Comment by piepie62** [comment]
Yes

**Comment by Francesco160** [comment]
Ok thanks, I'll try now!

**Comment by Francesco160** [comment]
Man, thanks a lot it works now!
