### ISSUE TITLE
Cant load ingame pc after using pksm to inject pokemon from qr code.

### ISSUE THREAD

**Issue by T3n3** [FlagBrew/PKSM#996]
Ever since i injected a pokemon from pkhex via qr code I have been unable to load the ingame pc. The only thing it does is lock me in a black screen with music still playing. The only way I can get out of this is by turning off the 2ds and tuning it back on again. When i go back to pksm the pokemon is nowhere to be seen.

**Comment by BernardoGiordano** [comment]
do you still have the QR code you used?

**Comment by T3n3** [comment]
Yes

**Comment by BernardoGiordano** [comment]
Send it please?

**Comment by T3n3** [comment]
![image](https://user-images.githubusercontent.com/50780407/57974180-2c88a800-79ac-11e9-8f3e-b5dace837d34.png)

**Comment by BernardoGiordano** [comment]
what version of PKSM are you on?

**Comment by T3n3** [comment]
v6.2.1f8657b3

**Comment by T3n3** [comment]
i can access my pc ingame now, but i dont know what fixed it though

**Comment by T3n3** [comment]
I think I know what caused it.

When i scanned the qr code i was trying to save the pokemon in a unnamed box, but i cannot find the unnamed boxes again.

**Comment by T3n3** [comment]
Thank you for your help today

**Comment by T3n3** [comment]
I figured out what caused it.

When ingame my last box that i was in was the battle box and so when i opened pksm i caused me to have all these unnamed boxes

**Comment by beastin23** [comment]
can someone help, i have a sort of the same problem. I was interacting with the battle box in pokemon y then exited to open PKSM to storage and no pokemon are in my boxes and they are unnamed. When i i open my ingame pc, its just black screen with music playing.

**Comment by piepie62** [comment]
Restore an automatic backup. Next version will fix this issue
