### ISSUE TITLE
Bug Report - Appropriately

### ISSUE THREAD

**Issue by Andrew755** [FlagBrew/PKSM#999]
**Describe the bug**
A clear and concise description of what the bug is. a glitch 

**To Reproduce**
1. Go to box and then go right or left 
2. Click on N/A
3. Scroll down to N/A
4. See Glitch

**Screenshots**
![IMG_0560](https://user-images.githubusercontent.com/34986149/58440776-3db77000-80a2-11e9-8154-e5bbcdde718a.JPG)
![IMG_0559](https://user-images.githubusercontent.com/34986149/58440782-4740d800-80a2-11e9-8efb-443198495f35.JPG)

**Information about your environment**
 - OS version: 11.9 New 3ds XL
 - PKSM version: latest verson 6.1.2
 - Entrypoint:

**Additional context**
Add any other context about the problem here. my main file
[main file.zip](https://github.com/FlagBrew/PKSM/files/3225057/main.file.zip)

](url)

**Comment by piepie62** [comment]
Already fixed in commits
